### ISSUE TITLE
Refactor the spartanizations mechanism

### ISSUE THREAD

**Issue by danielmittelman** [SpartanRefactoring/Spartanizer#10]
There's currently only one functional spartanization (called Trimmer). Refactor the code by removing the old, unused classes extending spartanization, and move Trimmer to the spartanization package

**Comment by mittelman** [comment]
Maybe in the future

**Comment by yossigil** [comment]
@M4tt30rru : we need this for running experiments.
@GalLalouche : FYI.

**Comment by yossigil** [comment]
Mostly done with last arch. changes
