### ISSUE TITLE
Operation assignment to non assignment with operator

### ISSUE THREAD

**Issue by mdoron** [SpartanRefactoring/Spartanizer#1001]
Convert
``` x #= exp; ```
to
``` x = x # exp;```
where # can be any operator.

**Comment by tomerdragucki** [comment]
#973

**Comment by mdoron** [comment]
thanks

**Comment by yossigil** [comment]
@tomerdragucki : if you did it, then make sure it shows that you are the assignee

**Comment by tomerdragucki** [comment]
@yossigil This issue is a duplicate of an expander idea that @OriRoth implemented.

**Comment by yossigil** [comment]
Tests are failing

**Comment by yuvalsimon** [comment]
Fixed it already, my commit was reverted
