### ISSUE TITLE
Prefix to Postfix

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1005]
```
++i
```
to 
```
i++
```

**Comment by ravivos** [comment]
tests number 6,7,9,13 contrast issue #975

**Comment by yuvalsimon** [comment]
@ravivos If I remove all expanders except #975 I get `a.toString()` goes to `a+""){;}}}`. If I add `;` to the statement it does not do this bug. Seems like problem with the inflater because your expanders should work only on For and While ASTNodes and are not related to this command.

**Comment by ravivos** [comment]
@yuvalsimon 
You are right, though the for expander is fine and does not make bugs.
The while expander does

**Comment by yuvalsimon** [comment]
```
for (String s = parentNameScope(¢); !"".equals(s); s = parentNameScope(s)) {
```
goes to
```
for (String s = parentNameScope(¢); "".equals(s)++; s = parentNameScope(s)) {
```
makes error "Invalid argument to operation ++/--"
