### ISSUE TITLE
Testing utility - athenize whole project

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1009]
Should add an option to athenize a whole project (like ctrl+5 on some project spartanizes the whole project), it will help finding bugs. For now it should be only for debugging and not for release, but should consider adding this as a feature for release.

**Comment by OriRoth** [comment]
OK listen...
Click on a project, then type `ctrl+alt+q`. This is a complete inflation of the selection - that way you can inflate whole project/package/files you choose.
But it should be removed before release! Remind me to do so.
