### ISSUE TITLE
Bug in InliningPrefix

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1013]
Might be in AssignmentToFromInfixIncludingTo, not sure.
original is
```
a[x] = a[x] + x++;
++x;
```
when including AssignmentToFromInfixIncludingTo in Toolbox we get
```
a[x]  += x++;
```
when not including it we get
```
a[x++] = a[x++] + x++;
```
when reincluding it the above code stays.

**Comment by yuvalsimon** [comment]
Also `a[x] = x; ++x;` and `a[x++] = x;` are not equivalent yet InliningPrefix tips it

**Comment by yuvalsimon** [comment]
Dor it's your tipper.
Consider also `foo(a[i], i); ++i;` , I think your tipper tips this, and should not

**Comment by yuvalsimon** [comment]
@dormaayan There was still the second bug from above. I changed the tipper so that it would work only for Assignment astnode and InfixExpression, but can improve it to work on more types. This should tip only if there is no use if the index variable and the right side of the array access.

**Comment by yuvalsimon** [comment]
Keep this for next milestone

**Comment by dormaayan** [comment]
Checked it, it seems like working well and covering the relevant cases
