### ISSUE TITLE
Bug in TernaryPushdown

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1015]
convert
```
$ = iz.prefixExpression(e) ? az.simpleName(az.prefixExpression(e)) : az.simpleName(az.postfixExpression(e));
```
to
```
$ = az.simpleName(iz.prefixExpression(e) ? az.prefixExpression(e) : az.postfixExpression(e));
```
is a bug (Maybe because of overloading simpleName(ASTNode)? I'm not sure)
You can find the code in OutlineArrayAccess expander, if I spartanize this line the tests fail. #1004

**Comment by yossigil** [comment]
Yes. This is the famous #232 bug.
