### ISSUE TITLE
Rename names to Java's convention

### ISSUE THREAD

**Issue by mdoron** [SpartanRefactoring/Spartanizer#1017]
In order to get a clear code, we would like to have a uniform code convention.
[Java's naming convention](http://www.oracle.com/technetwork/java/codeconventions-135099.html) is nice and clean, and when applied on the project, will make our code look better!
For example:
`int svd_result_code;`
should become
`int svdResultCode;`

Usage of namespace is required.

**Comment by OriRoth** [comment]
Be careful, may requires namespace analysis.

**Comment by OriRoth** [comment]
Also assign yourself if you are working of it.

**Comment by yossigil** [comment]
Doron: Please consult with @ravivos before working on this.
