### ISSUE TITLE
Integrate the new dictionary/environment DS

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#102]

**Comment by yossigil** [comment]
- [ ] @sakopzon Did you see this?

**Comment by sakopzon** [comment]
Rossi, you said that you have started already to write something, what is the name of this file?

**Comment by yossigil** [comment]
No work for now

**Comment by yossigil** [comment]
Passing on to your @dormaayan , mostly FYI. Probably needs to close
