### ISSUE TITLE
Bug in SimplifyComparisionOfAdditions

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#1021]
```JavA
public class C {
  public  void foo() {
        t(A + 50 < B);
    }
}
```

goes into infinite loop because `SimplifyComparisionOfAdditions ` and `InfixComparisonSpecific` applies after each other infinitely.

Disabled  `SimplifyComparisionOfAdditions ` for now... Add again when fixed...

**Comment by OriRoth** [comment]
Make sure it becomes a test @dormaayan

**Comment by dormaayan** [comment]
Done
