### ISSUE TITLE
Renaming and adding docs to expanders

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1025]
For each of your expanders (that you wrote or will write) please make sure they hold the convetions:
- Test class name is `Issue#` for the appropriate issue
- Add `{@link Issue#}` in the expander class docs
- Add `{@link ExpanderClass}` in the test class docs for the tested expander
- Add code example of the expander function
- Add `@author` and `@since`

Please reference this issue when you commit.

**Comment by OriRoth** [comment]
Example:
```Java
/** Unit test for {@link BuggyExpander}
  * @author Ori Roth
  * @since 29/12/2016
  */
```

**Comment by yossigil** [comment]
Great job Yuval.
