### ISSUE TITLE
Exception thrown from ExtractExpressionFromReturn expander

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1028]
It throws `java.lang.IllegalArgumentException: statements is not a property of type org.eclipse.jdt.core.dom.IfStatement` after running the athenizer on the project.

**Comment by mdoron** [comment]
@yuvalsimon Do you have a case that fail? Can you tell me the setting of the run you did (toolbox, on which files, etc)?

**Comment by yuvalsimon** [comment]
Checkout #425 . We created the configuration at one of the first meetings of the course. I don't have a case, you probably assume some statement type somewhere where it could be also if statement.

**Comment by mdoron** [comment]
Done
