### ISSUE TITLE
Make The Test Mechanism Support Binding

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Spartanizer#1030]
My current idea that is partially work with some problems (that's why I didn't push it) : 

- Write a separate class which you want to expand.

- Overload the `expansionOf` method to handle also with `ASTNodes`

- Pass to `expansionOf` the compilation unit of the class and do a single flater over that.

- compare the results as strings.

My problem currently:
Even when I pass them the compilation unit of a real class, the don't recognize the binding for some reason.
@OriRoth , @ravivos : Maybe do you have any idea why is that happen ?

**Comment by OriRoth** [comment]
There is no binding if the compilation unit does not compile properly. Also make sure you create a compilation unit with bindings in the first place.

**Comment by dormaayan** [comment]
Done
