### ISSUE TITLE
Bug in toStringExpander

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1036]
```
for (int i = 1; i < children1.size(); i++) {
      final String diff;
      diff = singleAtomicDifference(children1.get(i), children2.get(i));
      $ = $ != "" || diff == null ? $ : diff;
      if (!$.equals(diff) && !"".equals(diff))
        return null;
    }
```
goes to
```
for (int i = 1; i < children1.size(); i++) {
      final String diff;
      diff = singleAtomicDifference(children1.get(i), children2.get(i));
      $ = $.toString() || diff == null ? $ : diff;
      if (!$.equals(diff) && !"".equals(diff))
        return null;
    }
```
makes error for left operand is not a boolean. 
I checked and it does not do this expansion in junit test. you can find this code in `il.org.spartan.spartanizer.ast.navigate/find.java`

Also this:
```
return (¢ == null || (¢ + "").length() < 35 ? ¢ + "" : (¢ + "").substring(0, 35)).trim().replaceAll("[\r\n\f]", " ").replaceAll("\\s\\s", " ");
```
goes to
```
return (¢ == null || (¢.toString()).length() < 35 ? ¢.toString() : (¢.toString()).substring(0, 35)).trim().replaceAll("[\r\n\f]", " ").replaceAll("\\s\\s", " ");
```

makes warning for potential null pointer access, but you can see that before the change it should not throw null pointer exception (I checked this).

**Comment by yuvalsimon** [comment]
@yossigil For the last piece of code above (that produces warning) the spartanizer corresponding tipper will make the reverse tip and prevent the null pointer exception, and it might be a semantic error sometimes. Should I open an issue for it?

**Comment by yossigil** [comment]
If the warning is in the zoomer, then don't worry about it. Ignore it. It is a failure of the null analysis of Eclipse. Not nice, but we can live with it.

**Comment by yuvalsimon** [comment]
@yossigil but `null+""` and `null.toString()` are not equivalent because the first one does not throw exception..
@dormaayan Still need to fix the first bug if we don't remove the expander/tipper

**Comment by yossigil** [comment]
Feel free to be optimistic here, assuming that x + "" never execute when x == null

**Comment by dormaayan** [comment]
Couldn't find any problem here, probably other new expander / bugs in other expanders solved that

**Comment by yuvalsimon** [comment]
@dormaayan check the class il.org.spartan.spartanizer.ast.navigate->find.java. 
If you replace the class with the class of 3 weeks ago (Yosi changed the code a few days ago) and apply all the zoomer on the class you will see this bug.

**Comment by dormaayan** [comment]
@yuvalsimon : As we spoke on that,  I close
