### ISSUE TITLE
Convert all key bindings to menu options

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1037]
All shortcuts must have a menu option.
If a shortcut has no menu option, it does not exists

**Comment by ravivos** [comment]
@OriRoth 
I guess that's our GUI GUY's issue

**Comment by OriRoth** [comment]
OK see `TopMenuHandlers` in `plugin` package. There I define most of the handlers used in the top menu.
An issue we've got is the Spartanization and Zoom tools are very flexible, i.e. can operate on many entities (projects, packages, files etc.). When building the top menu I decided to include the options for spartanizing/zooming *current window* and *current project*.
Current top menu structure:
* Refactor
  * Spartanizer
    * Laconize..
      * current window
      * current project
    * Zoom..
      * current window
      * current project
    * Refresh all

Notice activating the zoom tool on current window will trigger the main zoom tool, i.e. wheel operation in editors.

@ravivos check it out

**Comment by OriRoth** [comment]
Added current selection, see #1051 
Seams about right I think.
