### ISSUE TITLE
More Features to BindingTests

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Spartanizer#1040]
- [x] Support more than one pass

- [x] Inspect a single function from the tested class each time.

**Comment by dormaayan** [comment]
@yuvalsimon : Are you ok with your task ? if you need any help don't hesitate to ask me (:

**Comment by yuvalsimon** [comment]
Yes sure, I will do it on the weekend. Thanks

**Comment by yuvalsimon** [comment]
@OriRoth Is it ok if I change SingleFlater class? I want to add an option to apply tips/expanders from specific astnode instead of compilation unit node (in go method).

**Comment by OriRoth** [comment]
Yes this is fine I guess.

**Comment by yuvalsimon** [comment]
@dormaayan @OriRoth checkout Issue1040 and Issue1040Aux classes in the tests package. The _givesWithBinding(String s, String f)_ gets the name of the method to test (in f) and the expected method after applying zoomer (in s). It applies zoomer only for this method. Is it ok?
I still have to check that it resolves bindings, but I used some of Dor's implementation for _givesWithBinding(String s)_ so it should work.

**Comment by yuvalsimon** [comment]
Also there should be only one method with a specific identifier (no inner classes with methods with the same identifier for example).

**Comment by OriRoth** [comment]
Is there a chance it would work with one test class only?

**Comment by yuvalsimon** [comment]
What do you mean?

**Comment by yuvalsimon** [comment]
It works now. I tested it with your #973 @OriRoth , you can checkout Issue1040 test class.

**Comment by yuvalsimon** [comment]
@dormaayan I added example for testing with binding using inner class. You said it should not work. Checkout my code in Issue1040, I used inner class for testing with binding in test6 and test7. It does not work if I use the test class itself (class Issue1040) or outer class in the same file.

**Comment by dormaayan** [comment]
@yuvalsimon :
It looks ok, you can announce the changes to everybody.
