### ISSUE TITLE
Initial crazy idea, and how to do JTL for your implementation of Leonidas

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1041]
This challenge is purely optional. here is an absolutely random list of names of people who might try this in the next week they have less than five submissions. @dormaayan @Kolikant @KaplanAlexander @OriRoth @RoeiRaz @RoeyMaor @orimarco  @orenafek. Thi s list can be edited by anyone.

Consider this crazy java program which uses funny "new" Java tokens. Don't be scared....
```java
Effective rules() {
when (()-> {
  if (b) 
      s1(); 
  else 
      s2();
   body     (()->{       s1();        },()->{
     return v1();
  });
   body     (()->{       s2();        },()->{
     return v2();
  });
v1().litera(true);
v2().litera(false);

} )->(()->{


return b;

});});
}
```
Tips: java 8, lambda expressions, fluent api, crazy identation, incidental "clever" names, typos, external definitions not shown.

Now, couldn't this be related to JTL? @amirsagiv83 care to provide the link to your summary of JTL?

```java
if[_] then[S1] else[S2],
S1.return[V1], S2.return[V2],
V1.literal["true"],
V2.literal["false"];
```
as

**Comment by amirsagiv83** [comment]
This is a short summary I wrote of what is JTL all about. Notice that there is a link in this issue to the original paper written on JTL.
[JTL summery](https://github.com/TechnionYP5777/IntelliJ-Spartanizer/issues/67)

**Comment by yossigil** [comment]
@michalcohen @amirsagiv83

**Comment by yossigil** [comment]
Defunct
