### ISSUE TITLE
Bug in remove continue

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1047]
plugin fails on this code. @yuvalsimon  please reassign to whoever dealt with this

  for (int i = 0; i < length; ++i) {
      char c1 = s1.charAt(i);
      char c2 = s2.charAt(i);
      if (c1 == c2)
		continue;
      int alphaIndex = getAlphaIndex(c1);
      if (alphaIndex >= 26 || alphaIndex != getAlphaIndex(c2))
		return false;
	continue;
    }

**Comment by yuvalsimon** [comment]
@yossigil I'm not sure where you say it fails, I tried in debug mode and also with trimmer tests and it is alright, both when athenizing or spartanizing. There is another bug in #1048 related to continue statement. Is it the bug you talk about?

**Comment by yossigil** [comment]
It happens when I use the plugin on Guava.

**Comment by yossigil** [comment]
Cannot reproduce. Closing

**Comment by yuvalsimon** [comment]
@mdoron The spartanizer stucks on your ForRedundantContinue tipper for this code.

**Comment by yuvalsimon** [comment]
@mdoron I added test case (Issue1047), make sure all tests pass
