### ISSUE TITLE
Fix seleciton model

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1051]
Currently, the selection model is: youu hit laconize project, and it searches for the project.

However, Eclipse model is better: Once you hit the general purpose button: "Spartanize", the button figures out which is the selected item: 

1.  it is a project, a bunch of packages, or just more than one file, it offers a dialog box,  : Do you want to laconize X files/ Y packages/Project T/Projects X,Y,Z.
2. If it is one file, it does it no dialog box
3. If it is selected item(s), even in outline, just do it. no dialog box.
3. If not text marker, just do it on current window
3. If text marked, do it on current text.

**Comment by OriRoth** [comment]
See `Spartanize.. -> current selection` and `Zoom.. -> current selection` in top menu. Works from the outline view. In the current implementation a dialog is shown iff the selection contains at least *2 files*.

Remaining issues:
* Multi-selection name: if you choose *some* projects/packages/files, it asks the user if he wants to spartanize "selections". I'll take care of it.
* Spartanizing the whole window if the text selection is empty" are you sure we want this? This was implemented before, but removed - this is a feature that *fixes* empty text selection to wrap the entire file, and was previously replaced by a features the fixes empty text selection to *wrap enclosing marker*. This is more "expected" in my opinion - if someone sees a marker, put the cursor on it and spartanize, he will be surprised if the whole file will be spartanized... so what do you think?

**Comment by OriRoth** [comment]
See `Selection#getMultiSelectionName`. Current status:
![guava](https://cloud.githubusercontent.com/assets/15183108/21805374/8aa2937a-d73c-11e6-9028-8ac1b9cca946.jpg)

**Comment by yossigil** [comment]
Splendid!
