### ISSUE TITLE
Make zoon in / out more smooth

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1052]
- Perhaps ctrl mouse rool should do zoom in / zoom out all the time?

If not different color or something...

*Edited by @OriRoth*:
zoom in current window.

**Comment by OriRoth** [comment]
There is an existing functionality for zoom in-out. When designing the GUI I took an inspiration from the *box selection tool* (i.e. `ctrl+shft+A`). So I think the colors would be nice.

**Comment by OriRoth** [comment]
OK, zooming is in current window only + background color changes when inflating/deflating.
Tell me if you want to change colors / set background for all lines (and not just edited lines) (looks worse though).
