### ISSUE TITLE
Spartanizer performance - disable java builder during spartanization

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1054]
I'll check out whether this is worthwhile.
*Update*:
* http://stackoverflow.com/questions/36041282/how-to-programmatically-add-a-builder-to-a-project-in-eclipse
* http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2FJavaCore.html
* Seams like what we are looking for... http://stackoverflow.com/questions/2505229/disable-building-workspace-process-in-eclipse

**Comment by OriRoth** [comment]
@yossigil what do you think? Spartanization time of guava sub project dropped from 400 seconds to 88 seconds (!):

![guava](https://cloud.githubusercontent.com/assets/15183108/21789504/37e1907c-d6de-11e6-9798-ae2080efea3a.jpg)

Do you see any improvement on your machine?

**Comment by yossigil** [comment]
Good results. I did not test them yet. Will probably when I delve into the project again
