### ISSUE TITLE
While Expander Causes Problems with Wrapping

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Spartanizer#1060]
As we said at the meeting the wrapping if code with while statements may cause problems with your expander, I disabled it for now and we should think what to do about that...

**Comment by yuvalsimon** [comment]
@dormaayan I think if you add `;` to tested code it won't do this because then it is considered a statement astnode and it won't wrap it with while statement probably. I add this problem for example in testing with input `i=x+1`, then for `i=x+1;` it does not make this problem.

**Comment by dormaayan** [comment]
Got it, I returned the expander
Thanks
