### ISSUE TITLE
Binding tests should ignore names

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1061]
We want to write binding tests for `Expander`s that produces new variables with names generated by `NameSpace`. We want to be independent of the internal implementation of `NameSpace`.
The algorithm I offer:
When running `expansionOf(...).gives(...)` do:
1. expand code
2. in both *actual* and *expected* codes, replace all `Name`s with arbitrary names (such as `v1`, `v2` an so on) while preserving a map of transformations:
* if the name appears in the map, replace it with the map's value
* else generate a new arbitrary name and insert it into the map
* example: `MyObject f() {MyObject $ = g(); return $;}` ==> `v1 v2() {v1 v3 = v4(); return v3;}`
3. if the ASTs are *similar*, the equation wil be successful.

**Comment by dormaayan** [comment]
Done
