### ISSUE TITLE
Bug in PostFixToInfixExpander

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1062]
The tests you added to #1005 are with semantic error (the code in the gives is not equivalent to the original code). Please fix the expander. These are the tests you added: 
```
@Test public void t3() {
    zoomingInto("if(++i + i++ > ++i + y) { x = f(); }").
    gives("if(++i+(i=i+1)>++i+y){x=f();}");
  }

  @Test public void t4() {
    zoomingInto("f(i++,--j,++x);").gives("f(i=i+1,--j,++x);");
  }
```

**Comment by yuvalsimon** [comment]
Also in #1004:
```
@Test public void t2() {
    zoomingInto("arr[i++] = i;").gives("arr[i=i+1] = i;").stays();
  }

  @Test public void t3() {
    zoomingInto("arr[i++] = arr[i++] + i;").gives("arr[i=i+1]=arr[i++]+i;");
  }
```
not equivalent.

**Comment by dormaayan** [comment]
Didn't find anything, please be clear if the problem is still exist, I didn't understand what you want here...

**Comment by yuvalsimon** [comment]
if  `i=0` then when you write `x[i++] = i` you will get `x[0]=1;`.
For `x[i=i+1]=i` you will get `x[1]=1;`. You can check this.

**Comment by yuvalsimon** [comment]
@dormaayan Please try this with system.println. Should disable this tipper before version release and restore the tests of #1004. Please do it if you agree with me.

**Comment by OriRoth** [comment]
@dormaayan I think Yuval is right. you should convert `++i` to `i += 1`, not `i++`. Check it out.

**Comment by dormaayan** [comment]
I cancelled the i++ expander because it is not correct. you can delete it (I already fixed the tests) and fixed the ++i expander to give i+=1
