### ISSUE TITLE
Expand mathematical expressions

### ISSUE THREAD

**Issue by mdoron** [SpartanRefactoring/Spartanizer#1063]
`c = x + y * z`;
into 
```
a = x;
b = y*z;
c = a + b;
```

**Comment by OriRoth** [comment]
My expander should take care of it, talk to me before starting working on it.

**Comment by mdoron** [comment]
Which one of them? link it here please

**Comment by yossigil** [comment]
If you decide to do it, take a look at classes Term and Factor

**Comment by mdoron** [comment]
@OriRoth you implemented a large zoomer but didn't documented not in  class nor in issue, thus we have this duplications...
