### ISSUE TITLE
Wiki page about how to use Auto-Generation of names

### ISSUE THREAD

**Issue by mdoron** [SpartanRefactoring/Spartanizer#1066]

**Comment by mdoron** [comment]
Done 
https://github.com/SpartanRefactoring/Spartanizer/wiki/How-to-use-Auto-Generation-of-names-in-Zoomers%3F

**Comment by yossigil** [comment]
👎 can you please rewrite the wiki in a more readable way?

**Comment by mdoron** [comment]
@yossigil I rewrited it. Can you recheck please?

**Comment by yossigil** [comment]
Much better, thanks. Take note that I wrote a generateName generator. Find it, and see if you can use it.
