### ISSUE TITLE
Bug in DeclarationInlineIntoNext

### ISSUE THREAD

**Issue by tomerdragucki** [SpartanRefactoring/Spartanizer#1067]
```java
String s = "7", $ = s;
System.out.println(s);
System.out.println($);
```

is spartanized to:
```java
System.out.println("7");
System.out.println($);
```

and:
```java
String s = X, $ = s;
x.y.f(h2A+ $ + 0 + s);
```

is spartanized to:
```java
String $=s;
x.y.f(h2A+$+0+X);
```

**Comment by tomerdragucki** [comment]
The same bug in DeclarationInitializerStatementTerminatingScope:
```java
int zero = 0, result = 8 / zero;
++result;
```
is spartanized to:
```java
int result=8/zero;
++result;
```

**Comment by yuvalsimon** [comment]
@orimarco It's your tipper. Can you solve it until next week?

**Comment by yuvalsimon** [comment]
@orimarco I move this to next milestone. for now I fixed your tipper to work with stronger condition. I will do the same for Yosi's tipper.
