### ISSUE TITLE
Wring to convert a += 1 to a++, if a is an integer.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#107]
Same for a-=1.

You cannot do it without the Environment, since ++ does only work on int, char, long, and short, but not on any other type.

**Comment by NivShalmon** [comment]
look at the latest tests I uploaded. ++ works for double and float as well. forgot to add tests for byte, but it would most likely work for it as well, meaning it can probably work on any numeric type.

**Comment by yossigil** [comment]
You are right. I did not know that. The only worry is then String,
``` String s = "";
s += 1;
```

**Comment by sakopzon** [comment]
Do you want us to handle the String also in some way?

**Comment by sakopzon** [comment]
Finished the textual part, next step is building the Environment to ask for the type.

**Comment by yossigil** [comment]
@NivShalmon : did we finish this? If yes, please close.

**Comment by NivShalmon** [comment]
I have no idea, I never worked on this wring. @sakopzon or @dngreenst should know

**Comment by yossigil** [comment]
@dngreenst : finish this up.
Create a class named: `Issue107Test`. Move all the tests there, make sure it works, and close it.

**Comment by dngreenst** [comment]
@yossigil It works, and is String safe (turned the `Assignment` into an `InfixExpression` and used `stringType.IsNot`). Problem is that when looking on a single ASTNode, the requirements of the left operand, in order to be provably not String, are very steep. Wrings on operator+ will almost never happen. 

I suggest we don't close this - I think we would be able to do much better with an Environment.

**Comment by yossigil** [comment]
Close it. Add a note to the environment.

**Comment by yossigil** [comment]
OOPS, tests still fail:

![image](https://cloud.githubusercontent.com/assets/12775400/18416743/3981dba2-7825-11e6-8cae-f1e38f589823.png)

**Comment by yossigil** [comment]
Fix these tests.

**Comment by yossigil** [comment]
Just checked. It works.
