### ISSUE TITLE
Bug in renaming tipper when nesting

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Spartanizer#1074]
```
  public static <E extends Enum<?>> EventListener<E> simpleListener(final Class<E> enumClass, final Consumer<E> c, final BiConsumer<E, Object> bc) {
    return new EventListener<E>(enumClass) {
      @Override public void tick(final E e) {
        c.accept(e);
      }

      @Override public void tick(final E e, final Object o) {
        bc.accept(e, o);
      }
    };
  }
```
spartanizer offers to rename c to e but then e gets hidden inside and we get `e.accept(e)` which yields an error

**Comment by yossigil** [comment]
Note that the only way to resolve this is by using the `Environment` class

**Comment by yuvalsimon** [comment]
@ravivos it's your issue, I dealed with most of my issues already and I have to be on the QA tasks. Also it does not suggest tip for this example (I checked on EventListener class).

**Comment by ravivos** [comment]
@yuvalsimon 
You are right - the bug is fixed.
probably by Ori's config
