### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1080]
Please checkout my commit in fix your tests as soon as possible. If someone else is responsible for that assign him. 
https://github.com/SpartanRefactoring/Spartanizer/commit/66e093cbd5fbd69f424ef29d20afb94ced5f7710
Also see #1078

**Comment by mdoron** [comment]
Is everything okay now? Can I close this issue? @yuvalsimon

**Comment by dormaayan** [comment]
Everything seems ok, I close

**Comment by yuvalsimon** [comment]
The tests are ignored, if they are needed check they pass.

**Comment by dormaayan** [comment]
@yuvalsimon : Do you mean to @mdoron or me ? Why am I assign to that ?

**Comment by yuvalsimon** [comment]
For both, check the commit in the issue (https://github.com/SpartanRefactoring/Spartanizer/commit/66e093cbd5fbd69f424ef29d20afb94ced5f7710). Your classes Issue0965 and Issue1036 had failing tests, I ignored them so just make them pass or remove if they are wrong. Same for Doron for Issue1044.

**Comment by dormaayan** [comment]
For now I fixed but there are some issues there that will be done in the second semester...

**Comment by yuvalsimon** [comment]
Alright, just make sure to open an issue if there isn't one already so we won't forget this
