### ISSUE TITLE
Bug in name generation

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Spartanizer#1081]
```
	public int non(int i, double b) {
		b = i;
		return i;
		
	}

```
turns to
```
	public int non(int i1, double d1) {
		d1 = i1;
		return i1;
		
	}
```
**but**
```
	public int non(int i, int b) {
		b = i;
		return i;
		
	}
```
turns to
```
	public int non(int i1, int i1) {
		i1 = i1;
		return i1;
		
	}
```
in renaming expander #979  - which points that the problem might be in the generation of 2 different variable names of same type.
I remembered that this issue was already open but couldn't find it, so if such exists, feel free to reference it and close this

**Comment by mdoron** [comment]
It is not possible to change two variables in one expander yet (see: [wiki](https://github.com/SpartanRefactoring/Spartanizer/wiki/How-to-use-Auto-Generation-of-names-in-Zoomers%3F)).

**Comment by ravivos** [comment]
then don't close it, label it as "on-hold"

**Comment by mdoron** [comment]
This is duplication !

**Comment by mdoron** [comment]
For now, in order to solve this issue, you should implement the Zoomer one name change at a time.

**Comment by mdoron** [comment]
And also, the problem is not with the same type, consider the same code but instead of `double` put `Integer`

**Comment by ravivos** [comment]
Then what is the problem for int and int? @mdoron

**Comment by mdoron** [comment]
The `namer` returns `i` for parameter of type `int` but also for type `Integer`, this is the `namer` algorithm (Yossi's).

**Comment by mdoron** [comment]
Duplication issue see #1068
