### ISSUE TITLE
Bug in switch to if statement tipper

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1082]
Need to consider side effects, for example
```
switch(foo()) {
case 1: case 2: x=1;break;
default: x=2;
}
```
to
```
if(foo() == 1 || foo() ==2) x=1;
else x=2;
```
I will not tip when have side effects for now.
@yossigil If we want to tip when have side effects we need to add temporary variable using environment, but still we will get less code when using the tipper so it is spartan programming. Should I add it?

**Comment by OriRoth** [comment]
You cannot create such a variable without binding, because you do not know the type of the Expression! (though switch accepts limited types). And we do not support binding in Tippers at the moment.

**Comment by yossigil** [comment]
actually, @OriRoth if you can help, this could be a great feature: a configuration toggle: with/without binding. This tipper should not do anything when binding is off.


If you agree, open an issue and start doing it. Otherwise, please mark this as "will-not-fix", close it as well as all "will-not-fix" labelled issues

**Comment by yuvalsimon** [comment]
Yes I know Ori. The environment/binding class should work also for tippers, isn't it?
I will keep the issue open for later.

**Comment by OriRoth** [comment]
No It cannot - what if the function is defined in another file? (among the reasons)

**Comment by yuvalsimon** [comment]
The bug is solved already @yossigil . I can convert the code above to
```
int newVar = foo()
if(newVar  == 1 || newVar  ==2) x=1;
else x=2;
```
but need binding for this

**Comment by OriRoth** [comment]
What about Strings? We need to use `equals` instead of `==` (well actually not, but this is a secret).

**Comment by yossigil** [comment]
@yuvalsimon : maybe you can limi the tipper to the case where there is only one case and perhaps a default?

**Comment by yossigil** [comment]
Yuval please finish up with this switch and case mess

**Comment by yossigil** [comment]
@ravivos : FYI
