### ISSUE TITLE
Binding in Spartanizer

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1083]
* GUI toggle in preferences screen
* Tippers that use binding would query the AST as a prerequisite: `n.getAST().hasResolvedBinding()`
* Easy fix at `GUIBatchLaconizer` (root Spartanizer application), maybe in other applications (@orimarco?)

@yossigil looks possible, though the demand at the moment is rather low (or is there something I am not aware of?)

#1082

**Comment by yossigil** [comment]
It is something we in the research team need: when we do batch processing, there could be no binding information. We must be able to experiment without binding.
