### ISSUE TITLE
Making the Final presentation

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Spartanizer#1095]
as described here #1084 
Also, the presentation itself will be as described in @yossigil message:

> Yossi Gil, [19 Jan 2017, 10:59]: 
שלום לכולם, ביום שלישי הקרוב,  בשעה 17 בטאוב 235 נקיים מצגת משותפת של צוות 8 וצוות 12: צוות 12 יתחיל ויציג את עבודתו. אחריו צוות 8. 
למצגת מהסוג הזה קוראים שיפודיה. השיפודיה תתקיים בטאוב 235.
לשיפודיה יש מבנה  מבדח קבוע:
שלב הפדיחות - מישהו מהצוות האחר מנסה להתקין את התכנה שלכם ולהריץ אותו.
שלב הפשלות: מדגימים את התכנה על מחשב שצלח את שלב הפדיחות.
שלב העצמות: אתם עושים מצגת על השלד הארכיטקטוני שאיפשר את צליחת שלב הפשלות. (הסגל הופך את השלד לגל עצמות)
שלב המלח על הפצעים: איפה טעינו, איך התחרטנו, למה לי כל זה?
אתם מתבקשים להכין את השיפודיה כך:
הוראות התקנה ברורות, ופרוצדורת התקנה ברורה. (אחת מהפתעות השיפודיה היא לבקש להתקין על נניח Windows)
תכנית מסודרת: מה אתם מדגימים? למה זה מגניב? שונה? מעניין?
מצגת על מה למדתם: טכנולוגית. הארכיטקטורה.
 שקף אחד שיכין אורן בצוות 8 ורביב בצוות 12, ויהיה סודי עד למצגת - תובנות ומחשבה ביחס לשיתוף פעולה, מה עבד ומה לא עבד?
השקף (אפשר שניים אם צריך) , יכיל - מילים אישיות של המחבר ביחס לכל אחד מחברי
הצוות, שמדגישות את תרומתו היחודית. לדוגמה:
הרשלי אוסטרפולר: אתה בדחן ליצן. הייתי שמח אם היית איתי יותר בשעות הקשות.
ג'וחא נסאראלדין: אין כמוך, פרש ומנהיג אתה, הובלת אותנו.
טיל אוינשפיגל: אשמח אם תבטא כישוריך כראוי להם בסמסטר הבא.
אלימלך זורקין:  כל הכבוד על שינוע המכולות

**Comment by yossigil** [comment]
Please add the slides to github. See if you can embed it in a wiki page. Also, think about the video
