### ISSUE TITLE
Clever ternarizations, adding 0, 1, empty string, etc.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#110]
Convert
```java
if (polite)
     return "Eat your meal."
else
return "Eat your meal, please"
````
to
```java
return return "Eat your meal" (!polite ? "." : else ", please");
```

more over, can you do so while adding a blank string if necessary? Adding a zero? Adding a one?

**Comment by yossigil** [comment]
Maybe you can do the same for multiplication,  (add 1) addition (add 0), etc.

**Comment by yossigil** [comment]
Does it do suffixes?

**Comment by NivShalmon** [comment]
Not yet, but we are working on it. It should recognize any shared substring when we are done.
Also, our wring works on trenary expressions rather than if statements, since we already have a wring that turns the if into a trenary

**Comment by dormaayan** [comment]
> Maybe you can do the same for multiplication, (add 1) addition (add 0), etc.
@yossigil  : what do you mean by that ? won't the automatic evaluation mechanism will catch such things before ?

**Comment by yossigil** [comment]
No. Sometimes you need 
```java
if (a)
  return 3*b
else
return 2 + 3*b
```
clever optimization would return:
```java
return  3 * b + (a? 0: 2);
```

**Comment by yossigil** [comment]
Also, for strings, just as arithmetical expression, the ?: could be in the middle.

```java
Sring s = a ? "abracadabra" : "abba";
```
to 
```java
Sring s = "ab" + (a ? "racadabr" : "b") + "a";
```
Same for addition:
```java
int s = a ? x+ y + z: x + z;
```
to 
```java
int s = x + z + (a ? y : a) ;
```

**Comment by dormaayan** [comment]
@yossigil :
It handles the case :

```
 Sring s = a ? "abracadabra" : "abba";
to
Sring s = "ab" + (a ? "racadabr" : "b") + "a";
```

Currently working on the number cases

**Comment by yossigil** [comment]
This one is not captured
```java
  @Override String description(final MethodInvocation i) {
    final Expression receiver = step.receiver(i);
    return receiver == null ? "Use \"\" + x" : "Use \"\" + " + receiver;
  }
```

**Comment by yossigil** [comment]
There might be similar examples for other operations which are not commutative

**Comment by yossigil** [comment]
Did you check it on:
```
  private static String description(final Expression x) {
    return x == null ? "Use isEmpty()" : "Use " + x + ".isEmpty()";
  }
```

I am not sure it gets the right result

**Comment by dormaayan** [comment]
@yossigil :

 I add a test case of :

`  private static String description(final Expression x) {
    return x == null ? "Use isEmpty()" : "Use " + x + ".isEmpty()";
  }`

And it seems like it works fine

**Comment by yossigil** [comment]
This also seems like something we do not want to do:
```java
		$.setName(b.simpleName(booleanLiteral ? "TRUE" : "FALSE"));
```
goes to
```
		$.setName(b.simpleName((booleanLiteral ? "TRU" : "FALS") + "E"));
```

**Comment by dormaayan** [comment]
@yossigil  :
Do you want us to limit the work of that wring to prefixes/postfixes over a certain length ?

**Comment by yossigil** [comment]
No, I think it better to limit it to not break between two alphabetical characters.

**Comment by dormaayan** [comment]
@yossigil : Done
