### ISSUE TITLE
Project interview 

### ISSUE THREAD

**Issue by AdiOmari** [SpartanRefactoring/Spartanizer#1106]
Sapir @SapirBismot  and Doron @mdoron ,

We would like to interview each of you tomorrow. Please select a time for the interview by writing your name in the following document:
https://docs.google.com/document/d/14eTOc1KL5d0LQEymoZCmf7RuqoBlHJfbmDcnUN8l2lM/edit#

Thanks

**Comment by yossigil** [comment]
@tomerdragucki : In view of your request, you are welcome to represent your work
