### ISSUE TITLE
Generate name with desired prefix

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1108]
e.g if we want variable named `res`, without considering the type. Add number a needed, such as res22.
@ravivos use it for the RenameShortNameMethodDec when it's done.

**Comment by mdoron** [comment]
@yuvalsimon this was the first implementation, but @yossigil didn't approved.
I will add this function right away, but I think it's dangerous... be careful when you're using it.

**Comment by yuvalsimon** [comment]
Yes but Raviv needs it for his issue to make _res_ variable for example. Keep it open until closing 1044.

**Comment by mdoron** [comment]
@yuvalsimon what's going on with this issue? I'm not sure whether the current implementation answer this request or not, can you help me understand if it does since you are the one who faced this problem? I think it does but I'm not 100% sure so I don't want to close this issue.

**Comment by yuvalsimon** [comment]
Yes, it should work, it solves the issue, I'll also check it on run today.

**Comment by yossigil** [comment]
I think this should issue should be moved to @dormaayan

**Comment by dormaayan** [comment]
@yuvalsimon, can you please explain to me what is going on with that issue ?

**Comment by ravivos** [comment]
guess it is related to this issue #1044.
Dor, please close one and work on the other of your choice - because they are some what duplicates

**Comment by dormaayan** [comment]
Move the work to #1044 , not as part of the  YP
