### ISSUE TITLE
Exceptions from RenameShortNamesMethodDec

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1109]
It throws lots of exceptions. Do not add it to the release please, not enough time to make sure it works until tomorrow...

**Comment by yuvalsimon** [comment]
See #1108

**Comment by ravivos** [comment]
you are right.
Im taking it out of the toolbox but I think that the problem is in the name generation though
#1044

**Comment by ravivos** [comment]
I think it's a duplicate of #1100, don't you?
@yuvalsimon if so, close this issue

**Comment by yuvalsimon** [comment]
@ravivos keep this open until it's solved. I'm not sure what causes there, I think you should wait for #1008 and use it, then it would be easier to check this.

**Comment by yuvalsimon** [comment]
Yes it's a duplicate, I closed #1100. I thought it was closed already..

**Comment by yuvalsimon** [comment]
@ravivos I implemented the method for #1008, you can use it. Checkout my last commit. It still has the problem I mentioned in #1044, so this should work well only when using the wheel. If you finish this issue check that all the errors you get when debugging are of the type in #1044.

**Comment by ravivos** [comment]
will be fixed.
for Now, this expander is out of use
