### ISSUE TITLE
A wring to sort modifiers.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#111]
This wring should sort modifiers:

1. Public/protected
2. static
3. abstract/final
4. syncrhonized
5. volatile.

Take a class named RedundantModifiers or something to see how to deal with them.
Make sure you insert test cases for all.

**Comment by sakopzon** [comment]
> When two or more modifiers appear in the source code of an element
 * then it is customary, though not required, that they appear in the same
 * order as the constants listed in the detail section below.
(from Modifier.class binary)

Do you mean to sort the modifiers by the order they appear in this file?

**Comment by yossigil** [comment]
You may still need it. Wrings are type specific, and you may want to sort modifiers on several entities:

- Fields
- Variables
- Methods
- Classes
- Interfaces
- Enums
- Whatever I forgot.

You many need different wrings for each of these types. So, it best to place the commonality in an abstract  class, say CanonicalOrderOfModifiers, and have several wrings that extend it, as per the kind on item that takes this modifiers.

**Comment by sakopzon** [comment]
Yes, a minute ago I faced the truth, while trying to implement ABC which extends AbstractSorting and should have overwritten eligible() method which in it's turn would gotten some type of BodyDeclaration/SingleVariableDeclaration/VariableDeclarationStatement which step.modifiers() can accept.

**Comment by yossigil** [comment]
Yes, you got it. There is nothing we can do at the current state of affairs. You would have to deal with similar nodes, whose similarity is not captured by inheritance. This is the best solution I have for now.
You will need it also to deal with the Environment. Same problem there

**Comment by sakopzon** [comment]
Now when we have some implementation:
The only abstract method I could think about is compare(), But every entity which extends BodyDeclaration can have only sub group of Modifiers from:
`public enum Modifier {

    // See JLS sections 8.1.1, 8.3.1, 8.4.3, 8.8.3, and 9.1.1.
    // java.lang.reflect.Modifier includes INTERFACE, but that's a VMism.

    /** The modifier {@code public} */          PUBLIC,
    /** The modifier {@code protected} */       PROTECTED,
    /** The modifier {@code private} */         PRIVATE,
    /** The modifier {@code abstract} */        ABSTRACT,
    /**
     * The modifier {@code default}
     * @since 1.8
     */
     DEFAULT,
    /** The modifier {@code static} */          STATIC,
    /** The modifier {@code final} */           FINAL,
    /** The modifier {@code transient} */       TRANSIENT,
    /** The modifier {@code volatile} */        VOLATILE,
    /** The modifier {@code synchronized} */    SYNCHRONIZED,
    /** The modifier {@code native} */          NATIVE,
    /** The modifier {@code strictfp} */        STRICTFP;

    /**
     * Returns this modifier's name in lowercase.
     */
    public String toString() {
        return name().toLowerCase(java.util.Locale.US);
    }`
I think I can implement one compare() function which will handle all mentioned above entities.
Am I wrong?

**Comment by yossigil** [comment]
Alex,  you are on your own on this. Finish the issue first. I cannot hand walk you on this.

**Comment by yossigil** [comment]
![image](https://cloud.githubusercontent.com/assets/12775400/18226829/de5b9e26-721a-11e6-896e-31105a34e3fd.png)

@sakopzon : you may have did something here? These two tests seem related to RedundantModifier

**Comment by yossigil** [comment]
I implemented an enum called `Modifiers` for you. Please add a couple of tests for it.
Then it would be easy to use in your wring

**Comment by sakopzon** [comment]
nice, thanks

**Comment by sakopzon** [comment]
Ok, I think that there is some collision between your Wrapper in to() for methods and our ModifierSort which doesn't let the code be unwrapped before returning to the output.
Didn't have enough time to dig in it, but I think our interface works well as a stand alone code.
What do you think?
Good night.

**Comment by yossigil** [comment]
The bug is in that you claim the right to wring the code even though you do not not do anything with it.if you run the project on itself you will see what I mean: lots of places where your wring claims to do something, but it doesn't. Please read the wring on remove subtraction, or other wrings: you will see that when you cannot find anything you return `null`.

**Comment by yossigil** [comment]
I did not see any progress on this one today. Shame.

**Comment by sakopzon** [comment]
Is it ready for closing now?

**Comment by sakopzon** [comment]
Can't see where does it falls... could you name the test?
