### ISSUE TITLE
Bug: eliminate dead assignment:  a = b; a = c; => a =c;

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#1110]
```java
a = 0;
a = b; 
```
should become:
```java
a = b;
```

and another:

```java
hasDefault = 0;
hasDefault = cases.stream().filter(¢ -> ¢.isDefault()).map(¢ -> 1).findFirst().orElse(hasDefault);
```   
to:
```java
 hasDefault = cases.stream().filter(¢ -> ¢.isDefault()).map(¢ -> 1).findFirst().orElse(hasDefault);
```

**Comment by yossigil** [comment]
Only kill the assignment if the 'from' is something for which 'iz.sink' returns true/

**Comment by OriRoth** [comment]
Done, see `AssignmentAndAssignmentOfSameVariable`.
@yossigil no test file only examples (should be fine for simple tippers in my opinion). Also used `sideEffects.sink`.
