### ISSUE TITLE
Spartanization Bug - Bad Removal of Parentheses 

### ISSUE THREAD

**Issue by dngreenst** [SpartanRefactoring/Spartanizer#112]
The spartanization seems to remove necessary parentheses when spartanizing a string with mathematical expressions mixed in.  

<img width="960" alt="spartanizationbug1_1" src="https://cloud.githubusercontent.com/assets/20325207/18224147/28f8d25a-71d5-11e6-88c3-b9acbe0ced6d.png">

<img width="957" alt="spartanizationbug1_2" src="https://cloud.githubusercontent.com/assets/20325207/18224162/86a93de0-71d5-11e6-9634-59f6bb497b79.png">

<img width="960" alt="spartanizationbug1_3" src="https://cloud.githubusercontent.com/assets/20325207/18224163/8e2e3be2-71d5-11e6-9369-27412a4b239a.png">

**Comment by yossigil** [comment]
@Stav1472: this is a bug you introduced. Search for planting.

**Comment by yossigil** [comment]
To fix, first create a `@Test` method that fails. Then create other variations of the test, that all fail.
Then fix it.

**Comment by Stav1472** [comment]
This is not a bug I introduced. i had it before writing any of my wrings. i don't know which wring causes this bug.

**Comment by yossigil** [comment]
pending on #119

**Comment by yossigil** [comment]
Probably
