### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#1126]
- [ ] All big Rs to small r - Matteo
- [ ] highlight guava lines - Matteo
- [ ] Tables to one column - resize width or replace repository names with letters - Matteo
- [ ] Table 2.1 - reconstruct data as much as can

**Comment by M4tt30rru** [comment]
- [ ] All big Rs to small r
- [ ] highlight guava lines
- [ ] Tables to one column - resize width or replace repository names with letters
- [ ] Table 2.1 - reconstruct data as much as can
