### ISSUE TITLE
Make main menu item

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1127]
So, just after Refactor, you will have Spartanize main menu. See if Alt-Z or Alt-S are free

**Comment by OriRoth** [comment]
Now there is a single `Refactoring` tab. I have added a mnemonic `t` to `Refactoring` tab, so now you can access `Spartanizer` menu by typing `Alt+t` then using the arrow keys to navigate to and in it.
Shortcut options (mnemonics) are quite limited, nevertheless every menu option already has a keyboard shortcut.
I can use the mnemonic `R` for `Refactoring`, but it collides with `Run`... looks bad, but it is possible to use this instead.

**Comment by yossigil** [comment]
It still does not work for me. I cannot run the plugin

**Comment by OriRoth** [comment]
On my machine it took about a minute to build the Spartanizer project, and showed 123 Spartanization suggestions. All the Spartanization top menu options seam to work. I have not made changes that can interfere with the plugin's loading during my work on the preferences revision...
@orimarco can you check if you are able to run the plugin on the Spartanizer project? Try spartanize it through the top menu (Refactor->Spartanizer->Spartanize...->current project).
@yossigil try to wait a bit for the build to complete (if you have several projects in the workspace, it may take some time). Another option is to disable auto build temporarily and try to spartanize the project without the markers.
