### ISSUE TITLE
Convert a+=1 to a++;

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1138]
Be careful, 'a' may be of type String.

**Comment by dormaayan** [comment]
@yossigil : I already implemented that but then I noticed we have an expander which turn `a+=1` to `a = a+1`
Which one do you think is more suitable for that case ? I support the `a = a+1`

**Comment by yossigil** [comment]
this is a trimming tipper, not expanded.

**Comment by dormaayan** [comment]
@yossigil : Sorry, Didn't notice, I'll also update the test utilities of the trimmers to support binding, too.

**Comment by OriRoth** [comment]
We can use the naming mechanism to track types of variables for free @yossigil @dormaayan . We can store references to variable declarations as well as for their names.

**Comment by yossigil** [comment]
Class Namespace is a home made approximation of binding. Perhaps it should be defunct.

**Comment by dormaayan** [comment]
I putt it in hold now until I'll add the binding support both for the Bloaters and the Tippers

**Comment by yossigil** [comment]
Can you try using the Namespace? This way we can decide whether it is worth maintaining

**Comment by dormaayan** [comment]
The using of namespace isn't working in all cases, for example with multiple variables, needs a further inspection if we go in that path.
The issue itself is done.
