### ISSUE TITLE
Purim: Include Spartan Warrior on readme.md

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1140]
![image](https://cloud.githubusercontent.com/assets/12775400/23852989/357ff2c4-07f3-11e7-8900-eabf9467744a.png)

**Comment by yossigil** [comment]
Upon closing remove all labels

**Comment by OriRoth** [comment]
You can edit top comment to access picture URL.

**Comment by orenafek** [comment]
Done :fearful:
