### ISSUE TITLE
Bug is switch

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1147]
```java

    switch (digits(round3(¢))) {
      case -1:
      case 0:
        return "%.3f";
      case 1:
        return "%.2f";
      case 2:
        return "%.1f";
      default:
        return "%.0f";
    }

````
should not be sorted.

**Comment by yuvalsimon** [comment]
How should I sort it then? according to the rules I wrote in #861 it should be sorted. 
What about
switch (digits(round3(¢))) {
      case 2:
      case 0:
        return "%.3f";
      case 1:
        return "%.2f";
      case -1:
        return "%.1f";
      default:
        return "%.0f";
    }

**Comment by yossigil** [comment]
If these are numbers they should be sorted numerically

**Comment by yuvalsimon** [comment]
Do you want me to do it? You did not say to enable this tipper in #1160.
So if a branch has two cases on it such as `case 2: case 1:` I'll treat it has a branch with only `case 1:` for the sorting (the minimal number).

**Comment by OriRoth** [comment]
Consider more flexible implementation, so Yossi will be able to edit it without going into implementation details. For example, defining `Comparator`s as a static final array.

**Comment by yossigil** [comment]
Yes... It should take 5 min, not even worth discussing

**Comment by yuvalsimon** [comment]
Alright, I made it easier to changes priority order, you just have to change the order in the priorityOrder array. I will add documentation for this class and comparator for sorting by numeric value of cases. The current order is I wrote in #861.

**Comment by yossigil** [comment]
Great. Now finish the mission

**Comment by yuvalsimon** [comment]
I'll add the documentation as part of the todos I already in switchBranch class. I also had to fix the depth calculation, I used some function that did not do what I thought.
