### ISSUE TITLE
"Ignore" tests need reviewing

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1148]
`trimmingOf(...).stays()` has a serious bug- it does not report failures in `Trimmer`, thus a test may pass when the tipper fails to some exception. I think I wrote `stays`, and at the time of its creation it was not a big issue. It clearly needs reviewing, while improving `Trimmer`'s exceptions report capabilities (listener?).

*Note*: it is now being used, for example, in `ExamplesTests`

**Comment by yossigil** [comment]
@yuvalsimon : please lead the discussion with Doron. Ori: give them tips on cost, etc.

**Comment by OriRoth** [comment]
"cost"?
In my opinion the best way to implement this is with a listener. This listener would record exception thrown by tippers.
* Should be added in `Trimmer` and invoked in `Trimmer#consolidateTips` and `Trimmer#makeTipsCollector` (I believe).
* Probably would be a `Consumer<Throwable>` defaults to `e -> {}` (or null?).
* A good opportunity to make `Trimmer` more configurable and fluent. This is a good start:
```Java
Consumer<Throwable> tippersExceptionMonitor = e -> {};
...
public Trimmer onException(Consumer<Throwable> monitor) {
  tippersExceptionMonitor  = monitor;
  return this;
}
```

**Comment by OriRoth** [comment]
Also fix `doesNotCrash` - same problem, same solution.
