### ISSUE TITLE
Spartanization disabling mechanism problems

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1149]
@yossigil please elaborate. I didn't managed to recreate any problem, so I'll need a code example (with what you are trying to disable + where do you put the disabling comment). It might be OS related, but I don't think so (though I will check it if needed, of course).

**Comment by yossigil** [comment]
Let's close it until I can reproduce. I tried spartanizing the spartan project. You should try doing it once...
