### ISSUE TITLE
Bug in annotation sorting

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1158]
With tipper AnnotationSort:
```
@SuppressWarnings("rawtypes") // TreeBasedTable.create() is defined as such
  @Generates private static <R extends Comparable, C extends Comparable, V> RowSortedTable<R, C, V>
      generateRowSortedTable(R row, C column, V value) {
    return generateTreeBasedTable(row, column, value);
  }
```
goes to
```
@Generates
  @SuppressWarnings("rawtypes") // TreeBasedTable.create() is defined as such private static <R extends Comparable, C extends Comparable, V> RowSortedTable<R, C, V>
      generateRowSortedTable(R row, C column, V value) {
    return generateTreeBasedTable(row, column, value);
  }
```

**Comment by yossigil** [comment]
@kobybs : your help please...

**Comment by kobybs** [comment]
I'm on it.

**Comment by kobybs** [comment]
dear @yuvalsimon  @yossigil 
This bug is not about the sorting but about comments handling, 
which wasn't written by me therefore I haven't achieved much success fixing it. 
please see issue #881

**Comment by OriRoth** [comment]
Not sure about that. Try using `copy.of(...)` instead of `createMoveTarget`.

**Comment by yossigil** [comment]
@kobybs part of the course experience is enjoying fixing bugs you created along your career. We don't want you to miss it, so I place this on your shoulders. Please try to get it over with over the weekend

**Comment by kobybs** [comment]
Probably done, check it out. many thanks to yuval and ori for directions.
