### ISSUE TITLE
Another bug in switch tipper

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1160]
```
public final boolean hasNext() {
    checkState(state != State.FAILED);
    switch (state) {
      case READY:
        return true;
      case DONE:
        return false;
      default:
    }
    return tryToComputeNext();
  }
```
goes to
```
  public final boolean hasNext() {
    checkState(state != State.FAILED);
    switch (state) {
	case READY:
	   return true;
	case DONE:
	default:
	   return false;
	   break;
	}
    return tryToComputeNext();
  }
```
==> Code unreachable error

**Comment by yossigil** [comment]
I take an admin decision: the switch was a nice exercise, both for you and for @OriRoth . In both cases, we ended up with something that does not do us much good, but gives us a lot of pain. So, I would like to disable all switch tippers for now. The whole switch thing has to be redone... 

Only one or two tippers should remain: unite branches with same code, which reduces code size, and perhaps convert `case 1: default:` to `default:`

**Comment by yuvalsimon** [comment]
I fixed it anyway, it is related to other switch tippers as well. The bug probably failed spartanizing of switch statements where last statement was empty case branch, but it is fixed now. I'll disable the tippers you said.
