### ISSUE TITLE
Bug in CasesSplit

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1164]
```
switch(x) {
case 1:
case 2:
  int y = f();
  return y+1;
}
```
goes to
```
switch(x) {
case 1:
  int y = f();
  return y+1;
case 2:
  int y = f();
  return y+1;
}
```
==> Duplicate local variable error

**Comment by yuvalsimon** [comment]
Another bug - for some of your tests when I add default case it throws IndexOutOfBounds exception. For example for
```
@Test public void complexSequencerNotLast() {
    bloatingOf("switch (a()){case 1:if (b()){return c();} else{throw d();} f();case 2:e(); default:}")//
        .stays();
  }
```
I ignore the tests for now.

**Comment by OriRoth** [comment]
No do not ignore them. Why ignoring tests? If we wanted a perfect project we wouldn't write any code.
I'll try solving those issues tomorrow.

**Comment by yossigil** [comment]
Yuval. You are expected to solve this as part of this week mission, so I thought?
