### ISSUE TITLE
Choosing the next step

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Spartanizer#1167]
Hello team.
Passover is right ahead and we need to come up with goals for the following semester, including architectonic changes, UX improvements and new features (may be even a major one).
The following suggestions had been brought up in today's meeting (26/03/17) and here they are:

1. Adding a widget with buttons that will be always in the background and can be used with a hover of a mouse.
2. Adding support for a joystick that can expand or spartan the project, similar to the scrolling method.
With this option we can also add other features than just expanding or spartanizing the code, so this UX feature can be added in addition to others.
3. Finding collateral statements  and switching the order between them to be a "clearer" or "spartanized" one, according to the function we use.
4. Changing the Toolbox - starting one from scratch.
5. Implementing a new "Leonidas" and using it for making a system that will let the user define it's own tippers and expanders.
The purpose of this option is one of a couple in order to make the spartanizer/athenizer accesible and usable for every coder, including the "rookies".
We can also add an instruction infrastructure which will help achieve this goal.

You are more than welcome to add more ideas, or comment on the ones that are described here 💯

**Comment by yossigil** [comment]
Please break this into closeable issues.

**Comment by ravivos** [comment]
described in sprint milestones
