### ISSUE TITLE
Inlining into for loop. 

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#117]
![image](https://cloud.githubusercontent.com/assets/12775400/18227041/fe861f22-7220-11e6-9c68-8dfd0112ca49.png)

**Comment by yossigil** [comment]
Pending #119

**Comment by yossigil** [comment]
Not sure it is related to #119.
it is probably related to the use/define collectors

**Comment by yossigil** [comment]
@OriRoth ???

**Comment by OriRoth** [comment]
I couldn't find these tests in TrimmerTest (renamed?). All tests for issue 54 are currently passing.

**Comment by OriRoth** [comment]
OK I found those tests in IgnoreTrimmerTest... I'll check it out once the project will be buildable.

**Comment by yossigil** [comment]
It is buildable now, I think

**Comment by yossigil** [comment]
@OriRoth: If you write the test cases, I will solve this.

**Comment by yossigil** [comment]
What's up?

**Comment by OriRoth** [comment]
* Test case moved from `IgnoredTrimmerTest.java` to `Issue117.java`.
* Currently passing.
* Changes done in:
  * `haz.java`
  * `searchAncestors.java`
  * `step.java`
