### ISSUE TITLE
Removing a crucial comma  

### ISSUE THREAD

**Issue by orenafek** [SpartanRefactoring/Spartanizer#1181]
For some reason, after applying the plugin in the **entire window**,
This code:
``` java
private File openSourceFile(String className) {
        String path = Paths.get("").toAbsolutePath().toString();
        sourceFile = new File(String.format("%s\\test\\%s.java", path, className));
        return sourceFile;
    }
```
was changed as follows:
``` java
private File openSourceFile(String className) {
        String p$= "" + Paths.get("").toAbsolutePath();
        return sourceFile = new File(String.format("%s\\test\\%s.java", p$ className));
}
```

Zooming in on the bug:
``` java
String.format(..., **p$ className**));
```

notice that the comma between `p$` and `className`, was removed, even though this comma separates between passed parameters.

**Comment by OriRoth** [comment]
Couldn't recreate. Please try doing so again, I suspect the page you tried to spartanize was not saved properly (we should address that, but it is not that crucial). Also tell me please on what version of the spartanizer you are working on (current project? current release? older release?).

**Comment by OriRoth** [comment]
Notice this: normally we would expect `path` to become `p` then `$`. It appears `path` was changed to `p` properly, then we got a one character miss for some reason- you can see the `$` came one character after `p`, so we got a space overridden in line 2 and a comma overridden in line 3!

**Comment by OriRoth** [comment]
*Update*: this is what I get for the current version of the project with all tippers enabled:
```Java
private File openSourceFile(String className) {
  return sourceFile = new File(String.format("%s\\test\\%s.java", Paths.get("").toAbsolutePath() + "", className));
}
```
Notice we can now specify enabled tippers (type `ctrl+alt+q`), so I'll also need to know what tippers you are using.

**Comment by orenafek** [comment]
I'm using the latest version from the market (downloaded **today**).
I've selected `Refactoring->Spartanizer->active window`

**Comment by OriRoth** [comment]
OK then did you managed to recreate the problem? If so please give me the entire code. Also tell me what tippers you are using (`ctrl+alt+q`).

**Comment by orenafek** [comment]
After applying 'active window' I have "ctrl+1"'ed until I could do it anymore ....
