### ISSUE TITLE
Eclipse Neon @ char open spartanize preference dialog

### ISSUE THREAD

**Issue by integrys-net** [SpartanRefactoring/Spartanizer#1182]
![eclipse-neon_at-symbol_open_spartanization_preferences_dialog](https://cloud.githubusercontent.com/assets/4998790/24424720/f141c37e-1401-11e7-8a04-521497d476ea.png)
In eclipse neon when press `ctrl+alt+q` with keyboard setted for italian layout with 142 keys, this keys combination open spartanize preferences dialog, if i insert `@` in editing java or xhtml editor.
This issue isn't happen with eclipse mars

**Comment by OriRoth** [comment]
Hi! Thanks for posting your issue. I found a nice solution:
1. Access the key-binding menu via `Window --> Preferences --> General --> Keys`.
2. Remove filters from search: `Filters...` --> Uncheck all.
3. In the search bar (in the top of the window, just below `scheme`) type `ctrl+alt+q`.
4. You should see all key bindings for this combination. You may remove/edit at will- then press `OK`. The changes should be applied imminently.

So, did it work?

**Comment by integrys-net** [comment]
Thnx a lot for your fast reply, i've changed the key combination associated with preferences dialogs. Now works correctly
