### ISSUE TITLE
How to use the standart Java compiler on eclipse

### ISSUE THREAD

**Issue by orenafek** [SpartanRefactoring/Spartanizer#1185]
when trying to fire 
``` java
ToolProvider.getSystemJavaCompiler();
```

i'm getting a NPE.
(on IntelliJ, I get the default's compiler object)

After Some research online, it seems that this issue could be raised when running under the JRE and not the JDK. 
Any thoughts ?

**Comment by orenafek** [comment]
This problem blocks #1183
@yossigil  FYI

**Comment by yossigil** [comment]
No idea

**Comment by OriRoth** [comment]
Where do you try to invoke it? How do you run your code?

![picture](https://cloud.githubusercontent.com/assets/15183108/24456884/151e44f2-149d-11e7-812c-2f1c0b3422d9.jpg)

**Comment by yossigil** [comment]
Perhaps you can make an issue and a test case, and then, we can see whether it depends on linux/windows/etc. test case will just make sure the compiler exists and does not throw an exception

**Comment by orenafek** [comment]
Fixed. It turns out that on every IDE one should specifically ask to run using the JDK otherwise it takes the JRE as the default (hence it makes the Compiler unreachable)
