### ISSUE TITLE
Put spartanization range and marker range in markers

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1186]
For:
```Java
try {
  f();
} catch (CoreException e) {
  monitor.log(e);
}
```
`e` was marked for spartanization but applying the tip did nothing. The problem is that we want to mark `e` but to spartanize the entire catch clause. The obvious solution would be to store "spartanization range" alongside existing "marker range" within spartanization markers.

This is a problem with `CatchClauseRenameParameterToIt`, and for now the tipper is invoked on the entire catch clause.

@yossigil this is the bug we observed, I believe the above solution would be fine.

**Comment by yossigil** [comment]
Good point.
