### ISSUE TITLE
Fix bug in Proposition

### ISSUE THREAD

**Issue by oran1248** [SpartanRefactoring/Spartanizer#1187]
Create a new list instead of changing it.

**Comment by OriRoth** [comment]
Did you fixed the bug? When committing with message containing `fix`/`close` then an issue reference, GitHub automatically closes the issue.

**Comment by oran1248** [comment]
I don't know if this is the only bug in Proposition class but yes, i fixed that bug.
I'm familiar with option for commiting+closing an issue but i thought (for some reason) that it will close it with this message too.

**Comment by yossigil** [comment]
:100:
