### ISSUE TITLE
Batch testing

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1190]
Make a simple batch tester that runs the spartanizer on itself with no errors nothing else.

**Comment by OriRoth** [comment]
@yuvalsimon has added an Exception listener to `Trimmer` while working on #1148 , it should be helpful.

**Comment by ravivos** [comment]
@oran1248 
runTheSpartinizerOnItself is failing

**Comment by oran1248** [comment]
That's because the spartinizer has bugs, the test is good and fulfill its purpose

**Comment by OriRoth** [comment]
You are throwing `assert false;` when encountering Exception and print the Exception to the console. Maybe it can be improved by wrapping the `AssertException` to show the caught Exception's stack trace + description (so it will be easier to fix by people not familiar with the mechanism).

We can also think about making tests out of failures automatically - I wrote some code that does that at the time that creates tests of the form `trimmingOf(...).doesNotCrash();` from Exceptions + code (which we have during Spartanization).

@yossigil do you want to stop Spartanizing when encountering an Exception, or continue Spartanizing until finished then do something with the Exceptions caught? Reassign the issue as you please.

**Comment by yossigil** [comment]
It must be configurable. In testing you want to abort immediately, but not in plugin

**Comment by yossigil** [comment]
OOPS, in the test, it must be printed, but not abort the test. See MetaTester @orenafek

**Comment by oran1248** [comment]
We want to fail the test to notify that the spartinizer doesnt work. As simple as that. How the printing is going to help us? (except from the stack trace)

**Comment by yossigil** [comment]
The printing should identify the tipper that failed, and the pertinent information, on which input and maybe more. Stack trace does not help.


Without this, the fix would be tough. It would be useful to get a summary of all faiing tests in the batch.

Ori once wrote something that converts a failing test into a generated test unit.
