### ISSUE TITLE
Explore javap

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1191]
take a java program, and
1. sparranize
2. compile, javap, spartanize
3. compare

**Comment by oran1248** [comment]
@yossigil 
Exploration results:
1. You cannot get an original java code from a class file using javap.
2. I found this java decompiler: [http://jd.benow.ca/](url). I tried it, works good.
It generates original java code from a class file, so step 3 result will be that **there is no difference**...

**Comment by yossigil** [comment]
@oran1248 please communicate your finding to @orenafek he would need this for the MetaTestsr

**Comment by oran1248** [comment]
@orenafek , see my findings above. if you need more information feel free to contact me :)
