### ISSUE TITLE
"Build Me" Wiki - command line instructions for downloading, building and testing

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1193]

**Comment by OriRoth** [comment]
@ravivos Saluton! I am planning to start cleaning the wikis. If you started this wiki/going to, please send me it's name so I won't remove it.

**Comment by ravivos** [comment]
[Install Me](https://github.com/SpartanRefactoring/Spartanizer/wiki/Installation-instructions) includes also a "build me" part, because I think both come hand in hand for developers.
Of course it can be separated but this will be your (@OriRoth) choice according to #1210
