### ISSUE TITLE
"Continuous Integration" Wiki

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1194]

**Comment by NivShalmon** [comment]
@yossigil can you clarify what this wiki is about? I'm not sure what I'm supposed to write here

**Comment by yossigil** [comment]
Brief doc. We should get started with codecov, to examine your code only, see at other groups. 
What do we do when the CI breaks?

**Comment by yossigil** [comment]
@NivShalmon  perhaps it is better if @ravivos does this? He may need this to monitor the work?

**Comment by OriRoth** [comment]
@NivShalmon Saluton! I am planning to start cleaning the wikis. If you started this wiki/going to, please send me it's name so I won't remove it.

**Comment by ravivos** [comment]
Done along with @NivShalmon - [link to wiki](https://github.com/SpartanRefactoring/Spartanizer/wiki/Continuous-Integration)
