### ISSUE TITLE
Bug in SingleFlater (or AbstractPattern?)

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1198]
AbstractPattern applys the tip on the node in the field _current_, and in the current implementation of InflaterProvider you firstly find all the bloaters in the ast tree that can be applied on some node and then make another iteration to call the _go_ method, but AbstractPattern uses this field in the _go_ method and does not use the node passed from the _Operation_ struct (only asserts that _current_ equals to the argument), so you have to apply the _go_ method in the same iterateration you check the bloater. (_Trimmer_ uses single iteration so it works for tippers)

For example the bloater _SwitchAddDefault_ for the code `switch(a){ case 1: switch(b){ default: } }` is checked on the outside SwitchStatement node and is added to _operations_ list in _SingleFlater_ (because the preqruisite is true) and then it is checked on the inner SwitchStatement node and the preqruisite is false, but still _current_ field of _SwitchAddDefault_ is the inner SwitchStatement node so in the second iteration `assert n == current();` in AbstractPattern.tip() fails. 

I think we made two iterations to work only on the original ast and not on nodes that were expanded before that.

**Comment by yuvalsimon** [comment]
** The bug is in SingleFlater.go()

**Comment by yuvalsimon** [comment]
Ok it works now but I had to add SetCurrent method to AbstractPattern @yossigil , to replace it with the correct node in the second iteration.

**Comment by OriRoth** [comment]
*Analysis*: (some) tippers are now stateful (AbstractPatterns). We do not have any issue with it in Trimmer because the tipper is fired right after being checked. In SingleFlater on the other hand, we check multiple nodes before firing on one of them, so the state is corrupted. Seems @yuvalsimon has fixed it.

**Comment by yuvalsimon** [comment]
Actually it might be a more serious problem because we use fields of subclasses of AbstractPattern to save fields of actual ASTNodes, such has `Expression left` field for left handside of an InfixExpression node. Since we initialize them in the preqruisite they are corrupted as well, but it would be a problem to restore them.
