### ISSUE TITLE
Resolve failing tests in Issue #711 (currently ignored)

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1203]

**Comment by ravivos** [comment]
@danabra there's a bug in your issue, please fix if possible 😄

**Comment by yossigil** [comment]
@danabra :  I know it feels awkward but that's the way it is ... there is special "joy" and experience of fixing dusty code. So, this is yours.

**Comment by danabra** [comment]
Not awkward at all, mistakes can happen. I'll fix it.

**Comment by yossigil** [comment]
:100: @danabra @tanyabrokhman

**Comment by danabra** [comment]
Done.

**Comment by yossigil** [comment]
Good job @danabra
