### ISSUE TITLE
Resolve failing tests in GuessedContextTest (currently ignored)

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1204]

**Comment by NivShalmon** [comment]
I've solved the tests I could, but some tests just don't make sense, such as a public final variable declared inside a method, afte an assignment to it, and I just couldn't figure out what those tests are supposed to do. Didn't delete them yet, @yossigil can you go over them and see if you know what they are supposed to test, you are written as the author and @yuvalsimon who has them as TODO's had no idea what to do either

**Comment by NivShalmon** [comment]
Managed to figure out what is going on in those tests just now, and now it cannot parse.
The problem seems to be the fact that there is a constructor in the test, and our parser doesn't know how to handle that. @yossigil what should I do with the remaining tests?

**Comment by yossigil** [comment]
Wrap in class. There is no way to know a method is a ctor without the wrap

**Comment by NivShalmon** [comment]
I've deleted one test which is complete gibrish, and solved everything else

**Comment by yossigil** [comment]
:100:
