### ISSUE TITLE
Suspected Spartanization Bug - Variable Renaming In Lambda Expressions

### ISSUE THREAD

**Issue by dngreenst** [SpartanRefactoring/Spartanizer#121]
Think n should have been rewritten in the enclosed function, too.

<img width="960" alt="spartanizationbug" src="https://cloud.githubusercontent.com/assets/20325207/18233753/110977c0-72f8-11e6-864b-fe7c32dceafd.png">

**Comment by yossigil** [comment]
This can only be resolved with your environment information

**Comment by yossigil** [comment]
@dngreenst : what's your exam schedule?

**Comment by dngreenst** [comment]
Tommorow afternoon, and the 27th.

**Comment by yossigil** [comment]
@dngreenst : you do not get paid by the hour. When you can do it is irrelevant. The question is whether you can, or cannot do it.

**Comment by yossigil** [comment]
A proper answer would be: 

1. Can't do it
2. It will be done by XXX.

**Comment by dngreenst** [comment]
Conclusions:

1. I can't recreate the original bug. I theorize that it occurred because we had other compilation issues in that file, when we found the bug. 

2. There is a real renaming bug, but that is truly Environment related. For example:

`  class A{
    class B{
      int t;
      B(int t){
        this.t = t;
      }
    }
    B f(int t){
      return new B(t){
        int g(){
          return t*t;
        }
      };
    }
  }`

is changed into:

`  class A{
    class B{
      int t;
      B(int t){
        this.t = t;
      }
    }
    B f(int i){
      return new B(i){
        int g(){
          return i*i;
        }
      };
    }
  }`

The "t" in the method "g" should have not been renamed. But, as you wrote in the head of this issue, this is not a thing we can solve without an Environment. 

I suggest we close this issue, and add this wring to the list of after-Environment TODOs.

**Comment by yossigil** [comment]
Good to have this off our heads. When you get a chance, ie after the exams, add a test to this effect.

**Comment by OriRoth** [comment]
Test class `Issue121.java` has failures. @dngreenst do you think you can solve it?
