### ISSUE TITLE
Wiki User Manual Review

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1210]
Maybe move to archive

**Comment by OriRoth** [comment]
YES! We should do that before the next release. I am planning to remove all wiki pages, then reconstruct:
* User manual
* Developer manual
* Theoretical background

@yossigil what is the "archive"? Also, d you mind I'll get someone to help me with this?

**Comment by yossigil** [comment]
There are the demo classes.

**Comment by OriRoth** [comment]
Cool trick: one can `git clone` wiki pages by changing `.git` extension in our project's URL to `.wiki`:
`git clone https://github.com/SpartanRefactoring/Spartanizer.wiki`

**Comment by OriRoth** [comment]
Incomplete wikis:
* https://github.com/SpartanRefactoring/Spartanizer/wiki/Installation-instructions

**Comment by yossigil** [comment]
@SpartanRefactoring/zoomers
