### ISSUE TITLE
A JAVA-SWT Wiki 

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Spartanizer#1216]
Wiki about getting started with GUI

**Comment by yossigil** [comment]
Talk to @ortroyaner , he is  an expert @tanyabrokhman : FYI

**Comment by OriRoth** [comment]
This would include mostly GUI features of Eclipse (handlers, bindings, plugin definitions) and inter-project utilities, so standard SWT will not fit exactly... I myself worked for some time with Eclipse GUI, yet I am pretty clueless with SWT, unfortunately.

**Comment by ravivos** [comment]
[link to wiki](https://github.com/SpartanRefactoring/Spartanizer/wiki/Java-SWT-For-Eclipse-Plugin-Widgets)
