### ISSUE TITLE
GUI for class JUnitTestMaker

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1217]
I want the input and the outputs in a dialog box

**Comment by OriRoth** [comment]
This is internal GUI, you may choose to do it in JavaFX or whatever. Anyway, you'll start from scratch (Except for `JUnitTestMaker` of course).

**Comment by OriRoth** [comment]
Also, you may use some sort of configuration in your dialog:
1. Maximal number of spartanization pass (1 to infinity) (i.e. how much `gives` do you use).
2. Whether to end the test with `.stays()` (toggle).
3. Whatever you want.

**Comment by ravivos** [comment]
starting to look nice with SWT and @tomerdragucki 
<img width="1174" alt="screenshot 2017-04-04 15 50 37" src="https://cloud.githubusercontent.com/assets/7875588/24657373/a1a95866-194e-11e7-83d6-470436ed3509.png">

**Comment by yuvalsimon** [comment]
@yossigil Can you give me some GUI issue to get started with it too please?
