### ISSUE TITLE
Fix new bloater implementations

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1221]
New implementations of IfElseBlockBloater and OutlineTernaryMethodInvocation failed tests, I kept the original implementations, you can find yours' in git history. It is low priority though because the original implementations work..

**Comment by OriRoth** [comment]
Check whether it is a bug with the `AbstractPattern` mechanism....

**Comment by yuvalsimon** [comment]
It is not, I already checked. I think one of the problems is that some preqruisites are checked in the `go` method and after calling it other expanders can not be called on this ast node

**Comment by dormaayan** [comment]
Done
