### ISSUE TITLE
Custom widget operation

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1227]
Run user command as in cmd on click. Should be supported in the preferences page (i.e. String editor field or whatever + multiple commands).

**Comment by OriRoth** [comment]
Not on hold!

**Comment by yuvalsimon** [comment]
@OriRoth I you meant to open a text window to execute a single input command right?

**Comment by yuvalsimon** [comment]
It looks like that now: 
![image](https://cloud.githubusercontent.com/assets/17455055/25534573/d6125ed0-2c3c-11e7-9f92-9a337d7918eb.png)
and executes a single command and will show the output in new window

**Comment by OriRoth** [comment]
NO, the user would predefine the command, so just specify your widget operation to come with a String condiguration. Nothing like this, anyway.

**Comment by yuvalsimon** [comment]
I think it can be a nice widget operation as well, and I'm almost done it. I'll finish it and write another operation that will do what you meant in the issue

**Comment by OriRoth** [comment]
This is his responsibility, you may close this issue. Be sure you've registered the operation in `plugin.xml`.

**Comment by OriRoth** [comment]
למה אתה פותח חלון גוי? אמרנו שלא עושים את זה.

**Comment by yuvalsimon** [comment]
I wrote two widget operations, one is using gui and the other uses the preferences page to ge the commands to run.
