### ISSUE TITLE
Bug in tippers preferences

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1234]
When seleting tipper categories in _Spartanization Preferences_ window and then restarting eclipse it does not show tips for the selected categories (which are not default) although they are still selected.

**Comment by OriRoth** [comment]
@yossigil why did you opened this issue? I identified the bug in `Builder` class and fixed it.

**Comment by yossigil** [comment]
OOPS, sorry
