### ISSUE TITLE
making a wiki about handling build errors with travis

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Spartanizer#1236]

**Comment by OriRoth** [comment]
Put it under "Developer Guide"

**Comment by ravivos** [comment]
Done - https://github.com/SpartanRefactoring/Spartanizer/wiki/Fixing-Build-Errors---Travis

**Comment by OriRoth** [comment]
Please put it in the home page, otherwise no one is going to use it.

**Comment by ravivos** [comment]
Already there
