### ISSUE TITLE
Adding CodeCov to CI

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Spartanizer#1237]

**Comment by ravivos** [comment]
Might be an internal problem with the system:

- [https://github.com/cobertura/cobertura/issues/223](https://github.com/cobertura/cobertura/issues/223)
-[https://github.com/cobertura/cobertura/issues/176](https://github.com/cobertura/cobertura/issues/176)

Meanwhile I fixed the build but I will remove it if the problem comes back.
The CI doesn't look like it does soe thing with the CodCov, @OriRoth What do you think?

**Comment by OriRoth** [comment]
By inspecting Travis' error log it seems your tool is not configured for Java 8 (does not recognize `default`, confused by `>` which may be a part of lambda expression etc.).

**Comment by OriRoth** [comment]
Also check UTF-8 stuff for Greek letters.

**Comment by ravivos** [comment]
From searching the web I found out that it is probably because of java8 lambda functions, as the links I added as a comment say.
But I didn't find a solution yet, just the cause

**Comment by OriRoth** [comment]
Your changes to `pom.xml` cause warnings, please notice.
