### ISSUE TITLE
Add exclusion manager to athenizer

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1241]

**Comment by OriRoth** [comment]
@yuvalsimon can you give a concrete example?

**Comment by OriRoth** [comment]
OK fixed it in 1bcb4b1. @yuvalsimon please add tests or close the issue.

**Comment by yuvalsimon** [comment]
It works, before that the bloaters for renaming renamed the variables partially as other bloaters worked on same nodes, now it's not doing that.
