### ISSUE TITLE
Change project name to Athenizer

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1243]
- Triage
- Add info
- Open issues for changing class names (set policy? meeting? dictatorship?)

**Comment by OriRoth** [comment]
Dictatorship?! I thought we are Democratic People's Republic of Spartanizer.

**Comment by ravivos** [comment]
Going for dictatorship:
Tippers stay tippers, zoomers stay zoomers, The name of the whole project is Athenizer and it includes the option of zooming, tipping, has the zooming in and out option with the mouse and a GUI which is TBD.

this will be added to the project info
