### ISSUE TITLE
Modernize StringBuilder tipper

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1247]
- [x] Find the tests in Version290.java
- [x] Try to make the tip do as little as possible and use subject, and other classes.
- [ ] Try to use recursion

Only let me know when you are done

**Comment by yossigil** [comment]
Here is an example 
	return new StringBuilder(maxLength).append(s, 0, $).append(truncationIndicator) + "";

**Comment by OriRoth** [comment]
@yossigil Done. Please check the (modified) tests at `Version290.java` to see whether I messed things up.
The tipper is now a `ClassInstanceCreation` tipper with extended span/highlight.
