### ISSUE TITLE
SwitchAddDefault keeps on sending tips and markers. It should be only on athenizer

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1248]
![image](https://cloud.githubusercontent.com/assets/12775400/24954363/c9a09818-1f87-11e7-9ecd-a55074e211da.png)

Please put a fire wall between the bloaters and the spartanizer

**Comment by yossigil** [comment]
Yuval. Please finish this asap

**Comment by yuvalsimon** [comment]
@yossigil I don't see it, works fine for me. This expander is only in athenizer, not in _Configurations_, what's the problem you mean?

**Comment by yossigil** [comment]
Ori and I disabled your code. Check history of this issue

**Comment by yuvalsimon** [comment]
I see that you deleted _default_ case that was added in the commit above. Eclipse marks it as specified in the project properties:
![image](https://cloud.githubusercontent.com/assets/17455055/25201207/a24dcc86-2559-11e7-9fe0-7503a2c98294.png)
It is not related to the expander.

**Comment by yuvalsimon** [comment]
@yossigil Is it alright? May I activate the bloater and close the issue?

**Comment by yossigil** [comment]
The eclipse thing is unrelated. Why did you mention this?

**Comment by OriRoth** [comment]
@yossigil he claims you see Eclipse's marker proposition, not our marker (notice different projects may define different warning preferences).

This tipper is no longer in `Configuration`, so @yuvalsimon you may close this issue.

**Comment by yossigil** [comment]
Will reopen if pops again
