### ISSUE TITLE
Marked code without any suggestions 

### ISSUE THREAD

**Issue by orenafek** [SpartanRefactoring/Spartanizer#1251]
Latest version of Spartanizer Installed. This is what I get after trying to hit `ctrl + A` and `ctrl + 5` several times and nothing is happening at this point.

![image](https://cloud.githubusercontent.com/assets/15859817/24971115/74dc4b28-1fbf-11e7-9a5d-306383260375.png)

**Comment by OriRoth** [comment]
Could not recreate in either current release/current project build. Please elaborate:
1. What version of the plugin are you using? You can check it via `Help -> Installation Details`
2. What tip is it? You may type it's description
3. Try save the file then refresh and see whether the tip disappears
3. Next time, please copy-paste relevant code (at zero cost), I had to type it by hand:
```Java
private List<String> tests(List<String> prefixes) {
  final Int $ = Int.valueOf(0);
  return prefixes.stream().map(λ -> String.format("@Test public void test%d(){\n\t%s\n}", $.next(), λ))
      .peek(System.out::println).collect(Collectors.toList());
}
```
