### ISSUE TITLE
MetaTest fails.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1253]
Running tests on eclipse not intellij yields faults.

**Comment by orenafek** [comment]
Can you specify which test file you've tried to run with the meta tester?
because running both `PropositionTest` yields no errors at all in my working env.

**Comment by yossigil** [comment]
]run this under eclipse not intellij, and show me screen capture

**Comment by yossigil** [comment]
?

**Comment by orenafek** [comment]
![image](https://cloud.githubusercontent.com/assets/15859817/25190364/a82e0758-2534-11e7-9bfd-3391a1e763f4.png)

**Comment by yossigil** [comment]
I trust you can find ways to reproduce the bug, since it occurs all the time.
Try Linux

**Comment by yossigil** [comment]
![image](https://cloud.githubusercontent.com/assets/12775400/25194078/ea9be440-2541-11e7-8764-88f098b9f890.png)

**Comment by orenafek** [comment]
By reading the stack trace it seems that i don't have permissions to create a temp file in Linux.
Working on acquiring those permissions or finding a workaround

**Comment by OriRoth** [comment]
@ravivos Oren is in PAGRA this week, FYI.

**Comment by ravivos** [comment]
Hey @orenafek, enjoy in Rome.
Im gonna take this one on my self because Im challenged

**Comment by ravivos** [comment]
![screenshot 2017-04-30 16 18 22](https://cloud.githubusercontent.com/assets/7875588/25564657/b4aee6a2-2dc0-11e7-9461-502aa07922f2.png)
found our villians - @AmitOhayon, @tonylekhtman, @yosefraisman ❤️
