### ISSUE TITLE
Test run is not clean

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1254]
Running tests does not give clean output

**Comment by yuvalsimon** [comment]
@yossigil do you mean to clean the System.out.println ? Do you want no output at all, except for the quickfix?

**Comment by yossigil** [comment]
I think this was said many times before, but, yes.
ZERO OUTPUT. ZILCH if the build is clean.

**Comment by ravivos** [comment]
Im already fixing up some tests so I will also clean everything up

**Comment by ravivos** [comment]
All Done, Let's keep our test run clean guys, It's in our standards
