### ISSUE TITLE
Bug with inlining increament/decreament

### ISSUE THREAD

**Issue by NivShalmon** [SpartanRefactoring/Spartanizer#1255]
```
int $ = f(x);
++$;
return $;
```
turns to
```
int $ = f(x) + 1;
return ++$;
```
seems like issue #1146 is working at the same time as a tipper that inlines increment/decrement into a return, and one of them doesn't block spartanization on the increment, which causes them both to act at once.

**Comment by yossigil** [comment]
Check out the "span" and "highlight" make sure that the span of both tippers is defined to include all nodes they work on
