### ISSUE TITLE
bug in subject/plant

### ISSUE THREAD

**Issue by NivShalmon** [SpartanRefactoring/Spartanizer#1257]
when using subject operands on the expressions `(0)` and `(++b)` with operator +, the result is `0+++b`.
however, this does not compile, as it is considered as 0 with postfix increment added to b.  If 0 is replaced with a variable the code compiles, but gives the wrong result. This is most likely a problem with plant, that removes parenthesis when it shouldn't be removed.

**Comment by OriRoth** [comment]
They can be removed, the problem here is with the missing space: `0+ ++b` should compile just fine I think...

**Comment by NivShalmon** [comment]
adding a space does solve this. question is, how do we add space to the code from the ast?

**Comment by OriRoth** [comment]
First we should revise the current code to see if everything is being done correctly. if it is not our bug, it is Eclipse's... and we'll have to deal with it somehow.

**Comment by NivShalmon** [comment]
Doesn't seem like we can do much about this in our code. I think that using` rewriteAST(IDocument document, Map options)` may allow us to set an option to add spacing, but haven't found one yet (still looking). @OriRoth @yossigil I don't know much about our use of rewitreAST. Would it be possible to convert to using this version of the method? right now we are using the version with no arguments, and I'm not sure if have access to the IDocument object needed.

If this doesn't work, the only other idea I can think of is to warp the prefix expression in parenthesis

**Comment by yossigil** [comment]
I created a unit test and marked it `@Ignore`. Closing this for now.
