### ISSUE TITLE
Make some default reducers

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1260]
- [x] List<T> reducer
- [x] String reducer
- [x] T reducer. Find the first element. findFirst reducer
- [ ] Boolean reducer. Or. Null is considered false. in fact this is the same as T reducer,
for a type T that has only two legal values: null, and some other value. Your best bet
for Or reducer is T reducer with Outer<Void>
- [x] Count reducers with integers.

**Comment by yossigil** [comment]
merge into current code, see where it was used.
eventually, we will go into file/folder/location/batch reducer.

**Comment by oran1248** [comment]
@yossigil , I didn't understand why Boolean Or reducer needs to use T reducer.
Why not just return Or result?

**Comment by yossigil** [comment]
Because you need two valued type,and Boolean is three values: TRUE/FALSE/Null.
Use Outer<Void>

**Comment by oran1248** [comment]
So I will just consider Null as false.
Also, T reducer returns the first element that is not Null, and that's not what I need here, I think.
Please clarify.

**Comment by yossigil** [comment]
Oran - this is exactly OR. First element which is not false

**Comment by oran1248** [comment]
I agree, so why not just write
`return Boolean.TRUE.equals(r1) || Boolean.TRUE.equals(r2);`
?
T reducer returns the first element which is not **Null** and not the first element which is not **false**.

**Comment by yossigil** [comment]
כי אני מבקש לפשט את הקוד כך שלא יהיה צורך לחשוב על שאלות של 
NULL

**Comment by oran1248** [comment]
I still don't get it.
Can you give me a snippet?

**Comment by yossigil** [comment]
Use this class for T. Do **not** try to understand it. Just **do** it.
```java
class Binary {
}
```

I will try to push it. DO NOT TRY TO UNDERSTAND IT.

**Comment by oran1248** [comment]
Do you mean That BooleanOrReducer will extends Reduce<Binary>?

**Comment by yossigil** [comment]
I mean that you need to be more independent, and figure out some questions yourself.
