### ISSUE TITLE
TraversalMonitor with explanations.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1264]
Challenge: the monitor should explain **why** a tipper did not produce a tip.

Each abstract Pattern has a prerequisite which is a symbolic proposition.
Your task is to evaluate the proposition symbolically, and print the result, explaining why
the tipper did not work.
Result of each component should be one of:

1. True
2. False
3. X - general error
4. N = null pointer exception

The proposition is a tree. You should print the value and name of each leaf.

A  || B && C

A = T 
B = X
C = N.
B && C = X.
A || (B&&C) = T

**Comment by oran1248** [comment]
It cannot explain why a tipper did not produce a tip, but if `prerequisite(c)==false` it can explain it by displaying the evaluation tree.

**Comment by OriRoth** [comment]
If the tipper is written properly (using `prerequisite` / `AbstractPattern`) (not necessarily bug-less), the only reason for tip failure would be an exception thrown- and that would be documented by other means.

In other words: in the past, tippers had only *one* method that returned a tip (=> tipping is possible) or `null` (==> tipping is not possible). Nowadays, `prerequisite` tells us whether a tipper can be applied to some node, and `tip` produces the solution. `tip` should not return `null`!! ever. If the tipper has been written properly, all relevant checks are done in `prerequisite`, while `AbstractPattern` / statefull tippers saves us repetitive computations. `CarefulTipper` and such exists for legacy solely.

**Comment by oran1248** [comment]
Correct me if i'm wrong, but only `NodePattern` has `prerequisite` field, and there are tippers without it.

**Comment by OriRoth** [comment]
This is a method of `CarefulTipper` and it's son `AbstractPattern`.

**Comment by OriRoth** [comment]
Ah ok I get you... yes the field is located in `AbstractPattern`, `CarefulTipper` and others are legacy.

**Comment by oran1248** [comment]
I think there is no more `AbstractPattern` class, not it's called `NodePattern`.
So, if i want to display the prerequisite logic tree, i can do it only for `NodePattern` type.

**Comment by yossigil** [comment]
I renamed the class it is the same

**Comment by oran1248** [comment]
@OriRoth , I commit some changes in comments for project safety reasons. can you please review them and tell me what do you think?

**Comment by OriRoth** [comment]
You modified the default listener, which means the operations you added in `TraversalMonitor` are called many times per spartanization run (and they are quite heavy)... try checking whether you can question `Logger` to see if the current `Level` is loggable, otherwise don't do the computations (in `tipperRejects`).
Otherwise looks cool.

**Comment by oran1248** [comment]
commit in [fluent.ly](https://github.com/SpartanRefactoring/fluent.ly)

**Comment by OriRoth** [comment]
@oran1248 in order to apply your changes in the Spartanizer, `mvn package` it and put in `Spartanizer/lib`. Currently I and @RoeiRaz are working on putting `fluent.ly`, `Spartanizer` and other relevant projects under one parent-project, so after we're finished you'd be able to see your changes immediately.

**Comment by oran1248** [comment]
@OriRoth , **DONE**
