### ISSUE TITLE
Bug in apply tipper to all

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1269]
It should display the tipper's name, and apply only this tipper. Currently, it applies **all** tippers

![image](https://cloud.githubusercontent.com/assets/12775400/25279571/85c66102-26af-11e7-9c28-8403faa0079f.png)

**Comment by OriRoth** [comment]
Thank you for noting me. It is now solved (I hope so :P).

![pic](https://cloud.githubusercontent.com/assets/15183108/25282308/c37ece22-26b8-11e7-9f4a-fc84308d6080.jpg)

**Comment by OriRoth** [comment]
If you want it to look differently, please tell me.
