### ISSUE TITLE
ParameterAbbreviate throws exception

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1270]
While adding markers to JUnit4, for example.

**Comment by OriRoth** [comment]
@yossigil reassign this if you have a suspect. Otherwise @ravivos reassign.

**Comment by yossigil** [comment]
Can anyone produce a unit test, or specify more information

**Comment by OriRoth** [comment]
It is a bit difficult, because the logger does not give much information except the culprit... I'll try to get some examples, look for `Issue1270.java` later today.

**Comment by OriRoth** [comment]
OK made some tests. It's simple: the tipper does not deal with abstract method declarations in abstract classes / interfaces. Shouldn't be complicated... @ravivos reassign this to someone.

**Comment by yossigil** [comment]
I fixed the bug. Raviv is asleep.
