### ISSUE TITLE
Metrics, flowerishness  and dexterity: Implement recursive services

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#128]
In package ast, I woould like to see an interface metrics,
with methods such:

- length(ASTNode n), total number of characters in a compressed printout
- identifiers(ASTNode n) how many identifiers were mentioned in the tree
- nodes(.._) How many nodes in the tree
- internal(.._) How many internal nodes in the tree
- leaves(.._) How many leaves in the tree
- flowerishness(...) How many distinct identifiers were used
- dexterity(how many distinct kinds of nodes in the tree). Each keyword should be counted as a token.

**Comment by yossigil** [comment]
All these are to be implemented by your recursing class....

**Comment by dormaayan** [comment]
@yossigil  :

On length : can you please clarify what do you mean by 

> number of charcters in the compressed printout

Is that mean I need to return the total length of a string that represents the AST (for example, an expression) ?

**Comment by yossigil** [comment]
After I got you hooked, can you please change to the `[Halstead metrics](https://en.wikipedia.org/wiki/Halstead_complexity_measures)`?
I think there are 8 in total...

**Comment by yossigil** [comment]
Keep the length in characters, just change the name to chars.

**Comment by yossigil** [comment]
TO make this clear:
Operands are identifiers and literals.
Operators are internal nodes.

**Comment by yossigil** [comment]
Can this be closed?

**Comment by dormaayan** [comment]
@yossigil  :

Currently, the interface includes the methods : nodes, internals,leaves and dexterity + tests.
We can keep that for future uses and also as a demonstration of using Recurser.
I close that issue but if you want me to continue, feel free to reopen it.

**Comment by yossigil** [comment]
Thanks. Good job!
