### ISSUE TITLE
ConstructorEmptyRemove bug

### ISSUE THREAD

**Issue by NivShalmon** [SpartanRefactoring/Spartanizer#1280]
don't remove the constructor when other constructors exist, as in this case it can cause complation errors (see Bool for example)

**Comment by yossigil** [comment]
What's with Bool? Why is there a bug with it?

**Comment by NivShalmon** [comment]
The tipper suggests to remove the empty constructor of Bool. Doing that cuases compilation errors, since another constructor exists and the empty constructor is used.

**Comment by yossigil** [comment]
OK. I fixed this.
