### ISSUE TITLE
A stick that brings joy

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1282]
Find a joystick (for Windows?).

**Comment by ravivos** [comment]
I see what you did there...

**Comment by dormaayan** [comment]
@OriRoth : Found a good working JoyStick and started to explore ways to connect it to the plugin

**Comment by OriRoth** [comment]
Show a pic or it didn't happen.

**Comment by dormaayan** [comment]
![img_0747](https://cloud.githubusercontent.com/assets/19957447/25544690/4651a9ae-2c64-11e7-9c73-25bf12f2bf88.JPG)

Are you happy now Mr. GUI ?
