### ISSUE TITLE
TraversalImplementation: tipper->marker->tipper bijection

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1283]
Consider this code: `Integer x = new Integer(new Integer(0));`. The marker appears on the inner-most call, but the tipper applies to the outer-most on quick-fix `apply` option.
@yossigil this is the same issue we talked about, nothing new. Not a blocker though... I hope.

**Comment by yossigil** [comment]
Well, I was thinking of this. I was wondering how eclipse does it. Perhaps you can search the sources.
If not, one can always store another property in the marker: target, which has begin and end. You only match the node, if the target is **identical** to the node.

**Comment by OriRoth** [comment]
We still want to support multiple changes within a certain range, thus my fix proposal `contained` (to check whether the current node is contained in selected range). `whether(¢).in(range())`
If you want me to deal with it you may assign me anytime.

**Comment by OriRoth** [comment]
Consider this case:
```Java
@Override protected void gitOperation(Git g) throws Throwable {
  g.pull().call();
}
```
Only the first `g` is marked, yet it is applied when spartanizing range that does not include it. (for example, when selecting `call`). This is because the *span* of this tipper is the entire method (or something close), thus it is not disjoint with the range of `call`!

Note that I have solved the other end of this buggy stick: when the range does include a marker, I automatically extends it to contain the entire span.

**Comment by yossigil** [comment]
I do not see it as a problem
