### ISSUE TITLE
Tippers serialVersionUID test

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1285]
Create new tippers test: all tippers in `Configuration` (former `Toolbox`) should **not** have a `serialVersionUID` equals to the default 1.
@tomerdragucki add milestone and solve.

**Comment by OriRoth** [comment]
And that they are all different.

**Comment by yossigil** [comment]
@ravivos we need this for stability.

**Comment by ravivos** [comment]
@tomerdragucki is working on it at the moment
