### ISSUE TITLE
Manage our opening page

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1288]
it is much[ too long](https://github.com/SpartanRefactoring/Spartanizer). Break it into references to wikis.

**Comment by OriRoth** [comment]
Looks great 🎉

**Comment by yossigil** [comment]
Sorry to bug you again, I mean horizontal table: like so, but I could not figure it out though:
![image](https://cloud.githubusercontent.com/assets/12775400/25554290/1750e822-2cd2-11e7-96e4-ac34ec26aa6c.png)

**Comment by M4tt30rru** [comment]
Sure, no problem of course.

**Comment by yossigil** [comment]
Keep the video entry, it was my mistake to remove it.

**Comment by M4tt30rru** [comment]
done
