### ISSUE TITLE
Allow plugin contribution to the Spartan Plugin

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1291]
So other plugins can contribute widget operation.

**Comment by OriRoth** [comment]
@AdiOmari I checked the issue, and it is very feasible- that is how you [do it](http://www.vogella.com/tutorials/EclipseExtensionPoint/article.html). Contributing to our extension point is similar to other Eclipse contributions, so there is no problem from the user side.
@ravivos please verify with Yossi (as a client) this is allowed (talk with him later today/other day).

**Comment by OriRoth** [comment]
Done! @dormaayan @NivShalmon  @ravivos @tomerdragucki @yuvalsimon please read the following guide: (convert to wiki?)
**What is going on here?** I have created a new extension point for our plugin, allowing other plugins to contribute us with `WidgetOperation`s. A by-product of this is we should declare new `WidgetOpertaion`s in `plugin.xml` file. Fortunately, this is very simple:
```
<extension point="il.org.spartan.widgetoperation">
	<widget-operation class="il.org.spartan.spartanizer.plugin.widget.operations.RunOperation" />
	<widget-operation class="il.org.spartan.spartanizer.plugin.widget.operations.GitPullOperation" />
	<widget-operation class="il.org.spartan.spartanizer.plugin.widget.operations.GitPushOperation" />
	<widget-operation class="il.org.spartan.spartanizer.plugin.widget.operations.GitCommitOperation" />
</extension>
```

**Comment by AdiOmari** [comment]
@OriRoth well done, I think yossi will like it , we will wait for raviv to update us in this regard.

**Comment by ravivos** [comment]
Very glad to see this!!
Will ask Yossi tomorrow for his opinion/approval.
meanwhile, @yuvalsimon, want to make a short wiki out of Ori's comment?

**Comment by ravivos** [comment]
@AdiOmari , @OriRoth 
I've spoken with our client (Yossi) and he doesn't show interest in it at all.
Infect, he shows disinterest and claims it is not related at all to our project 😞 
I am glad we should it is possible, good job Ori with this research, but I guess the client wants what the client wants so - case closed.

**Comment by OriRoth** [comment]
You should have talked to Yossi earlier. This is already implemented and a vital part of our system. If other teams (BugQuery) want to contribute their operations to our plugin, they definitely can.

**Comment by ravivos** [comment]
Don't worry everything is fine and research is always good and blessed.
I am glad we have the option even if we don't implement it in our widget.
Very Good Job! 👍
