### ISSUE TITLE
fix failing tests for athenizer

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Spartanizer#1293]
fix athenizer related failing tests.
Ignore with a TODO comment the spartanizer failing tests

**Comment by OriRoth** [comment]
There are also failing Spartanizer tests. We should fix all tests if we want to work properly.

**Comment by ravivos** [comment]
I added Todos and ignored the ones which were not related at all to our project.
Remember, That was our client request - focus on the Athenizer

**Comment by ravivos** [comment]
All Done, let's keep that way, shall we? 😄
