### ISSUE TITLE
Bug in ExamplesTests

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Spartanizer#1294]
Should be fixed in order to get trusted results while unittesting and of course a green bar

**Comment by ravivos** [comment]
When you think that you have fixed the problem, you should remove some ignores and comments from tippers.
you can see it in the TODO tasks in "example"

**Comment by OriRoth** [comment]
What problem? You cannot open a bug issue without specifying a problem.

**Comment by ravivos** [comment]
Correct tests fail and I added a TODO for those so you can examine them.
I *did* specify the problem...

**Comment by yossigil** [comment]
I did not see any bugs. It runs cleanly for me. Can you be more specific or give hints

**Comment by OriRoth** [comment]
מה שהולך כאן הוא ממש לא טוב. אני עברתי עכשיו על כל הקומיטים האחרונים שלך בניסיון להבין מה הבעיה. לפי איך שזה נראה, יש דוגמאות ספציפיות שלא בנויות טוב (או יותר סביר, שיש באגים בטיפרים). מה שאתה עשית: למחוק את הדוגמאות. מה שצריך לעשות: לפתור את הבעיות הפשוטות בעצמך, אם צריך לדבר עם האנשים הרלוונטיים ולבקש מהם עזרה.

**Comment by ravivos** [comment]
@yossigil  - it works cleanly now because I disabled it.
@OriRoth  - I deleted the specific examples that were wrong and checked the tippers - there were tippers that worked correctly buy there examples failed - all the examples I commented out and added a todo for you.
I recall @yuvalsimon recognized these bugs even before me and said something about it a week ago.
Yuval, penny for your thoughts?

**Comment by yossigil** [comment]
But, how can I fix the problems if you erased them?

**Comment by OriRoth** [comment]
The rogue commits are: 9a6cd2d9204deeb4a71c9e70d16deeb78d362331, c42fe99e71f5c3169b631ce8665b7261a0c6cfa6

**Comment by yuvalsimon** [comment]
The bloater examples testing class is already fixed. About the spartanizer examples @OriRoth should know whether it is fixed.

**Comment by OriRoth** [comment]
No Yuval this is old news- the test mechanisms are fine now.

**Comment by OriRoth** [comment]
NO bug in `ExamplesTest`. If there is something I missed, reopen this issue and **specify the actual bug please**.
