### ISSUE TITLE
Infinite loops wring

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#130]
In loops such
as 
for (x; /** */ ; y) 
and 
while (true)
and 
do {
} while (true)

any break followed by return should be inlined.

@NivShalmon : interested?

**Comment by NivShalmon** [comment]
I can do this, but it seems that it will get stuck in a loop with #131. For something like this:
```
 while(true){
    doSomething();
    if(done())
      break;
  }
  return something();
```

This wring would turn the break to return, and then #131 will turn it back into a break, since we can't remove this return or the code won't compile. Should #131 only work on non-infinite loops than?

**Comment by yossigil** [comment]
Note that 
```java
 while(true){
    doSomething();
    if(done())
      break;
  }
  return something();
```
is shorter than
```
 while(true){
    doSomething();
    if(done())
       return something();
  }
```
The #131 thing is for the case the loop is not infinite.

**Comment by dormaayan** [comment]
@yossigil : Done
