### ISSUE TITLE
Return from loops, convert to break.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#131]
in loop such as 
```
for (..) {
   asdfasdfasdf
   return XXX;
}
return XXX;
```
convert to the slightly shorter and clearer

```
for (..) {
   asdfasdfasdf
   break; 
}
return XXX;
```
@NivShalmon : interested?

**Comment by dormaayan** [comment]
@yossigil  : 
It seems like working fine, and also pass Spartanization.
I close the Issue.

**Comment by yossigil** [comment]
:+1:
