### ISSUE TITLE
remove protected modifier in final classes

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#135]
- [ ] create a test case

- [ ] fix class remove modifiers

**Comment by yossigil** [comment]
@sakopzon : did you take a look?

**Comment by yossigil** [comment]
@dngreenst : Would  you mind bugging Alex for us? he is holding everyone waiting, for this and other stuff.

**Comment by sakopzon** [comment]
after tomorrow's exam I have a meeting until 2 PM, and after this, it will be the first think I will do.

**Comment by yossigil** [comment]
IN second thought, this request is buggy. If a class is final, it can still have protected methods overriding methods which are protected in the super class.
