### ISSUE TITLE
Ignore spartanization commect-annotation

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#139]
Currently implemented in Trimmer class for BodyDeclaration nodes (classes, methods etc).
Comment-annotation should appear in node's JavaDoc comment (part of its EBNF!).
Usage example:
```
/**
 * [2 spartanization options]
 */
class Debug {
  int f(boolean b) {
    if (b)
      return 1;
    return 2;
  }
  int g(boolean b) {
    if (b)
      return 2;
    return 1;
  }
}
```
```
/**
 * [one spartanization option]
 */
class Debug {
  /**
   * @DisableSpartan
   */
  int f(boolean b) {
    if (b)
      return 1;
    return 2;
  }
  int g(boolean b) {
    if (b)
      return 2;
    return 1;
  }
}
```
```
/**
 * @DisableSpartan
 * [no sartanization options]
 */
class Debug {
  int f(boolean b) {
    if (b)
      return 1;
    return 2;
  }
  int g(boolean b) {
    if (b)
      return 2;
    return 1;
  }
}
```
Open for improvement suggestions. Annotation string "@DisableSpartan" is hard-coded and can be changed (later should be moved to a configuration file):
`public final static String dsi = "@DisableSpartan";`

**Comment by OriRoth** [comment]
Implementation issues:
* Implemented as an inner class in Trimmer class.
* Used before collecting spartanization options in Trimmer's collect and fillRewrite methods: Collects all disabled nodes (= string "@DisableSpartan" in JavaDoc comment), then during spartanization collection phase checks if a node is a decedent of a disabled node- thus disabled itself.

**Comment by yossigil** [comment]
Good job, and right on TIME. We are having problems in managing test cases, so you never know
when the added java code trigger an unsurprised trimming.

But, where is the class?

**Comment by yossigil** [comment]
Can you commit the class and close this issue. We continue with Issue #142

**Comment by OriRoth** [comment]
@yossigil see commit 96021979511d72f4eef14193bcae6865ed3e678b class DisabledChecker is inner class of Trimmer
