### ISSUE TITLE
Environment Test Engine

### ISSUE THREAD

**Issue by sakopzon** [SpartanRefactoring/Spartanizer#140]

**Comment by yossigil** [comment]
@sakopzon : who is in charge? What's the deadline? Should be open/close?

**Comment by dngreenst** [comment]
Currently debugging it. At the moment, there is a problem with equality, as mentioned in #106. I intend to finish this this evening.

**Comment by yossigil** [comment]
:+1:

**Comment by dngreenst** [comment]
Added a function to PrudentType, to generate PrudentTypes from a string that is a simple type name (based on typeSwitch). Minor changes will be made as Environment progresses, but for the most part, the work on the tester is done.
