### ISSUE TITLE
Enable/Disable spartanization

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#142]
We need something like `@EnableSparatanization`, which activates spartanization in all down nodes
(regardless of of `@Disables` in upper nodes).

Similarly,   `@DisableSparatanization`, which deactivates spartanization in all down nodes
(regardless of of` @Enables` in upper nodes).

IN both cases, the effect takes place to down nodes , but the annotation can be overridden by opposing definitions.

**Comment by OriRoth** [comment]
**Moved class to il.org.spartan.refactoring.utils.DisableChecker**
Usage example:
```
/**
 * @DisableSpartan
 */
class Debug {
  /**
   * @EnableSpartan
   */
  int f(boolean b) {
    if (b)
      return 1; // one spartanization option
    return 2;
  }
  int g(boolean b) {
    if (b)
      return 2; // no spartanization options
    return 1;
  }
}
```

**Comment by OriRoth** [comment]
About the annotations' names... I don't mind to change them, but as part of the final product (a feature, after all) I believe they should be easy to type, and as short as possible (remember, no auto complete!).

**Comment by yossigil** [comment]
OK, but as I said, I prefer comments in the JavaDOC. They are much more robust. They won't go crazy if you project is not using spartanization any more.

How about temporary names:

1. `Spartan`
2. `Hedonistic`

And in java doc
```
/** 
 * [[spartan]]
*/
```
anywhere, lower upper case, spaces don't matter.

**Comment by yossigil** [comment]
Variations should be allowed
```
/** 
 * [[spartan]]
 * [[sparta]]
 * [[hedoni]]
 * [[hedonisti]]
 * [[hedon]]
 * [[hedo]]
*/
```

**Comment by OriRoth** [comment]
OK various identifiers is a good idea - I have replaced the strings with strings arrays, so one can use each of the options above (more can be added, of course).

As I mentioned, those strings **must** come in a JavaDoc comment: the "annotations" are simple strings in the JavaDoc (not real annotation, but don't tell them). In previous implementations of the DisabledChecker one could add a @SpartanDisable near every code element in every sort of a comment... the current state is much more simplified.

Currently the project has some issues, so the Trimmer does not use DisabledChecker. Please tell me when I can reboot it (I'll probably add the feature once the project stabilize).

**Comment by yossigil** [comment]
Try running it now. There are still problems in plugin.xml, but I think you can manage these

**Comment by OriRoth** [comment]
Corrected and used (in Trimmer), you can check it out (my example from above is valid). Can I close the issue?

**Comment by yossigil** [comment]
Do you have tests?

**Comment by OriRoth** [comment]
No... I'll add some after merging test files, then I'll close the issue

**Comment by OriRoth** [comment]
Tests added!

**Comment by yossigil** [comment]
@OriRoth :+1:

**Comment by yossigil** [comment]
Can you move the tests to `Issue142Test`?

**Comment by OriRoth** [comment]
Done! no specific guidelines for trimmer-to usage so it remained as is.
