### ISSUE TITLE
Arithmetic simplification bug cannot do x*1

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#143]
Here is an example
```

    @Override public int hashCode() {
      return 31 * ((hiding == null ? 0 : hiding.hashCode()) + 31 * (1 * 31 + (blockScope == null ? 0 : blockScope.hashCode())))
          + (self == null ? 0 : self.hashCode());
    }

```
stays, but we want 1*31 to go to 31.

**Comment by yossigil** [comment]
Attach files by dragging & dropping,  Choose Files selecting them, or pasting from 

- [ ] Add this example as is the `@ArithmeticTest`
- [ ] Add more an more simplified versions of test functions
- [ ] Pinpoint the problem, it could be a case of a different wring
- [ ] Keep the different wring and fix the problem

**Comment by dormaayan** [comment]
@yossigil :
I added the exact example you gave here in ArithmeticTest and it seems to work just fine, you can have a look.
I close the issue.

**Comment by yossigil** [comment]
Thanks. I could be using a too early version.
