### ISSUE TITLE
Use traditional for when possible: Step I

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#144]
This wring is especially for @OriRoth who likes to write code like so:

```java
  public boolean check(final ASTNode n) {
    ASTNode p = n;
    while (p != null) {
      if (dns.contains(p))
        return true;
      if (ens.contains(p))
        return false;
      p = p.getParent();
    }
    return false;
  }
```

We would like to convert it into a for loop. This wring will convert the above to:

```java
  public boolean check(final ASTNode n) {
    ASTNode p = n;
    for (; p != null; p = p.getParent()) {
      if (dns.contains(p))
        return true;
      if (ens.contains(p))
        return false;
    }
    return false;
  }
```

Preconditions:

- There is no `continue` before the last statement in the loop.
- The loop is either a `for` or a `while`

**Comment by yossigil** [comment]
Similar to #145

**Comment by OriRoth** [comment]
Well... I blame Python

**Comment by yossigil** [comment]
Don't blame Python, blame the spartanizer. It should do it for you.

**Comment by yossigil** [comment]
Here is another example:

```java 
    private static String toPath(String groupId) {
        final StringBuilder sb = new StringBuilder(groupId);
        int length = sb.length();
        for (int i = 0; i < length; ++i)
			if (sb.charAt(i) == '.')
				sb.setCharAt(i, '/');
        return sb + "";
    }
```
to 
```java 
    private static String toPath(String groupId) {
        final StringBuilder sb = new StringBuilder(groupId);
        for (int i = 0, length=sb.lentth; i < length; ++i)
			if (sb.charAt(i) == '.')
				sb.setCharAt(i, '/');
        return sb + "";
    }
```

**Comment by sakopzon** [comment]
I am going to implement removeLastStatement(), where is better to put it, in hop or step?

**Comment by yossigil** [comment]
assemble

**Comment by dormaayan** [comment]
@sakopzon : Did you find any convenient way to create a for statement and to add expressions to its initializer / updaters ?

**Comment by OriRoth** [comment]
@dormaayan maybe `forStatement.initializers().add(initializer)`? Consider `step#initializers`, `step#condition` and `step#updaters`.

**Comment by dormaayan** [comment]
@OriRoth  : Im aware to that way, but when I tried to add them, it didn't work because there are very specific requirements from the nodes you insert to those lists.

**Comment by OriRoth** [comment]
You can always check the source code: http://grepcode.com/file/repository.grepcode.com/java/eclipse.org/3.7.2/org.eclipse.jdt/core/3.7.3/org/eclipse/jdt/core/dom/ForStatement.java#ForStatement
They say about the initializers that `the list should consist of either a list of so called statement expressions (JLS2, 14.8), or a single VariableDeclarationExpression`, and about the updaters that `The list should consist of so called statement expressions`.
Also this may help http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FExpressionStatement.html

**Comment by yossigil** [comment]
I think you need to cater for this case as well:
```java
  private static void copyFile(final File source, final File target) throws IOException {
    try (InputStream in = new FileInputStream(source); OutputStream out = new FileOutputStream(target)) {
      final byte[] buf = new byte[1024];
      int length;
      for (; (length = in.read(buf)) > 0; out.write(buf, 0, length))
        ;
    }
  }
```

**Comment by sakopzon** [comment]
I think there are two different tippers. One should extend ReplaceToNextStatement<ForStatement>, and second ReplaceToNextStatement<WhileStatement> (then it won't be an issue which tip was activated first). And the insertion to the initializers List shouldn't be different from the insertion to the updates List I made.

**Comment by yossigil** [comment]
So, are you on this?

**Comment by sakopzon** [comment]
yes

**Comment by yossigil** [comment]
I took a look at the code and spartanized it a bit. You need to write two **independent** tippers:

- One to deal with Something While(..) {}
- One to deal with for ( X; Y; ) {... lastStatementToBeRelocatedAsStepper)

Please checkout `has.sideEffects()` function. It can much help for you.

**Comment by OriRoth** [comment]
Test class `Issue144.java` has failures. @sakopzon can you solve this? we want all tests to pass before release. Also @dormaayan - you are signed on the test class, consider helping us. If you have any problem talk to me.

**Comment by sakopzon** [comment]
Working on it my on last commit there are only 3 falling tests of issue 144.
To make it perfect I think we need 4 tippers:
First and second for WhileStatement and ForStatement to be converted to for considering the last statement of the body.
Third and fourth for VariableDeclarations to consider ForStatement or WhileStatement as next statements and convert to for with initializers.

**Comment by yossigil** [comment]
Seems you are right. But, you do not have to do this perfect.
To do your job perfectly, open up two issues, tag them as 'new-tipper' and 'YPP'.

**Comment by sakopzon** [comment]
What does YPP means?

**Comment by OriRoth** [comment]
Consider following example from JUnit project:
```
for (int i = 0; i < 20; i++) {
  File newFolder = folder.newFolder();
  assertThat(Arrays.asList(createdFiles), not(hasItem(newFolder)));
  createdFiles[i] = newFolder;
  new File(newFolder, "a.txt").createNewFile();
  assertTrue(newFolder.exists());
}
```
==laconized to==>
```
for (int i = 0; i < 20;
        ++i,
        assertTrue(newFolder.exists()), // newFolder unrecognized
        new File(newFolder, "a.txt").createNewFile(), // newFolder unrecognized
        createdFiles[i] = newFolder, // newFolder unrecognized
        assertThat(Arrays.asList(createdFiles),
        not(hasItem(newFolder)))) { // newFolder unrecognized
  File newFolder = folder.newFolder();
}
```
Looks strange, and also not compiling (see comments). This needs to be a test.

**Comment by sakopzon** [comment]
I opened new issues for this topic 310,311. I will consider it when I finish the main functionality of 311.

**Comment by yossigil** [comment]
:+1:
