### ISSUE TITLE
Plugin.xml warnings

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#146]
![image](https://cloud.githubusercontent.com/assets/12775400/18357277/003255b2-75f9-11e6-9b89-f9cc69b928fa.png)

@danielmittelman : any tips?

**Comment by danielmittelman** [comment]
Did you solve it? I opened the project in Eclipse and I don't see any plugin.xml warnings

**Comment by yossigil** [comment]
NO, I could not. This is what I get:

![image](https://cloud.githubusercontent.com/assets/12775400/18385750/1f7fbd2c-769b-11e6-9c6d-f17536fc3cc9.png)

You may need to enable Plugin Warnings for this to show up

**Comment by danielmittelman** [comment]
I still can't see the warnings, however I pushed commit 352a0db that may have fixed these warnings. Let me know if that helped

**Comment by yossigil** [comment]
It helped, I am getting fewer, but still many:

![image](https://cloud.githubusercontent.com/assets/12775400/18392626/23fac656-76bb-11e6-9f3e-b0d9c0b8385d.png)

I am not sure I fully understood the id stuff there, but we have only three commands, which should show up in the menu:

-  Togggle spartanization suggestions
- SpartanizeAll
- Spartanize Current

there is no nothing called Cleanup nor ApplySpartanization

**Comment by yossigil** [comment]
@OriRoth Lets keep `plugin.xml` free of warnings. Please find using search in preferences how to set them all.

**Comment by yossigil** [comment]
At some point in time, these warnings returned. Please eliminate them all, before doing anything else.

**Comment by yossigil** [comment]
Similar to  #174

**Comment by OriRoth** [comment]
The "No schema found ..." warnings are because of eclipse:
https://jazz.net/forum/questions/47598/no-schema-found-for-orgeclipseuipopupmenus-extension-po
Reinstalling the eclipse SDK is very traumatic for eclipse though... I cannot recommend it, although it removed the warnings.
Is there another kind of warnings for `plugin.xml`?

**Comment by yossigil** [comment]
Yes, it is just the schema. We put this now on hold.

**Comment by OriRoth** [comment]
@yossigil there should be a reference in the relevant tutorial to this issue, indicating the solution in case someone gets a warning for this file.
I hope that newly workers would download the updated SDK and will not confront any problems.
