### ISSUE TITLE
Quick fix: apply wring to all/current window

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#148]
The quickfix should allow applying this wring repeatedly on all occurrences in file, and another
fix for entire project.

**Comment by yossigil** [comment]
?

**Comment by OriRoth** [comment]
Its implemented in the quickfix, and I have recently added ending messages for both **apply wring to file/project**, and made **apply wring to project** cancleable.

**Comment by yossigil** [comment]
Splendid, close issues as you proceed. can we close this one?

**Comment by OriRoth** [comment]
Yes. Consider we want to add metrics for end message, but this is another issue.
