### ISSUE TITLE
Alex TODO's

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#150]
Do a search in the code for all TODOs.
How is this going?

**Comment by sakopzon** [comment]
Monday afternoon

**Comment by OriRoth** [comment]
Eclipse can show you a summary of all TODOs in the project, you can check it out.

**Comment by yossigil** [comment]
:+1:

**Comment by yossigil** [comment]
there are some still little things

**Comment by yossigil** [comment]
:+1:
