### ISSUE TITLE
Dan's TODOs: 

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#151]
Do a search in all files for your todos:

**Comment by OriRoth** [comment]
Eclipse can show you a summary of all TODOs in the project, you can check it out.

**Comment by dngreenst** [comment]
I found the TODOs (thanks, @OriRoth ), in Application.java/line 118 and in Environment.java/line 181, but I did not understand your intention. Could you elaborate, please?

**Comment by yossigil** [comment]
Add the question next to the todo

**Comment by yossigil** [comment]
Sorry, I could not find anything in Application.java. The other I explained.

**Comment by dngreenst** [comment]
It is in spartanizer/application/Application.java - line 124, under the method definition: 

MethodInvocation getMethodInvocation(final CompilationUnit u, final int lineNumber, final MethodInvocation i). 

A 'TODO: Dan', with no further elaboration (beyond the question I have added).

**Comment by yossigil** [comment]
It was probably a leftover from Daniel Mittleman's wor,

**Comment by yossigil** [comment]
Dan: the last you touched your TODOs is 22 days ago

**Comment by dngreenst** [comment]
The old TODOs (not the ones that you have added in the last 3 days) are Environment related. 

Do you want me to resolve them? leave them as unassigned TODOs? leave them as comments in the code without 'TODO'? Delete them? 

Dealing with the new TODOs now.

**Comment by OriRoth** [comment]
Old problems tend to become new ones.

**Comment by yossigil** [comment]
Good point, sorry for any confusion. yes, fix your tasks please

**Comment by dngreenst** [comment]
All TODOs are done.

**Comment by yossigil** [comment]
:100:
