### ISSUE TITLE
Tipper to fix code after interm replacement

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#153]
Wring to remove code after sequencer:

``` java
    public int removeDeadCodeAfterEmbeddedIfTrueWithThrow(final int i) {
        System.out.println(i);
        throw new RuntimeException();
        return 2;
    }
```

To 

``` java
    public int removeDeadCodeAfterEmbeddedIfTrueWithThrow(final int i) {
        System.out.println(i);
        throw new RuntimeException();
    }
```

Should include all unconditional sequencers:
1. break
2. return
3. continue
4. throw

**Comment by OriRoth** [comment]
Doesn't Java's compiler take care of this? Apparently it is quite sophisticated... the following codes does *not* compile:
```
int f() {
 for (;;) {
		break;
		return 1;
	}
	return 2;
}
```
```
int f() {
 for (;;) {
		throw new RuntimeException();
		return 1;
	}
	return 2;
}
```

**Comment by yossigil** [comment]
I know, the Java compiler emits an error, but we need to fix this, so that automatic spartanization would work.

**Comment by yossigil** [comment]
I think I implemented a tipper + tests for this, but for 'throw x' only

**Comment by yossigil** [comment]
So, we still need one for:

- [ ] return
- [ ] break
- [ ] System.exit?
- [ ] continue

we will have one issue for each

**Comment by OriRoth** [comment]
Why different solution for each case? Can't we construct a single tipper to detect and work on *unconditional sequencer statements*?
*Note*: I recommend to make this tipper a *Statement* tipper, and use the `ExcluderManager` to exclude all next statements in the block.

**Comment by yossigil** [comment]
Sure. it is possible, and should be done. In our current technology we must inherit four or whatever how many sequencers we find, from an abstract tipper which does this.The generics begin in `$`

**Comment by yossigil** [comment]
Done. Somewhere. Code is not a bug anymore
