### ISSUE TITLE
Renaming bug

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#157]
```java
  public static String combine(final Class<?>[] classes) {
    final String[] ss = new String[classes.length];
    for (int i = 0; i < ss.length; ++i)
      ss[i] = classes[i] == null ? null : classes[i].getName();
    return combine(ss);
  }
```

Suggest to rename classes to nulls.

**Comment by dngreenst** [comment]
Two bugs here - 

1. ParameterizedType that is not a Set/List/some other Collection gets an additional "s" anyway.
2. WildcardType that has no bounds (not <? extends SomeClass> or <? super SomeClass>) returns null.

Changed `shorten(ParameterizedType t)` to fix both. Thought it is reasonable that a WildcardType with no bounds will be named after the Collection that it is contained in (in case of `List<?>`, ls, for example).

**Comment by yossigil** [comment]
Good decision, it should change to the name of the collection

**Comment by yossigil** [comment]
I tried it on the plugin itself. It creates a mess:
Class<N> should be c, not N.

**Comment by dngreenst** [comment]
I tried undoing my changes and creating a jar file - getting the same problem that I had with the changes, when trying to run the plugin on itself.

Regarding the N - I thought that Class<N> should be renamed n, instead of c - that's similar to what we do in case of List<Integer>.

**Comment by yossigil** [comment]
A class of integer is not an integer.
A list of integer is "is", meaning, i in the plural

**Comment by dngreenst** [comment]
Which naming convention would you like me to adhere to, then?

I tried to implement:

`Entry<String>` => s
`Entry<? extends String>` => s
`Entry<? super String>` => s
`Entry<?>` => e
`List<?>` => ls
`List<String>` => ss
`List<? extends String>` => ss
`List<? super String>` => ss

**Comment by yossigil** [comment]
Yes. This is good. If it works, close this.
