### ISSUE TITLE
Arithmetic bugs:

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#158]
1. Do not compute if the result is longer, e.g.,
```java
    assertEquals(5 / 9.0, s_4x0_5x1.mean(), 1E-6);
```
2. Do not compute shifts, they have a reason
```java
  public final static int MAX_RUNS = 1 << 30
```
3. Description in shift is wrong: ` Spartanize: Evaluate substraction of numbers`
4. Spelling error in `substraction` should be `subtraction`

**Comment by dormaayan** [comment]
@yossigil :
Currently, I put a comment over the wrings of the shift for a future use...
Just to make sure I understand, Do you want me to check every time i compute something that the length of the result is sorter than the arithmetic expression's length  and only than to do the evaluation ?

**Comment by yossigil** [comment]
Yes. This is it.

**Comment by dormaayan** [comment]
@yossigil :
Done
I will spartanize my changes when the plugin will work again
(Now I get "Null Pointer Exception" and I hope I didn't caused to that, is so, please let me know)
