### ISSUE TITLE
GUI/IT/Plugin issues

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#160]
**Write here GUI/IT/Plugin issues here**

*Tasks:*
- [ ] Change configuration selection from drop menu to checkbox
- [ ] Activate plugin for newly created project
- [ ] Add the following options to marker menu:
    * spartanize entire project
    * spartanize entire file
    * spartanize containing class
    * spartanize containing function
- [ ] Clean problem view menu, add quick-fix option
- [ ] Automatically apply wring to: containing function/class/file (only if file and class are different maybe?).
- [x] Disable spartanization on function/class/file.
- [x] A new mark menu option to conduct all spartanization of that type in the project
    * Find a name for it: ___________________________________
    * see #167.
    * Apply to function/method/class.
* Find a way to consolidate similar menu options (like pop-up window).

*Updates:*
* Spartanization suggestion marker menu again available
* No start-up exception (without the usual NPE)

*Comments:*
* Reverted Spartanizations.map object key mechanism from Spartanization.getClass().getSimpleName() to Spartanization.getName()

**Comment by OriRoth** [comment]
*Relevant documentation:*
* http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_core_resources_natures.html&cp=2_1_1_22&anchor=e.one-of-nature

**Comment by yossigil** [comment]
I add  tasks for the submenu:

- [ ] Automatically apply wring to: containing function/class/file (only if file and class are different maybe?)

- [ ] Disable spartanization on function/class/file

**Comment by OriRoth** [comment]
"Disable spartanization on function/class/file" means editing/adding JavaDoc? Possible...

**Comment by yossigil** [comment]
Yes. Sure. We do that for renaming, so why not for javadoc?

**Comment by OriRoth** [comment]
OK added auto disable in marker menu, @yossigil you can check it out.
I tried other GUI method (options window), without reaching conclusions... for now it is three different options in the menu.

**Comment by OriRoth** [comment]
@yossigil Hi! I don't know if you noticed, but I have closed issue #167 and added a new checkbox here - please check the relevant line in the first comment of this issue (you are tagged nearby). Thanks.

**Comment by yossigil** [comment]
Indeed, I miss it. I would say, "Apply to function/method/class".

**Comment by yossigil** [comment]
It is quite difficult to follow up on such a long issue. From now, on I will add new separate issues. GitHub has issue management, but it has not sub issue management, so we have to do this management manually if you consolidate everything into one place.

**Comment by OriRoth** [comment]
See specific issues, such as #383
