### ISSUE TITLE
Wring: change variable name "_" => "__"

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#161]
Already implemented, see wring VariableRenameUnderscoreToDoubleUnderscore.
Is there something o change?

**Comment by yossigil** [comment]
It is a matter of searching in git for the wring you wrote and resurrecting it.

**Comment by OriRoth** [comment]
Yes I mean it is in the current version as well

**Comment by yossigil** [comment]
@OriRoth :please finish up with it

**Comment by OriRoth** [comment]
Fixed a bug... seems to work, notice you have to have a @SuppressWarnings("unused") before the variable name in order for the wring to take place.

**Comment by yossigil** [comment]
The unused is part of the spec. That's fine. Close if done.
