### ISSUE TITLE
Remove uneccecary parenthesis in String concating

### ISSUE THREAD

**Issue by NivShalmon** [SpartanRefactoring/Spartanizer#162]
After fixing the bug in TermExpander (issue #129), the following doesn't work:
```
0+(0+x+y+(4))
```
In this case, the parenthesis around 4 are meaningless and should be removed

**Comment by NivShalmon** [comment]
@yossigil I tried to do this using `subject.operands(es).(wizard.PLUS2)`, but that doesn't work because core is called in the procces, which removes parethrensis that are neccecary. I currently created a function that does this without using core in InfixPlusRemoveParenthesis, since I didn't find anything that does this. I wanted to bring this to your attention, as this might be a bug in `subject.operands().to()`

**Comment by yossigil** [comment]
Thanks. I now see the problem. I think the issue is with "plant", which decides when parenthesis are necessary. This is the class that should be fixed.  It is a clever class, looking at the parent, and deciding based on it, whether the parenthesis are necessary. Apparently, it is not clever enough to deal with strings.  Try to help it.

**Comment by NivShalmon** [comment]
I tried to solve this bug in plant by changing nonAccociative to return that infixPlus is nonAccociative if the expression might be a String, but I ran into a problem. Because nonAccociative is called on the host, it may be called on an InfixExpression who only has one operand. type can't handle that, which causes a wrong value to be returned. I'll see if I can change type to handle that case, and once I do I'll finish this issue.

**Comment by yossigil** [comment]
Type must be able to do deal with prefix and postfix expressions. Type inference for them is particularly easy. I believe the original version of PrudentType did that.

**Comment by NivShalmon** [comment]
type is able to deal with prefix and postfix expressions (and should have many tests for that in typeTest), that's not the problem here. The problem is that when plants faces the operands list [4,y,z] for + it calls nonAssociative with the following infixExpression: `4+MISSING`, for which stringType.isNot will say it can be a string, thus the + is non associative, even when it can be.
Solving this in type will create a bug so I'm trying to solve this in plant, but that would take me a while longer since I'm not familiar with that code

**Comment by yossigil** [comment]
Thanks.

**Comment by NivShalmon** [comment]
I dont think this bug can be solved in plant, since it is introduced by a very specific case created in subject.Pair.to.
When you make an infixExpression and don't set operands for it, the default operands seems to be a SimpleName whose name is "MISSING". As long as the operands are missing, type can't determine whether this is a string or not and can't decide whether the plus operation is associative or not. This can't by solved properly by plant, since plant doesn't know the other operands, but can be solved by subject.Pair, since we do know both operands there.

**Comment by NivShalmon** [comment]
It now works and passes all tests, InfixPlusRemoveParenthesis now uses subject.Operands as well. I belive this issue is finished.
