### ISSUE TITLE
Apply this wring button

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#167]
Run the plugin on itself. You would see about 500 suggestions. All but 3 belong to the same new wring (Issue #165). There must be a way to apply them at onee.
At the very minimum, we need a short cut key.

**Comment by yossigil** [comment]
@danielmittelman : do you have any tips for us? Pass it on to Ori, after you are done with, or without tips...

**Comment by yossigil** [comment]
@OriRoth : FYI.

**Comment by yossigil** [comment]
@orimarco , @M4tt30rru : this might be a nano pattern. Function that takes only one argument, which is JD. May be related to Jungleoid. Ori, try applying the plugin to itself and to your code. The number of cases is amazing.

**Comment by orimarco** [comment]
What does JD stand for?

**Comment by yossigil** [comment]
John Doe, i.e., something whose name is unimportant, give a penny take a penny

**Comment by OriRoth** [comment]
It may be possible using a modified trimming mechanism... added to #160!

**Comment by OriRoth** [comment]
@yossigil
Reopened for convenience.
OK added "commit change for scope/file/project" to mark menu. Check it out! I can add/change the selection option for the local options (scope/file) (containing class for example).
"commit change for project" is not currently implemented.

**Comment by OriRoth** [comment]
UPDATE: commit change for project - implemented!

**Comment by yossigil** [comment]
The correct terminology,
apply to function/class/project?
What's scope?

**Comment by OriRoth** [comment]
OK I think I fixed it... the terminology is flexible - I chose:
* "commit change to scope" - most inner BodyDeclaration containing node (may be function).
* "commit change to file" - most outer BodyDeclaration (may be class).
* "commit change to project" - "commit change to file" for every file.

It possible to add more features if necessary... but I think this is enough options.

**Comment by yossigil** [comment]
We need a progress monitor for this one. It takes forever on a large project

**Comment by OriRoth** [comment]
SABABA added a nice display box for plugin operation, similar to "spartanize entire project" message.

**Comment by yossigil** [comment]
I believe we have sync problems. It may be running the traversal in parallel...
