### ISSUE TITLE
compile time evaluation throws NPE

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#171]
![image](https://cloud.githubusercontent.com/assets/12775400/18462716/775d970e-798d-11e6-8b24-4cbe57db93ef.png)

**Comment by yossigil** [comment]
This renders the plugin unusable.

**Comment by dormaayan** [comment]
@yossigil :
When I run the plugin by myself I don't see any NPE in the console,Am I suppose see the exception after trying to spartanize something specific or when I simply run the plugin ?

**Comment by yossigil** [comment]
Sorry, you would have to localize the bug by this information. The code looks pretty suspicious, in the sense it that it did not convince me that an error of this sort could not happen.

**Comment by dormaayan** [comment]
@yossigil : I think the bug was found, I close the issue
