### ISSUE TITLE
Remove 0 from addition

### ISSUE THREAD

**Issue by NivShalmon** [SpartanRefactoring/Spartanizer#172]
0 addition can be safely removed from an infix plus operation if no strings have been added yet.
`0+\"\"` should be unchanged but `0+x+\"\"` or `x+0+\"\"` should turn to `x+\"\"`.

**Comment by yossigil** [comment]
I think we have like 2-3 implementations. I think I wrote this twice...

**Comment by NivShalmon** [comment]
non of them work though. One works only for non-String, and another is bugged and removes 0 even from String concating. Just using stringType on the entire expression doesn't work either,  `x+0+""` is a String, but the 0 can be removed.

**Comment by yossigil** [comment]
:100:

**Comment by OriRoth** [comment]
Well... I don't believe it is **completely** safe...
Consider implicit casting operations by the compiler. After all, we don't know how the compiler decides the type of the numeral literals in many cases (`int`/`long`, `float`/`double`). A similar issue (changing order of operations: `x+0.0`->`0.0+x`) caused tests failure in the Apache common math library.
Probably rare issue though.

**Comment by yossigil** [comment]
This one should be completely safe. We know how the compiler manages types. This is given. What's  not known, is the result of floating point computation which in general do not obey the rules of algebra. commutativity holds but not associativity and not the distributive rule. 

There may be strange things related to +0/-0, etc, but do not worry about this.

**Comment by NivShalmon** [comment]
This seems to work fine now, though I couldn't find out how.
