### ISSUE TITLE
SubProgressMonitor

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#173]
We get deprecated warnings on this. We need something more sensible, and get rid of the warnings.

**Comment by yossigil** [comment]
![image](https://cloud.githubusercontent.com/assets/12775400/18471193/600e39ec-79b9-11e6-9324-6437600c2ee7.png)

**Comment by yossigil** [comment]
There is a great article in the internet on `monitor`  or `convert` or something

**Comment by OriRoth** [comment]
Yes this is the new API for *deprecated* SubProgressMonitor: SubMonitor. We should see how we can use it in GUI$Applicator instead of `pm.start(...)`.
We should also look into monitors groups.

**Comment by yossigil** [comment]
Please DO NOT USE the new API. Just use the plain `convert`, or something. The system is shaking is unstsable at the moment

**Comment by OriRoth** [comment]
In the current planning we are not going to use submonitoring.

**Comment by yossigil** [comment]
:+1:
