### ISSUE TITLE
Manifest warnings

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#175]
![image](https://cloud.githubusercontent.com/assets/12775400/18471130/0bb9ee36-79b9-11e6-9a0f-7e307a312451.png)

**Comment by yossigil** [comment]
Take note that I worked on warnings in `plugin.xml`, currently, there should not be any. check out #146

**Comment by yossigil** [comment]
I did this

**Comment by OriRoth** [comment]
@yossigil 
![Uploading manifest.jpg…]()

**Comment by yossigil** [comment]
Change it to your version of jface. You can do so in editing the constraints by the the dialog of `plugin.xml`. You can set the minimal version of any product. Do this for each requirement for which you are using an earlier version

**Comment by OriRoth** [comment]
Travis also shouts about this https://travis-ci.org/SpartanRefactoring/Spartanizer/builds/164604214 (hope it is visible) (look for "[error]")

**Comment by yossigil** [comment]
Hack it one way or another, warnings may return

**Comment by yossigil** [comment]
We need a clean warnings page.

**Comment by OriRoth** [comment]
Indeed. Travis would not build with the version specifications in `MANIFEST.MF`. I think something more should be added in order for the project to compile... If there are no problems in your environment, we should change the project's definitions accordingly.

**Comment by yossigil** [comment]
We do this first because:
- It was fixed, and  then broke again.
- it is easy to fix
- it is on the table for a very long time
- it disturbs our workflow, each warning is a **"WARNING SIGNAL"** 
  - Leaving out warnings unfixed makes our developers be careless
  - Leaving out warnings makes even it difficult for developers to apply the "**no warnings on my code**" principle. they have to scan through warnings of others' code.

**Comment by yossigil** [comment]
@OriRoth : reminder

**Comment by OriRoth** [comment]
OK found a (legit) hack for it. There is currently only one warning left: `This plug-in does not export all of its packages`.
@yossigil do you have any objection for exporting all packages?

**Comment by yossigil** [comment]
- Export all, no problem.
- As to fixing other people's code; this is the standard, not the exception @orimarco , FYI.

**Comment by OriRoth** [comment]
Apparently this is a buggy issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=308274
So I just changed the project definition to ignore this warning.
Done done for now.

**Comment by yossigil** [comment]
@OElmak
