### ISSUE TITLE
Centification in for loop makes a suggestion, but cannot implement it

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#176]
Try this in the plugin, not in a test:
```java
  static Expression applyDeMorgan(final InfixExpression inner) {
    final List<Expression> operands = new ArrayList<>();
    for (final Expression e : hop.operands(flatten.of(inner)))
      operands.add(make.notOf(e));
    return subject.operands(operands).to(PrefixNotPushdown.conjugate(inner.getOperator()));
  }
```

**Comment by yossigil** [comment]
#170

**Comment by OriRoth** [comment]
@yossigil 
*Conclusions:*
* The source of the problem = marked code part is not in wring's domain. i.e. the wring is for enhanced for statement but changes only a single variable definition.
* Solution: change wring's domain to single variable definition.
* Remark: tests pass, code above spartanize well.

**Comment by yossigil** [comment]
:100:

**Comment by yossigil** [comment]
Well, not sure, seems the plugin gets into an infinite loop

**Comment by OriRoth** [comment]
It just take a lot of time to spartanize an entire project.

**Comment by yossigil** [comment]
We found an infinite loop somewhere related to this, no?

**Comment by OriRoth** [comment]
Not together... talk to me if you see something suspicious.
