### ISSUE TITLE
Bug in [[X=X||Y]

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#177]
- [x]  Figure out if it is safe to convert `x=x||y` to `x |= y`, particularly if y has side effects, either in the manual or by trying it. If you try it, write a test case for it.
- [x]  Write test cases for all bit wise/boolean operations, each one in a distinct function, according to your findings.
- [x]  Fix the test case
- [x]  Checkout all steps you did
- [x]  Close this issue

The bug should be easy to fix,

**Comment by yossigil** [comment]
#108

**Comment by sakopzon** [comment]
I guess you meant x=x|y..

**Comment by yossigil** [comment]
No, I did not. I meant x = x || y

**Comment by sakopzon** [comment]
didn't know it's possible, now have to go, will continue to write tests for other operators and integrate the changes to the wring in a few hours

**Comment by yossigil** [comment]
:100:
