### ISSUE TITLE
Place holder

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#178]
Kill all assignment to a local variable if these do not change the end result.

**Comment by OriRoth** [comment]
Probably need to:

1. track each assignment to the variable.
2. from each assignment, search for a route to variable usage.

Is there maybe some utility mechanism to do that? It is very logical work.

**Comment by yossigil** [comment]
What you suggest is to use a def-use computation. It is a well known theory, but hard to implement. My suggestion is simpler,  concentrate on the linear paths. The commands just before a return, and eliminate these.

**Comment by yossigil** [comment]
I am closing this for now, as it is even more complicated than #251  Use-def is tricky. Auto refactor has that though

**Comment by yossigil** [comment]
To do that properly, you need to mess with the side effects issue as in #251 , other than doing the CFG.
