### ISSUE TITLE
Wring to convert a -= 1 to a--, if a is not a string

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#179]
Try to be careful, main gotcha is the RVALUE of a--, --a, and a-=1?
Why didn't I say anything about LVALUE?

**Comment by dngreenst** [comment]
Didn't we do this wring? Issue #107 handles a-=1 too. In fact, that's the main thing that issue handles.

**Comment by yossigil** [comment]
Just checked online. Indeed, this is done!
