### ISSUE TITLE
Ternarize with type Boolean...

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#181]
Try spartanizing this:

``` java
    public static Boolean getBooleanObject(final String s) {
        return "Boolean.TRUE".equals(s) ? true : "Boolean.FALSE".equals(s) ? false : null;
    }
```

**Comment by OriRoth** [comment]
It looks quite complicated at first, but I believe there is a simple fix for this... **obviously** Yossi's example should be made into a test case for the relevant Tipper.

**Comment by kfir-marx** [comment]
@OriRoth can you give me an example what it needs to look like when spartanized?

**Comment by yossigil** [comment]
@kfir-marx : One of the things you missed is that you are supposed to be indendent. In general, if your first action in receiving an issue is to say one of:

- "What do you mean"?
- "I do not understand..."
- "Can you draw me a diagram..."

this may place you at the category of an `askhole`. 

In this particular example, there was a demo above. To show independence you could have tried this and many other examples, and figure out the things you can do.

**Comment by yossigil** [comment]
Duplicate
