### ISSUE TITLE
Shortcut key for spartanization

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#183]

**Comment by yossigil** [comment]
@OriRoth  it is all  a mater of editing `plugin.xml`; be sure to keep it free of warnings.
I would like CTRL-SHIFT-S to apply the current spartanization.
and CTRL-SHIFT-N to fully spartanize current window.

**Comment by OriRoth** [comment]
What does "apply current spartanization" mean? spartanize entire project?

**Comment by yossigil** [comment]
1. Apply current spartnization to the current text. Just something better than Ctrl 1. Ctrl 2, just says, do it. 
2. We can think about this later.
3. Are ctrl-1 ctrl-2 etc take?

**Comment by OriRoth** [comment]
`ctrl+1` is quickfix... I think the best option is to find unoccupied, easy to use combinations, and include a remark about them in the menu/quickfix for acknowledgement. Also it can be easily changed.

**Comment by yossigil** [comment]
Can we start by having this first implemented?

**Comment by OriRoth** [comment]
Yes it is just a change to the `plugin.xml` file.
BTW I believe I enabled warnings in this file... anyway I would not make a mess.
`Ctrl+1/2/3` are occupied.
For start: `Ctrl+5` to spartanize current window.
I will give the second task to `Ctrl+4`, but it will take more time because it requires a new handler... similar to the old `ApplySpartanization`. Probably will be called `SpartanizeSelection` (and would spartanized marked code part).

**Comment by yossigil** [comment]
> I will give the second task to Ctrl+4, but it will take more time because it requires a new handler... similar to the old ApplySpartanization. Probably will be called SpartanizeSelection (and would spartanized marked code part).

No. Don't do it. My intent was that when you see a tip (note the new name, tip, not suggestion), in the problems view of eclipse, you would be able to hit:CRTL-SOMETHING, which will automatically apply the first quick fix option.  But, this is not our job, as much as I need this key...

**Comment by yossigil** [comment]
@OriRoth : here is another related request, which can be made into an issue if you like, but it is really short: add to the resolvers list one more resolver (known as quickfix): "Spartanize current window". This should not do anything on the GUI.

**Comment by yossigil** [comment]
@OriRoth : can we see some progress here?

**Comment by OriRoth** [comment]
I do not think I completely understand you.

*What is currently implemented:*
* Quickfix menu, opened by hovering over the marker or pressing `ctrl+1`. There you can:
 * Apply tip
 * Apply tip in ...
 * Disable tipping in ...
* Shortcut `ctrl+5` to spartanize current window

*What can I add:*
* More options o the quickfix
* More shortcuts

*Consider:*
* Fastest way to apply tip is currently `ctrl+1+enter`
* If we will group the tip warnings (my suggestion for `WringCommit` replacement, though I cannot promise it will work), clicking `ctrl+1` then `ctrl+enter` will apply all similar tips

I will be happy to get a use-case scenario: what you want to see/what you want to be able to do and how.

**Comment by yossigil** [comment]
Wow looking forward to seeing this work

**Comment by yossigil** [comment]
When these are active, don't forget to place a reminder in the Spartanization menu.

**Comment by OriRoth** [comment]
Apparently eclipse does that automatically for us:
![shortcut](https://cloud.githubusercontent.com/assets/15183108/18840389/13034fc6-8417-11e6-85d5-df3e29824fa4.jpg)

**Comment by yossigil** [comment]
Let me check it out.

**Comment by OriRoth** [comment]
Well, what more should I do here? I can change the `ctrl+5` to something else (`ctrl+4` is unoccupied, also `alt+shift+w`). There is a way to quickly activate first marker resolution - `ctrl+1+enter`: it is possible to create a shortcut for it, but apparently it requires a *new handler* (I did not find a trivial way to do so, besides `ctrl+1+enter`).

**Comment by yossigil** [comment]
Leave it as is. Once we have a keybinding, we can change it later.
