### ISSUE TITLE
String contains

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#189]
```java
    private boolean replaceStringIndexOfGreaterThanOrEqual(String ¢) {
        return ¢.indexOf("test") >= 0;
    }

    private boolean replaceStringIndexOfLesserThan(String ¢) {
        return ¢.indexOf("test") < 0;
    }

    private boolean replaceStringIndexOfNotEqualsMinusOne(String ¢) {
        return ¢.indexOf("test") != -1;
    }
```

Could be related to user defined wrings.

**Comment by OriRoth** [comment]
There is a similar tip regarding the usage of `isEmpty` method with collections.... maybe in one of the older versions, if not imported to the current one.
A nice solution can be an abstract tip, replacing `InfixExpression` with `MethodInvocation` using rules defined by successors.

**Comment by yossigil** [comment]
@orimarco

**Comment by yossigil** [comment]
Should be easy with your user define match/replace

**Comment by orimarco** [comment]
https://github.com/SpartanRefactoring/Spartanizer/blob/1589de203a312a238044df70fa772f94c3829363/src/main/java/il/org/spartan/spartanizer/tippers/InfixIndexOfToStringContains.java
