### ISSUE TITLE
X*0->0

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#193]
This might be interesting to implement/think about since X might have side effects.

**Comment by yossigil** [comment]
This is actually the same as #251

**Comment by dormaayan** [comment]
@yossigil : I implemented that, if you see more things to add/consider please let me know, if not, we can close the issue.

**Comment by dormaayan** [comment]
@yossigil :
I think its done, If you find any other case you want me to handle please let me know.
For now, I close that issue.

**Comment by yossigil** [comment]
Wow, you are amazing. Thank you very much :100:
