### ISSUE TITLE
Issues #130 & #131 don't work in all cases

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Spartanizer#198]
For example here :

```
  @Test public void issue131_13() {
    trimming("int i=1;while(i<7){if(i==5){t+=9;return xxx;}y+=15;return xxx;}return xxx;")
.to("int i=1;while(i<7){if(i==5){t+=9;return xxx;}y+=15;break;}return xxx;")
        .to("int i=1;while(i<7){if(i==5){t+=9;break;}y+=15;break;}return xxx;");
  }
```

There is assertion error of nothing done

**Comment by dormaayan** [comment]
@yossigil :
 After checking that issue for some time I return to my findings from the original issues:
There is a problem with wrings directly over ForStatements and WhileStatements, it seems like during running it does't take into consideration in some place this 2 kind of nodes and because of that, every wring of that type is simply ignored. I found some places with functions related to the choose-wring algorithm that exclude the handling with ForStatment and WhileStatement.
Do you aware to that problem ? do you want me to try to add the support for wrings over that kind of nodes ?

**Comment by yossigil** [comment]
Checkout class DispatchingVisitor. You must have these two types there.

**Comment by dormaayan** [comment]
Solved

**Comment by yossigil** [comment]
:100:
