### ISSUE TITLE
Tipper: Paramter names in constructor, to match fields, if they are assigned to them

### ISSUE THREAD

**Issue by danielmittelman** [SpartanRefactoring/Spartanizer#20]
A few comments made by Yossi:
Change parameter names in constructors to the names of the corresponding private fields (this.variable = variable)

**Comment by yossigil** [comment]
@dngreenst , @sakopzon : This is a bit too much  I am going to take it of your shoulders

**Comment by sakopzon** [comment]
I can start working on it, but a lot of test cases can't be satisfied without the environment.
Should I start working on this wring, return to environment, or there is some research you saved for me?

**Comment by yossigil** [comment]
No. Not a good time. We have a huge bug at the sorting, which now makes about 799 suggestions. I had to disable this, see #269 .

All this sorting of annotations needs more care.

**Comment by mdoron** [comment]
@dormaayan What should we implement and extends?

**Comment by mdoron** [comment]
@dormaayan @yossigil @orimarco @OriRoth do we have a function that gets a parameter old name, parameter new name and a block and rename the parameter in the block?

**Comment by mdoron** [comment]
Finished all besides renaming which I'm not sure how to do it correctly. Tried to use Tippers.rename and encountered a problem. Waiting for version 2.7 to be released and then I'll commit my changes for this issue.

**Comment by yossigil** [comment]
What's going on?

**Comment by mdoron** [comment]
@yossigil I never uploaded the full version since I think this issue's tests are way too hard to pass, and so does @OriRoth.
So, since I'm not passing all of the tests (but I do the most of them in terms of frequent cases in real projects), I didn't close this issue.

**Comment by yossigil** [comment]
I looked at the tests in Issue0020.java. I thin they are reasonable. I think you should try harder.

@OriRoth : FYI

**Comment by yossigil** [comment]
I also took a look at the code. I think it is very doable. Try to follow all standards, and then I could step in and help you.
In particular: 

-  conventions on class name. 
- Make sure you fully understand what class `az` does. You seem to have missed the point. 
- Same for class `iz` here is an excerpt from your code:
```java
      if (!iz.simpleName(right(a)))
        continue;
      final SimpleName paramName = az.simpleName(right(a));
```
- You can use the environment if you need to figure out the name of fields.
- make sure  you understand what Eclipse calls FieldAccess. 
- Inline all variables that are used once.
- never commit code with warnings, unlaconized. Do not commit code which as commented (you did it in Toolbox)
- if you factor our the main loop in your code to a distinct function with a meaningful name, you have better chances.

**Comment by mdoron** [comment]
@yossigil I accept the comment, but are you sure that all the circularities checks are necessary?

**Comment by yossigil** [comment]
I am not sure I understand the question.  It is more important that you do first the easy stuff I asked for

**Comment by yossigil** [comment]
Updates?

**Comment by dormaayan** [comment]
Done
