### ISSUE TITLE
Apply wring finish, inlcluding dialog box.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#202]
- [x] Automatically apply wring to: containing function/class/file (only if file and class are different maybe?)

- [x] Disable spartanization on function/class/file

Use appropriate names. Get a decent progress monitor.

**Comment by yossigil** [comment]
Names?

**Comment by OriRoth** [comment]
You can tag everybody for ideas... it is quite a subjective, so a poll would be nice. Can also be applied to other gui stuff.

**Comment by yossigil** [comment]
I see you are planning on getting me to work on this more than I planned... No.

**Comment by OriRoth** [comment]
OK added stable progress bar + closable + end message. Check it out, and see #282

**Comment by yossigil** [comment]
:100:
