### ISSUE TITLE
Apply wring to file, does not always work, and never gives an indication

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#203]

**Comment by OriRoth** [comment]
@yossigil do tou want me to change WringCommit's implementation? we saw that things kind of worked, so I don't think we can blame WringCommit entirely... but we also conclude that it can be implemented better.
The dialog boxes can be problematic- if we can see the progress bar in "Progress" view, is it still a blocker?

**Comment by yossigil** [comment]
I want you to start with SpartanizeAll. Yes, it is blocker. People will dump the plugin this way.

**Comment by OriRoth** [comment]
OK Spartanize all is at stable condition.
Now `WringCommit` for project is more usable:
  * Show end message
  * Non busy
  * Cancleable

**Comment by OriRoth** [comment]
OK now `WringComit` for **file** is more stable. Are you sure you want an end message? It's operation is rather short.
Closable?

**Comment by yossigil** [comment]
Yes, I want an end message that would present statistics, such as how much we saved overall, etc... But that's a subject for a separate issue, which I will hopefully open soon.
