### ISSUE TITLE
Evaluation of long does not work

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#206]
```
    public int compareTo(final Fraction other) {
      return other == this || numerator == other.numerator && denominator == other.denominator
          || 1L * 1L * numerator * other.denominator == 1L * 1L * denominator * other.numerator ? 0
              : 1L * 1L * numerator * other.denominator < 1L * 1L * denominator * other.numerator ? -1 : 1;
    }
```
This is bug in #158

**Comment by dormaayan** [comment]
@yossigil :
My evaluation handles only the cases where the expressions contains only numbers (positive or negative), thats not the case here

**Comment by yossigil** [comment]
But we have 1L*1L. Why can't you deal with that? it is a subexpression

**Comment by dormaayan** [comment]
I can but I thought we don't need to handers such cases according to your definition of the Evaluation Wrings :
> "Don't change expressions that involves anything other than literals"

If you want me to support evaluation of subexpressions too, I will open a new  Issue and work on that.

**Comment by yossigil** [comment]
But, a subexpression only includes literals.. 
The tricky part is that the type of 
A*B in (A*B*C) is not the type of A*B*C.
Just deal with the case that left and right are of literals. I think this covers most of it.

**Comment by dormaayan** [comment]
@yossigil :
Done

**Comment by yossigil** [comment]
:100:
