### ISSUE TITLE
Spartanize active window

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#208]
Separate this into several commands.

-  Spartanize selection
-. Spartanize window
- spartanize containing function
- spartanize class

Make sure that they do this repeatedly, until done. Not just once.

**Comment by OriRoth** [comment]
@yossigil Have you implemented something? a handler maybe? I want to work on it.

**Comment by yossigil** [comment]
Yes, there is a handler: `SpartanizeCurrent`

**Comment by OriRoth** [comment]
`SpartanizeCurrent` is former `ApplySpartanization`, which allowed spartanization by text selection, i.e. you could have spartanize just suugestions inside marked code. This feature is still present in `GUI$Applicator`, though it always accepts no text selection.
My plan is:
* Add an option to `GUI$Applicator` for applying spartanization for a specific text selection.
* Make `SpartanizeCurrent` abstract, with concrete successors `SpartanizeCurrentWindow`, `SpartanizeCurrentClass` and `SpartanizeCurrentFunction` deciding only what text selection to use

Acceptable?

**Comment by OriRoth** [comment]
OK `Laconize function` and `Laconize class` are available to use in the marker resolution view.

*Initial state:*
We had a handler for spartanizing entire window (`LaconizeCurrent`). We wanted two new marker resolution, `Laconize function` and `Laconize class` that do basically do the same thing but only for the containing function/class.

*Solution:*
The solution chosen is to create an abstract handler `LaconizeSelection`, from whom we can inherit the spartanization execution process. The concrete implementations should decide the **range** they want to spartanize.
We further generalized the problem by creating `LaconizeSelection.Enclosure`, which get different ranges by calling `serchAncestors` with different node classes.
Thus:
* `LaconizeSelection` contains actual spartanization execution process.
* `LaconizeCurrent` extends `LaconizeSelection`, range is **all window**.
* `LaconizeSelection.Enclosure` extends `LaconizeSelection` and implements `IMarkerResolution`, range is **decided dynamically by both marker and input class**.
* `Laconize function` and `Laconize class` are created using `LaconizeSelection.Enclosure` with `MethodDeclaration` and `TypeDeclaration`.

*Problem:*
Both `Laconize function` and `Laconize class` run only *once* per function/class. We loose the context of the original marker after the rewrite has been completed. A solution may be **tracking the original function/class**, getting their new position after each rewrite.

**Comment by OriRoth** [comment]
@yossigil closable, or do you want me to allow multiple-runs-until-finish for `Laconize function` and `Laconize class`? (see *Problem* above)

**Comment by yossigil** [comment]
Finished. Locanize handler to use in Eclipse. It should what is marked, and act accordingly.
