### ISSUE TITLE
x.toString() bug.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#209]
The following 
```java
new Integer(3).toString();
```
is perfectly legal. However, its spartanization 
```java
new Integer(3).toString() + "";
```
is not. 

Solution: add a simple test case, and then make sure the wring does not do anything if the expression parent `iz.expressionStatement()`

**Comment by yossigil** [comment]
or, better yet, do not append the `""`. Let assume that `toString()` is a pure, deterministic function.

**Comment by NivShalmon** [comment]
Can you explain what you mean in the comment?
Also, the spartanization of `new Integer(3).toString();` is `new Integer(3) + "";`, without the toString(). For Now I've changed it the way you recommended using `iz.expressionStatement()`.

**Comment by yossigil** [comment]
The comment is "future thoughts". When we restructure, it may be easier if we know that a function is just a pure function, as in 234319, nothing like `toBe()` of Hamlet. A function is pure roughly when it has no side effects, and when it does not depend on external values.
