### ISSUE TITLE
Centification of traditional  for loop.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#212]
Here is an example:
```java
for (int i =0; i < n; i ++) sum += i;
```
goes to 
```java
for (int ¢ =0; ¢ < n; ¢ ++) sum += ¢;
```

precondition, no other variables are defined, in the body of the loop,

**Comment by dngreenst** [comment]
@yossigil , I'm going over the failing tests, and I see some that are related to this issue that are failing (vanilla01, vanilla02 in issue212.java, postfixToPrefixAvoidChangeOnLoopInitializer in TrimmerTest.java). 

Should I debug this, or would you rather that I leave it to you?

**Comment by yossigil** [comment]
Please debug. Talk to Alex

**Comment by dngreenst** [comment]
The tests fail because this tip requires uses of the changed variable in the ForStatement body. Inlining emptied the body, and hence this check returns false. 

I can either amend the tests, or change the requirements of the tip. I think the latter would be the better option.

**Comment by yossigil** [comment]
Indeed. Please do.
To be precise, if the loop variable is used in the updaters or the condition then it is a use
