### ISSUE TITLE
Introduce a mySubjectsClass() method in wrings.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#214]
This method should use reflection to find the actual `Class` object of the the nodes to which this wring is applicable. 

@OriRoth We need this also for #137 .

**Comment by OriRoth** [comment]
Nice... is it implemented? I wrote similar a logic a while ago using reflection, although it may be done more efficiently from inside the class.

**Comment by yossigil** [comment]
Yes, it is done. Take a look at class `Wring`! and `Issue214Test` This was the quickie I wanted you to do...
