### ISSUE TITLE
Common Lang project as preformance and correctness benchmark

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#215]
**Execution time:** 16 minutes

**Number of errors:** 62

Relevant issues:
* #213 
* #216

**Comment by OriRoth** [comment]
@yossigil 
Plugin "spartanize entire project" is very slow (16 minutes for common lang). I have tried lowering execution time by ignoring files without spartanizaion options, but project's build is still very slow. Why does it happens? shouldn't eclipse be building only changed files?

**Comment by OriRoth** [comment]
@yossigil 
What about Java's compiler bug regarding type of conditional expressions? (i.e. b ? x : y) Ignoring it? I need a confirmation.

**Comment by yossigil** [comment]
Yes, ignore it, meaning disable spartanization of this one.
Are you sure you did not change anything?
It used to be faster day before yesterday.
If not, we would have to do `git bisect` or profiling
