### ISSUE TITLE
Casting bug in `type`

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#218]
here is an example, I get a an assertionError in join
```java
  @Ignore() @Test public void issue82c() {
    trimming("(long)(long)2").to("1L*(long)2").to("1L*1L*2").stays();
  }
```

**Comment by yossigil** [comment]
Cancel the `@Ignore` and you should be getting a more detailed error message

**Comment by NivShalmon** [comment]
@yossigil I don't get an assertionError  in join, but I do get the following:

java.lang.AssertionError: 
Expected: is "1L*1L*2"
     but: was "2L"

Changing the expected to be 2L results in this:

java.lang.AssertionError: 
Expected: is "2L"
     but: was "1L*1L*2"

Don't know how to solve this test, but I can't reproduce the assertionError you got.

**Comment by yossigil** [comment]
Could it be that I `@Ignore`ed this test?  
Where do you get this bug?

**Comment by NivShalmon** [comment]
In issue82c

**Comment by yossigil** [comment]
I just pushed a demo for you. You may need to run the test twice, because something goes wrong in the second run. Try to make a test that demonstrates the problem of a second run:
Commit 3c23728339fda1e9be4a4f9bc3263d95aa79b3c3

**Comment by yossigil** [comment]
![image](https://cloud.githubusercontent.com/assets/12775400/18561964/9a1ba7f0-7b8a-11e6-9383-0a2f8a13cef0.png)

**Comment by NivShalmon** [comment]
It seems that the constructor of LONG is called a second time, so the key "long" is already in the dictionary, but the dictionary was kept so the result is attempting to add the key a second time. I'll change the call to join to a types.put call for now and that should fix this
