### ISSUE TITLE
Two to three string concatenation

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#224]
```java
a + b.toString()
```
goes to 
```java
a + b + ""
```
which is buggy

same bug with

**Comment by NivShalmon** [comment]
I've solved this by changing the order from `b+""` to `""+b`, this will ensure that the conversion to String happens at the right place. In cases where `b+""` should work, there are other wrings that will either change the order to  `b+""` or drop the empty string, depanding on what is possible (both cases shown in the test file for this issue).
@yossigil you started writing same bug with and didn't finish. Is there another case to this bug?

**Comment by yossigil** [comment]
No. This is it. Good job. We do not mind small spartanizations, as long as they are as safe as possible and converge to the correct result.
