### ISSUE TITLE
Return from loops, convert to break, does not work in the case of a plain for and a nested if

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#225]
Does not work in this one:
```java
        private int free(int max) {
            int $ = 0;
            for (; $ < max; ++$) {
              Entry<T> entry = queue.poll();
              if (entry == null)
                return $;
              freeEntry(entry);
            }
            return $;
        }
```

**Comment by yossigil** [comment]
#131 @dormaayan

**Comment by yossigil** [comment]
@dormaayan can this be closed?

**Comment by yossigil** [comment]
@dormaayan : actually, we need a `@Test case` for this one.

**Comment by dormaayan** [comment]
@yossigil : actually, I added a test case of that in friday (didn't push it yet) and it seems to works ok in the test case. But, when I run the plugin with that code it doesn't work (it shows the suggestion to spartanize but then it doesn't do the spartanization itself), I tried to find if there is any conflict between the scopeIncludes and the replacement but I did'nt find any one.
Do you have any idea what can cause to that ?

**Comment by yossigil** [comment]
Sure. This must be a thing related to ranges. It happens all the times. You see, a spartanization returns, and it sets a marker, to which region in the code we associate the suggestion.

Now, the Trimmer tries to execute as many suggestions as possible in each batch. So, it applies a kind of trimming of the list. If a suggestion does not properly define its region (see constructors of class Suggestion), then we are in bad shape, since it may overrule others, or others overrule it.

There is also a trick using the exclusion manager. Not sure how much you need this hairy exclusion in  your case.  It is used in renaming parameters to methods

**Comment by dormaayan** [comment]
@yossigil : Done

**Comment by yossigil** [comment]
:+1:
