### ISSUE TITLE
Bug in return $

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#228]
May be duplicate. Here is an example that cannot be automatically achieved:

``` java
  private static ASTNode replacementLong(final List<Expression> xs, final InfixExpression x) {
    long $ = 1;
    for (final Expression ¢ : xs) {
      if (!iz.pseudoNumber(¢))
        return null;
      Long l = az.boxed.long¢(¢);
      if (l == null)
        return null;
      $ *= l.longValue(); 
    }
    return x.getAST().newNumberLiteral(Long.toString($) + "L");
  }
```

**Comment by danabramovich** [comment]
@yossigil do you mean that the bug is that the spartanizer does not "improve" this piece of code, or that the bug is somewhere in this function?

**Comment by yossigil** [comment]
What I mean that if the input does not use `$`, the spartanizer does not recognize it as such. Could be fixd already. Create a test class, and if it passes, close this issue.

**Comment by danabramovich** [comment]
I have checked and the spartanizer does nothing on this code. is it ok?

**Comment by danabramovich** [comment]
@yossigil Ok, so I found out where the problem at : its in MethodDeclarationRenameReturnToDollar class, line 136:
`if (dependencies.contains(n + "") && dependencies.size() == 1)`
if I change the contidition into:
`if (dependencies.contains(n + "") )`
it passes the test, but it breaks two existing tests in the project.
So i came to a point in which I'm not sure what is the desirable behavior. In other words, are you sure the test you have given me should pass?

**Comment by danabramovich** [comment]
Plus, I'm not entirely sure what is the purpose of the `dependencies.size() == 1` condition.

**Comment by danabramovich** [comment]
inlineintoInstanceCreation

**Comment by danabramovich** [comment]
I decides to remove that condition so now the bug mentioned in this issue is **fixed**.

**Comment by yossigil** [comment]
Good independent job @danabramovich. What were the other tests? The idea is to approximate the user's intention as closely as possible.

**Comment by danabramovich** [comment]
you can see the tests I have changed here:https://github.com/SpartanRefactoring/Spartanizer/commit/4b432051ce084a39539458752ad51ba4d208811a
TL:DR - 
in class : Issue222.java - test chocolate2().
in class : Issue711.java - test test0().
in class : Version230.java - test inlineintoInstanceCreation(). - in this test there was also a variable name that didn't change into cent.
