### ISSUE TITLE
Failing test for sorting modifiers

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#230]
#111:

```java
  @Ignore @Test public void issue111e() {
    trimming("protected public final class A{volatile static int a;}") //
        .to("public protected class A{volatile static int a;}") //
        .to("public protected class A{static volatile int a;}") //
        .stays();
  }

```

**Comment by sakopzon** [comment]
the issue falls because the final modifier is missing in the "to" string.

**Comment by yossigil** [comment]
- Fix the bug in the test then...
A1: it is a bug/
A2: it should not.

Cannot find the test anymore.

**Comment by sakopzon** [comment]
test issue230a/1/2/3

**Comment by yossigil** [comment]
Try to see if you can get the code to remove duplicates in modifiers. The code is illegal, but the plugin may be able to fix it...

Move the tests to a different Issue file as a I have done for all others.

**Comment by yossigil** [comment]
Also, when the tests are moved to a testing class, remove  "issue230" from their name

**Comment by sakopzon** [comment]
I got there the deepest I can and found that the built in equals() function is not recognizing equal annotations when called from distinct(), so I implemented it myself (during some research I found out that java actually has List<baseClass> and List<? extends baseClass> and the differences between them). I tried to find generic distinct(), contains() or equals() function of a List or stream which would get a comparator (like the sorted()), but without success.
Actually while writing this massage I thought about using some filter() os the Stream. Will try it later today.
Eventually the work is done but from my poor acquaintance with java, I have a filling it could be done much better. Still working on it

**Comment by yossigil** [comment]
Good job. I promised you hell on Java. Welcome to hell!

**Comment by yossigil** [comment]
And yes, you are right, the stream library has distinct filter, but then you need to mess with the `equals` function. My advice: don't! Do a quick  manual sort of your own.

Or, if you feel that you have learnt enough, fix the tests; that is remove those illegal errors.

My advise: go for the second option, and close the issue with these tests running. Take note that there are three  more failing tests. Fix these as well.

Java training should proceed to the  annotations and to the environment.

**Comment by sakopzon** [comment]
Do you mean this one:
@Ignore("Issue #230") @Test public void a2() {
    trimmingOf("private @Nullable T value = null;") //
        .gives("@Nullable private T value = null;") //
        .stays();
  }
Because I tan all existing tests write now and everything works..

**Comment by yossigil** [comment]
I think there are more `@Ignore`s like this in other folders / issues, all of a result. In junit test, ask it to present only "skipped" tests: go over them. Some are related to removed features such as Switch, but yours will pop out

**Comment by sakopzon** [comment]
As I didn't see the falling tests and didn't look at the Ignored ones, I continued researching the filter idea I had.
Results: I avoided two for loops, while eliminating one by using direct access (array bit map), and the second loop is now hided under beautiful java 8 code style!

Now I saw the tests you talked about. Will treat them in a few hours.

**Comment by yossigil** [comment]
:+1:

**Comment by sakopzon** [comment]
I close the issue, as the remaining tests refer to an other wring.

**Comment by yossigil** [comment]
@sakopzon : any idea which issue?

**Comment by OriRoth** [comment]
I inspected the failing test, and it appears the Tip called is `$BodyDeclarationModifiersPrune`.
Failing test is `Issue111#A$g`. @sakopzon notice the result is different from what you would expected, and also from applying in real environment (!) because the test utils preform the spartanization process in reverse order to the marking process, i.e. top-bottom instead bottom-up.
@yossigil Further more, the example in this test appears to create an ***infinite loop*** of spartanizations:
```
protected public final public enum Level {
  HIGH, MEDIUM, LOW
}
```
==>
```
protected public public enum Level {
  HIGH, MEDIUM, LOW
}
```
==>
```
public public protected enum Level {
  HIGH, MEDIUM, LOW
}
```
==>
```
public public protected enum Level {
  HIGH, MEDIUM, LOW
}
```
(same! bad...)

**Comment by yossigil** [comment]
I will take a look tonight
