### ISSUE TITLE
Do not ternarize into method in case of overloading and in case of template methods

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#232]
Search the current compilation unit. This is a good enough heuristic

**Comment by yossigil** [comment]
@NivShalmon : here is a challenge for you, which I cannot get on doing. The strategy is simple:
1. Go top as high as you can in the local context. There might e a function that returns the root directly.
2. From the top go down, collecting all occurrences of method declaration, in which the declared method name is the same as that of the method your are going to push into.
3. at the moment you suspect an ambiguity  might occur in pushing down into the method you abort the pushdown.
4. Ambiguity can happen due to overloading, which can occur if the same method occurs twice, with different signatures, but with different types of the position in the function you pushdown into.
5. Ambiguity can happen also due to genericity. If you find a function that has the same name and the same number of parameters, but generics we must abort the pushdown.


Also:

1. Create and use `iz.generic` function
2. if you use `iz`, `haz`, etc., you will be saving time. Feel free to add functions to these.
3. Perhaps the easiest way to start is with making a function hat gives all methods:
hop.allMethods(), i.e., returning also methods defined in other methods. , could also do a 
hop.methods() which returns all methods at the upper level, but not sure you need this for the 
current project
-

**Comment by NivShalmon** [comment]
@yossigil Shouldn't using MethodInvocation.typeArguments be enough to determine whether the same method is used or not? If the type arguments in both lists are the same and non-generic, pushing down the trenarization should be safe.

**Comment by yossigil** [comment]
You seem to be right. Could not find a counter example. But I suggest to leave this point aside for now. The original intent was to deal with about three cases in about 1000 in common-langs.  I believe the simplest solution, i.e., do not take the risk with generics, will suffice. 

But, I also know we will need this sometime. So why not leave the safe cases in case of generics to the time we need them. Best to open a dormant issue in the backlog, just to keep this new optimization for times to come.

**Comment by yossigil** [comment]
@NivShalmon : but do you take the challenge?

**Comment by NivShalmon** [comment]
I don't think I can implement the search of the compilation before the 30.9, but I will try to solve this using typeArguments, at least to avoid generics for now.

**Comment by yossigil** [comment]
Is searching for the method in the compilation unit so bad?

**Comment by NivShalmon** [comment]
After some testing of typeArguments, it seems that using it wouldn't solve most cases, even for generics. I'll try to do a search of the compilation unit

**Comment by NivShalmon** [comment]
@yossigil I think I can get this done today, once I solve a small bug with recurser. Should I finish this or just leave it?

**Comment by yossigil** [comment]
Leave it, and save your energy, we will need it today and tomorrow
