### ISSUE TITLE
Eliminate empty switch

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#233]

**Comment by yossigil** [comment]
@yuvalsimon How come this is still open???

**Comment by yuvalsimon** [comment]
@yossigil I found this test in the project: (il.org.spartan.spartanizer.tippers.Version230.java)
 ```
 @Test public void dontELiminateSwitch() {
    trimmingOf("switch (a) { default: }").stays();
  }
```
Why should not eliminate the switch?

**Comment by dormaayan** [comment]
@yuvalsimon : after you added the tip, does this test fails ?

**Comment by yuvalsimon** [comment]
@dormaayan I disabled the switch default eliminiation and forgot to ignore tests

**Comment by yossigil** [comment]
You should have changed the test and keep your change.

**Comment by yossigil** [comment]
Please add `@author` and `@since` fields to your test code. I added one more test, and rewrote your code so that you never `@Ignore` a single test.

**Comment by yuvalsimon** [comment]
@yossigil Do you mean to change the dontEliminateSwitch test from above?

**Comment by yossigil** [comment]
Yes. You could have figured this yourself...

**Comment by yossigil** [comment]
Six test fail. Check the `@Ignore` label.

**Comment by yuvalsimon** [comment]
Nothing failed for me after git pull...

**Comment by yuvalsimon** [comment]
I opened issue #880 for such cases to treat this and more complicated cases

**Comment by yossigil** [comment]
:+1:
