### ISSUE TITLE
Eliminate empty finally

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#235]

**Comment by dormaayan** [comment]
@yossigil :
We are done here

**Comment by yossigil** [comment]
Good job.
Please don't use wafflebot. It's behavior is erratic

**Comment by dormaayan** [comment]
@yossigil :
That's strange, I thought  wafflebot is something you added, I didn't do nothing with that....
how can we get rid of it ?

**Comment by yossigil** [comment]
Check if this is a among the allowed applications. I will do so myself.
