### ISSUE TITLE
Make TrimmerLog use csv

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#238]
Logic is:

- record to CSV.
- Print to screen, as per the limited numbers
- Use static fields with meaningful names of types boolean / integer /File types, th to control (a) do we log to screen? (b) do we log to file? (c) How much logging to screen? (d) which files names
- This flags could later  be injected by CLI ,Dont worry about this now.
- In the CSV, do not be afraid to log whatever information you have.

**Comment by yossigil** [comment]
@M4tt30rru : did you finish this?

**Comment by M4tt30rru** [comment]
Yes, but at the moment it is printing some basic information. I would like to improve it a little bit.
