### ISSUE TITLE
type of conditional expressions

### ISSUE THREAD

**Issue by NivShalmon** [SpartanRefactoring/Spartanizer#240]
Conditional expressions handle type in an odd way, that needs to be looked into deeper. It's possible that a recursive call won't be enough when getting the type of a conditional, since it sometimes casts and sometimes doesn't (such as axiomConditional01 compared to axiomConditional19).

**Comment by yossigil** [comment]
Yes, this is a good point. thanks for taking care of this. Note that there is a limit to what you can do here, since the mechanism is a bit defective. See #226 and #227
