### ISSUE TITLE
Complete the batch spartanizer

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#245]
This means, running the command line `essence` from the batch, and reporting the compression ratios based on `wc` of these.

**Comment by yossigil** [comment]
https://github.com/SpartanRefactoring/Spartanizer/blob/7a36250e46166f998de36415f705600934acc99a/src/main/java/il/org/spartan/spartanizer/application/BatchSpartanizer.java

**Comment by yossigil** [comment]
https://github.com/SpartanRefactoring/Spartanizer/blob/80da96e4879f6fd9810e9f527375b70288b7404f/essence[](url)

**Comment by M4tt30rru** [comment]
@yossigil just to be sure that I well understood. Do I need to implement the essence script inside BatchSpartanizer?

**Comment by yossigil** [comment]
No, just call it from Java..

**Comment by M4tt30rru** [comment]
I had already worked on an implementation of the script in Java. However, I can certainly make BatchSpartanizer call the script instead.

**Comment by yossigil** [comment]
And, you do not need to do that for every file. Just apply it to the overall input file and the overall output file.

**Comment by oran1248** [comment]
I don't understand what functionality do I need to add to the `BatchSpartanizer` that it hasn't already had
