### ISSUE TITLE
Change config to checkboxes

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#25]
Instead of list

**Comment by yossigil** [comment]
@OriRoth :8ball:

**Comment by OriRoth** [comment]
Closed, see issue #160

**Comment by OriRoth** [comment]
I have put a picture of the current status in #473. It does has check-boxes in the configuration page - are you sure you are using the updated version?

**Comment by yossigil** [comment]
Boomer. UR right.
