### ISSUE TITLE
"if (b) {int x = some(expression(with(possible(side(effects))))); }

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#251]
Sometimes, as an intermediate, we get kinds of weird stuff such as `if (b) {int i;}`or or just plain unconditional block `{int f =E;}`, or a block within an iterative `while(b){int i= E;}`, and it may even occur in plain and enhanced `for` loops.

What do we do? When can we kill the **block**, the **initializer**, the **conditional**, or the **loop guard** in `while loop`? Things get even more hairy when you talk about plain `for` loops, and even enhanced `for` loops ain't completely trivial. 

And what about `while` loops?  And `do` ... `while` loops also need to be addressed somehow. And can this happen in a switch? And in `try` block?  What are other block kinds in Java? How about lambda expressions.

And `synchronized` block? Lots of options to consider. Many should be probably pruned right away, e.g., it would not be wise to touch `synchronized` blocks.

Your mission is to sort out the options here, make clever design choices on what can and what cannot be done based on:

- is the initialize deterministic? free of side effects?
- same for the conditional
- same for the iteration variable.

the decision should be pretty clear, if you want to preserve semantics. Part of your mission is to find the most extreme, yet safe winging.

**Comment by yossigil** [comment]
My advise: do not mess too much with the `sideEffects` function. I know it needs tweaking,  but it is a lot of work and I am not sure it is worth it. It is pretty robust now.

**Comment by dormaayan** [comment]
@yossigil :
I handled the cases of if/for/while that contains only variable declarations and don't have any side effect.
Do you see more things I should do here ?

**Comment by yossigil** [comment]
Do you have a test for the above case? If so, please close them both.
