### ISSUE TITLE
Automatic detection of nanos

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#252]
Perhapsour traveral system can be used to find  nanons itself?

**Comment by yossigil** [comment]
Here comes a commit with an example plain macros cannot do. **Fill in for syntax baggage** 
Something like this
```java
  @Override protected void addUserInputPages() {
    ___.______unused(this); 
  }
```
This is a real nano pattern!

@orimarco @M4tt30rru

**Comment by orimarco** [comment]
Well, I think we're doing this
