### ISSUE TITLE
GUI Performance Improvements

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#266]
@yossigil what is your opinion?
*Suggestions:*
* Count markers instead of first collectSuggestions in SpartanizeAll.
* GUI$Applicator should return number of changes (instead of boolean) instead of collectSuggestions in SpartanizeAll.
* Or markers as well, if possible.

**Comment by yossigil** [comment]
Not at this stage. The real performance boost will be exactly when WE DO NOT SAVE THE "ACTION" method in the marker. If you save the action, you save the parameter, if you save the parameters you save the entire AST, and this happens for EVERY compilation unit.

There are too many unstable parts. Sorry, don't touch this now.
