### ISSUE TITLE
Efficient markers

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#268]
The real performance boost will be   when we stop saving the "ACTION" method in the marker. If you save the action, you save the parameter, if you save the parameters you save the entire AST, and this happens for EVERY compilation unit.

The architecture should be able to  save the class (or the integer coming from .getNodeType()) with the marker, and nothing more. We should have a "QuickApplicator" (name TBD), which takes a marker and apply its tip to it.

**Comment by yossigil** [comment]
Not to be touched before 2.5 is out

**Comment by yossigil** [comment]
@OriRoth this is for you

**Comment by yossigil** [comment]
Related to #276

**Comment by OriRoth** [comment]
So you are talking about the marker resolutions right?
We may create a singletonic marker resolutions instead... what do you think? It has the potential for performances boost in matters of time and memory.

**Comment by yossigil** [comment]
No, I was talking about #286

**Comment by OriRoth** [comment]
See #387
