### ISSUE TITLE
Sort modifiers makes an empty suggestion

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#269]
when the modifiers include an annotation, this lead to an infinite loop

**Comment by sakopzon** [comment]
my last commits don'y appear now!! some shit happened

**Comment by yossigil** [comment]
Please make a small change, that resolves this, just this and get it over with

**Comment by sakopzon** [comment]
Some one wanted me to suffer:( I got a little bit crazy here now... the TODO I left about what is better, to save bitMap inside the enum or create an instance in removeSame(), made some one try and suggest a third solution: create new instance every time we call the predicate... not good :)
everything is back on it's place, but all my today's work on whileToFor wring is gone (at least the code.. but writing something again is sometimes useful). Tomorrow will proceed to this one 144 if I remember right.

**Comment by sakopzon** [comment]
I saw "// Disabled to protect against infinite loop" comment in the toolBox, I removed comments from two wrings like this (otherwise 230 can't be activated), steel I didn't see any infinite loop...

**Comment by yossigil** [comment]
The loop happens when you apply the plugin, not in testing. Your tipper (wrings are dead, remember?) says it can offer a tip, but the tip it offers has no changes in it. So, the global spartanizer, thinks there is more to do, and goes on into an infinite loop.

**Comment by yossigil** [comment]
@dormaayan : you mission, should you choose to accept it is to resolve this issue which turned out to be a blocker.

In short,the issue is the sorting of modifiers such as abstract static protected. It is hairy because modifiers and annotations are stored in one list by the JDT: list of things called extended modifiers.
The tipper (remember, no more wring lest we kill someone), should sort the modifiers and modifers only. And it should only offer a tip, if the sorting would change the order in one way or another. 

To help, I wrote three functions

1. step.extendedModifiers() which returns the raw list of extended modifiers. 
2. extract.modfiers() which returns a copy of the raw list, which has only modifiers.
3. extract.annotations(), which returns a copy of raw list, which has only annotations. 

I think function 1 should be used mostly for optimization: there is nothing to do in the tipper, if the list is empty.

See if you can help.

**Comment by yossigil** [comment]
I would have made sure that the tipper only sorts modifiers, and have another tipper that sorts annotations, which is a whole new business

**Comment by yossigil** [comment]
@dormaayan : this one is becoming critical, upon applying the plugin on itself, we can about 800 tips such as this. Worse, they make our fixed point spartanizer go ballistic.

**Comment by dormaayan** [comment]
@yossigil : few minutes is done

**Comment by dormaayan** [comment]
@yossigil : How do you want me to sort the annotations, Alphabetically ?

**Comment by dormaayan** [comment]
I close that issue and move to Issue #283

**Comment by yossigil** [comment]
:100:
