### ISSUE TITLE
Before and after statistics for spartanize active window and spartanize project

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#270]
Compute total, and accumuating stats as in SpartanizeCurrent, for :+1: 

- [ ] Spartanize entire project
- [ ] Apply tipper to current window

- [ ] LOC

- [ ] NOT: number of tokens

- [ ] Halstead metrics

**Comment by yossigil** [comment]
This issue was opened as promised in #203

**Comment by yossigil** [comment]
@OriRoth : if you like it it, wait to the end of the week

**Comment by OriRoth** [comment]
See #287

**Comment by yossigil** [comment]
This is not the same as stats. Stats include various structural issues.

**Comment by OriRoth** [comment]
@yossigil I need some explanations:
* NOT => size of AST???
* Halstead metrics.... I did no find any good implementations on the net - is it done in our project or should I implement it myself?

**Comment by yossigil** [comment]
NOT = Nmber of Tokens.
Halstead? This will wait for version 2.7, don't work on this now
