### ISSUE TITLE
The stub pseudo-syntax

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#275]
Automatically generate self documenting snippets such as:

``` java
  @Override public void stop() {
    ___.nothing();
  }
```

or

``` java
  @Override public void tickTack(Tick tack, Tack tick) {
    ___.nothing(tick, tack);
  }
```

if you pardon the pun.

The issue is similar to #274

**Comment by orimarco** [comment]
?

**Comment by yossigil** [comment]
It is way to show that the nano pattern was found here, for unused parameters.

**Comment by orimarco** [comment]
Have other  ways to annotate pattern occurrences: 
1. New syntax
2. Method javadoc for method patterns
