### ISSUE TITLE
An architecture for easy traversal of ASTs

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#276]
- [ ] 1. Describe initial libraries: Perhaps even move into a different library, which has noo GUI in it!
- [ ] 2. Describe Lola implementation
- [ ] 3. Apply the implementation.
- [ ] 4. Find bugs in the original
- [ ] 5. Nice OOPSLA submission

**Comment by orimarco** [comment]
Wow, I don't think i understood...
This means to use Lola for traversing ASTs instead of your iz\az\... libraries?

**Comment by yossigil** [comment]
It's a huge thing, but not as huge:

What you do is use lola to generate classes such as `az`, `iz`, and perhaps a few others, automatically

**Comment by yossigil** [comment]
Done with MapReduce
