### ISSUE TITLE
QUICKFIX += OPTION to Resolve by fully spartanizing the current window

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#279]
really short: add to the resolvers list one more resolver (known as quickfix): "Spartanize current window". Should be easy and would **not** need a handler.

(Based on an idea of #183 , which seems difficult to implement)

**Comment by OriRoth** [comment]
See new marker resolution `Laconize file`. Implemented by adding `implements IMarkerResolution` to `LaconizeCurrent`. Is that what you meant?

**Comment by yossigil** [comment]
Don't know. Does this work?

**Comment by OriRoth** [comment]
Well... yes. It just performs `LaconizeCurrent` from the problem resolution menu.
