### ISSUE TITLE
Convert while to for, gets confused, or are we missing a step?

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#281]
Does not work correctly in the code taken from our CWD code base.

``` java
  static Statement recursiveElze(final IfStatement ¢) {
    Statement $ = ¢.getElseStatement();
    while ($ instanceof IfStatement)
      $ = ((IfStatement) $).getElseStatement();
    return $;
  }
```

The conversion is good since it is little, so please tell me that after this  tipper is applied, at least planned, to complete the conversion.

**Comment by sakopzon** [comment]
Isn't it the same?
`static Statement recursiveElze(final IfStatement ¢) {
    Statement $ = ¢.getElseStatement();
    for ( ; $ instanceof IfStatement ; $ = ((IfStatement) $).getElseStatement());
    return $;
  }`

**Comment by yossigil** [comment]
OK, I am converting this into a new-tipper. Your challenge is to produce from
```java
  static Statement recursiveElze(final IfStatement ¢) {
    Statement $ = ¢.getElseStatement();
    while ($ instanceof IfStatement)
      $ = ((IfStatement) $).getElseStatement();
    return $;
  }
```

the following 
```java
  static Statement recursiveElze(final IfStatement ¢) {
    for (Statement $ = ¢.getElseStatement();; $ = ((IfStatement) $).getElseStatement())
      if (!($ instanceof IfStatement))
        return $;
  }

```

it is tough enough, but doable, for this special case, but try to make it so it converges to the result in two, three or maybe even more tip applications.

The smaller the tip, the better

**Comment by yossigil** [comment]
Actually, a non-issue at this stage. The return makes it impossible to inline into, unless we want
```java

**Comment by yossigil** [comment]
But, when it is opened, here is a test case
```java
  private static void copyFile(final File source, final File target) throws IOException {
    try (InputStream in = new FileInputStream(source); OutputStream out = new FileOutputStream(target)) {
      final byte[] buf = new byte[1024];
      int length;
      for (; (length = in.read(buf)) > 0; out.write(buf, 0, length))
        ;
    }
  }
```

**Comment by dormaayan** [comment]
Did as much as I can here, but there are much more problems that are relates to the still open Issues on loops....
