### ISSUE TITLE
Non modal dialog box SpartanizeCurrent/SpartanizeProject/WringCommit

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#282]
Appears to be a problem with **`eclipse#announce`** or even with **spartan icon**. If someone gets his eclipse freezing without getting an end message, **contact me**.
It is not clear what causes this problem, and it has a non deterministic behavior.
@yossigil it can be something with my eclipse, or a major usability issue... we should see if it is a real thing.

**Comment by yossigil** [comment]
I believe this is a matter of someone (probably me) who called the first think he caught on the web. There must be a way to place a non-freezing dialog. Find it,, and you have found the holy grail of this blackout

**Comment by yossigil** [comment]
This is were the trimmer can use the progress monitor

**Comment by OriRoth** [comment]
Only after organizing GUI$Applicator's sub monitoring. Then we can go wild with it- the new API allows doing that kind of things.

**Comment by yossigil** [comment]
See if you can do this quickly?

**Comment by yossigil** [comment]
The busywait is really unpleasant: you never know if Eclipse hung on you.

**Comment by OriRoth** [comment]
From the JOptionPane (used in `eclipse#announce`) documentation:
```
All dialogs are modal. Each showXxxDialog method blocks the caller until the user's interaction is complete. 
```
So should I find another way to display messages?

**Comment by yossigil** [comment]
Yes, find another way

**Comment by OriRoth** [comment]
Implemented a solution 🎉
[notice #400]
* `eclipse#announceNonBusy`: announce a message in non blocking way. Former announce now call this function, so all dialogs are now non blocking (but... see below).
* `eclipse#progressMonitorDialog`: the `ProgressMonitorDialog` gives us a new way to run progress monitors as non blocking. But it requires changes in code, because it provides a substitute to the `ProgressMonitor` (actually wraps it).

Currently only the `Refactorer` use non blocking progress monitor shell, thus the progress monitor shell still block in all handlers beside `Apply to entire project` marker resolution, that as you know extends the `Refactorer`.

@yossigil as you see, you can check the non blockness by running `Apply to entire project` marker resolution. You told me it was not working - it *does* work in my eclipse, so the problem may be that the plugin was not fully built. So the solution is either to wait until all project are done building, or to run the plugin in a "clean" environment (this all due to recent performance issues (???)).
But, as I said, the progress monitor shell is still blocking in most handlers. Do you want me to apply the change to all handlers, or to wait until #389 is done?

**Comment by OriRoth** [comment]
Probably will be completed in #389

**Comment by yossigil** [comment]
:8ball:
