### ISSUE TITLE
Sorting of Annotations

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Spartanizer#283]
Write a new wring that sorts the annotations properly.
@yossigil : What do you think is the right order ?

**Comment by yossigil** [comment]
Reasonable order IMHO is:

 - `@Deprecated`
 - `@Override`
 - other standard annotations, defined in the lang spec in some alphabetical order 
 - all other java.lang annotations, probably in alphabetical order
 - all other standard probably in alphabetical order
 - penultimate: `@SupressWarning` annotations 
 - last: annotations that stick to the return type, currently I think only `@Nullable` and `@NonNull`

**Comment by yossigil** [comment]
@dormaayan Yet, I am not sure we should be bothered with this. Feel free to remove the `wont-fix` label

**Comment by yossigil** [comment]
@dormaayan : find someone in the teamd todo it. It is good training

**Comment by dormaayan** [comment]
@kobybs :
I think thats easier to start with, if you need any help talk to me

**Comment by yossigil** [comment]
@kobybs, use a table of the right order. One option is an enum, see e.g., class associativity and there are other classes that manager ordering. I think also the one used for sorting modifiers.

**Comment by kobybs** [comment]
@yossigil  (1)in order to prevent deja vu code i've used an existing Class named IExtendedModifiersRank created by you, which pretend to sort all extended modifiers. for now it works, but  IExtendedModifiersRank current design will fail for Annotations names which are also modifiers names.
example: 
public native  --> native public
since @Native is also an annotation and annotations are higher on the IExtendedModifiersRank enum.

(2) any ideas why my eclipse won't let me open any of the JDT tree source files?
example: "Source not found" screen, while trying to open "Statement.class"
"

**Comment by yossigil** [comment]
Redo this. The previous imlemenentation was a hack. Just define  a sorting order using a table. It is independent of modifiers, which always come **after** modifiers

**Comment by kobybs** [comment]
@yossigil Done.

**Comment by kobybs** [comment]
@yossigil I'm not sure if it's a mistake or intended, but everything reverted back to my first implementation.

**Comment by yossigil** [comment]
I have no idea what happened. Do a git search

**Comment by yossigil** [comment]
@OriRoth do you know anything?

**Comment by OriRoth** [comment]
One of my files has been reverted as well... @kobybs its not too bad, just find your last commit in file's history: right clock file -> team -> show in -> history, then you can observe all previous commits + committers. Talk to me if you face any problem.

**Comment by yossigil** [comment]
@kobybs : there is still a minor thing that the you do not use `listrewrite` to sort the elements. This may lead to comments being lost. Create a new issue for fixing this. Don't deal with it now.

**Comment by OriRoth** [comment]
You may use the label `comments-preservation`.

**Comment by kobybs** [comment]
Why is it closed? tests are still failing.

**Comment by kobybs** [comment]
well, fixing the duplication itself was rather easy. I have no idea how to commit changes into the AST, in my days it was done like that:
``` 
@Override public ASTNode replacement(final N d) {
    N $ = duplicate.of(d);
    final List<IExtendedModifier> as = new ArrayList<>(sort(extract.annotations($)));
    final List<IExtendedModifier> ms = new ArrayList<>(extract.modifiers($));
    extendedModifiers($).clear();
    extendedModifiers($).addAll(as);
    extendedModifiers($).addAll(ms);
    return !wizard.same($, d) ? $ : null;
  }
``` 

now it's not working anymore.

**Comment by kobybs** [comment]
Done.

**Comment by yossigil** [comment]
Kudus Koby!
