### ISSUE TITLE
It ain't polite to stare, ask others to look at you. 

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#286]
You keep a pointer to an AST, the AST is alive as long as you.
You let the AST save a pointer to you, you die, when the AST dies.

Applies to #268

**Comment by yossigil** [comment]
Therefore, you do attach to the node (of an AST), by storing into a node a reference into your `this` . You do not store in `this` a reference to the node, lest its life is dependent on  you.

**Comment by yossigil** [comment]
@sakopzon , @M4tteo , @orimarco , @dngreenst , @NivShalmon , FYI:

this is relevant to `type`, computing environment, application of wrings, etc.

**Comment by yossigil** [comment]
This is the general rule behind #268

**Comment by OriRoth** [comment]
@yossigil this is the code that adds the markers:
```
  static void addMarkers(final IResource ¢) throws CoreException {
    if (¢ instanceof IFile && ¢.getName().endsWith(".java"))
      addMarkers((IFile) ¢);
  }

  private static void addMarkers(final IFile ¢) throws CoreException {
    Tips.reset();
    deleteMarkers(¢);
    addMarkers(¢, (CompilationUnit) makeAST.COMPILATION_UNIT.from(¢));
  }

  private static void addMarkers(final IFile f, final CompilationUnit u) throws CoreException {
    for (final GUI$Applicator s : Tips.all())
      for (final Tip ¢ : s.collectSuggesions(u))
        if (¢ != null)
          addMarker(s, ¢, f.createMarker(MARKER_TYPE));
  }

  private static void addMarker(final GUI$Applicator a, final Tip r, final IMarker m) throws CoreException {
    m.setAttribute(IMarker.SEVERITY, IMarker.SEVERITY_INFO);
    m.setAttribute(SPARTANIZATION_TYPE_KEY, a + "");
    m.setAttribute(IMarker.MESSAGE, prefix() + r.description);
    m.setAttribute(IMarker.CHAR_START, r.from);
    m.setAttribute(IMarker.CHAR_END, r.to);
    m.setAttribute(IMarker.TRANSIENT, false);
    m.setAttribute(IMarker.LINE_NUMBER, r.lineNumber);
  }
```
I do not see anything suspicious...
Adding markers is the only thing we do in the building phase, besides `Toolbox.refresh()` and `Tips.reset()`. Maybe the problem is somewhere else?
Now I will add the Tipper class to the markers.

**Comment by yossigil** [comment]
Indeed, I cannot find it either.

**Comment by yossigil** [comment]
We do this first because we did something with it and you know what's going on. So, we update everyone: 
- that the issue is closed?
- that this is a wont fix?
- that more work is done?

We do not want to leave loose ends behind us.

**Comment by OriRoth** [comment]
Well, we saw nothing can be done with the markers' content... #268 looks as it has more potential (efficient marker resolutions).

**Comment by OriRoth** [comment]
See #387

**Comment by yossigil** [comment]
This belongs with #345

**Comment by yossigil** [comment]
no longer relevant
