### ISSUE TITLE
Compute totals

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#287]
Compute total number of tips applied, and number of tips before and after
- [ ] Spartanize entire project
- [ ] Apply tipper to current window

**Comment by OriRoth** [comment]
Does it requires **metrics**? I need a short guide for it (what to include, how to get etc.).

**Comment by yossigil** [comment]
No, it doesn't. Later. Not for 2.5

**Comment by yossigil** [comment]
This is a duplicate of #270

**Comment by yossigil** [comment]
No, it is not a duplicate, we just want the total number of applications.

**Comment by yossigil** [comment]
We do this first because:
- it is easy to do
- it is quick to do
- it makes the system more consistent
- clients will find the information useful
- it would help **us** understand our product better
- it is the usual the case of tell the user what you do.

**Comment by OriRoth** [comment]
Changed `GUI$Applicator` to update number of tippers committed.
Implemented in `Refactorer` *only*, so you can see the computations in `apply to entire project` (the single tipper version, not `spartanize entire project`).

**Comment by OriRoth** [comment]
@yossigil 
Before and after message boxes for `apply to entire project`:
![tips](https://cloud.githubusercontent.com/assets/15183108/19205306/4324602e-8cea-11e6-8602-89e59e6ac4f3.jpg)

**Comment by yossigil** [comment]
:100:
