### ISSUE TITLE
Put time out of one second on the application of tipper.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#288]
If a tipper cannot return an answer within that time, remove it from the toolbox and abort it. Any time a tipper is a big buggy, we cannot do any more runs

**Comment by yossigil** [comment]
@orimarco I think the wring should be smart enough to commit suicide, unless in a debugging mode

**Comment by orimarco** [comment]
I think the only way to limit the Tipper's running time is to use a thread which will be supervised and killed if it's not responding for some time.
I think the simplest way will be to create a new thread every time a Tipper is examined and limit it's time, but I'm afraid the overhead will be big, do we really want that?

**Comment by yossigil** [comment]
Not yet...
