### ISSUE TITLE
Inline Into bug

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#289]
``` java
    public static void test() {
        final XTestArray01[] array = new TestArrayAccess01[1];
        array[0] = new XTestArray01();
    }
```

some info is lot or watever

**Comment by OriRoth** [comment]
An example for later:
```
void f() {
  final Object[] os = new Integer[1];
  os[0] = new Object();
}
```
Pass compilation, spartanize to
```
void f() {
  (new Integer[1])[0] = new Object();
}
```
Does not pass compilation.

**Comment by yossigil** [comment]
There is a quickfix I think: there should be a service telling you whether something is `deterministic`, and there should be some code guarding against inlining into something such as anonymous class,body of loop, and maybe one or more cases. The solution is to guard against inlining into the left hand side of an assignment.

**Comment by OriRoth** [comment]
All of the examples above should be made into test cases.

**Comment by tomerdragucki** [comment]
Tests are passing.
