### ISSUE TITLE
Tests for issue28

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#29]
Add to trimmerTest

**Comment by yossigil** [comment]
- [ ] Must be able to enable binding in tests.

**Comment by yossigil** [comment]
@OriRoth :8ball: This can be interesting research

**Comment by yossigil** [comment]
Just in case, #28 .
Stav: can we close this?

**Comment by Stav1472** [comment]
you want me to write tests for #28?

if so, that won't be a problem. i'll start tomorrow.
