### ISSUE TITLE
Simplify comparison of additions by moving negative elements sides and by moving integers

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#291]
- [x] Input `a + 2 == 3' output`a == 1`
- [x] Input `a + 2 > length + 1' output`a  > length -1` always move integers to the right
- [x] Input `a + 1 <= length' output`a  <= length - 1 ` always move integers to the right, and then to 'a < length', since we prefer '<' and '>' over '<=' and '>='; they are not only one character shorter, they are also clearer, since they have no ambiguity of the sort found in the phrase: "_greater **or** equal_"
- [x] Now, what about the input `a <= length` should we rewrite as `a < length+1` just because we prefer '<=' over '<'? The answer is NO, for two reasons: first we save one character, but gain two instead, even more if we count spaces. waste is also in the number of tokens: we gain two tokens for no good reason.
  The other reason is conceptual and commons sense: 'a <= length`means that a can be up and including a, we do not want to be super pure in some sense of the word pure, by saying ' a < length+1`
- [x] For input such as `a-b > c-d`, the output will be `a + d > c + d'
- [x] For input 'a < b + 1`output is`a <= b`

**Comment by OriRoth** [comment]
The last suggestion may be dangerous, considering `double` variables. An optional safety measure may be allowing the suggestion only for whole number (assuming we do not have binding).

**Comment by yossigil** [comment]
If we have binding from @sakopzon  and @dngreenst , then the `type.of(x)` might give much more accurate information. I agree that without this, very little can be said.

@sakopzon , @dngreenst : this is where your local type binder gets into play, not mentioning renaming.

**Comment by dormaayan** [comment]
@yossigil : Do you want it to work also for the following case ?
given : `a+b>c` convert it to `a>c-b` or to do that only when numbers are involve ?

**Comment by yossigil** [comment]
Definitely, and as shown in the examples, the preference is towards using '>' rather than '>='

**Comment by dormaayan** [comment]
@yossigil :
But there are cases that some tips will apply, for example here :
`a-b > c-d` --> `a+d > c+b` -->  `a > c+b-d` is that the desired result from your perspective ?

**Comment by yossigil** [comment]
So, I understand you deal with`a <= lenght-1`

**Comment by dormaayan** [comment]
@yossigil yes I deal with that it passes your test
