### ISSUE TITLE
Same as extract head but tail

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#298]
Start from

``` java
  private static String runScript(final String pathname) throws IOException {
    final ProcessBuilder b = new ProcessBuilder("/bin/bash");
    b.command(script, pathname);
    b.redirectErrorStream(true);
    return runScript(b.start());
  }
```

and identify automatically that extract head is better than extract tail, whereby idenifying the essence of the problem:, starting with the ProcessBuilder

``` java
  public static ProcessBuilder runScript¢(final String pathname) {
    final ProcessBuilder b = new ProcessBuilder("/bin/bash");
    b.redirectErrorStream(true);
    b.command(script, pathname);
    return b;
  }
```

Observe that the name  is `runScript¢`, with a little cent ¢, penny.  Now we allow ourselves to drop a penny pick a penny, when there is an overloading issue. Point in case here is that the newly generated function has the same signature, so we had to pick a penny.

These are the cases you pick a penny? Coming to think of it, I never dropped a penny in these jars, but and I cannot think right now of a time when a  penny be dropped back.

Now, the original function is reducd to: 

```
  private static String runScript(final String pathname) throws IOException {
    final ProcessBuilder b = runScript¢(pathname);
    return runScript(b.start());
  }
```

which is then further laconized into:

```
  private static String runScript(final String pathname) throws IOException {
    return runScript(runScript¢(pathname).start());
  }
```

laxonizing, further we get:

``` java
  public static ProcessBuilder runScript¢(final String pathname) {
    final ProcessBuilder $ = new ProcessBuilder("/bin/bash");
    $.redirectErrorStream(true);
    $.command(script, pathname);
    return $;
  }
```

**Comment by yossigil** [comment]
@dormaayan : FYI

**Comment by OriRoth** [comment]
Did you meant "Same as extract tail but head"? Also reference #255

**Comment by OriRoth** [comment]
Also... it does seam like a different problem, thus requires a different tipper.

**Comment by OriRoth** [comment]
Continued in #257
