### ISSUE TITLE
Block Simplify Bug

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Spartanizer#302]
Transforms :
```
if(b){
    int i;
}
```
into :
```
if(b)
    int i;
```
Which is Illegal...

**Comment by OriRoth** [comment]
I think this issue has a duplication, but I cannot remember what it is called...

**Comment by yossigil** [comment]
@dormaayan , @NivShalmon 

What do you know of this?
Isn't this related to #251?
If so and you deal with this, close this issue

**Comment by dormaayan** [comment]
@yossigil : That is not caused by Issue #251 but I found that problem during my work on Issue 251.
I can try to solve that

**Comment by dormaayan** [comment]
@yossigil : Solved
