### ISSUE TITLE
One handler to tip them all

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#303]
Consolidate *all* BaseHandlers; LaconizeProject, LaconizeCurrent, LaconizeClass, TipCommit etc. under **one** handler. This meta handler should support variations of:
* What *files* do we spartanize
* What *tippers* do we use
* In what *text selection* do we operate
* How many *operation cycles* we need to conduct
* What *messages* to show to the user, if any

And maybe more.

@yossigil worth consideration... making more and more handlers is unmaintainable.

**Comment by yossigil** [comment]
:+1:

**Comment by OriRoth** [comment]
@yossigil I am getting it ready in order to replace the `SingleTipperApplicator` (former `WringCommit`) implementation.

The main base handler/marker resolution class is `Refactorer` (*I will change the name later*). It contains the running logic of out handlers, so successors may override specific methods in order to run as they wish.

The new implementation of WringCommit is `SingleTipper`: this is a GUI$Applicator that fit to use with one tipper. Also, this class contains the implementations of Refactorer used as marker resolutions (*I will move them out later*), i.e. apply on function/file/project:
* `SingleTipper.InDeclaration`
* `SingleTipper.InFile`
* `SingleTipper.InProject`

What do you think? your opinion is very important at this moment, as I consider using `Refactorer` for *all* the handlers and marker resolutions.

Also you may check #379, a problem I encountered while working on this.

**Comment by OriRoth** [comment]
Continued at #389
