### ISSUE TITLE
RemoveRedundantIf creates a new empty block

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#304]
Notice (failed) test `ifEmptyThenThrowVariant` in `TrimmerTest.java`:

```
@Test public void ifEmptyThenThrowVariant() {
  trimmingOf("if (b) {;} throw new Exception();\n").gives("  throw new Exception();");
}
```

This is actually spartanizes to `"{} throw new Exception();"`.
I believe this is caused by `RemoveRedundantIf` tipper, replacing redundant if with an empty block. We should consider not adding the block, just erasing the if statement.
@yossigil what do you think? another option is to fix the test to:

```
@Test public void ifEmptyThenThrowVariant() {
  trimmingOf("if (b) {;} throw new Exception();\n")
    .gives("{} throw new Exception();").gives("throw new Exception();");
}
```

Notice a regular spartanization will first remove the parenthesis, then the if statement. LaconizeCurrent (and the test utilities doing spartanization) will first replace the redundant if with an empty block (not cool), then remove the empty block (cool) so the final result is what we want. In other words, this issue applies only to tests, not for real usage.
@dormaayan you are signed on `RemoveRedundentIf`, consider helping me solve this.

**Comment by yossigil** [comment]
@dormaayan : I fixed the test. 
@sakopzon : wheren't you in charge of this?

**Comment by yossigil** [comment]
@SapirBismot ?

**Comment by SapirBismot** [comment]
I checked it and the test doesn't fail.
I run the plugin with 
```Java
if (b) {;} throw new Exception();
```
and ==>
```Java
throw new Exception();
```
as we wanted.
