### ISSUE TITLE
Loop conversion with last body statement updater

### ISSUE THREAD

**Issue by sakopzon** [SpartanRefactoring/Spartanizer#310]
`while(true) ++i;` ---> `for(;true;++i);`
and
`for(;true;) ++i;` ---> `for(;true;++i);`

**Comment by sakopzon** [comment]
ConvertWhileWithLastStatementUpdateToFor
ConvertForWithLastStatementUpdateToFor
Are the names of the tippers. They have been tested for any kind of updater I know.

**Comment by yossigil** [comment]
:+1:

**Comment by yossigil** [comment]
another example
```java
  static void removeAll(final boolean b, final List<Expression> xs) {
    for (final Expression ¢ = find(b, xs);;) {
      if (¢ == null)
        return;
      xs.remove(¢);
    }
  }
```
to
```java
  static void removeAll(final boolean b, final List<Expression> xs) {
    for (final Expression ¢ = find(b, xs);;) {
      if (¢ == null)
        return;
      xs.remove(¢);
    }
  }
```

**Comment by sakopzon** [comment]
This is easy... the tipper is on challenge stage. If till night no one would give a falling test, I'll close it.

**Comment by yossigil** [comment]
:+1:
