### ISSUE TITLE
Python tool to consolidate tests by issue

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#313]
Should be simple. I still have the script I used to split `TrimmerTest` into `TrimmerTestValid` and `TrimmerTestIgnore`.
A good behavior can be ignoring test files with `@Ignore` annotation.
@yossigil I guess we would like to do that once in a while

**Comment by yossigil** [comment]
Good idea. But, on hold for now. TOo many things don't work
