### ISSUE TITLE
All classes have authors

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#316]
Can we have a tool on conarQube?

**Comment by M4tt30rru** [comment]
@yossigil I was looking for something related to the authors on the sonarqube website, but I still did not find anything related. Would you like something to compute some "people" metrics like ownership, authorship and the like?

**Comment by yossigil** [comment]
No, don't worry about this. It is just a general quality principle

**Comment by yossigil** [comment]
@idabran : we need this to be on a wiki page, can you please find someone to do it?

**Comment by yossigil** [comment]
@ravivos : can we close this now?

**Comment by ravivos** [comment]
@yossigil, I Guess so.
Also you can see the program we made for it and use it for your own will:
https://github.com/yaakovs/since-authorAdder

**Comment by yossigil** [comment]
💯
