### ISSUE TITLE
Pattern to search for idioms such as empty implementation

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#319]
``` java
@Override fWithSomeLongName(SomeVeryLongListOfParameters(){
// Do nothing
}
```

Or many of the things in the syntactic baggage `TipperCategory`

or an exception block that does nothing/ignore the exception/print a trace, and other fillers.

Or setters and getters, or common loop structures, such as the one in #311 #309 and their vicinity

**Comment by yossigil** [comment]
Here is another caching idiom to search for 
```java
  public static Toolbox defaultInstance() {
    // Lazy evaluation pattern.
    if (instance == null)
      instance = allTippers(); 
    return instance;
  }
```

**Comment by orimarco** [comment]
done those
