### ISSUE TITLE
Tutorial I: My first comment on an issue

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#326]
**Previous**: #338 **Next**: #328 
# Welcome

Welcome to the first issue in our study. **Read through** this issue:
- Do **not modify** this issue
- As you read, you would be asked **add a comment** on this issue that you are reading now. 
- Please **follow** the request. Don't worry, _you are in safe hands_. 

**Don't read** the next sentence , unless you are a lawyer, or criminal. _This issue is dedicated to students of the yearly programming project at the Technion, but can be borrowed for other purposes, subject to the MIT licence._ Also, we know how to deal, complain on, sue, etc. trolls. So, if you are one, don't waste our time.
# From ideas to actions with issues

Issues are often born as a raw idea.  The idea evolves by a discussion: Participants **make comments**,. Th  rolling discussion,  eventually leads to the resolution of the issue in ways such as:
- Holding any further unfruitful discussion, and placing the issue in the backlog, for further consideration sometime
- Fine tuning the idea into an actionable, assigning it to an individual, who eventually close this issue.
- Labeling this issue as `wont-fix` and closing it
- Marking as duplicate of another issue
  - Closing the current issue
  - Giving reference to the closed issue from the non duplicate
# Your First Comment

The life time of an idea issue requires comments. You can comment on any issue, and you will quickly learn when it a  good idea to do so.

This article you read, is an issue just like any other issue. You are **requested** to make a comment on it. To do so,  scroll down as much as necessary, to the wide window for adding comments.

This course is not just to read. It is to **play** with:
-  No fear, chances of you making **any harm** are slim. 
- They are **infinitesimal** if you follow the instructions.
- If any thing goes wrong, the administrator will forgive **honest mistakes**. 

So, please scroll down **now**, and add a thumbs up icon :+1: by  hitting these characters

``` java
:+1:
```

that is `:`, followed by `+`, `1` and `:`. You can also add a few words if you like.
## **Do this now.**  After making your first comment this, scroll back **HERE**

Next step of this interactive game, you scrolled back, now is the tie to find the EMOJI button on the issue. See if you can find it, to express how you feel about your first lesson.
# Where am I?

You are being hosted at the [spartanizer](url) project. 

**Huh?** I did not want to bother you with the trouble of creating a new repository, adding labels, etc. Before you see what an issue is. So, for the purpose of this study, you are a very welcome guest, and you wish to stay, that's also fine.
# Conclusion

You should know (roughly) what are:
- Issues
- Comments
- Emoji
- Ideas evolution with issues

You have encountered the terms:
- backlog
- wont-fix
- creating an issue
- closing an issue
# Required further reading

[GitHub 10 min tutorial](https://guides.github.com/features/issues/)

**Comment by idabran** [comment]
:+1: I think it is a very good platform to share and improve ideas. It can be mostly interesting when a brain storm appears..

**Comment by sakopzon** [comment]
:+1: nice

**Comment by M4tt30rru** [comment]
:+1: cool

**Comment by zvili** [comment]
:+1:

**Comment by AdiOmari** [comment]
nice

**Comment by kfir-marx** [comment]
👍

**Comment by ravivos** [comment]
:+1:

**Comment by matityahuinba** [comment]
:+1:

**Comment by noamyft** [comment]
:+1:

**Comment by zahimizrahi** [comment]
👍

**Comment by ortroyaner** [comment]
:+1: hash tag - we've started

**Comment by Tomnof** [comment]
:+1:

**Comment by NikDizh** [comment]
:+1:

**Comment by TonyLek** [comment]
:+1:

**Comment by RonGatenio** [comment]
👍

**Comment by Kolikant** [comment]
:+1:

**Comment by yuval250** [comment]
:+1:

**Comment by yossigil** [comment]
@yuval250 : use an appropriate name.

**Comment by roy-shchory** [comment]
:+1:*dabing*

**Comment by ylevv** [comment]
:+1: :cake:

**Comment by orenafek** [comment]
:+1:

**Comment by SapirBismot** [comment]
:+1:

**Comment by SharonKL** [comment]
:+1:

**Comment by yosefraisman** [comment]
:+1:

**Comment by Roei-m** [comment]
:+1:

**Comment by leyaniv** [comment]
:+1:

**Comment by maoritsius** [comment]
:+1:

**Comment by yaelAmitay** [comment]
:+1:

**Comment by sefialbo** [comment]
:+1:

**Comment by Shahar-Y** [comment]
:+1:

**Comment by AmitOhayon** [comment]
👍

**Comment by osherh** [comment]
:+1:

**Comment by viviansh** [comment]
:+1:

**Comment by inbalzukerman** [comment]
:+1:

**Comment by shimonAzulay** [comment]
:+1:

**Comment by LiorBenAmi** [comment]
:+1:

**Comment by OmriBS** [comment]
:+1:

**Comment by HadadIdan** [comment]
ok

**Comment by HadadIdan** [comment]
:+1:

**Comment by maxcalderon1997** [comment]
:+1:

**Comment by igorbash** [comment]
:+1:

**Comment by OmerGlick** [comment]
👍

**Comment by LiorBenYamin** [comment]
👍

**Comment by NirChachmovitz** [comment]
👍

**Comment by shalev-kuba** [comment]
:+1:

**Comment by addirabasker** [comment]
:+1:

**Comment by OrYasso** [comment]
:+1:
