### ISSUE TITLE
JUnit project as preformance and correctness benchmark

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#33]
Need to check spartanizations apply on the junit project, in regard of:
1) the time it takes
2) is the final code correct
3) does it has comments preservation
https://github.com/junit-team/junit4

**Comment by OriRoth** [comment]
I have been running spartanization on the project. Some important observations:
1) it took about half a minute to run the entire spartanization
2) *there have been some errors* after the spartanization, need to check it out
3) I have added some comments by hand, and they have been preserved (need further check with @DisableSpartan)

**Comment by OriRoth** [comment]
The Source mechanism has become quite complicated, and a real bottleneck for maintenance and comments manipulations... Is there a better way of document the subject?

**Comment by OriRoth** [comment]
Now that the Wrings are dependent on a context (source code + compilation unit) in order to work properly (for comments management), there should be a Wring for each compilation unit currently worked. The simple solution currently implemented is a *different Toolbox for each activation of a Trimmer*

**Comment by OriRoth** [comment]
Spartanizing JUnit project with postorder and safe*** visitor takes about a minute and a half, and conducts four passes (instead of one pass in half a minute).
Postorder and safe visitor visit nodes post order, and exclude from spartanazation any parent of spartanized node (see Trimmer class).

**Comment by yossigil** [comment]
OK, I think we are beyond this now
