### ISSUE TITLE
Tutorial III: A presentable GitHub profile

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#330]
**Previous**: #328  Next: #479 

## Introduction: Joining the community
You mission in this tutorial is to make yourself part of the developers' **community**. 
- Most projects are just to large for an individual
- We have to work in a team
- Team must work together
- To work together, you must play by _social rules...

## What should I do?
Concretely, you should create a new issue whose name is:  **John Doe: introduction**_, except that you replace the words `John Doe` with your name. 

**Example**: Issue #366, that I created for introducing myself  (Yossi Gil), following my own instructions in this current issue

## If I am expert, should I still do it?
1. If you are *not* an expert, skip to the next section. This one is for people who know it all. 
2. Yes, but it should be a breeze. 
3. Show us that you are an expert by creating your *\* Big Expert: Introduction *\* with as few as possible editing operations in the issue's history. (If you look at Issue#338, you will see that I did much too many change operations)
4. Minimizing the number of operations is not an objective by itself. It is just that if someone is watching the issue, and currently online, he would be buzzed for every little change you make. No big deal. People know how to deal with this.

## Steps
1. Create a new issue which **duplicates** this one (#330)
2. Assign the **new** issue to yourself.
3. Check marks the items in it, after doing it. 
4. Close your issue, with a comment mentioning me, or another staff member:

```
@YossiGil: Done.
```

# Checklist and progress bar

Your issue should include the following checklist. I will tell you below how to create it.
- [x]  Use a picture, photo or distinct, familiar, personal 
avatar. Don't use an automatic icon (we need this to be able to identify you in the tens of students we have):

| Example | Score | Why? |
| --- | --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142710/39a00e24-8ba8-11e6-9971-da4e2f3b67c7.png) | Bad | Vague |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142719/472644c8-8ba8-11e6-8061-f152156545dd.png) | OK | Reasonably identifying |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142724/5a508a04-8ba8-11e6-80e4-25cff412acc9.png) | Huh? | Monkey? |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142805/d3e92c4a-8ba8-11e6-86fc-02c1559b8b8b.png)
![image](https://cloud.githubusercontent.com/assets/12775400/19851642/9db66d36-9f67-11e6-8615-2a087b9d3b66.png) | Terrible | GitHub auto generated |

If you have an issue with privacy, talk to the staff. We are usually reasonable.

- [x] Present yourself by a not too rude **nick**  

| Example | Score | Why? |
| --- | --- | --- |
| `Moshe Levy II` | Super | Clear identification |
| `YossiGil` | Very Good | You identify yourself by full name |
| `IDabran` | Very Good | == **I**tai **Dabran** |
| `YossiG` | Very Good | == **Yossi** **G**il |
| `rms`    | Good | == **R**ichard **M**. **S**tallman | 
| `yogi` | OK | Well known nick |
| `j1046` | Bad | Who the hell are  you? |
| `zm&4jk` | Worse | Not even pronounceable |
| `r2d2` | Terrible | We are not playing games here |
| `ghost` | Disaster | Are you a troll or what? |

    Summary:
      - Fine: `yogi`  (**Yo**ssi **G**il), `idarban` (**I**tai **D**arban)
      - Not so fine: `j1046` / `r2d2` / `bb8` / `biscuit` / `the destroyer`/`nukethem69h7`

    (Again, we need this to be able to identify you in personal meetings. If someone feels the bear with basket is the best representation of his identity, so be it. If someone presents herself the *Mac Apple Icon*? Not so sure.)
- [x]  Describe yourself in the bio page; FYI, here is my description:
  ![image](https://cloud.githubusercontent.com/assets/12775400/19105201/753bb934-8ae9-11e6-8f63-659f5c14162e.png)
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
  ![image](https://cloud.githubusercontent.com/assets/12775400/19105155/3554e8cc-8ae9-11e6-8915-a180075388b1.png)
  14162e.png)
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
  ![image](https://cloud.githubusercontent.com/assets/12775400/19105155/3554e8cc-8ae9-11e6-8915-a180075388b1.png)

# 
  How do I create the above nice checklist in my new issue?

Cut and paste the following into your new issue:

```markdown
- [ ]  Use a picture, photo or distinct, familiar, personal 
avatar. Don't use an automatic icon (we need this to be able to identify you in the tens of students we have):

| Example | Score | Why? |
| --- | --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142710/39a00e24-8ba8-11e6-9971-da4e2f3b67c7.png) | Bad | Vague |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142719/472644c8-8ba8-11e6-8061-f152156545dd.png) | OK | Reasonably identifying |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142724/5a508a04-8ba8-11e6-80e4-25cff412acc9.png) | Huh? | Monkey? |
| | Example | Score | Why? |
| --- | --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142710/39a00e24-8ba8-11e6-9971-da4e2f3b67c7.png) | Bad | Vague |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142719/472644c8-8ba8-11e6-8061-f152156545dd.png) | OK | Reasonably identifying |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142724/5a508a04-8ba8-11e6-80e4-25cff412acc9.png) | Huh? | Monkey? |
|![image](https://cloud.githubusercontent.com/assets/12775400/19851642/9db66d36-9f67-11e6-8615-2a087b9d3b66.png) | Terrible | GitHub auto generated | | Terrible | GitHub auto generated |

If you have an issue with privacy, talk to the staff. We are usually reasonable.

- [ ] Present yourself by a not too rude **nick**  

| Example | Score | Why? |
| --- | --- | --- |
| `Moshe Levy II` | Super | Clear identification |
| `YossiGil` | Very Good | You identify yourself by full name |
| `IDabran` | Very Good | == **I**tai **Dabran** |
| `YossiG` | Very Good | == **Yossi** **G**il |
| `rms`    | Good | == **R**ichard **M**. **S**tallman | 
| `yogi` | OK | Well known nick |
| `j1046` | Bad | Who the hell are  you? |
| `zm&4jk` | Worse | Not even pronounceable |
| `r2d2` | Terrible | We are not playing games here |
| `ghost` | Disaster | Are you a troll or what? |

    Summary:
      - Fine: `yogi`  (**Yo**ssi **G**il), `idarban` (**I**tai **D**arban)
      - Not so fine: `j1046` / `r2d2` / `bb8` / `biscuit` / `the destroyer`/`nukethem69h7`

    (Again, we need this to be able to identify you in personal meetings. If someone feels the bear with basket is the best representation of his identity, so be it. If someone presents herself the *Mac Apple Icon*? Not so sure.)
- [ ]  Describe yourself in the bio page; FYI, here is my description:
  ![image](https://cloud.githubusercontent.com/assets/12775400/19105201/753bb934-8ae9-11e6-8f63-659f5c14162e.png)
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
  ![image](https://cloud.githubusercontent.com/assets/12775400/19105155/3554e8cc-8ae9-11e6-8915-a180075388b1.png)
  14162e.png)
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
  ![image](https://cloud.githubusercontent.com/assets/12775400/19105155/3554e8cc-8ae9-11e6-8915-a180075388b1.png)

```

**Comment by sakopzon** [comment]
:+1:

**Comment by idabran** [comment]
Idabran is better readable nick than Idarban :)

**Comment by idabran** [comment]
Issue #369 holds my initial intro, Itai.
