### ISSUE TITLE
Unveiling the secrets of ASTRewrite - preservation of code formatting

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#331]
Hi all!
As you may (or may not) know, the refactoring process tend to eliminate any _user code formatting_. It can be seen while creating a new piece of code, or while copying existing code - there is no connection to the source code, thus we usually destroy the formatting (by calling `duplicate.of(...)`, for instance).
In the past, a risky solution was to get the source code for duplication operation.
After looking for the subject on the net, I encountered this article:
www.eclipse.org/articles/article.php?file=Article-Unleashing-the-Power-of-Refactoring/index.html
which is very nice... It contains some really cool tips, including:
![astrewrite](https://cloud.githubusercontent.com/assets/15183108/18973931/e73cfc2c-86a8-11e6-8434-b3477c23c7ad.jpg)
It appears to be the designated way of copying/moving around chunks of code. This is mostly relevant for changes in a large node, that does not touch some of its parts - that can be moved as is.
@yossigil I believe a simple change in tipper-building methodology can rid us from the formatting nuisance. I'll create a new abstract subclass for `Tipper` implementing this work method and use it in `ExtractMethodSuffix` (#255). I proved it could work, I just need to organize and document it all.

**Comment by sakopzon** [comment]
There are already abstract tippers which use it.. You can look at them for inspiration.

**Comment by OriRoth** [comment]
Which ones?

**Comment by sakopzon** [comment]
ReplaceToNextStatement uses Rewrite.

**Comment by OriRoth** [comment]
Yes all the tippers have an ASTRewriter (it sometimes concealed), but the question is *how do they use it*. Check this issue in a few days, I will post some explanations about a new way to deal with refactoring of large nodes, that keeps the formatting (using `ListRewrite`).

**Comment by yossigil** [comment]
Please pass it on to the person who works on tipper application

**Comment by OriRoth** [comment]
OK I'll tag him... I'll also add a clarification in the Spartanizer walkthrough (?).

**Comment by yossigil** [comment]
@michalcohen please assign

**Comment by yossigil** [comment]
@ravivos : please close this, by either creating a new wiki page, or moving the material into an existing one
