### ISSUE TITLE
Organizing searchAncestors

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#334]
@yossigil to your consideration.
I have included `inclusiveFrom` feature in `searchAncestors` because the original implementation of `from` was non inclusive - and unfortunately I have based on that claim while writing `lastInclusiveFrom`. It is unfortunate because `from` is now fixed to include first node (at least in `ByClass`), thus `lastInclusiveFrom` gets into infinite loop. I can fix some of the problems locally, but it is very clear this class need a revision.

**Comment by yossigil** [comment]
thanks for taking over this

**Comment by OriRoth** [comment]
Can I fix it myself? I want to get rid of the `inclusive` versions, then make all functions inclusive. I am not doing it because I'm not sure every usage of `from` do not assume it is non inclusive. (that is why I created the inclusive functions in the first place).

**Comment by yossigil** [comment]
Sure! But not now please

**Comment by dormaayan** [comment]
an old issue from the old group of the YP, doesn't seems relevant for now...

**Comment by yossigil** [comment]
Defunct
