### ISSUE TITLE
Sane tips for 'for(;;)' loops

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#335]
- [x] Never add to updaters list if this will the body empty

- [x] Never add to updaters anything other than
     - [x] Increment/Decrement statement
     - [x] Statement which directly updates the loop variable as, defined  in the  part of 'for(initializer;;)'

- [x] Never add to updaters something that modifies anything else other than the loop variable 
   - [x]  Maybe in the case that this is an update of a variable defined outside the loop

- [x] Never add to initializers of a an empty initializer of a for loop of this structure 'for(/* empty */;test(); iterate())', if there are more statements after the loop, which may be using the variable you are moving into the initializer.

**Comment by yossigil** [comment]
@sakopzon 
@OriRoth 
@NivShalmon 
@dngreenst 
@M4tteo 
@dormaayan

**Comment by OriRoth** [comment]
Very important:
http://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.14.1
look for the order of initializers/updaters execution - it is not undeterministic as I thought, but also not as we do it in the tipper!

**Comment by sakopzon** [comment]
On this case the `int x = 1; i += x` will first convert to `i += 1;`.
I checked what if x is used afterwards, and there is a bug. Handling it now.

**Comment by OriRoth** [comment]
Alex, check my first remark as well, and make sure we insert statements into updaters in the right order (a matter of `insertFirst` or `insertLast`).
