### ISSUE TITLE
InteractiveSpartanizer

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#336]
You receive a field bug report on this long and messy code:

``` java
public Void execute() throws ExecutionException {
    final ICompilationUnit currentCompilationUnit = eclipse.currentCompilationUnit();
    final StringBuilder status = new StringBuilder("Spartanizing " + currentCompilationUnit.getElementName());
    new JOptionPane(status, JOptionPane.INFORMATION_MESSAGE, JOptionPane.NO_OPTION, eclipse.icon, null, Integer.valueOf(0));
    final IWorkbench wb = PlatformUI.getWorkbench();
    final GUI$Applicator applicator = new Trimmer();
    applicator.setICompilationUnit(currentCompilationUnit);
    int i, total = 0;
    for (i = 0; i < (!isRepeating() ? 1 : MAX_PASSES); ++i) {
      final Int n = new Int();
      final IProgressService ps = wb.getProgressService();
      try {
        ps.busyCursorWhile(pm -> {
          applicator.setProgressMonitor(pm);
          pm.setTaskName(status + "");
          applicator.parse();
          applicator.scan();
          n.inner = applicator.TipsCount();
          applicator.apply(currentCompilationUnit, getSelection(currentCompilationUnit));
        });
      } catch (final InvocationTargetException x) {
        LoggingManner.logEvaluationError(this, x);
      } catch (final InterruptedException x) {
        LoggingManner.logCancellationRequest(this, x);
        return null;
      }
      if (n.inner <= 0) {
        status.append("\n Applied a total of " + total + " tips in " + i + " rounds");
        return eclipse.announce(status);
      }
      status.append("\n Round " + (i + 1) + ": " + n.inner + " tips (previous rounds: " + total + " tips");
      total += n.inner;
    }
    if (i != MAX_PASSES) {
      status.append("\n Applied a total of " + total + " tips in " + i + " rounds");
      return eclipse.announce(status);
    }
    status.append("\n too many passes; aborting");
    throw new ExecutionException(status + "");
  }
```

You want to start working on it, and convert it into a test case. There is a lot to do manually to convert this report into unit tests and start working on fixing this bug.

This epic is about automatically converting the report into a test case. The task is to automate following editing chores. Python is one way. Perl perhaps a better one.   
- [x] Removing all redundant spaces as done in my `sed` script: `squeeze.sed`
- [x] Removing all redundant spaces as done in my `bash/perl` script: `essence` 
- [x] Simplifying the list of identifiers, so that the first identifier is named `a`, the second `b`, the third `c`, etc.
- [x] Convert this result into a reasonably looking Java literal, such as 

``` java
  @Test public void report1593() {
    trimmingOf("// From use case of issue#1593\n" + //
            "public void f(){\n" + //
            "  if(!g){\n" + //
            "    foo();\n" + //
            "    bar();\n" + //
            "  }\n" + //
            "}"//
    ).gives("// Edit this to reflect your expectation, but leave this comment" + //
        "public void f(){"
        +"if(g)"
        + " return;"
        + "foo();"
        + "bar();}")//
       .stays();
  }
```

**Comment by yossigil** [comment]
@dormaayan , @NivShalmon , @OriRoth : just for your general information. This is not for you to start working on

**Comment by OriRoth** [comment]
Though it is a scriptual task, it can be made in Java using the strong AST tools from our project. Then it can be activate from within the project.

**Comment by yossigil** [comment]
This might be a great idea. A class with main that does this.

**Comment by OriRoth** [comment]
http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Fguide%2Fjdt_api_codeformatter.htm
(!!!)

**Comment by yossigil** [comment]
@orimarco , this is what I talked about, 

- see initial implementation as tagged in a forthcoming commit 
- see `JOptionPane.showMessageDialog` on how to obtain input.

**Comment by OriRoth** [comment]
Why not just a cmd application? This can make the feature available much sooner.

**Comment by yossigil** [comment]
We have a command line now. Take a look at the interactive. I think it is a matter of few minutes to find a way to open a dialog box...

**Comment by orimarco** [comment]
Kind of working now.
For the above example outputs:

  @Test public void report234() {
	trimmingOf("// From use case of issue285" //
 + "public A a()throws B{final C b=c.b();final D d=new D(\"Spartanizing\"+b.e());new E(d,F,H,f,null,J.h(0));final K i=L.j();final M k=new N();k.l(b);int m,n=0;for(m=0;m<(!o()? 1:O);++m){final P p=new P();final Q q=i.r();try{q.s(t->{k.u(t);t.v(d+\"\");k.w();k.x();y=k.R();k.x1(b,x50(b));});}catch(final S x54){T.x54(this,x54);}catch(final U x54){T.x54(this,x54);return null;}if(y<=0){d.x54(\"\n Applied a total of\"+n+\"tips in\"+m+\"rounds\");return c.x54(d);}d.x54(\"\n Round\"+ (m+1)+ \":\" +y+\"tips(previous rounds:\" +n+\"tips\");n+=y;}if(m!=O){d.x54(\"\n Applied a total of\"+n+\"tips in\"+m+\"rounds\");return c.x54(d);}d.x54(\"\n too many passes;aborting\");throw new B(d+\"\");}"//
).gives("// Edit this to reflect your expectation, but leave this comment" + //
"public A a()throws B{final C b=c.b();final D d=new D(\"Spartanizing\"+b.e());new E(d,F,H,f,null,J.h(0));final K i=L.j();final M k=new N();k.l(b);int m,n=0;for(m=0;m<(!o()? 1:O);++m){final P p=new P();final Q q=i.r();try{q.s(t->{k.u(t);t.v(d+\"\");k.w();k.x();y=k.R();k.x1(b,x50(b));});}catch(final S x54){T.x54(this,x54);}catch(final U x54){T.x54(this,x54);return null;}if(y<=0){d.x54(\"\n Applied a total of\"+n+\"tips in\"+m+\"rounds\");return c.x54(d);}d.x54(\"\n Round\"+ (m+1)+ \":\" +y+\"tips(previous rounds:\" +n+\"tips\");n+=y;}if(m!=O){d.x54(\"\n Applied a total of\"+n+\"tips in\"+m+\"rounds\");return c.x54(d);}d.x54(\"\n too many passes;aborting\");throw new B(d+\"\");}"//
).stays();
}
