### ISSUE TITLE
META ISSUE: Collect all Laconize tips on loops and add the label " Loopy Loops" to  to them.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#337]
This epic will include all issue related to stparanization of loops

**Comment by sakopzon** [comment]
#310 #311 #290 #155 #312 #325 #117 #130 #313 #144 #145 #147 #176 #212 #213 #225 #289 #290 #292 #293 #306 #307 #324 #325 #335.
