### ISSUE TITLE
Tutorial 0: What's ahead?

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#338]
Next: #328 
# What's this?

This is a **sprint** to get you going into working with basic software engineering tools:
1. Issue management; staff members in charge: @idabran
2. Version management; staff members in charge: @AdiOmari and @ZviLi
3. Standardization; staff member in charge @yossigil 
4. Developer/client relationship; staff member in charge @yh-github 
3. IDE: Staff member in charge @YossiGil

(a **sprint** is part of the **agile** lingo)
# What will you learn?

**Terms** you will know by the end of this tutorial 
1. Issue management: 
- Open and close operation 
- Issues and issue numbers
- Kinds of issues, and their lifecycle 
- Assignment to assignees
- Milestones and labels
- The backlog
  1. Version management:
- VCS = Version control system
- Distributive VCS 
- `git` / steps in time
- commit and commit message
- branch and merge
  1. Standardization: 
- Formatting
- Code cleanup
- Spartanization
- Signature
# Handins
1. Trace of workout through the tutorials
2. In general, every thing you do, each commit, comment and issue, contribute to your karma (somet contributions are negative)
# What is version control
- Software tools that help a software team manage changes to source code over time.
# Basic Git Workflow

**1. New Git repository**
- Create a new Git repository
  - git init
- Configure your Git installation
  - git config --global user.name <name>
  - git config --global user.email <email>
  - git config --system core.editor <editor>
  - git config --list
- Create/Edit files
  - git diff --verify changes

**2. Existing Git repository**
- Clone repository.
- Modify files in your working directory.
- Stage the files, adding snapshots of them to your staging area.
- Commit, which takes the files as they are in the staging area and stores that snapshot permanently to your Git directory.

**3. Inspect repository**
- git status --List which files are staged, unstaged, and untracked
- git log     --Display committed snapshots
- git tag     -- Create tag

**Comment by zvili** [comment]
This issue was moved to SpartanRefactoring/YP5777_Sprint0_Old-Stuff#3
