### ISSUE TITLE
Installation instructtions

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#34]
I tried installing the source following the instructions, and it simply did no matter how many times I tried, and in which fresh install I used, and permuting the order. Nothing worked. I suspect the problem lies with the fact that the package depends on itself. One of the Build commands.

Daniel, can you please check what's going on? Can you try the instructions with a fresh install?

**Comment by OriRoth** [comment]
Have you tried importing the project using egit? I have done it successfully a few days ago... It may still not work for you for some reason, but maybe its worth a shot
https://wiki.eclipse.org/EGit/User_Guide/Remote#Cloning_remote_Repositories

**Comment by yossigil** [comment]
Not sure what you did. What I did is: Fresh install of eclipse; git clone; import git project. What did  you do? Import it from "git repository"?  I tried but this did not work out for me. It did not see any of the branches.

**Comment by yossigil** [comment]
What's up with this one?
