### ISSUE TITLE
Checking plugin and publishing on Facebook

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#343]
Download link:
https://github.com/SpartanRefactoring/Spartanizer/releases/tag/2.5.0.1

**Comment by OriRoth** [comment]
@dngreenst I need you help: how to make a jar file out of this? Can you try find the easiest way to install the plugin, before publishing?

**Comment by OriRoth** [comment]
We can use the eclipse clean command like this `eclipse -clean` instead of changing `eclipse.ini`.... is there a better way?

**Comment by OriRoth** [comment]
@dngreenst Ready to publish. Please use the following links:
* What is spartan refactoring plugin? https://www.spartan.org.il/
* Github site https://github.com/SpartanRefactoring/Spartanizer
* Installation and usage tutorial https://github.com/SpartanRefactoring/Spartanizer/wiki/Tutorial
Explain shortly about the plugin.
Tag all crew members.
Publish on SSDL/faculty group, to your judgement.
Close issue when done.

**Comment by dngreenst** [comment]
Published in faculty group.

**Comment by yossigil** [comment]
How about SSDL? Ori, can you do it there?

**Comment by yossigil** [comment]
@OriRoth

**Comment by OriRoth** [comment]
Done
