### ISSUE TITLE
Release plugin to marketplace

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#344]
Daniel's instructions:
https://bitbucket.org/mittelmania/spartanupdatesite
...won't work. If anyone has some kind of experience with the eclipse marketplace, please talk to me or @yossigil.
Start up instructions from the marketplace:
http://marketplace.eclipse.org/quickstart
@yossigil you probably have a user there - if you want you can give me access to it, or we can meet to solve this issue together after the holiday.

**Comment by yossigil** [comment]
@dngreenst: Can you please place an add in facebook, including a ref to the marketplace listing and our issues page for clients to post new issues?

**Comment by yossigil** [comment]
I sent you my pw and user

**Comment by OriRoth** [comment]
@orimarco can you specify what is not working in the preferences menu? Seams to work fine... maybe fixed by Yossi...

**Comment by OriRoth** [comment]
@yossigil 
The preferences page seams to work after all (did you fixed it?). Can we release? I wait for your final permission.
Also, I saw you change the popups mechanism for debugging.... do you want me to revert it?

**Comment by yossigil** [comment]
- Revert it. I think I did.
- Warnings. Is this new? I removed warnings long time ago, just forgot to tell

**Comment by OriRoth** [comment]
@yossigil OK the plugin is now stable.
Consider the bypass I wrote in `LaconizeProject` (not that bad... necessary because of changes in `GUI$Applicator`).
Can we release?

**Comment by yossigil** [comment]
:+1:

**Comment by OriRoth** [comment]
Done. Current release is `2.5.3`.

**Comment by yossigil** [comment]
Good job
