### ISSUE TITLE
Tutorial/Git 5:  the git glossary

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#350]
- origin
- master
- head
- branch
- stash
- repository
- commit
- stage

**Comment by sakopzon** [comment]
**origin** - Local alias to the remote repository's URL.
**master** - Default name given to the "main" branch (both remote and local).
**head** - The "current" version. doesn't have to be the latest version, for example if you checkout some older version. Another definition I liked is "The parent of your next commit".
**branch** - A snapshot of the project. You can create branches with `git branch`, and change branches by `git checkout`.
**stash** - Save unfinished work on the stack, without committing it. Useful when you didn't finish work and want to move working from clean state (HEAD), or another branch. After stashing, files are re-modified to the head version.
**repository** - The remote repository holds all the snapshots of a project on the remote server, while the local saves the asked branches only.
**commit** - Save and name changes to project files (snapshots) in local repository.
**stage** - (add) Gives you the opportunity to save your work on some stage, work more, and finally commit only the staged work.

**Comment by yossigil** [comment]
defunct for now
