### ISSUE TITLE
Bug in remove else

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#352]
On this one

``` java
@Override
    Iterator<Entry<Cut<C>, Range<C>>> entryIterator() {
      if (restriction.isEmpty())
        return Iterators.emptyIterator();
      final Iterator<Range<C>> completeRangeItr;
      if (lowerBoundWindow.upperBound.isLessThan(restriction.lowerBound))
        return Iterators.emptyIterator();
    else
        completeRangeItr = ((lowerBoundWindow.lowerBound.isLessThan(restriction.lowerBound)
                ? rangesByUpperBound.tailMap(restriction.lowerBound, false)
                : rangesByLowerBound.tailMap(lowerBoundWindow.lowerBound.endpoint(),
                        lowerBoundWindow.lowerBoundType() == BoundType.CLOSED)).values()).iterator();
      final Cut<Cut<C>> upperBoundOnLowerBounds =
          Ordering.natural()
              .min(lowerBoundWindow.upperBound, Cut.belowValue(restriction.upperBound));
      return new AbstractIterator<Entry<Cut<C>, Range<C>>>() {
        @Override
        protected Entry<Cut<C>, Range<C>> computeNext() {
            if (!completeRangeItr.hasNext())
                return endOfData();
            Range<C> nextRange = completeRangeItr.next();
            if (upperBoundOnLowerBounds.isLessThan(nextRange.lowerBound))
                return endOfData();
            nextRange = nextRange.intersection(restriction);
            return Maps.immutableEntry(nextRange.lowerBound, nextRange);
        }
      };
    }

```

**Comment by yossigil** [comment]
#336

**Comment by yuvalsimon** [comment]
I don't find this method (also not in InteractiveSpartanizer.java) @yossigil 
Where is it defined?

**Comment by yossigil** [comment]
@yuvalsimon You should create a test case from the above example, and see if the bug recurs. If not, you can close, otherwise, solve.

**Comment by yuvalsimon** [comment]
@yossigil I don't understand how is it related to #336 and what is the buggy behavior. The above code is only partial  (only Override). What do I need to test there?

**Comment by dormaayan** [comment]
@yuvalsimon :
That isn't important that the code above is partial, the trimmer (as we saw on Tuesday can handle that), you simply need to create a test case with that code and see what happens, you can look over other test files in the package of tippers in order to understand how the concept works

**Comment by yossigil** [comment]
THere is also a class that takes a piece of code and simplifies it and generates a unit test. Author is @orimarco.
Try to search for it by looking at his issues and classes he wrote.

**Comment by yuvalsimon** [comment]
I don't find it @yossigil 
@orimarco  do you remember what class is it?

**Comment by orimarco** [comment]
@yuvalsimon `normalize.testcase`

**Comment by yossigil** [comment]
@yuvalsimon ?

**Comment by tomerdragucki** [comment]
passing the test of remove else.
