### ISSUE TITLE
Pack and release 2.6

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#353]

**Comment by OriRoth** [comment]
The preferences page seams to work after all (did you fixed it?). Can we release? I wait for your permission.

**Comment by OriRoth** [comment]
Reminder to self: DO NOT have two plugin packages (aka `plugin` and `plugin.old`) at release time.

**Comment by OriRoth** [comment]
@yossigil *Update:*
* No warnings.
* No spartanization suggestions (I am using the pre-release version though)
* Not all tests pass - those are the same mal-tests from last time... can you address this? I am not familiar with the mechanism/relevant project definitions.

**Comment by yossigil** [comment]
Ok, here is my result:
31 warnings, 2 errors.
0 spartanization warnings (the plugin does not run)
All tests passs.

GUI, I am worried about spartanization on and off: currently it does not make sense at all: no inidcation whether they are ON or OFF.

**Comment by OriRoth** [comment]
Yes but... what kind of indication do you expect? I have thought about showing the *button* only for spartan-enabled projects (maybe not a good idea though).... I'll open an issue for this.

**Comment by OriRoth** [comment]
@yossigil the tests won;t pass on my eclipse - there is probably some eclipse preference need to be changed... not urgent but I'll try to work it through before releasing, then update the tutorial.

**Comment by yossigil** [comment]
seems I r right
 one needs -ea

**Comment by OriRoth** [comment]
[You can extend/modify the list as you wish]
*Requests*:
- [ ] Spartanize all - add dialog.
- [ ] Add tips count in dialogs.
- [ ] Enable/disable tippers by name instead/in addition to by category.

**Comment by OriRoth** [comment]
@yossigil *Update*: implemented a user interface for selecting specific tippers in the preferences page (only GUI, **does nothing**). I want you to check it out and say if you like it - another possible option is to show the tippers on selection and not always... this is a cleaner solution, so I want to know if you like the existing GUI or you want me to implement the replacement.

In order to open the preferences page go to `Window->preferences->Java->Laconization`

**Comment by yossigil** [comment]
Ok, but I am on the bug now. ring me back if I forget

**Comment by OriRoth** [comment]
Reverted changes to preferences page, moved to next release(s). See #567.

**Comment by yossigil** [comment]
:+1:

**Comment by OriRoth** [comment]
Dooooooonneeeeeee!!!!
https://github.com/SpartanRefactoring/Spartanizer/releases/tag/2.6.3

**Comment by yossigil** [comment]
:100: 
Superb job!
