### ISSUE TITLE
Update the look of our landing page in market place

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#357]
This is a bit old:
![image](https://cloud.githubusercontent.com/assets/12775400/19063092/425fce60-8a08-11e6-8fa2-611867ca615e.png)

**Comment by OriRoth** [comment]
Yea... I could not find a way to change it from your account. Is it possible there are two Yossi Gils on that site? https://marketplace.eclipse.org/user/dmittelman/favorites
@yossigil Also please call me when you are available, thanks.

**Comment by yossigil** [comment]
@danielmittelman , when you are back, we want  your help in this

**Comment by OriRoth** [comment]
```
Automatically find and correct fragments of code to make your project&apos;s
source code more efficient, shorter and more readable
```

This is the project's description in SpartanFeature project. I am not sure this is where the description can be edited, but it looks so (same as here https://marketplace.eclipse.org/content/spartan-refactoring-0)

@yossigil do you want to put something else instead? not urgent though.

**Comment by OriRoth** [comment]
Done. We still need to wiki the process, see #955. Many thanks for @danielmittelman!
