### ISSUE TITLE
Deal with dead variables

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#359]
See test class with this number

**Comment by OriRoth** [comment]
Maybe the usage of `usesOf` is a bit costly here. Consider using a cheaper solution.

**Comment by yossigil** [comment]
it will be resolved by our environment

**Comment by kobybs** [comment]
@OriRoth can you explain where is the bug? cause all existing tests seems to pass.

**Comment by OriRoth** [comment]
Well... the tests pass but maybe they can be improved. For example:
```Java
...
.gives("if(b)return;g();int tipper;")
.stays()
```
can become
```Java
...
.gives("if(b)return;g();")
.gives("if(!b)g();")
.stays()
```
I am not sure about @yossigil 's intentions here, but it seams like an improvement could be achieved only by creating a new Tipper, and editing those tests as I described.

**Comment by kobybs** [comment]
solution was implemented as a new tipper named : BlockRemoveDeadVariables. 
many existing tests used dead variables, most of them I fixed. but some of them couldn't be fixed without loosing their original meaning, therefore I marked them as comments.  
please do not use dead variables in your tests from now on.
