### ISSUE TITLE
Applying autoformatting after spartanization

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#36]
We should consider adding auto-formatting (ctrl + shift + f in eclipse)  to apply spartanization - there are some inaccuracies while taking care of comments and overall spartanizating, so easily arranging the code using builtin formatting will resolve all the problem + future issues.

**Comment by OriRoth** [comment]
In the meanwhile I have added some basic formatting to Comments class, so the damage is not that bad.

**Comment by yossigil** [comment]
Good job.

**Comment by yossigil** [comment]
Do we need this? Can we just avoid changing the text as much as we can?

**Comment by yossigil** [comment]
Thinking again, it is best if we try to disturb the code as little as possible. Fixing this this would mean that we would hide out the cases in which we make a great mess. In addition, in fixing this we will get into a whole new mess with interacting with the user formatting preferences, and the fact that he may not be using any. So, https://github.com/SpartanRefactoring/Spartanizer/labels/wontfix
