### ISSUE TITLE
Use prefix ++ 

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#363]
from

``` java
          optarg = argv[optind];
          ++optind;
```

to

``` java
          optarg = argv[optind++];
```

**Comment by OriRoth** [comment]
Could be problematic: We cannot know whether another spartanization suggestion was offered to the previous statement. Unless, of course, the tipper will be invoked on the first statement instead...

**Comment by OriRoth** [comment]
This problem may be solved by expanding the `ExcluderManager` mechanism to track edited nodes... useful for tippers of this kind.

**Comment by yossigil** [comment]
I don't see the problem. I think there is none

**Comment by dormaayan** [comment]
@yossigil : Done

**Comment by yossigil** [comment]
:+1:
