### ISSUE TITLE
Alexander Kopzon: Introduction

### ISSUE THREAD

**Issue by sakopzon** [SpartanRefactoring/Spartanizer#368]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
  -  **No No**:  ![image](https://cloud.githubusercontent.com/assets/12775400/19101024/d3b3aa84-8acc-11e6-888f-70ce4a25b042.png)
  - **OK**: 
![image](https://cloud.githubusercontent.com/assets/12775400/19101029/e525d7d8-8acc-11e6-97f1-8bdc0bb9ac4f.png)
  - **Excellent**: 
- [x]  Make sure you present yourself by a readable **nick**
  - Bad: `j10463` / `r2d2` / `bb8` / `biscuit` / `the destroyer`
  - Ok: `yogi`  (**Yo**ssi **G**il), `idarban` (**I**tai **D**arban)
  - Excellent: `Moshe Levy II`
- [x]  Describe yourself in the bio page
- [x]  State that you are (not) in search for a job

**Comment by yossigil** [comment]
Where is your avatar?  Why didn't  you mention me, before you closed?

**Comment by sakopzon** [comment]
@yossigil  I mention you now.
What do you mean by "avatar"?

**Comment by yossigil** [comment]
Avatar is 
![image](https://cloud.githubusercontent.com/assets/12775400/19160562/fecad03a-8bf8-11e6-9cff-69cfe613c54d.png)
