### ISSUE TITLE
Itai Dabran: introduction

### ISSUE THREAD

**Issue by idabran** [SpartanRefactoring/Spartanizer#369]
- [x]  My ICON will be displayed soon
  - **Image**:  will be updated soon
- [x]  a readable **nick** presentation
  - `idabran` (**I**tai **D**abran)
- [x]  Bio page
- [x]  I'm not in search for a job

**Comment by yossigil** [comment]
@idabran 
Still to do:
1. Avatar
2. Bio

**Comment by idabran** [comment]
Done, Itai,

**Comment by yossigil** [comment]
Good job!
