### ISSUE TITLE
Pack and release of comments preservation

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#37]

**Comment by OriRoth** [comment]
- [ ] Refactor code
- [ ] Auto saving after refactoring
- [ ] Switch related wrings:
    * Currently used:
        - SwitchBreakReturn (insert non break sequencer to switch instead of break)
        - SwitchFewCasesReplaceWithIf (replaces short switch with if statement)
        - SwitchFewCasesReplaceWithIf (replaces short switch with if statement)
        - SwitchSimplify:
            - [ ] group equally branched cases
            - [ ] reorder cases by sequencer priority
            - [ ] eliminate useless cases
- [ ] Comments preservation in:
    - [ ] IfBarFooElseBazFoo
    - [ ] IfEmptyThen
    - [ ] IfEmptyThenEmptyElse
    - [ ] IfExpressionStatementElseSimilarExpressionStatement
    - [ ] IfLastInMethod
    - [ ] IfLastInMethodElseEndingWithEmptyReturn
    - [ ] IfLastInMethodThenEndingWithEmptyReturn
    - [ ] IfShortestFirst
    - [ ] IfThenFooBarElseFooBaz
    - [ ] IfThenIfThenNoElseNoElse
    - [ ] IfThenOrElseIsCommandsFollowedBySequencer
    - [ ] InfixDivisionMultiplicationNegatives
    - [ ] InfixSortingOfCDR
    - [ ] MethodRemoveDegenerateOverride
    - [ ] MethodRenameReturnToDollar
    - [ ] ReturnLastInMethod
    - [ ] SingleVariableDeclarationAbbreviation
    - [ ] SuperConstructorInvocationRemover

**Comment by yossigil** [comment]
Looks beautiful. Is it there?

**Comment by OriRoth** [comment]
Comments preservation... was a beautiful dream.

Consider #331 though.

**Comment by yossigil** [comment]
We will do comments I trust

**Comment by yossigil** [comment]
Not easy, but I believe @OriRoth can do it!

**Comment by yossigil** [comment]
Defunct
