### ISSUE TITLE
Tutorial/Git 3: create my SSH public key and place it in GitHub

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#372]
Here are a couple of hints.
- Read this [tutorial](https://help.github.com/articles/generating-an-ssh-key/)
- This one is also a great [tutorial](https://confluence.atlassian.com/bitbucketserver/creating-ssh-keys-776639788.html), by GitHub competitor
- sequence of commands on linux

``` bash
cd ~ # goto home folder
mkdir -p .ssh # make sure we have an .ssh folder
ls ~/.ssh # See what's in it
ls ~/.ssh/id_* # Stop here if you already have an id
ssh-keygen -t rsa -C "yogi@cs.technion.ac.il"
Generating public/private rsa key pair.
Enter file in which to save the key (/home/yogi/.ssh/id_rsa): 
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /home/yogi/.ssh/id_rsa.
Your public key has been saved in /home/yogi/.ssh/id_rsa.pub.
The key fingerprint is:
52:e0:05:08:f5:77:4f:f1:e5:72:8d:1b:67:52:5c:40 yogi@cs.technion.ac.il
The key's randomart image is:
+--[ RSA 2048]----+
|  .o..o..   ..Eo=|
|    .o o   . o =o|
|   o  . o . . * *|
|       o . o   O |
|      . S   . .  |
|       .  .      |
|   .o.O          |
|                 |
|                 |
+-----------------+
```
-  This screen dump from gitHub. Get there with this [link](https://github.com/settings/ssh)
  ![image](https://cloud.githubusercontent.com/assets/12775400/19107640/e0798094-8af5-11e6-803b-5c5f54d3d27c.png)
# More to do

Please read this: https://help.github.com/articles/generating-an-ssh-key/

**Comment by zvili** [comment]
This issue was moved to SpartanRefactoring/YP5777_Sprint0_Old-Stuff#4
