### ISSUE TITLE
Auto scanning in disabler

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#377]

**Comment by yossigil** [comment]
We do this first because:
- It is quick to do
- it simplifies interfacing with an obscure module
- it would help others progress and for fewer mistakes

**Comment by yossigil** [comment]
@OriRoth What's this all about? I forget...

**Comment by OriRoth** [comment]
Changing the disabler's algorithm to add a designated *property* to each disabled node instead of calculating it on the run.
BTW you had some commits on this subject, and my tests started failing... did you @Ignored the tests or reverted your changes?

**Comment by yossigil** [comment]
Now I remember. It can still wait...

**Comment by yossigil** [comment]
What's up?

**Comment by OriRoth** [comment]
It appears someone had already done it (me? Yossi? I don't remember).
Node disabling: `property.set(¢, disabledPropertyId)`
Checking if a node is disabled: `property.has(¢, disabledPropertyId)`
