### ISSUE TITLE
Do not rename variable "__" unless it is REALLY unused

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#378]
Current implementation checks only whether `@supressWarnings("unused")` annotation is present.
[clue: `Collect.usesOf(...)`]

**Comment by sakopzon** [comment]
There is some nice flag (BY_ANNOTATION) which determines whether look at the annotation or not. Do you want me to change the value of some flag there? or remove it's usage? (till you answer I just change the flag.)

**Comment by sakopzon** [comment]
**Now there is some design questions:**
1. When there are more then one parameters, should we make the replacement?
2. When the parameter's name is not JD, should we rename it?

**For now the code is doing:**
1. Replace the first only
2. Replace not JD also

**My opinion:**
1. not a problem
2. Better not touching "not JD" parameters (then also we will not have to [[SupressWarningsSpartan]] the functions in the refactorer.java)

**Comment by OriRoth** [comment]
Flags were my thing once... after a lot of C programming :P we need to check first whether the other solution is valid.

**Comment by sakopzon** [comment]
what is the "other solution"?

**Comment by yossigil** [comment]
Well, this introduced three more bugs: #442, and two in #443,if you try to self laconize.

**Comment by yossigil** [comment]
Yes, but there is no  one who to maintain this flag. So, it is either active, or dead.
