### ISSUE TITLE
Java casting is no fun and games

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#379]
[Please acknowledge 261e81b940ef2a96b338d3482aa5e3552e0926ba, i.e. there are tipper classes in markers now]
@yossigil save me please?

*Problem?*
Consider the following code:
```
System.out.println(BodyDeclarationModifiersSort.ofMethod.class.newInstance().myAbstractOperandsClass());
System.out.println(BodyDeclarationModifiersSort.ofMethod.class.newInstance().myActualOperandsClass());
System.out.println(IfEmptyThen.class.newInstance().myAbstractOperandsClass());
System.out.println(IfEmptyThen.class.newInstance().myActualOperandsClass());
```
The result is:
```
class org.eclipse.jdt.core.dom.ASTNode
null
class org.eclipse.jdt.core.dom.IfStatement
class org.eclipse.jdt.core.dom.IfStatement
```
which I think is not correct (for the first two cases). But who is to blame? `BodyDeclarationModifiersSort.ofMethod` or Java generics?
....

I want to create a method that would tell me whether a node is applicable for a tipper, I previously extracted from a marker.
My first implementation was this:
```
@Override protected boolean check(ASTNode ¢) {
  return tipper.myAbstractOperandsClass().isInstance(¢);
}
```
But because of the problem above, it did not worked as expected.
The second try:
```
@Override protected boolean check(ASTNode ¢) {
  return Toolbox.defaultInstance().get(¢.getNodeType()) // list of tippers for node type
    .contains(tipper);
}
```
while defining `equals` method in `Tipper`:
```
@Override public boolean equals(Object ¢) {
  return ¢ != null && this.getClass().equals(¢.getClass());
}
```
do seam to work, but I think it is unsafe.
...

What is the best solution in your opinion?

An obvious yet expensive solution would be getting the operand class into the marker as well.

**Comment by yossigil** [comment]
I have some magic code that does precisely this, I think:
```java
  /** Heuristics to find the class of operands on which this class works.
   * @return a guess for the type of the node. */
  public final Class<N> myAbstractOperandsClass() {
    return myOperandsClass != null ? myOperandsClass : (myOperandsClass = initializeMyOperandsClass());
  }

  public Class<N> myActualOperandsClass() {
    final Class<N> $ = myAbstractOperandsClass();
    return !isAbstract($.getModifiers()) ? $ : null;
  }

```
this is all in the Tipper class. So, what you do, you create a new instance, and ask it what it's class.

**Comment by OriRoth** [comment]
It is not exactly what I am currently doing,,,
The current implementation is asking the *Toolbox* about it, like so:
```
@Override protected boolean check(ASTNode ¢) {
  return Toolbox.defaultInstance().get(¢.getNodeType()) // list of tippers for node type
    .contains(tipper);
}
```
I *really* prefer not to add things to the markers... Does this implementation safe enough? It can be improved be, for example, supplying the `Toolbox` with static final copy of all the tippers....

**Comment by yossigil** [comment]
yes. this should be safe.
