### ISSUE TITLE
Wiki: what are the training projects (for nano patterns)

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#381]
1. Junit - https://github.com/junit-team/junit4/tree/master
2. commons-bcel (Apache) - https://github.com/apache/commons-bcel
3. commons-lang (Apache) - https://github.com/apache/commons-lang
4. guava (Google) - https://github.com/google/guava
5. spartanizer
6. Auto-refactor - https://github.com/JnRouvignac/AutoRefactor

**Comment by yossigil** [comment]
For the purpose of research, we should not try the spartanizer for now on anything other than the above:
@OriRoth , @M4tt30rru ,

**Comment by orimarco** [comment]
https://github.com/SpartanRefactoring/Spartanizer/wiki/Training-Projects-for-Nano-Pattern-classification-%5C-Spartanization
