### ISSUE TITLE
Preference page: Use checkboxes

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#383]

**Comment by yossigil** [comment]
We do this first because:
-  it is quick to fix
- It improves the look by a whole lot
- Clients worry about configuration

**Comment by OriRoth** [comment]
![button](https://cloud.githubusercontent.com/assets/15183108/19162249/c8e950b6-8bff-11e6-98a6-40b26b22f25b.jpg)

Unfortunately, I was not able to properly align the drop menu to the left... not sure how to do that.
