### ISSUE TITLE
Karma and Todos for Zvi Listopad

### ISSUE THREAD

**Issue by zvili** [SpartanRefactoring/Spartanizer#386]
I've added basic Git workflow information to #338

**Comment by zvili** [comment]
tutorial issue is #328

**Comment by yossigil** [comment]
:+1:

**Comment by zvili** [comment]
1. Call me zvili
2. Done as per #394

**Comment by yossigil** [comment]
Amazing Karma you have!

**Comment by zvili** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Card 1](https://trello.com/c/dozzSxua/1-card-1)

**Comment by yossigil** [comment]
Wha't this card?

**Comment by zvili** [comment]
I'm testing some project management tools which integrate with GitHub. In this specific case I used trello.com. I used this tool last year for managing some yp projects.
The other project management tool I'm testing is Waffle.io; similar to overvIo.
I'll publish my conclusions.

**Comment by yossigil** [comment]
Waffle is a drag. It has a bot that changes thing without asking your permission, and they want money.

**Comment by zvili** [comment]
This issue was moved to SpartanRefactoring/YP5777_Sprint0_Old-Stuff#2
