### ISSUE TITLE
Centification collisions

### ISSUE THREAD

**Issue by sakopzon** [SpartanRefactoring/Spartanizer#390]

**Comment by sakopzon** [comment]
As I understand, all tippers which centificate, check the body of the instance they centificate.
The problem occurs when ¢ is already used before, and then the tippers just hide the previous ¢.
If so, the only solution I can think of is using declaresUp() function of the environment (which is yet not implemented), to check whether ¢ is declared or not.

**Comment by yossigil** [comment]
No, the problem lies with:
- For not checking that cent is used in its body prior to centification
- Method not checking that no definitions are made

**Comment by yossigil** [comment]
Process is:
- Create a new test class for this issue
- Find cases in our code using the [[Suppresswarningspartan]]
- Make test functions out of these.
- Fix the code of centificaiton of methods
- Fix the code of centification loop

See #391

**Comment by sakopzon** [comment]
Splitter into two issues: #420 #421

**Comment by sakopzon** [comment]
I walked threw all [[SuppressWarningsSpartan]] markers, and there is no one case falling for the reasons you described. I ran the current version of the plugin (not the released one), and checked all cases.
To be sure, I scanned the Centification relevant code, and saw that all the tippers do search for definitions in body before Centification, with haz.variableDefinition()!

**Comment by yossigil** [comment]
:100:
