### ISSUE TITLE
Tutorial/Social: TODOs, Personal TODOs issue

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#394]
# Mission

In this tutorial, you will:
- Learn what are TODOs
-  Create an issue for your TODOs, similar to #168 
-  Search the TODO's of others, and add a comment to this issue
  # Mission
  In this tutorial, you will:
- Learn what are TODOs
-  Create an issue for your TODOs, similar to #168 
-  Search the TODO's of others, and add a comment to this issue
# What are TODOs
- TODOs are a lightweight version of issues.
- TODOs are comments in the code,  that begin with the word `TODO` (capitalized)
- TODOs are managed by Eclipse's `tasks` view
- TODOs are used for quick, code related requests from yourself or others, and for very short code related discussions
# The structure of TODOs

Here is an example of a TODO message

``` java
// TODO Yossi Gil: I think this code need refactoring, talk to me (-Habakkuk)
```

Note the three components:
1. - Who is to carry out this TODO (`Yossi Gil`)
2. - Who wrote this TODO (`Habakkuk`). If the author name is missing, it is assumed that you wrote it for yourself.
3. - Content `I think this code need refactoring, talk to me`, which is a short message. If it is not short, make an issue out of it.

The above is a message from to me, suggesting that I refactor the code. I see this message in the tasks view of Eclipse.

TODOs can be placed in any kind of comments:
- line comments `// TODO John Doe:`
- Block comments `/* TODO John Doe: ...`
- JavaDOC comments: `/** TODO: John Doe ...`
# Response to TODO

 I can respond in several ways, e.g., 
1. Most common: I fix the TODO, and erase the comment, without troubling Habakkuk; adding a commit  comment to say
`Fixed TODO`
2. I start a conversation with Habakkuk

``` java
// TODO Yossi Gil: I think this code need refactoring, talk to me (-Habakkuk)
// TODO: Habakkuk: I am sorry, but I could not understand what you mean
```
1. Pass it on to someone else

``` java
// TODO Yossi Gil: I think this code need refactoring, talk to me (-Habakkuk)
// TODO: Athaliah: Can you help here?
```
1. Make an issue out of this specific TODO
2. In general, if the TODO cannot be solved quickly, you make an issue out of it
3. Issues management is easier than TODO management.
# My own TODO's issue
- Each member of the team must create and maintain his or her personal TODOs issue. 
- Your personal issue is a simple mechanism to put together in one place in GitHUB all correspondences related to your TODOs.
- When you fix your own TODO, it is customary to mention your own TODOs issue in the commit message.
- When you add a TODO for someone else, it is polite to refer to his own TODO issue, in the commit message

I will shortly push a commit that references this issue and my own's TODOs issue to demonstrate.

This is the checklist for your TODOs issue:
- [ ] Name must be `TODOs of John Doe`
- [ ] Label must be  `Quality assurance`
- [ ] The issue is assigned to you
- [ ] No deadline should be empty (this rule may be changed)
- [ ] You reference this current issue `#394`
- [ ] You suggest a short/long name by which you wish to be addressed
  - Try to use a short distinctive name:

Here is an example of what your new issue page should look like:
![image](https://cloud.githubusercontent.com/assets/12775400/19162722/b9fa92de-8c01-11e6-852c-1eb0baa23842.png)
# Searching for other people's TODOs
- if you place a TODO for someone, it is nice to mention this person in the commit message
- If you place a TODO for yourself, it is nice that it can be found in one place.

To demonstrate your search capability, add a comment with a screen dump. containing all current TODOs, sorted by `least recently updated`.

**Comment by OriRoth** [comment]
Tip: you can see all the `TODO`s in the project in an eclipse view:
`Window->Show View->Tasks`
Writing a name in the start of the `TODO` like Yossi suggested make it easy to sort the `TODO`s in this window.
