### ISSUE TITLE
Tutorial/Social: Karma, accountability, and personal responsibility

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#395]
# Buzzwords
- **Karma**: This is how well you cooperate with others and with team work. (May be tied with your grade, if you are a student)
-  **Accountability**: There is an individual in charge of every piece of code
- **Personal responsibility**: You identify your work as yours
# Rules
1. You do not write code unless you deal with an open issue (open one if necessary)
2. All classes you write bear your name
3. You commit your work, and your work only
4. You do not override the work of others
5. You respond to TODOs assigned to you ( #394)
6. You check your GitHub notifications frequetly, i..e, this 
7. You play nicely, cooppertively and politely
   - It is still OK to remove code commented out by others
   - It is still OK to revert commits in which there are classes with no `@Author` on them

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Info-Evaluation#2

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Accessibility-B#2

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Accessibility-A#2

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-ParkingManagement-B#3

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-ParkingManagement-A#2

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Wiki-Generator#1

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Bugquery#1
