### ISSUE TITLE
Lazy Evaluation Nano

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#398]
```
  public static Toolbox defaultInstance() {
    return defaultInstance = defaultInstance != null ? defaultInstance : freshCopyOfAllTippers();
  }
```

**Comment by orimarco** [comment]
[done ](https://github.com/SpartanRefactoring/Spartanizer/blob/412e5e9f79814dd6001f87424412c04958ea90a9/src/main/java/il/org/spartan/spartanizer/research/patterns/AssignmentLazyEvaluation.java)

**Comment by yossigil** [comment]
:8ball:
