### ISSUE TITLE
Organize eclipse

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#400]
What a messy file
it bugged my for a while
and I am to blame
what a shame!
Camembert.

**Comment by OriRoth** [comment]
400 issues! 🎉🎉🎉

**Comment by yossigil** [comment]
it was even worse before .can u believe...

**Comment by OriRoth** [comment]
This class will be deleted. Logic is now located in `Dialogs.java` and `Selection.Util`

**Comment by yossigil** [comment]
:+1:
