### ISSUE TITLE
Travis errors - does not acknowledge JFace

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#401]
![button](https://cloud.githubusercontent.com/assets/15183108/19174160/841a8140-8c35-11e6-9577-26902262062e.jpg)
Travis fails although the code compile.
@yossigil FYI

**Comment by OriRoth** [comment]
Maybe this?
https://www.eclipse.org/forums/index.php/t/109083/
I need someone to check if it is working on Linux.

**Comment by yossigil** [comment]
Please do not use DOS. We cannot afford diverging environments

**Comment by OriRoth** [comment]
I just use the JFace classes... just want to make sure it is not OS related problem.
I suspect the little icon on the corner of the opened window - this is a common feature in DOS but does not exist in LINUX (???). In worst case scenario I can just change the constructor I guess...

**Comment by yossigil** [comment]
Maybe try @M4tt30rru  on Sunday?

**Comment by OriRoth** [comment]
@yossigil I saw you commented my code in `QuickFixer`. Is it because of DOS related compilation errors (besides Travis)? If it does, I would be happy to get some screenshots. (it works in my eclipse without any problem).
In the meanwhile I have reactivated the marker resolution - until the DOS problem (???) would be clearer.

**Comment by yossigil** [comment]
Could be that file names went from lower case to upper case... I will ttry to check later

**Comment by OriRoth** [comment]
Stupid Travis...

**Comment by yossigil** [comment]
:+1:
