### ISSUE TITLE
TDD Project: Compute the list of string literals found in a given Java string

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#404]
### Secondary Objective

A function named `public List<String> stringLiterals(ASTNode n)` that 
- takes a single parameter, which is an 'ASTNode`
- returns a `List<String>` which is the list of all string literals in this node

This function is to be implemented as a static member of `interface dig { /*...*/ }` which you will find i the code somewhere.

This design is so that clients can apply this function in a **fluent API** style, e.g., 

``` java
for (CompilationUnit u: us)
   myList.addAll(dig.stringLiterals(u));
```
# Primary Objective

Demonstrate a TDD process.
## Preparations
- [x] Search for the class  `Issue000.java` 
- [x] Using eclipse's `Window->View->Package Explorer` view:
  - create a new class named `Issue404` and placed in a file named `Issue404.java`  
  - Edit this class to have your `@author` name in it.
  - Edit this class to have a correct `@since` label on it, e.g., the current date in the format YY-MM-DD
  - Keep the rest of the class. Don't remove now the `@Test` in it; you will have time to do so later, as you understand better what's going on.
- [x] Run the class as `junit` and make sure it has one test in it that does nor fail neither abort
## Stop to study
- [x] Search for TDD in Google and learn what it is
- [x] Search for tutorials and issues named `TDD` in this repo
  - If you can read git logs, search for commits with `TDD` in them
- [x] Learn all about the "green state" in tutorials found here
- [x] Think and plan
# Exercise
### Forcing

In TDD, you repeat cycles of **forcing**. In each cycle you write a test that forces the code you check to do something. In these forcing cycles, your are defining the specification of what you test, and write the code according to this specification.
For TDD to work,  you must follow this rule

<blockquote>
Production code is change is made only if 
  <ul><li> triggered by the need to fix a compilation error, or test failure
  <li>it is the smallest code that fixes the trigger
  </ul>
</blockquote>

Think of this is as a game betwee too players, the **tamer**, who tries to get the nasty, lazy,  and fiendish **leprechaun** to behave, who play this game:
1. Tamer and leprechaun  in a green state
   - Leprechaun is presumably innocent
   - Tamer know that there are always bugs
   - The tamer suspects that the leprechaun is cheating 
2.  The tamer add a `@Test` function that tries to catch the leprechaun cheating
   - If the test succeeds, the tamer could not detect a bug, so go back to step 1  
   - if If the method fails, and the leprechaun can fix the trigger, got back to step 1.
   - If the leprechaun cannot fix the code, the tamer helps in finding the fix by using binary search; 
   - the hunter adds another `@Test`  that tries to
   - help focus on the problem
   - bisect the problem into two.
   - If the Leprechaun is able to fix all newly introduced `@Tests`, now, 
     return to 1. Otherwise, repeat 3.

You will notice that 
- the **Leprechaun** behaves like  programmer who tries to cheat, but is careful of  not being caught. The Leprechaun  tries to write as little code as possible, and if must write code, he writes it a mischievously as he can.
  - the **tamer** is clever, he knows that how trick the leprechaun is, and he knows that real bugs are even trickier.
  - the **tamer** should also be lazy, e.g., by cut, paste and modify of 
    one your test methods. The tamer knows that the leprechaun might be sleazy, so he makes sure that the constants he uses are not always the same.
  - You play **both** roles yourself. The quality of the product depends on 
  - your honesty.
  - your agility
### Your green state
- [x] Start with a green state that all tests pass. 
- [x] Make sure that there are no `@Ignore` tests in your suite
- [x] Make sure that there are no `@Ignore` tests in your suite
- [x] Use a Dewey like notation for test names, which tells you were you are in the process of TDD. (If you do not know who and what Dewey was, go out and learn)
## Repeat the Leprechaun game to

The demands are not fully sorted; you may want to change the order to make sure you follow an efficient path
- [x] Force the FUT (function under test)  to return a non `null`, even when it receives a null. Hints 
  - Use plain `assert`
  - Write a specific `@Test` just for this purpose 
  - Use Dewey notation for test names.
- [x] Force the FUT to return some list on `null`. i.e., the function must return a non-null value of type `List`: Hints:
  - use `instanceOf(Some.class)`; see the examples in `Issue000.java`
  - no need to check for kind of elements in the list
- [x] Force FUT to return a list of `String`. Hint:
  - create an auxiliary function:

``` java
private static void forceTypeAtCompileTime(List<String> ss) {
assert true; 
}
```
- Call this auxiliary function from your code `@Test` code
- [x] Force FUT to return a list of length 0 on a couple of strings that contain no `"`
- [x] Force FUT to return a list of length 1 on some designated input string.
  - The leprechaun will cheat, and return 1 in any case the input contains a `"` character
  - Further short cheat is returning a wrong string.
- [x] Force FUT to return a list of length 2 on some other designated input string.
  - The leprechaun will cheat, and return the number of `"` divided by two or something. 
- [x] Force FUT to return the right string in the list of length 1
- [x] Force FUT to return the right strings in the list of length 2
  - Observe that it is getting more and more difficulty for the leprechaun cannot cheat now 
- [x] Force FUT to return the manage cases of odd numbers of `"` 
- [x] Force FUT to return the deal with escaped `"`. 
  - Cut, pasted and modify one your test methods
- [x] Force FUT to return the correct value with `'"'` i.e., double quote present as a quote.
- [x] Force FUT to deal with Unicode characters, including Hebrew, extended Latin. Hint:
  - Check for Unicode both inside and outside the input 
  - The leprechaun will cheat, and return the number of `"` divided by two wor something. 
- [x] Force FUT to return the right sequence of three strings
- [x] Force FUT to return the right result input that contains this character literal 
  ```java '"'
  `

**Comment by dngreenst** [comment]
Reading list:

#388 
#391 

https://technologyconversations.com/2014/09/30/test-driven-development-tdd/
https://technologyconversations.com/2013/12/20/test-driven-development-tdd-example-walkthrough/
https://technologyconversations.com/2013/12/24/test-driven-development-tdd-best-practices-using-java-examples-2/

(Highly recommended - to read in order of appearance)

http://agiledata.org/essays/tdd.html

(Recommended)

https://en.wikipedia.org/wiki/Test-driven_development

https://www.tutorialspoint.com/software_testing_dictionary/test_driven_development.htm

https://msdn.microsoft.com/en-us/library/aa730844(v=vs.80).aspx

**Comment by sakopzon** [comment]
http://agiledata.org/essays/tdd.html 👍

**Comment by dngreenst** [comment]
@yossigil , could you clarify your intention regarding "returning an Integer"? Do you want me to try and return a String literal that represents a number?

**Comment by dngreenst** [comment]
@yossigil

**Comment by yossigil** [comment]
Note the updates

**Comment by dngreenst** [comment]
Done. Should I leave it open, as it is a Teaching issue?

**Comment by yossigil** [comment]
More changes. Leave it open for now.

**Comment by dngreenst** [comment]
Done.

**Comment by yossigil** [comment]
ALL: this is a semi official demo of TDD.
