### ISSUE TITLE
Exception thrown for no reason

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#407]
@dormaayan: checkout this code
```java
  @Override double evaluateDouble(final List<Expression> xs) throws Exception {
    double $ = az.throwing.double¢(first(xs));
    for (final Expression ¢ : rest(xs))
      $ -= az.throwing.double¢(¢);
    return $;
  }
```
As can be seen, the conversion of the string to `double` may throw an exception. But, you can prevent th exceptions in many cases. The patter here is to first make the light weight check, as done in `type` for the kind of the string literal.

So,  if the classifier says it is a `double`, you never try to parse it as `long` nor as `int`. If the classifiers, which only examines things like dots and scientific notation, says it is a `double`, you can try to parse it. The real parsing can still throw an exception, e.g., if the number has 123 decimal digits, but chances are slimmer.

Also:
- [x] Eliminate class MyException
- [x] let `az.throwing` throw the ParseExceptio directly, and let your code catch and do whatever with this exception, probably loggin it.

**Comment by dormaayan** [comment]
@yossigil  :

- do you want me to continue using `az.throwing.double¢(¢)` but make sure before it that it won't throw anything ?

 - I didn't find any` ParseException`, do you mean throwing the `NumberFormatException `and catch it ?

**Comment by yossigil** [comment]
yes, I wish that we keep on using throwing, but only after checking the type by our lightweight classifier, so chances for exception are slimmer. 
Yes, I mean `NumberFormatException`

**Comment by dormaayan** [comment]
@yossigil : Done

**Comment by yossigil** [comment]
Good job and many thanks.
