### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#41]
Maven packaging and Travis build failing due to changes in pom file(s): SpartanRefactoring/pom.xml missing definition of parent pom, and spartan-refactoring/pom.xml contains Java1.8 declaration. I tried inserting missing definitions to pom or reverting to last version of pom.xml, but it did not work

**Comment by yossigil** [comment]
Undo changes to pom.xml

**Comment by mittelman** [comment]
On it

**Comment by mittelman** [comment]
Automatic build is now passing and reflects the build status on the "more-stable" branch. When returning to the "master" branch as the default branch, the README.md file should be changed to reflect the build status on "master"

**Comment by OriRoth** [comment]
Build is failing once more! I think it is something with unsupported mars eclipse version...
From Travis:
```
[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'mars' from location http://download.eclipse.org/releases/mars: Unable to read repository at http://download.eclipse.org/releases/mars/content.xml. Connect to download.eclipse.org:80 timed out -> [Help 1]

org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'mars' from location http://download.eclipse.org/releases/mars
```
From pom.xml:
```
	<properties>
		<tycho.version>0.24.0</tycho.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<mars-repo.url>http://download.eclipse.org/releases/mars</mars-repo.url>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>

	<repositories>
		<repository>
			<id>mars</id>
			<url>${mars-repo.url}</url>
			<layout>p2</layout>
		</repository>
	</repositories>
```

**Comment by OriRoth** [comment]
Wew done. Connected to neon's repository instead, did not changed any names though.

**Comment by yossigil** [comment]
Thanks.
