### ISSUE TITLE
Adi Omari: introduction

### ISSUE THREAD

**Issue by AdiOmari** [SpartanRefactoring/Spartanizer#418]
- [ ]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:

Example | Score | Why?
------- | ------|-----
![image](https://cloud.githubusercontent.com/assets/12775400/19101029/e525d7d8-8acc-11e6-97f1-8bdc0bb9ac4f.png) | Bad | Anonymous
![image](https://cloud.githubusercontent.com/assets/12775400/19101029/e525d7d8-8acc-11e6-97f1-8bdc0bb9ac4f.png) | OK | Personal trademark
  - **Excellent**: 
- [ ]  Make sure you present yourself by a readable **nick**

Example | Score | Why?
------- | ------|-----
`Moshe Levy II` | Super | Clear identification
`YossiGil` | Excellent | You identify yourself by full name
`IDabran`  | Good | == **I**tai **Dabran**
`yogi` | OK | Well known nick
`j1046`  | Bad | Who the hell are  you?
`zm&4jk` | Worse | Not even pronnounceable
`r2d2`   | Terrible | We are not playing games here
`ghost` | Disaster | Are you a troll or what? 
  - Bad: `j10463` / `r2d2` / `bb8` / `biscuit` / `the destroyer`
  - Ok: `yogi`  (**Yo**ssi **G**il), `idarban` (**I**tai **D**arban)

- [ ]  Describe yourself in the bio page; FYI, here is my description:
![image](https://cloud.githubusercontent.com/assets/12775400/19105201/753bb934-8ae9-11e6-8f63-659f5c14162e.png)

- [ ]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
![image](https://cloud.githubusercontent.com/assets/12775400/19105155/3554e8cc-8ae9-11e6-8915-a180075388b1.png)
14162e.png)

- [ ]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
![image](https://cloud.githubusercontent.com/assets/12775400/19105155/3554e8cc-8ae9-11e6-8915-a180075388b1.png)

**Comment by AdiOmari** [comment]
@YossiGil: Done.

**Comment by yossigil** [comment]
:+1:
