### ISSUE TITLE
Defunct the Trimmer

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#419]

**Comment by yossigil** [comment]
Make sure we use a listener

**Comment by OriRoth** [comment]
Notice that if you will use event-based listener (that accepts enum values, such as `listener.tick(event.visit_cu, currentCU)`) the `Trimmer` and the `EventApplicator` will be able to share the same Listener.
I can extends `EventApplicator` to accept several enums if needed (it is currently generic).

**Comment by yossigil** [comment]
I think enums are a bit of an overkill. Just use strings.

**Comment by OriRoth** [comment]
I have created a Trimmer like application for the Athenizer project called `SingleFlater`. I believe the new Trimmer design should look somewhat like it: It is configurable as the Spartanization applicators, that were a success.
