### ISSUE TITLE
Remove all redundant [[SuppressWarningsSpartan]] markers

### ISSUE THREAD

**Issue by sakopzon** [SpartanRefactoring/Spartanizer#423]
For example:
`/** Return null for canceled message.`
`   * @return opening message for given attributes [[SuppressWarningsSpartan]] */`
`  public String getOpeningMessage(@SuppressWarnings("unused") final Map<attribute, Object>` `attributes) {`
`    return null;`
`  }`

After removing the marker, Spartanizer suggests renaming "attributes" to "a" and then to "__".
As I understand those functions are not yet implemented, @yossigil , what do you expect from the Spartanizer in those cases?

**Comment by sakopzon** [comment]
In some cases, when I remove the [[SuppressWarningsSpartan]], there are no suggestions.
@yossigil, what do you expect from the Spartanizer here?
**For example what is expected here:**
`/** XXX: This is a bug of auto-laconize [[SuppressWarningsSpartan]]`
`   * @param ¢ JD`
`   * @return furtherest ancestor whose type matches the given type. */`
`  public ASTNode inclusiveLastFrom(final ASTNode ¢) {`
`    ASTNode $ = inclusiveFrom(¢);`
`    for (ASTNode p = $;; p = from(p.getParent())) {`
`      if (p == null)`
`        return $;`
`      $ = p;`
`    }`
`  }`

**Comment by OriRoth** [comment]
The release have not changed. Make sure the plugin is running, possibly by putting a well known spartanizable code (sucha as `int x = new Integer(0);`).

**Comment by sakopzon** [comment]
The plugin is working! The cases I speak about are usually with:
`  /** XXX: This is a bug of auto-laconize [[SuppressWarningsSpartan]] */` comment.

**Comment by OriRoth** [comment]
Alex

**Comment by OriRoth** [comment]
Do not touch `Refactorer.java` please.
Call me for clarifications.

**Comment by sakopzon** [comment]
OK, ran eclipse with the new configuration to handle the current plugin state, but still there are a lot of redundant `/** XXX: This is a bug of auto-laconize [[SuppressWarningsSpartan]] */` comments.
@yossigil, should I remove them?

**Comment by yossigil** [comment]
:+1:
