### ISSUE TITLE
Convert this into a wiki page: Debugging your Tipper

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#425]
See also #875 

After completing your cool new `Tipper`, you ask yourselves how to test it. As you know we are working in a TDD methodology, so running your pre-written tests would be a good idea.

But it is sometimes easier to check your newly created `Tipper` in a real environment, i.e. as part of the plugin run by eclipse. That way you can:
- Quickly check test cases, that later can be added as tests.
- Test the `Tipper` from the user perspective (what markers it creates, etc.).
- Challenge your Tipper with big , real world projects.
- And more!

So how does eclipse allow us to debug our plugin? It opens a _new_ eclipse window, in which the updated plugin (with your `Tipper` applied), is already installed.

_Configurations instructions:_
- In the eclipse top menu, go to `Run`->`Run configurations...`
- Enter `Eclipse Application`->`Eclipse Application`
- Choose `run an application`
- Press `Run` button at the bottom of the configuration window
- A new eclipse window should be open after a few seconds

From now on you can access the `Run as eclipse application` via:
- Right click on the project, then choosing `Run as...`->`Eclipse Application`
- `Run`->`Run History`->`Eclipse Application`
- The play button, if it was your last run

_Note:_
- Any **printing** you done in your code will appear in the **console** of the **original eclipse window**, so you can print-debug if you like to.

**Comment by OriRoth** [comment]
@yossigil it is very importent to tell new workers about this feature (I just found out @sakopzon did not use it, which is a loss).
@orimarco do you have something to add?

**Comment by orimarco** [comment]
In order to start the eclipse application, you need to  configure it as shown in [https://github.com/SpartanRefactoring/Spartanizer/wiki/Sterile--Import-into-Eclipse#run-configuration](url)

**Comment by OriRoth** [comment]
@orimarco link gets me to 404 not found

**Comment by orimarco** [comment]
@OriRoth  try now

**Comment by mdoron** [comment]
@yossigil Done. But note that @kobybs confused [here](https://github.com/SpartanRefactoring/Spartanizer/wiki/Testing-your-Tipper) and instead of wiking #875, he wikied this issue (#425).

**Comment by yossigil** [comment]
:+1:
