### ISSUE TITLE
Same evaluation conditional

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#427]
Turn

```Java
x == y ? x : y
```

or

```Java
x == y ? y : x
```

into

```Java
x
```

Notice `x` and `y` could be anything (or does it? **safety check is needed**).

**Comment by yossigil** [comment]
How is it going?

**Comment by danabramovich** [comment]
working on it

**Comment by OriRoth** [comment]
Wow there is actually a bug here - it should be
```Java
return null;
```
not
```Java
return $;
```

@danabramovich

**Comment by OriRoth** [comment]
Well... this is no beginners stuff after all 😕 tough life.

**Comment by OriRoth** [comment]
@yossigil can you postpone this assignment for @danabramovich? I have made some required changes to the subject so it became something completely different... original idea is pretty invalid.

**Comment by yossigil** [comment]
Should be easy. We have functions to compare things. We want each of the the expressions be both side effects free and determinstic.

**Comment by danabramovich** [comment]
@yossigil done.
