### ISSUE TITLE
Avoid Dolarization of declared field when $ is already used.

### ISSUE THREAD

**Issue by sakopzon** [SpartanRefactoring/Spartanizer#428]
Today spartanizing the next, creates a bug while changing j to $:

`func(int i){int j;System.out.println(j);System.out.println($);return j;}`

**Comment by OriRoth** [comment]
Alex! same problem - do not write a new code for this. It would make your job much easier.

**Comment by sakopzon** [comment]
👍

**Comment by sakopzon** [comment]
As I said, the code dealing with the dollar search (the one you wanted me to use) is buggy. While doing issue #426 I implemented StringCollector, which I used here also, and it's working.
