### ISSUE TITLE
Cannot relate issue to category

### ISSUE THREAD

**Issue by Bananeweizen** [SpartanRefactoring/Spartanizer#440]
Just testing Spartan for the first time. I get a huge amount of "replace toString() by concatenating empty string" tips. I want to disable that tip, since it is nonsense (less readable, worse bytecode). However, I cannot relate the findings to the categories in the preferences, so I basically have to do trial and error on all checkboxes in the preferences.

You could solve this by either adding all issue types to the categories in the preferences, or (better) by adding a property to the issue, which shows its category, when opening the properties of the issue via its context menu.

**Comment by yossigil** [comment]
Hi @Bananeweizen,indeed, cofnigurability should be improved, and we hope to do so in future release. But, the idea you suggest is also nice: "Configure severity", as right click on issue. I scheduled this for version 2.7.

**Comment by yossigil** [comment]
Current category is "Collapse". BTW

**Comment by yossigil** [comment]
@OriRoth: can we close this?

**Comment by yossigil** [comment]
@OriRoth: can we close this?

**Comment by OriRoth** [comment]
We now offer category names for each marker in the *problems* view. Is it enough? probably not.
The second solution is faisable, may be done by adding an empty marker resolution named `category: ...` what do you think?

**Comment by yossigil** [comment]
For other times.
