### ISSUE TITLE
Preference change blocks entire eclipse process

### ISSUE THREAD

**Issue by Bananeweizen** [SpartanRefactoring/Spartanizer#441]
When changing Spartan preferences, the UI is blocked for several minutes due to re-running the analysis in a blocking way. This makes Spartan unusable.

**Comment by yossigil** [comment]
@OriRoth  see if you can help

**Comment by OriRoth** [comment]
Spartanizer rebuild inspired by preference change now runs on different thread.
The change will be applied in the next version (2.6) that will be released in the next month or so.
@Bananeweizen thanks for helping us improve Spartan Refactoring!
