### ISSUE TITLE
Comments and ASTRewrite

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#447]
Can we use this?
![image](https://cloud.githubusercontent.com/assets/12775400/19252202/36868356-8f4c-11e6-85a2-a693de59a1d5.png)

http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2Frewrite%2FASTRewrite.html

**Comment by OriRoth** [comment]
It cannot help you preserve formatting or comments, unless you scavenge the source code. I strongly recommend the use of `ASTRewrite#makeCopyTarget` and `ASTRewrite#makeMoveTarget` that preserve both formatting and comments (see #331) whenever possible.

**Comment by yossigil** [comment]
but, it surely help cresating complex constructs, instad of using `subject`

**Comment by OriRoth** [comment]
Some notes after a talk with @orimarco:

* It is **dangerous** to make tippers that change comments! Notice you will have a hard time assuring your tipper would not be activated over and over again.
* Notice there *are* ASTNodes for comments: http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FComment.html
* General way to *edit* comments:
  * Javadoc: `
oldJavaDocString = method.getJavadoc() + "";
...
astRewrite.replace(oldJavadoc, astRewrite.createStringPlaceholder(newJavadocString, ASTNode.JAVADOC), null);
`
  * Block / line comments: **complicated**.
* General way to *create* comments, associated with ASTNodes: `astRewrite.replace(node, astRewrite.createGroupNode(new ASTNode[] { astRewrite.createStringPlaceholder(javadocString, ASTNode.JAVADOC), astRewrite.createCopyTarget(d) }), null);` notice how we use `astRewrite.makeCopyTarget`, see #331.
