### ISSUE TITLE
Classification of nanos

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#448]
Several kinds of macros:
1. normal, ie.. can be emulated with normal order function call
2. annotable ie. can be denoted by annotation
3. pseudo-normal, ie., using something like 

``` java
try { .. } catch(Exception e) { ___.ignore(e); }
```
1. Others. What are they?

**Comment by orimarco** [comment]
Actually it seems to me that:
1. are expressions NP.
2. are methods NP.
3. are statements NP.

**Comment by orimarco** [comment]
Some statements can be emulated with a function call, but those statements are really limited.
For example:
```
if (closed)
		throw new IOException("Cannot write to a closed writer.");
```
can be emulated by:
`whenNull(closed).throu(IOException("Cannot write to a closed writer."));`

**Comment by M4tt30rru** [comment]
I assume that _Loop_, namely nanopatterns involving loops, can be consider another category, right?  according to issues from #480 to #485.

**Comment by orimarco** [comment]
Some loops can be emulated by extracting their content to a method and then `Idiomating` a method invocation of it by using a lambda expression that invokes the method. (Working on this now)

Loops that I think can definitely be emulated this way are those that don't assign any local variable.

**Comment by orimarco** [comment]
For example:
```
  List<String> li;
  void printList() {
    for(String ¢ : li )
      System.out.println(¢);
  }
```

into
```
  List<String> li;
  void printList() {
    idiomatic.map(li).with(x -> printElement(x));
  }

  static String printElement(String ¢) {
    System.out.println(¢);
    return ¢;
  }
```

**Comment by yossigil** [comment]
in fluent you say:
```java
map(¢->printElement(x)).to(myList);
```
but I think this is not `map` but rather `apply`

**Comment by orimarco** [comment]
OK
but it has to be `map(li).to(x -> printElement(x))`, otherwise Java can't infer the types of the lambda expression and will complain.

**Comment by yossigil** [comment]
I think Java can deal with this. It was able to do so with 'eval(()->1/x).unless(x==0)'.

**Comment by orimarco** [comment]
```
static <T, R> MapperLambdaHolder<T, R> mapp(final Function<? super T, ? extends R> mapper) {
    return new MapperLambdaHolder<>(mapper);
  }

  class MapperLambdaHolder<T, R> {
    final Function<? super T, ? extends R> mapper;

    public MapperLambdaHolder(final Function<? super T, ? extends R> mapper) {
      this.mapper = mapper;
    }

    public Collection<R> to(Collection<T> ¢) {
      return ¢.stream().map(mapper).collect(new GenericCollector<R>(¢.getClass()));
    }
  }

**List<String> before = new ArrayList<>();
List<String> after = (List<String>) mapp(x -> mapper(x)).to(before);**
```

**Comment by yossigil** [comment]
Take a look at `idiomatic.eval(x ->y).when(x != 0), it does the job I think. Maks sure you use this version in your tippers.
