### ISSUE TITLE
Bug in inlining into loops

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#450]
Consider this example: 

``` java
  static void main(final String[] args) {
    final Separator s = new Separator(", ");
    for (final String a : args)
      System.out.print(s + a);
  }
```

Separator 's' should not be inlined. In fact, you should never inline into a loop's body, unless it is a constant.

**Comment by OriRoth** [comment]
Doesn't it has a side effect? The inlining probably fails because instance creation is considered as such.

**Comment by yossigil** [comment]
I still get a tip to do so.

**Comment by OriRoth** [comment]
Great job. Tests well written!

**Comment by yossigil** [comment]
:+1:
