### ISSUE TITLE
Multithreading Spartanization

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#453]
@yossigil now or never. It can be an interesting challenge with exceptional improvement in performance. I can start experimenting with it immediately.

**Comment by OriRoth** [comment]
Just before we refine the process in `plugin.revision`.

**Comment by OriRoth** [comment]
https://wiki.eclipse.org/FAQ_Does_the_platform_have_support_for_concurrency%3F

**Comment by yossigil** [comment]
No. Please not at this time. We are trying to make a stable version, not an efficient one.
