### ISSUE TITLE
Improve text selection recognition in GUI$Applicator/Trimmer

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#454]
The selection heuristic can be improved. Current code:
```
protected boolean isNodeOutsideSelection(final ASTNode ¢) {
  return !isSelected(¢.getStartPosition());
}
private boolean isSelected(final int offset) {
  return isTextSelected() && offset >= selection.getOffset() && offset < selection.getLength() + selection.getOffset();
}
protected boolean isTextSelected() {
  return selection != null && !selection.isEmpty() && selection.getLength() != 0;
}
```
*Explanation*: node is considered inside a marker if and only if the start of the node is inside the marker. Thus we get accepted cases like `[n]ew Integer(0)` and rejected cases like `n[ew Integer(0)]`. I believe a better heuristic can be conducted here.

**Comment by OriRoth** [comment]
Although it is a GUI related issue, the problem and the solution are *logical*, so anyone is invited to find a simple and effective resolution.

**Comment by yossigil** [comment]
there must be a search-google-cut-and-paste solution for this....
