### ISSUE TITLE
Omit {} from lambda expressions

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#455]
``` java
  public EventApplicator defaultListener() {
    listener(EventListener.simpleListener(event.class, e -> {
      System.out.println(e);
    }, (e, o) -> {
      System.out.println(e + ":\t" + o);
    }));
    return this;
  }
```

goes to

``` java
  public EventApplicator defaultListener() {
    listener(EventListener.simpleListener(event.class, //
        e -> System.out.println(e), //
        (e, o) -> System.out.println(e + ":\t" + o)//
    ));
    return this;
  }
```

**Comment by OriRoth** [comment]
I think you should replace the `Challenge` label with `Folks` - this looks like beginners stuff (not for first tipper, but still).

**Comment by yossigil** [comment]
Done :-)

**Comment by yossigil** [comment]
Do add it to the toolbox. And add tests for it.

**Comment by yossigil** [comment]
Superb comments on your commits :100: 

close if done.

**Comment by orenafek** [comment]
done. fixed toolbox and added more tests (without `withTipper()` method)

**Comment by OriRoth** [comment]
@orenafek I can see your tip, but activating it does nothing... did you know how to debug plugins? i.e. opening a new instance of eclipse with the plugin installed.
Also it does not recommended to include code in tip description, unless you are sure it is short.
Nevertheless, nice job, looks good.

**Comment by orenafek** [comment]
@OriRoth 
no idea on how to do that....
testing it in `Issue455.Java` does the work ...
what should I do next ?

**Comment by OriRoth** [comment]
@yossigil whats up with the waffle bot? Looks ominous.
@orenafek I'll show you how to do that asap... there should be a tutorial somewhere, but people tend to get into problems with it.

**Comment by OriRoth** [comment]
https://github.com/SpartanRefactoring/Spartanizer/issues/425 hopa hopa! That should do the work.

**Comment by OriRoth** [comment]
@orenafek okay the problem seams to actually be a npe in this code:
```
Consumer<Integer> x = (x) -> {System.out.println(x);};
```
Be sure to create a test out of it after fixing... our tests are filled with the remains of our enemies (code chunks from real world projects).

**Comment by yossigil** [comment]
Not sure what's going on with the waffle. We need to check.

**Comment by orenafek** [comment]
@OriRoth 
The tipper was missing the support of expression statements. done.

**Comment by yossigil** [comment]
:100:

**Comment by OriRoth** [comment]
@orenafek you are an optimistic guy I see! Not all code pieces are going to look the way you want... so you should take care of all possible case, and sometimes even uncompilable code!
Consider this for example:
```Java
Consumer<Integer> x = (y) -> {
    for (;;)
      break;
  };
```

**Comment by orenafek** [comment]
@OriRoth 
If you remove the `{ }` from your code example, it doesn't compile ,
which means this is not an example of a **redundant** curly braces in lambda expression....

**Comment by OriRoth** [comment]
Yes but it still follows the pre-requirements! I get a tip for it => npe.

**Comment by orenafek** [comment]
@OriRoth 
Added more tests (29 total) to determine for each statement type, if it should be tipped or not.
Hopes that solves it. 
Closing.

**Comment by orimarco** [comment]
A little problem in this tipper seem to occur when the lambda is passed to a function which is overloaded and has two implementations when one is defined for a lambda which returns void and one for a lambda which returns non-void.
If the statement inside lambda returns non-void and surrounded by {} the lambda returns void, but when removing the {} the lambda now returns non-void...
**So... using the tipper changes the lambda's type, which can cause ambiguity** (which overloaded method to choose? the one which gets a **Biconsumer** or the one that gets a **Functor**?)

For example: `EventMapper.java`.

@orenafek @OriRoth  @yossigil

**Comment by OriRoth** [comment]
Example:
```Java
/** Counts calls of this event. Conducts casting. */
@SuppressWarnings("unchecked") public EventMapperFunctor<E, AtomicInteger, AtomicInteger> counter() {
  return ((EventMapperFunctor<E, AtomicInteger, AtomicInteger>) this) //
      .startWith(new AtomicInteger(0)) //
      .does(c -> {
        c.incrementAndGet();
      });
}
```
==>
```Java
/** Counts calls of this event. Conducts casting. */
@SuppressWarnings("unchecked") public EventMapperFunctor<E, AtomicInteger, AtomicInteger> counter() {
  return ((EventMapperFunctor<E, AtomicInteger, AtomicInteger>) this) //
      .startWith(new AtomicInteger(0)) //
      .does(c -> c.incrementAndGet()); // ambiguity here
}
```

**Comment by yossigil** [comment]
You can also explicit typing...

**Comment by orenafek** [comment]
@OriRoth 

> class is deprecated 
which one ?
