### ISSUE TITLE
Bullet proofing... again

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#458]
With the new technology, we can get past these kinds of bugs:

- **buggy code for finding in tipper,** e.g.,  type analysis, which is buggy regarding arrays. When the typer receives an array type, it barfs with a class cast exception. ( @NivShalmon , @dormaayan , FYI).
- **buggy code for replacement in tipper**, e.g., a problem in the code for loop initializers, which identifies an opportunity to apply the tipper, but cannot apply it (problem wrong use of `subject`, @sakopzon , FYI).

So, the new applicator should catch exceptions and deal with them. In other words, the applicator should stop trusting the tippers.

Currently, what happens is that in interactive use, you see a tip  you cannot apply, and in "apply to project/file/class/funcion", the spartanizer aborts, with some trace in the eclipse error log.

**Comment by OriRoth** [comment]
Can you give me an example? I have spartanized JUnit, Guava and Spartanizer fully without any suspicious exceptions (only number format exceptions - but nothing that crashed the plugin).
Project's name would be enough probably.

**Comment by yossigil** [comment]
I get these in running the spartanizer intreactively. We need this bullet proofing also for our batches.

**Comment by OriRoth** [comment]
@M4tt30rru do you know something about it that can help me? If I recall you wrote both bulletproofing tippers and the batch spartanizer.

**Comment by M4tt30rru** [comment]
@OriRoth I think an example of how handle with the Exceptions thrown by tippers, might be this in AbstractBatch#consolidateTippers. When for some reason the tip method fails a TipperFailure is caught. I assume that the new solution should be more sofisticated.

```
public void consolidateTips(final ASTRewrite r, final BodyDeclaration u) {
    toolbox = Toolbox.defaultInstance();
    u.accept(new DispatchingVisitor() {
      @Override protected <N extends ASTNode> boolean go(final N n) {
        TrimmerLog.visitation(n);
        if (disabling.on(n))
          return true;
        final Tipper<N> tipper = getTipper(n);
        if (tipper == null)
          return true;
        Tip s = null;
        try {
          s = tipper.tip(n, exclude);
          tick(n, tipper);
        } catch (final TipperFailure f) {
          monitor.debug(this, f);
        }
        if (s != null) {
          ++tippersAppliedOnCurrentObject;
          tick2(tipper); // save coverage info
          TrimmerLog.application(r, s);
        }
        return true;
      }
```

**Comment by OriRoth** [comment]
Added try-catch-Exception for both tipper lookup and tipper commit:
```
public void consolidateTips(final ASTRewrite r, final BodyDeclaration u) {
  toolbox = Toolbox.defaultInstance();
  u.accept(new DispatchingVisitor() {
    @Override protected <N extends ASTNode> boolean go(final N n) {
      TrimmerLog.visitation(n);
      if (disabling.on(n))
        return true;
      Tipper<N> tipper = null;
      try {
        tipper = getTipper(n);
      } catch (final Exception x) {
        monitor.debug(this, x);
      }
      if (tipper == null)
        return true;
      Tip s = null;
      try {
        s = tipper.tip(n, exclude);
        tick(n, tipper);
      } catch (final TipperFailure f) {
        monitor.debug(this, f);
      } catch (final Exception x) {
        monitor.debug(this, x);
      }
      if (s != null) {
        ++tippersAppliedOnCurrentObject;
        tick2(tipper); // save coverage info
        TrimmerLog.application(r, s);
      }
      return true;
    }

    <N extends ASTNode> void tick2(final Tipper<N> w) {
      final String key = presentFileName + "-" + presentMethod + monitor.className(w.getClass());
      if (!coverage.containsKey(key))
        coverage.put(key, 0);
      coverage.put(key, coverage.get(key) + 1);
    }

    /** @param n
     * @param w
     * @throws TipperFailure */
    <N extends ASTNode> void tick(final N n, final Tipper<N> w) throws TipperFailure {
      tick(w);
      TrimmerLog.tip(w, n);
    }

    /** @param w */
    <N extends ASTNode> void tick(final Tipper<N> w) {
      final String key = monitor.className(w.getClass());
      if (!spectrum.containsKey(key))
        spectrum.put(key, 0);
      spectrum.put(key, spectrum.get(key) + 1);
    }

    @Override protected void initialization(final ASTNode ¢) {
      disabling.scan(¢);
    }
  });
}
```
@M4tt30rru how does it look? will it work? also sorry for touching your file...

**Comment by M4tt30rru** [comment]
@OriRoth I tested it on commons-bcel, commons-lang and guava and there and no exception was raised. As far as consolidatetips is concerned it is working. Since also InteractiveSpartanizer is based on consolidatetip (the one on Trimmer class) that was updated as well, it should work also for it. In any case I am going to test it thoroughly also on other systems.Thank you very much @OriRoth.

**Comment by OriRoth** [comment]
Done for now, see #349
