### ISSUE TITLE
The John Doe pattern

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#460]
Is when a method gets an argument which does not affect it's control.

The easiest to find are methods with arguments and no `IfStatement ` or loops.

**Comment by yossigil** [comment]
Except for checking that the value is null.

**Comment by orimarco** [comment]
Seems like this pattern applies to more then half of the methods in commons-lang!

**Comment by yossigil** [comment]
Amazing, ain't it?

The rule is LAD. Call me to figure out this acronym!
