### ISSUE TITLE
Examiner pattern

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#461]
A method which examines something about an object and returns true\false.
Actually, this is quite similar to a predicate...

For example:
```
  public static boolean isMarkedForReport(MethodDeclaration ¢) {
    return ¢.getProperty(Marker.AST_PROPERTY_NAME_MARKED_FOR_REPORT) != null;
  }
```

@yossigil  can we define this as a pattern?

**Comment by OriRoth** [comment]
@orimarco you can close an issue from your commit, like so:
```
Examiner pattern close #461
```
FYI

**Comment by orimarco** [comment]
Wow, GitHub is awesome!
thanks
