### ISSUE TITLE
Unused variable to double underscore bug

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#466]
```
@SuppressWarnings("unused") Object... os
```

==>

```
@SuppressWarnings("unused") Object __
```

**Comment by OriRoth** [comment]
Close if you are done. Remember to add tests and tag your progress in commits #466 like this.

**Comment by ravivos** [comment]
done testing, bug had been fixed.

**Comment by yossigil** [comment]
:+1:

**Comment by yossigil** [comment]
The test class is empty. What's going on?

**Comment by ravivos** [comment]
I only tested the GUI.
Just bumped into #875 and understood I should've tested it this like described overthere.
Working on it.
