### ISSUE TITLE
Replace dialogs with a view

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#468]
An idea worth considering. Would give the plugin nicer, sharper look.

_Documentation:_
- http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fworkbench_cmd_menus.htm

**Comment by yossigil** [comment]
:+1:

**Comment by OriRoth** [comment]
Duplicate of #1177
