### ISSUE TITLE
Use of exceptions in tippers as flow control = bad

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#469]
Throwing an exception for `division by zero` is not cool. Even if you catch it properly, it mess up the console with error notations. The `monitor` tool that deals with errors should be used for _debugging_ purposes, not for **standard activity**. See `$EvaluateInfixExpression` and its implementations.
@yossigil @dormaayan assign this please.
See also #407

**Comment by yossigil** [comment]
done by @orimarco
