### ISSUE TITLE
Through serious testing of switch

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#47]

**Comment by yossigil** [comment]
One thing you can do, is run the spartanization plugin from the marketplace, on the current code. It provides 6 warnings. I think it does not perform well on any of them.

**Comment by dormaayan** [comment]
I could't find the wrings related to switches.
are there wrings of that kind and where are they ?

**Comment by yossigil** [comment]
@dormaayan Oops it is in branch master.
@OriRoth : I think it would be fun doing it together

**Comment by dormaayan** [comment]
@yossigil :
So, should I work on it at the branch master ? , or you will add it to more stable ?

**Comment by yossigil** [comment]
It seems defunct now.
