### ISSUE TITLE
Tutorial/Travis: sign-up

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#470]
@orimarco lets write it together.
* Step 1: enter [https://travis-ci.org/SpartanRefactoring/Spartanizer](https://travis-ci.org/SpartanRefactoring/Spartanizer)
* Step 2: click on `Sign in with GitHub`
* Step 3: Profit $$$.

**Comment by yossigil** [comment]
:+1:

**Comment by yossigil** [comment]
@AdiOmari , @yh-github , @idabran , @zvili , @orimarco : please take note for of our teachings. Never commit broken code.
