### ISSUE TITLE
Convert GUI issue #429 into a wiki page.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#472]
#429

**Comment by OriRoth** [comment]
I have written a usage tutorial: https://github.com/SpartanRefactoring/Spartanizer/wiki/Tutorial
It needs to be updated.

**Comment by yossigil** [comment]
OK, this will be the job of the GUI/IT team of folks

**Comment by OriRoth** [comment]
Duplicate of #1210
