### ISSUE TITLE
Configuration page- better screen titles

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#473]
@OElmak 

![image](https://cloud.githubusercontent.com/assets/12775400/19507862/348303a2-95de-11e6-99f3-b58ccf5178f8.png)

It is quite good, you do not have an example. I think youshould add a tab saying what each rule does. 

Here is an example: 

![image](https://cloud.githubusercontent.com/assets/12775400/19507887/5f7e3c84-95de-11e6-8c43-640a2b41b842.png)

Related to #25

**Comment by yossigil** [comment]
@OriRoth FYI

**Comment by OriRoth** [comment]
Where do you see this?? Check you are using the updated version.
![pref](https://cloud.githubusercontent.com/assets/15183108/19510133/8ebde88a-95ea-11e6-9895-15680ce1bef4.jpg)

**Comment by OriRoth** [comment]
Ahh its an addition... OK I'll move it to the GUI project.

**Comment by OriRoth** [comment]
*Current status:*
![preferences](https://cloud.githubusercontent.com/assets/15183108/24934194/c5beeae8-1f22-11e7-9f4d-058eba185b56.jpg)
*****************************
*Features:*
* Tipper description on hover
* Tipper examples (`converts` examples only) on double click

I think the current implementation answers the original requirements. If someone want to change something, comment here.

*Left to do:*
* Better titles in preferences screens
* ? (TBD)

**Comment by OriRoth** [comment]
Done in 5eec40e52d110be78e8fd75fe1bd31f6905c5275
