### ISSUE TITLE
Installation instructions: Reference to plugin warnings 

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#474]
See #146 :

> there should be a reference in the relevant tutorial to this issue, indicating the solution in case someone gets a warning for this file.
> I hope that newly workers would download the updated SDK and will not confront any problems.

**Comment by yossigil** [comment]
I change this to week3

**Comment by ravivos** [comment]
@yossigil no need, done - [Install Me](https://github.com/SpartanRefactoring/Spartanizer/wiki/Installation-instructions)
