### ISSUE TITLE
Plug-in Problem: The markup in the document following the root element must be well-formed.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#475]
Resource: il.org.spartan.plugin/plugin.xml
Location: line 13

**Comment by OriRoth** [comment]
Sorry I am not seeing this. This is an XML warning - `plugin.xml` have been corrupted by mistake and I have fixed it, is the warning still there?

**Comment by yossigil** [comment]
It is gone now.
