### ISSUE TITLE
Tips on/off indication

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#477]
There is non at the moment, except for markers showing or not. In the past the menu option had a 'v' besides it, but it could not be maintained. Maybe a cool option is to change the option's name to `Tips on` and `Tips off` according to nature of current project... I think I know how to do this.

**Comment by yossigil** [comment]
Please add the checkmark, even if it only an apprxoimation. 
We need a new issue for this, to be done by the GUI/IT team of floks.

**Comment by OriRoth** [comment]
OK I just solved it... a different approach can be implemented later, but this solution is fairly sufficient.
I moved the `Tips on/off` option to project `Refactor` menu:
![menu](https://cloud.githubusercontent.com/assets/15183108/19528673/994da5f6-9635-11e6-967f-e2d9a9807cf4.jpg)
![menu2](https://cloud.githubusercontent.com/assets/15183108/19528674/9ab9526e-9635-11e6-842b-ba1339e4533c.jpg)

**Comment by OriRoth** [comment]
*Remainder*: tips on/off handler is available also via shortcut `ctrl+4`.
