### ISSUE TITLE
TDD tutorial (31.10) + Assignment 1

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#478]
**Previous**: #592 

## WTH

In the second meeting of the YP (31.10) we'll be talking about TDD.
- What is TDD and why it's very good.
- How to TDD (with [example](../issues/552)).
- Everyone is going to get a short assignment, which will include implementing a method using TDD. (A short explanation about eclipse DOM and ASTVisitor will be given).

## Assignment

teams of 2-3.
Will open issues per each assignment and each team will choose an issue to work on.
All commits will reference the issue.
Grades will be given according to the quality and detailing of the TDD process.

## OK. What should we do?

1. choose an issue which is labeled [TDD assignment](https://github.com/SpartanRefactoring/Spartanizer/labels/TDD%20assignment) and is not yet assigned.
2. assign yourselves to the issue.
3. from now on, the assignment is claimed yours.
4. read the **preperations** section in #404 and apply it.
5. complete the assignment using TDD. 
6. close the issue.

### Guidelines

- this assignment is for you to experience a TDD process, hence you are to take it to the extreme and to split the process into as many phases as you can (phase= test + code fix).
- after each phase you should commit your code with an appropriate message.
- all commits should reference your issue, meaning you should write \#issueNumber somewhere in your commit message.
- DO NOT commit code which has compilation errors or warnings.
- the assignment are per team, but all team members are expected to be involved and will be graded by their work.
- notice the due date for the assignment (check out it's milestone).

## Hints
- Use `wizard.ast(String)` to create an `ASTNode` out of `String`.
- Use `ASTVisitor` to iterate all descendants of node..
- [ASTNode documentation](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FExpression.html)
- [ASTVisitor documentation](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FASTVisitor.html)

**Comment by OriRoth** [comment]
@orimarco is this something for the yearly project? For all the students or just for those who work on this project?

**Comment by orimarco** [comment]
@OriRoth Everyone!
