### ISSUE TITLE
Nano: detect functions whose return value does not depend on he parameters.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#486]

**Comment by orimarco** [comment]
What about field dependencies? I think we should consider them as parameters.
Or we can define 2 patterns:

1. depends on nothing.
2. depends only on fields.

**Comment by yossigil** [comment]
Ok, so be it. I do not know what I am looking for yet.

**Comment by orimarco** [comment]
For now, an Independent method will be one that does not use he parameters nor fields.
**Problem:** cannot decide whether method uses fields which were inherited.
