### ISSUE TITLE
Symmetric variable nanon

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#487]
As in math.max()

**Comment by orimarco** [comment]
foo(x,y) is symmetric iff For Every x,y: foo(x,y) = foo(y,x).

We might need some analysis to determine that.

**Comment by yossigil** [comment]
not sure... I think you can make some simple subsitution and see if the result is the same.

**Comment by orimarco** [comment]
Hard to detect without semantic analysis.
