### ISSUE TITLE
Dialog Boxes: Laconize/Apply tip to entire project: Confirmation before starting:  add Cancel button

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#491]
It does not show:
![image](https://cloud.githubusercontent.com/assets/12775400/19576094/63aa5788-971a-11e6-8bdd-c0078ec83fa6.png)

**Comment by OriRoth** [comment]
It already exist in the new `Disalogs`. I'll remove the old implementations soon.

**Comment by OriRoth** [comment]
Yea I got confused because of the OK button... well now there should be a cancel button as well. Does it worked?

**Comment by yossigil** [comment]
It does!
