### ISSUE TITLE
Dialog Boxes: Apply tip over entire project": Progress Monitor: Add tipper name & category 

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#492]

**Comment by OriRoth** [comment]
May be complicated... remember we separated the `Trimmer` from the `Applicator`, so solving this may create some mess.

**Comment by yossigil** [comment]
Easy, you ask the applicator to tell you in string what it is , and use this information

**Comment by OriRoth** [comment]
![dialog](https://cloud.githubusercontent.com/assets/15183108/19597363/af7952fe-979c-11e6-907c-78b7ad935eaa.jpg)

Added name also for `Applicator`. This name is by default the name of the `GUI$Applicator` used.

**Comment by yossigil** [comment]
:+1:
