### ISSUE TITLE
Dialog Boxes: Laconize all/Apply tipper on all: Progress Monitor: add pass# and accumulating total(s) 

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#493]

**Comment by OriRoth** [comment]
Yes I have just disabled it to see if it solves our malicious issues. I'll activate it again soon.

**Comment by yossigil** [comment]
Please reenable. I am hunting the bug.

**Comment by OriRoth** [comment]
It is enabled in the new implementation, I'll try to quickly add it to the old one as well....

**Comment by OriRoth** [comment]
Well it is also enabled in the old version - can you tell me what do you wish to see exactly?

**Comment by yossigil** [comment]
Never seen it.... Not in new neither in old.

**Comment by OriRoth** [comment]
![dialog](https://cloud.githubusercontent.com/assets/15183108/19596748/c2e1b09c-9798-11e6-8a3a-6bf82e4e909f.jpg)

Seam nice... is it what you get in Linux too? (besides top right close button)

**Comment by yossigil** [comment]
:+1: 
will check

**Comment by OriRoth** [comment]
@yossigil check it out.

**Comment by yossigil** [comment]
Excellent job!
