### ISSUE TITLE
Problems Window: Add 'cateogry/name' to the last column (when you create the `IMarker` 

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#494]
That is, where Laconize is here.

![image](https://cloud.githubusercontent.com/assets/12775400/19575650/635d06a6-9718-11e6-80f3-1f842c498c3a.png)

**Comment by OriRoth** [comment]
I do not think it works that way... this is the generic info view I believe.

**Comment by yossigil** [comment]
It is easy, just search for the string `"Laconize"`, I placed it there...

**Comment by OriRoth** [comment]
I could not find a way to change the `Type` field - this is *not* an attribute, and constantize once in `plugin.xml` as marker name.

Instead I added the category to tip's name:

![dialog](https://cloud.githubusercontent.com/assets/15183108/19604454/fb983274-97bd-11e6-85b1-c4e6584bb03c.jpg)

Looks good, but can be improve with better (=shorter) category names (applies to either solution).

**Comment by OriRoth** [comment]
OK it may be possible if we are willing to maintain multiple marker types. That includes:
* Multiple marker definitions in `plugin.xml`
* Need to be updated with each category addition/modification.
We should decide if it is better than the solution I have offered.

**Comment by yossigil** [comment]
Sounds good

**Comment by OriRoth** [comment]
![dialog](https://cloud.githubusercontent.com/assets/15183108/19743682/e82807c8-9bd2-11e6-8a3e-db7635f4dc14.jpg)

**But**: this required brute-force changes in `plugin.xml` that **should be maintained** in the future:
1) Maker definition for each type - because each marker can have only one name.
```
<extension 
  id="il.org.spartan.tip.Abbreviation"
  name="Abbreviation"
  point="org.eclipse.core.resources.markers" 
>
  <super type="il.org.spartan.tip"/>
</extension>
<extension 
  id="il.org.spartan.tip.Annonimaization"
  name="Annonimaization"
  point="org.eclipse.core.resources.markers" 
>
  <super type="il.org.spartan.tip"/>
</extension>
[so on for like 50 lines]
```
2) Marker resolution for each type - it said explicitly in the documentation that:
```
the marker type for which this marker resolution generator applies.
It does not apply to marker subtypes.
```
thus we get
```
<extension point="org.eclipse.ui.ide.markerResolution">
  <markerResolutionGenerator 
   markerType="il.org.spartan.tip.Annonimaization"
   class="il.org.spartan.plugin.QuickFixer"
  />
</extension>
<extension point="org.eclipse.ui.ide.markerResolution">
  <markerResolutionGenerator 
   markerType="il.org.spartan.tip.Canonicalization"
   class="il.org.spartan.plugin.QuickFixer"
  />
</extension>
[so on for like 50 lines]
```

**Comment by yossigil** [comment]
Indeed. This makes no sense. Good that you have closed it.
