### ISSUE TITLE
Cascading nano

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#501]
```
a.setX(x);
a.setY(y);
```

and even more general ones. with a sequence of lambda functions.

**Comment by orimarco** [comment]
Can detect such method invocations and if methods are fluent methods (#505) combine them into one fluent statement.
But... this might need method binding to find out the `MethodDeclaration `of a `MethodInvocation`.

**Comment by yossigil** [comment]
Assume LOLA is to the rescue

**Comment by orimarco** [comment]
Hmm can't think of something Lola can do in this case (that JDT can't do safely...)

**Comment by yossigil** [comment]
How about the following syntax: ```a <* setX(x) <* setY(y) <* getZ```, Lola can convert it to Java.

**Comment by orimarco** [comment]
Of course, but the IDE will have problems with the syntax.
Unless we hack the build toolchain somehow and make it run Lola before javac.

**Comment by yossigil** [comment]
This is a famous problem. One needs to think about fitting a preprocessor in the IDE, but this is not our problem. this is engineering, we focus on science.

**Comment by orimarco** [comment]
#991
