### ISSUE TITLE
Collateral nano: 

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#502]
here is an example:

``` java
a++; f(x,y);  b++;
```

to

``` java
collaterally(++a, ++b, f(x,y));
```

use the no-aliasing assumption, i.e., even though function `f` may depend indirectly on `b`, you assume that no such dependency exists, unless a and b are data members.

**Comment by yossigil** [comment]
?

**Comment by orimarco** [comment]
#863
