### ISSUE TITLE
Fluent Method pattern

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#505]
Any method that returns `this`:
```
class C{
	C foo(int x){
		//whatever
		return this;
	}
}
```

related to #504 , #501

**Comment by OriRoth** [comment]
Maybe return value is same type as this? Can extend this pattern or be a different one.

**Comment by yossigil** [comment]
you can, but it is a can of worms, don't touch it

**Comment by OriRoth** [comment]
It actually may be implemented more easily. You should only check the return type. Consider this problematic example:
```
Class A {
  Object f() {
    return this;
  }
}
```
Not really a fluent API.

**Comment by orimarco** [comment]
1. Your'e right that I need to check the return type too.
2. The meaning of this pattern is that when we have a sequence of method invocations to _Fluent_ methods we can join them into one fluent statement. We can not do this if the methods just return some object of the same type of the class.
3. A method that returns the same type of the class can be one that just calculates something or retrieves an element from some collection, doesn't have to be a builder.
