### ISSUE TITLE
How to extract TipperCategory / TipperGroup out of Tip?

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#511]
It can be done like this:
```
Tipper tipper = null;
try {
  tipper = tip.tipperClass.newInstance();
} catch (InstantiationException | IllegalAccessException x) {
  x.printStackTrace();
}
TipperGroup group = tipper.tipperGroup();
```
But I need to do it for *every marker* [O(10000)], so it should be more efficient.

@yossigil following Telegram message.

**Comment by yossigil** [comment]
One way is to create a cache, in which class objects are mapped to cateogries.

**Comment by OriRoth** [comment]
Done. Thank you for the help.
