### ISSUE TITLE
Karma and Todos for Dor Ma'ayan

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Spartanizer#513]
- [x]  I have an Image
- [x]  My nickname is my actual name
- [x]  I described myself in the bio page
- [x]  I'm not in search for a job !

**Comment by dormaayan** [comment]
@yossigil : Done

**Comment by zahimizrahi** [comment]
looks very nice, good job!

please check out mine #551

**Comment by yossigil** [comment]
Good job.Make sure you keep thisopen

**Comment by yossigil** [comment]
1. Keep this open
2. Edit the content of the main issue, to remove the junk. Just leave the checked todos in it.
3. Assign yourself if you haven't done so yet.
:+1:

**Comment by OmriBS** [comment]
Karma be upon you

**Comment by dormaayan** [comment]
@yossigil : I think I will stay with my original page...

**Comment by yossigil** [comment]
We need some page for final grading. Use anyone you want, and put a ref to the other
