### ISSUE TITLE
Kfir Marx: TODOs 

### ISSUE THREAD

**Issue by kfir-marx** [SpartanRefactoring/Spartanizer#516]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by kfir-marx** [comment]
@IDabran: Done.

**Comment by ravivos** [comment]
Cool page, check out mine #519

**Comment by yossigil** [comment]
:+1: 
Try to leave your Karma page open, never close this issue...

**Comment by nisanarz** [comment]
Great Karma page! :) 
Please check out mine #542

**Comment by zahimizrahi** [comment]
Good job! keep up the good work!

check out mine #551

**Comment by yossigil** [comment]
1. Keep this open
2. Edit the content of the main issue, to remove the junk. Just leave the checked todos in it.
3. Assign yourself if you haven't done so yet.
:+1:

**Comment by NetanelFelcher** [comment]
awesome 💯 
check out mine #633

**Comment by yossigil** [comment]
Kfir: Were you absent this week?

@OriRoth tells me you had to vote by telephone.
