### ISSUE TITLE
Karma and Todos for Inbal Matityahu

### ISSUE THREAD

**Issue by matityahuinba** [SpartanRefactoring/Spartanizer#521]
- [x] Use a picture, photo or distinct avatar. Don''t use an automatic icon.
- [x] readable nick.
- [x] Describe yourself in the bio page.
- [x] Available for hire.

**Comment by matityahuinba** [comment]
@yossigil  Done?

**Comment by noamyft** [comment]
hi :+1: 
please check mine #524

**Comment by kobybs** [comment]
wow!👍

**Comment by yossigil** [comment]
Indeed :+1:

**Comment by ortroyaner** [comment]
Magical! 🌵 
karma4karma: #533 😆

**Comment by yossigil** [comment]
Indeed.

**Comment by zahimizrahi** [comment]
love what you've done with this place

I would like you check mine #551 if you can :)

**Comment by yossigil** [comment]
1. Keep this open
2. Edit the content of the main issue, to remove the junk. Just leave the checked todos in it.
:+1:

**Comment by Tomnof** [comment]
This is a great Karma page!
I would appreciate feedback on my own - #556
:)

**Comment by yossigil** [comment]
Good job Inbal.

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-ParkingManagement#14
