### ISSUE TITLE
Ben Shimol, Koby: TODOs

### ISSUE THREAD

**Issue by kobybs** [SpartanRefactoring/Spartanizer#522]
- [x]  Use a picture, photo or distinct avatar.
- [x]  Make sure you present yourself by a readable **nick**.
  - kobybs for koby ben shimol
- [x]  Describe yourself in the bio page.
- [x]  Available for hire.

**Comment by kobybs** [comment]
@YossiGil: Done.

**Comment by matityahuinba** [comment]
Nice :+1:
please check mine #521

**Comment by yossigil** [comment]
Did you decide whether you are available for hire?

**Comment by zahimizrahi** [comment]
Good job!

**Comment by yossigil** [comment]
1. Keep this open
2. Edit the content of the main issue, to remove the junk. Just leave the checked todos in it.
3. Assign yourself if you haven't done so yet.
:+1:

**Comment by yossigil** [comment]
- change name of issue as per the message sent on Telegram

**Comment by kobybs** [comment]
Summary of issues by that point:
last week:
#877 #886 #875 #359 
previous weeks:
#235 #283 #871 #872 #873

**Comment by yossigil** [comment]
If there is any update in this project in the past 12 days, this is the time to add it.
