### ISSUE TITLE
 Karma and Todos for Noam Yefet

### ISSUE THREAD

**Issue by noamyft** [SpartanRefactoring/Spartanizer#524]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by noamyft** [comment]
@YossiGil: Done.

**Comment by AviadCo** [comment]
Good Job Partner, Good luck in the project

**Comment by matityahuinba** [comment]
Good luck! :pray:

**Comment by nisanarz** [comment]
Great Karma page! :) 
Please check out mine #542

**Comment by AdiOmari** [comment]
Looks good 👍 , assign yourself if you haven't done so yet.

**Comment by yossigil** [comment]
edit our the blurb. leave the todos

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Market#5
