### ISSUE TITLE
Karma and Todos for Aviad Cohen

### ISSUE THREAD

**Issue by AviadCo** [SpartanRefactoring/Spartanizer#528]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by AviadCo** [comment]
- [ ]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:

Example | Score | Why?
------- | ------|-----
![image](https://cloud.githubusercontent.com/assets/12775400/19101029/e525d7d8-8acc-11e6-97f1-8bdc0bb9ac4f.png) | Bad | Anonymous
![image](https://cloud.githubusercontent.com/assets/12775400/19101029/e525d7d8-8acc-11e6-97f1-8bdc0bb9ac4f.png) | OK | Personal trademark
  - **Excellent**: 
- [ ]  Make sure you present yourself by a readable **nick**

Example | Score | Why?
------- | ------|-----
`Moshe Levy II` | Super | Clear identification
`YossiGil` | Excellent | You identify yourself by full name
`IDabran`  | Good | == **I**tai **Dabran**
`yogi` | OK | Well known nick
`j1046`  | Bad | Who the hell are  you?
`zm&4jk` | Worse | Not even pronnounceable
`r2d2`   | Terrible | We are not playing games here
`ghost` | Disaster | Are you a troll or what? 
  - Bad: `j10463` / `r2d2` / `bb8` / `biscuit` / `the destroyer`
  - Ok: `yogi`  (**Yo**ssi **G**il), `idarban` (**I**tai **D**arban)

- [ ]  Describe yourself in the bio page; FYI, here is my description:
![image](https://cloud.githubusercontent.com/assets/12775400/19105201/753bb934-8ae9-11e6-8f63-659f5c14162e.png)

- [ ]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
![image](https://cloud.githubusercontent.com/assets/12775400/19105155/3554e8cc-8ae9-11e6-8915-a180075388b1.png)
14162e.png)

- [ ]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
![image](https://cloud.githubusercontent.com/assets/12775400/19105155/3554e8cc-8ae9-11e6-8915-a180075388b1.png)

**Comment by noamyft** [comment]
Good luck!! :100:

**Comment by nisanarz** [comment]
Great Karma page! ;)
Please check out mine #542

**Comment by zahimizrahi** [comment]
Keep up the good work! 

check out mine #551

**Comment by yossigil** [comment]
1. Keep this open
2. Edit the content of the main issue, to remove the junk. Just leave the checked todos in it.
:+1:

**Comment by AviadCo** [comment]
@yossigil : **PSB [AC]**
1. Keep this open
**[AC] done.**
2. Edit the content of the main issue, to remove the junk. Just leave the checked todos in it.
**[AC] done.**
3. Assign yourself if you haven't done so yet. 👍
**[AC] done.**

**Comment by yosefraisman** [comment]
Your karma page is so great, it's a Nobel prize in literature waiting to happen! please check out mine at #616

**Comment by yonzarecki** [comment]
Nice work !

**Comment by IdanAtias** [comment]
Nice work!
plz feedback me ;)

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Market#4
