### ISSUE TITLE
A wring to convert x.toString() to "" + x

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#54]
This should be an easy wring.

**Comment by yossigil** [comment]
@Stav1472 : I think this will get you going for this week

**Comment by yossigil** [comment]
@NivShalmon , re: #94 .
The information  you provide in this issue could be used by @Stav1472 to make guesses as to when "", and when this is not necessary

**Comment by Stav1472** [comment]
i think this is solved. close if you agree.

**Comment by yossigil** [comment]
There is only one test case. The major tough tests are not there. You would have to search and find the other tests cases, and add them. Also, include coverage tests by eclemma

**Comment by yossigil** [comment]
Please add here a reference to the unit testing

**Comment by Stav1472** [comment]
these are the unit tests that i wrote:
`@Test public void issue54_01() {
    trimming("x.toString()").to("\"\" + x");
  }

  @Test public void issue54_02() {
    trimming("if(x.toString() == \"abc\") return a;").to("if(\"\" + x == \"abc\") return a;");
  }

  @Test public void issue54_03() {
    trimming("((Integer)6).toString()").to("\"\"+ (Integer)6");
  }

  @Test public void issue54_04() {
    trimming("switch(x.toString()){ case \"1\": return; case \"2\": return; default: return; }")
        .to("switch(\"\" + x){ case \"1\": return; case \"2\": return; default: return; }");
  }`

**Comment by yossigil** [comment]
Did you try it with the other wring, which is likely to make an error

```java
String s = f() + o.toString();
```
goes to
```java
String s = f() + "" + o;
```
goes to 
```java
String s = f() + o;
```
but I cheated, since f and or are both of type Integer, which makes the assignment legal in the code we started from, but not in the code we ended up with.

**Comment by Stav1472** [comment]
no I did not try that, nice idea!

but if o is Integer, then "" + o does not go to o according to the rules, only of o is string it does, and then it's OK.

**Comment by yossigil** [comment]
@NivShalmon , @dormaayan : this is all related to #119

**Comment by yossigil** [comment]
Is this done? Can it be closed? If so, please do

**Comment by dormaayan** [comment]
@yossigil :
I tested the case you mentioned above and it seems like working OK, you can have a look.
I close the issue, please reopen it if you meant something else.

**Comment by yossigil** [comment]
Try to run the plugin on itself.if you see no problem, and there is a test case for this example, then close.

**Comment by yossigil** [comment]
@dormaayan : can you apply the wring to the plugin?
