### ISSUE TITLE
setting up the working environment of Alexander Kaplan and Ariel Kolikant

### ISSUE THREAD

**Issue by KaplanAlexander** [SpartanRefactoring/Spartanizer#540]
The working environment for this project includes
- [x] Linux
- [x] Eclipe Neon
- [x] Java 8 Programming
- [x] Formatting conventions
- [x] Spartan programming
- [x] Fixed cleanup routine
- [x] Highest level of warning settting
- [x]  Git command line
- [x] Telegram (might be changed by another messaging application)

**Comment by yossigil** [comment]
@KaplanTheGreat : this is not an acceptable name.

**Comment by KaplanAlexander** [comment]
@yossigil Better?

**Comment by yossigil** [comment]
:+1:
