### ISSUE TITLE
Karma and Todos for Nisan Arzoan

### ISSUE THREAD

**Issue by nisanarz** [SpartanRefactoring/Spartanizer#542]
- [x]  Use a picture, photo or distinct avatar. 
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; 
- [x]  State that you are (not) in search for a job.

**Comment by nisanarz** [comment]
@yossigil : Done.

**Comment by AviadCo** [comment]
Yours great too (;

**Comment by AviadCo** [comment]
Yours great too (;

**Comment by noamyft** [comment]
Yours great too! :+1:

**Comment by zahimizrahi** [comment]
Good job!

**Comment by yossigil** [comment]
1. Keep this open
2. Edit the content of the main issue, to remove the junk. Just leave the checked todos in it.
3. Assign yourself if you haven't done so yet.
:+1:

**Comment by kfir-marx** [comment]
great page!

**Comment by NetanelFelcher** [comment]
awesome 💯

**Comment by yossigil** [comment]
:+1:

**Comment by yossigil** [comment]
@zvili : please move to student's current repo
