### ISSUE TITLE
Implement the environment and scope visitor

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#55]

**Comment by yossigil** [comment]
Here is a challenge, consider this
```
    // TODO: use this as a case of clever renaming and method extraction
    static int of(final ASTNode n) {
      final Expression e = extract.core((Expression) n);
      for (final Level l : values())
        if (l.includes(e))
          return l.ordinal();
      return values().length;
    }
```
I think the  output should be:
```
    static int of(final ASTNode ¢) {
      return of(extract.core((Expression) ¢));
    }

    private static int of(final Expression ¢) {
      for (final Level $ : values())
        if ($.includes(¢))
          return $.ordinal();
      return values().length;
    }
```
- [ ] can we do it?

**Comment by sakopzon** [comment]
We need the environment first, cause the next steps should be executed:

1. Find coercion.
2. Check for environment:
if !(current scope declares only ¢) then
    * create new function f() of the same type as the nearest parent method g().
    * change f()'s parameter name to ¢.
    * call from f() to g() with the coercion expression as actual parameter.
    * remove the coercion expression from g()
    * change g()'s formal parameter's type to the coercion type.

**Comment by yossigil** [comment]
No work for now

**Comment by yossigil** [comment]
Subsumed by `scope.of` and 'definition.kind()'
