### ISSUE TITLE
Karma and Todos for Zahi Mizrahi

### ISSUE THREAD

**Issue by zahimizrahi** [SpartanRefactoring/Spartanizer#551]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; 
- [x]  State that you are (not) in search for a job.

**Comment by zahimizrahi** [comment]
@yossigil : done. 
(I couldn't assign myself to this issue)

**Comment by dormaayan** [comment]
@zahimizrahi : Cool Page (:

**Comment by nisanarz** [comment]
Looks great! good luck! :)

**Comment by shaysegal** [comment]
Good job! 
check mine #558

**Comment by matityahuinba** [comment]
Awesome! Good luck!! :pray:

**Comment by yossigil** [comment]
Add a "quality assurance" and "teaching" labels to this issue. Add a deadline (which?). .
 erase much of the junk you copied from the tutorial. Assign yourself if you havent' done so yet.
Good luck.

**Comment by kfir-marx** [comment]
great page :+1:

**Comment by zahimizrahi** [comment]
#551 is closed.

**Comment by yossigil** [comment]
Did you mean #801 is closed?

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-ParkingManagement#12
