### ISSUE TITLE
Count expressions in ASTNode

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#552]
A function named 
```Java
public int expressions(ASTNode n);
```
 - takes a single parameter, which is an 'ASTNode`.
 - returns an `int` which is the number of expressions in `n`.

This function is to be implemented as a static member of `tdd.enumerate`.

**Comment by OriRoth** [comment]
If it is a static member of `tdd.count` can we call it `expressions`?

**Comment by orimarco** [comment]
_Updated the description_

**Comment by yossigil** [comment]
:+1:
