### ISSUE TITLE
Abramovich, Dan: TODOs

### ISSUE THREAD

**Issue by danabramovich** [SpartanRefactoring/Spartanizer#553]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page;
- [x]  State that you are (not) in search for a job.

**Comment by danabra** [comment]
@YossiGil: Done.

**Comment by danabra** [comment]
@YossiGil: Done.

**Comment by yossigil** [comment]
Add a "quality assurance" and "teaching" labels to this issue. Add a deadline (which?). .
 erase much of the junk you copied from the tutorial. Assign yourself if you havent' done so yet.
Good luck.

**Comment by yossigil** [comment]
Your avatar should be you

**Comment by danabramovich** [comment]
is it ok now?

**Comment by yossigil** [comment]
- change name of issue as per the message sent on Telegram

**Comment by danabramovich** [comment]
@yossigil done

**Comment by danabramovich** [comment]
Summary of my Issues:
Issues I have completed : #885 #228 #879 #711 #427 #191
Issues I have completed last week : #879 #885 #228
Issues I am currently working on : #853 (can't write tests due to bugs in leonidas) #877

**Comment by yossigil** [comment]
If there is any update in the past 12 days, this is the time to add it.

**Comment by danabramovich** [comment]
yes, I have coompleted Issue #881

**Comment by yossigil** [comment]
Thanks.

**Comment by yossigil** [comment]
Can you put your name here: https://docs.google.com/document/d/1UvP8tNBX4N-4dRM6ZIFREnbjf9Yvwo3TecFZJmJoApg/edit
