### ISSUE TITLE
Karma and Todos for Tom Nof

### ISSUE THREAD

**Issue by tomnof** [SpartanRefactoring/Spartanizer#556]
- [x] Makesure you present yourself by a readable nick
- [x] Describe yourself in the bio page
- [x] State that you are (not) in search for a job

**Comment by Tomnof** [comment]
@yossigil Done?

**Comment by yossigil** [comment]
:+1:

**Comment by yossigil** [comment]
Add a "quality assurance" and "teaching" labels to this issue. Add a deadline (which?). .
 erase much of the junk you copied from the tutorial. Good luck.

**Comment by Tomnof** [comment]
deadline - end of this semester? I believe this Karam page is going to be a very good fried of mine in the upcoming project :P

**Comment by matityahuinba** [comment]
Amazing! Good Luck! :sparkles:

**Comment by yossigil** [comment]
Deadline, sprint 0

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-ParkingManagement#11
