### ISSUE TITLE
Karma and Todos for Shay Segal

### ISSUE THREAD

**Issue by shaysegal** [SpartanRefactoring/Spartanizer#558]
- [X]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [X]  Make sure you present yourself by a readable **nick**
- [X]  Describe yourself in the bio page; FYI, here is my description:
- [X]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by shaysegal** [comment]
can't assgin to myself 
@YossiGil: Done.

**Comment by zahimizrahi** [comment]
I'm so astonished from this issue, and it's so scary that you mastered all the tasks. 
you are stepping forward to become the great ruler of GitHub. 💯 

I know that you're a very busy man, but if you can check mine #551 it will make my day.

**Comment by yossigil** [comment]
Add a "quality assurance" and "teaching" labels to this issue. Add a deadline (which?). .
 erase much of the junk you copied from the tutorial. Good luck.

**Comment by DavidCohen55** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9945775-202779545_1-s4-v1.png?transparent=1&width=246)

nice page Shay, check out my page #639 :)

**Comment by AdiOmari** [comment]
Good job, please assign yourself to the issue.

**Comment by AdiOmari** [comment]
@shaysegal  👍 , Just add teaching and quality assurance labels.

**Comment by yossigil** [comment]
Make sure you use lables @idabran, FYI.

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-ParkingManagement#10
