### ISSUE TITLE
Test cases for the environmental visitor 

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#56]

**Comment by yossigil** [comment]
The code was not tested at all,  I implemented it quickly.

Do make sure that you cover all cases. Use [this tool](http://www.eclemma.org/)

**Comment by sakopzon** [comment]
Ok, fixed the stupid problems I had with myself (lol) easy and medium tests are ready. Dan will be scanning it at 9 PM and by 10 we will start checking the coverage and finish the tests.

**Comment by yossigil** [comment]
> Ok, fixed the stupid problems I had with myself (lol) easy and medium tests are ready. Dan will be scanning it at 9 PM and by 10 we will start checking the coverage and finish the tests.

**Comment by yossigil** [comment]
How is this going?

**Comment by yossigil** [comment]
No work on this for the meantime.

**Comment by yossigil** [comment]
I think this one should be defunct. @dormaayan  take a quick look and close
