### ISSUE TITLE
Old Karma Page

### ISSUE THREAD

**Issue by yonilx** [SpartanRefactoring/Spartanizer#563]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon
- [x]  Make sure you present yourself by a readable nick
- [x] Describe yourself in the bio page
- [x] State that you are (not) in search for a job

**Comment by yonilx** [comment]
@YossiGil: Done. (can't assign myself tho)

**Comment by yossigil** [comment]
Add a "quality assurance" and "teaching" labels to this issue. Add a deadline (which?). .
 erase much of the junk you copied from the tutorial. Good luck.

**Comment by TonyLek** [comment]
Such a cool page!
Look at mine! #579

**Comment by yossigil** [comment]
Your nick is not good.

**Comment by yonilx** [comment]
My nick relates to my name where **yon**ilx -> **Yon**atan.
I would appreciate it if I could keep my old nick as I'm using GitHub for several of my projects (some kept under private repositories) and will need to update their origin links if I would change my nick.

**Comment by yossigil** [comment]
There is a way to change the nick without changing the account. Would this work?

**Comment by yonilx** [comment]
I'm aware of this option, It looks like mentions (@) and gists will still be broken when changing the nick (with the same account), I'm not quite sure what happens to git and ssh repository links (like ssh://git@bitbucket.org /< accountname>/<reponame>.git) as they both relate to a specific username.
I would prefer to avoid these issues if possible ("A clever person solves a problem. A wise person avoids it." ― Albert Einstein).

**Comment by yossigil** [comment]
if it was just I no. but we have 60+ students. can you do a Google search for the potential faults you describe?

**Comment by yonilx** [comment]
gists and @ mentions do get broken, repositories are redirected. [source](https://help.github.com/articles/what-happens-when-i-change-my-username/)
Another potential problem is IDEs like pycharm and IDEA that use GitHub credentials, they may get broken too.

**Comment by yossigil** [comment]
Kudos for finding this in Google. I searched a bit for yonilx on github. There are two projects in which this one is involved, but none of them have issues.  Can you provide more information that will help us make an exception in this case?

**Comment by yonilx** [comment]
As I stated above, I have more private repos related to my graduate studies.
For a public example, I'm currently collaboration on the project [libact](https://github.com/ntucllab/libact/blob/master/docs/index.rst). And working on adding a new feature to it (can be seen as a fork in my public page), an example (simple) pull request to can can be seen [here](https://github.com/ntucllab/libact/pull/62).

**Comment by yossigil** [comment]
https://github.com/ntucllab/libact/issues/12
I found only one mention of yonilx in all the public projects. Wouldn't people who work with you on the private projects be able to tolerate a slightly clearer name?

Can you please reconsider. I really do not want to make an exception nor do I want to make you start a new account for the course.

**Comment by RonGatenio** [comment]
Nice page! 
Take a look at mine #584

**Comment by yonilx** [comment]
@yossigil Too bad, I'll just use a different account then @yonzarecki
I'll close and rename this issue later.

**Comment by yonzarecki** [comment]
link to new karma page #613

**Comment by yossigil** [comment]
another option
use first  initial and last name or first name and first of last

**Comment by yossigil** [comment]
Don't make any commits from this account, nor pull requests. We need to follow up 60 students or more. You are making it difficult for us.

**Comment by yossigil** [comment]
Defunct
