### ISSUE TITLE
Cohen, Michal: TODOs

### ISSUE THREAD

**Issue by michalcohen** [SpartanRefactoring/Spartanizer#564]
- [x]  Use a picture, photo or distinct avatar.
- [x]  Make sure you present yourself by a readable **nick**.
- [x]  Describe yourself in the bio page.
- [x]  State that you are (not) in search for a job.

**Comment by michalcohen** [comment]
@YossiGil: Done.

**Comment by AnnaBel7** [comment]
Wow! Amazing!
check out my karma page #565

**Comment by yossigil** [comment]
Add a "quality assurance" and "teaching" labels to this issue. Add a deadline (which?). .
 erase much of the junk you copied from the tutorial. Good luck.

**Comment by AdiOmari** [comment]
Profile and nick-name are good 👍 . Edit the issue to remove junk (duplicate content - last todo, and examples), keep only the todos . 
Assign yourself if you haven't done so yet.

**Comment by yossigil** [comment]
:+1:

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/IntelliJ-Spartanizer#11
