### ISSUE TITLE
Belozovsky, Anna: TODOs

### ISSUE THREAD

**Issue by AnnaBel7** [SpartanRefactoring/Spartanizer#565]
- [x]  Use a picture, photo or distinct avatar. Don't use an automatic icon.
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page
- [x]  State that you are (not) in search for a job

**Comment by AnnaBel7** [comment]
@YossiGil: Done.

**Comment by michalcohen** [comment]
BEST partner in the world!!!

**Comment by yossigil** [comment]
Add a "quality assurance" and "teaching" labels to this issue. Add a deadline (which?).

**Comment by geniashand** [comment]
Yay for Karma! ^_^

**Comment by AdiOmari** [comment]
👍

**Comment by yossigil** [comment]
:+1:

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/IntelliJ-Spartanizer#10
