### ISSUE TITLE
Karma and Todos for Lidia Piatigorski

### ISSUE THREAD

**Issue by Lidkin5** [SpartanRefactoring/Spartanizer#572]
#330
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box

**Comment by Lidkin5** [comment]
@yossigil  : Done.

**Comment by alexvitho** [comment]
Great Karma page 👍

**Comment by yossigil** [comment]
:-1: full name please

**Comment by yossigil** [comment]
Add a "quality assurance" and "teaching" labels to this issue. Add a deadline (which?).

**Comment by nikitadizhur** [comment]
Great 👍 
Can you, please, put a feedback on my issue? #599

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Internet-Browser-Plugin#5
