### ISSUE TITLE
Karma and Todos for Alex V.

### ISSUE THREAD

**Issue by alexvitho** [SpartanRefactoring/Spartanizer#573]
#330
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by alexvitho** [comment]
@yossigil  Done.

**Comment by Lidkin5** [comment]
Great karma page  👍 
check mine :)

**Comment by yossigil** [comment]
:-1: full name please

**Comment by yossigil** [comment]
Add a "quality assurance" and "teaching" labels to this issue. Add a deadline.

**Comment by alexvitho** [comment]
@yossigil 
I have a problem with putting my full - first and last name on public website (even on Facebook). 
Can i please keep the first capital letter of my last name ?

**Comment by yossigil** [comment]
OK

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Internet-Browser-Plugin#4
