### ISSUE TITLE
setting up the working environment of Alex V. and Lidia Piatigorski

### ISSUE THREAD

**Issue by alexvitho** [SpartanRefactoring/Spartanizer#576]
The working environment for this project includes
- [x] Linux
- [x] Eclipe Neon
- [x] Java 8 Programming
- [x] Formatting conventions
- [x] Spartan programming
- [x] Fixed cleanup routine
- [x] Highest level of warning settting
- [x]  Git command line
- [x] Telegram (might be changed by another messaging application)

**Comment by yossigil** [comment]
:-1: full names please

**Comment by yossigil** [comment]
If you havent' installed Linux, this is the time to do it.

**Comment by yossigil** [comment]
@alexvitho , @sakopzon , @KaplanAlexander , which of you is this one? Please use last name in nick and title.

**Comment by alexvitho** [comment]
@yossigil 
it is @alexvitho. 
If you want my full Last name i can email it to you in private. ( I added myself to the contributers file as Alexander Vitho ) .

**Comment by yossigil** [comment]
OK
