### ISSUE TITLE
Karma and Todos for Entony Lekhtman

### ISSUE THREAD

**Issue by tonylekhtman** [SpartanRefactoring/Spartanizer#579]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by TonyLek** [comment]
@YossiGil: Done.

**Comment by RonGatenio** [comment]
Nice page Tony!
Here is mine #584

**Comment by AmitOhayon** [comment]
This Karma page represents everything that I love about you.
What do you think of mine? #680

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Bugquery#6
