### ISSUE TITLE
Karma and Todos for Ron Gatenio

### ISSUE THREAD

**Issue by RonGatenio** [SpartanRefactoring/Spartanizer#584]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon.
- [x]  Make sure you present yourself by a readable **nick**.
- [x]  Describe yourself in the bio page.
- [x]  State that you are (not) in search for a job.

**Comment by RonGatenio** [comment]
@YossiGil: Done.

**Comment by yossigil** [comment]
Keep this one open. Assign labels teaching and quality-assurance. Edit the content so it looks more decent. Add a milestone.

**Comment by yossigil** [comment]
Assign yourself please

**Comment by ylevv** [comment]
That's a really nice Karma Page! 🎉 
Take a look at mine #598 😄

**Comment by SapirBismot** [comment]
**Ron, this is a very nice Karma Page** 👍 
 #612

**Comment by SharonKL** [comment]
👌 
#614

**Comment by orenafek** [comment]
Awesome Karma Page :)
I hope you'll love mine #624

**Comment by ZivIzhar** [comment]
nice nice shushi
what's that? : #644

**Comment by tonylekhtman** [comment]
Cool Page!

**Comment by inbalzukerman** [comment]
Such a nice Karma page!! 🏆 😃 
Check out mine- #684

**Comment by EliaTraore** [comment]
omg this is the best page everr 😲 
check this one out #694

**Comment by roy-shchory** [comment]
what a lovely page! i showed it to my firend Ema Stone and she wanted you to call her for a chat.
her number is on my Karma page in #621

**Comment by zvili** [comment]
@RonGatenio - Please close this issue

**Comment by zvili** [comment]
@RonGatenio - Sorry, Ori is right. This issue must remain opened.

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Elderly-Support#13
