### ISSUE TITLE
Class work: Tuesday - Aviad Cohen

### ISSUE THREAD

**Issue by AviadCo** [SpartanRefactoring/Spartanizer#596]
Create a new issue, assing yourself, copy the checklist below, set labels and milestone.
- [x]  [Login](https://accounts.eclipse.org/user/login?destination=oauth2/authorize) to eclipse. If you do not have a user name, create one.
- [x] Search in the eclipse market place for the [spartanizer, version 2.6](https://marketplace.eclipse.org/content/spartan-refactoring-0)
- [x]  Star the project
- [ ]  Install the plugin by dragging it into eclipse Neon
- [x]  run the plugin on one of your Java projects.to see what it does.
- [x] exit from eclipse
- [x] Star the project on [github](https://github.com/SpartanRefactoring/Spartanizer/issues/new): ![image](https://cloud.githubusercontent.com/assets/12775400/19832195/bb8dc860-9e25-11e6-9d92-aee51fcedd8c.png)
- [x]  Install git and maven on your machine:

``` bash
sudo update
sudo apt-get install mvn git
sudo apt-get upgrade
```
- [x]  Clone the project, using ssh: ![image](https://cloud.githubusercontent.com/assets/12775400/19832218/49de666a-9e26-11e6-8b73-3dc8672f61d2.png)

``` bash
mkir -p ~/git
cd !$
git clone git@github.com:SpartanRefactoring/Spartanizer.git
```
- [x]  Mvn build the project

```
cd ~/git/Spartanizer
mvn build
```

Make sure that the maven works.
- [x]  Search for installation instructions in the spartanizer project
- [x]  Install all plugins in eclipse as described there
- [x]  Import the project into eclipse
- [x]  Run junit tests.
- [x] Start working on TDD.

**Comment by yossigil** [comment]
THis hasn't been announced yet.

**Comment by AviadCo** [comment]
I started it before it was announced :)

**Comment by yossigil** [comment]
👑
