### ISSUE TITLE
Karma and Todos for Yarden Lev

### ISSUE THREAD

**Issue by ylevv** [SpartanRefactoring/Spartanizer#598]
duplicates #330 
- [x]  Use a picture, photo or distinct avatar. Don't use an automatic icon
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page;
- [x]  State that you are (not) in search for a job

**Comment by ylevv** [comment]
@yossigil Done?

**Comment by RonGatenio** [comment]
This is a beautiful karma page. Good job! 😸 👍

**Comment by yossigil** [comment]
Cleanup the contents so that only the todos are there.
Add milestone and quality and teaching labels.
Use full name in link.

**Comment by geniashand** [comment]
great page 👍 🍡 
You're invited to check mine

**Comment by SapirBismot** [comment]
Your Karma Page is very nice 💯 
#612

**Comment by SharonKL** [comment]
not bad 👍 
#614

**Comment by yossigil** [comment]
OK didn't notice that

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Elderly-Support#12
