### ISSUE TITLE
Karma and Todos for Nikita Dizhur

### ISSUE THREAD

**Issue by nikitadizhur** [SpartanRefactoring/Spartanizer#599]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon.
- [x]  Make sure you present yourself by a readable **nick**.
- [x]  Describe yourself in the bio page; FYI, here is my description.
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box.
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box.

**Comment by nikitadizhur** [comment]
@YossiGil: Done.

**Comment by yossigil** [comment]
Cleanup the issue, leaving only the todos. 
use teacihing and quality assurance labels
Set milestones

**Comment by Lidkin5** [comment]
Nice karma page :+1:

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Internet-Browser-Plugin#3
