### ISSUE TITLE
Karma and Todos for Yevgenia Shandalov

### ISSUE THREAD

**Issue by geniashand** [SpartanRefactoring/Spartanizer#604]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description
- [x]  State that you are (not) in search for a job

**Comment by geniashand** [comment]
@yossigil Done!

**Comment by ylevv** [comment]
Good looking Karma Page 😄

**Comment by SapirBismot** [comment]
**# Genia**
_This is a beautiful karma page._ 
#612

**Comment by yosefraisman** [comment]
@geniashand, your karma page is possibly the prettiest thing on GitHub right now. Mine isn't bad either (#616)!

**Comment by yossigil** [comment]
Keep this one open

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Info-Evaluation#8
