### ISSUE TITLE
Bismot, Sapir: TODOs

### ISSUE THREAD

**Issue by SapirBismot** [SpartanRefactoring/Spartanizer#612]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by SapirBismot** [comment]
@YossiGil: Done.

**Comment by ylevv** [comment]
Nice Karma Page :+1:

**Comment by RonGatenio** [comment]
Beautiful page! 👍

**Comment by leyaniv** [comment]
best karma page ever! what do you think of #627?

**Comment by AdiOmari** [comment]
👍 , 
- [ ] Add teaching and quality assurance labels. 
- [ ] Assign yourself (you can do it once you are invited to the project after doing assignment 0)

**Comment by OmriBS** [comment]
Karma be upon you

**Comment by yossigil** [comment]
Please do not forget to tag commits with the issue you work on

**Comment by SapirBismot** [comment]
Summary of issues by that point:
last week:
#877 #450 
#451 (not completed yet)
previous weeks:
#234 #706 #850 #852

**Comment by yossigil** [comment]
If there is any update in this project the past 12 days, this is the time to add it :-)
