### ISSUE TITLE
Karma and Todos for Yonatan Zarecki

### ISSUE THREAD

**Issue by yonzarecki** [SpartanRefactoring/Spartanizer#613]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon
- [x]  Make sure you present yourself by a readable nick
- [x] Describe yourself in the bio page
- [x] State that you are (not) in search for a job

**Comment by yosefraisman** [comment]
Something about your karma page really speaks to me, @yonzarecki. Please tell me what you think about #616

**Comment by AviadCo** [comment]
Great Job :) You can view mine if you want: #528

**Comment by ZivIzhar** [comment]
great page : D
here's mine : #644

**Comment by yonzarecki** [comment]
Done. @yossigil

**Comment by yossigil** [comment]
:100:

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Bugquery#5
