### ISSUE TITLE
Karma and Todos for Sharon Kuninin

### ISSUE THREAD

**Issue by SharonKL** [SpartanRefactoring/Spartanizer#614]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box

**Comment by SharonKL** [comment]
@YossiGil: Done.

**Comment by yosefraisman** [comment]
@SharonKL, your karma page truly is astounding, hope you get a chance to look at mine! #616

**Comment by RonGatenio** [comment]
This is a great page Kuninin. Good job! 👍

**Comment by EliaTraore** [comment]
what a lovely page 😍 check out mine #694

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Elderly-Support#11
