### ISSUE TITLE
Karma and Todos for Yosef Raisman

### ISSUE THREAD

**Issue by yosefraisman** [SpartanRefactoring/Spartanizer#616]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon
- [x]  Make sure you present yourself by a readable nick
- [x]  Describe yourself in the bio page
- [x]  State that you are (not) in search for a job

**Comment by yosefraisman** [comment]
@YossiGil: Done.

**Comment by SharonKL** [comment]
One of the best karma pages I have ever seen, well done!

**Comment by AviadCo** [comment]
Great karma page bro ;)

**Comment by yonilx** [comment]
This is amazing yosef !

**Comment by yonzarecki** [comment]
I knew the best karma page would come last !

**Comment by ZivIzhar** [comment]
meow meow mitsi meow? karmeow

**Comment by Roei-m** [comment]
Solid karma page, well done 👍

**Comment by Shahar-Y** [comment]
great karma page! visit mine at: #665

**Comment by roy-shchory** [comment]
im contacting you in regards of your awsome band! we would like to sign you! this is totaly not a scam!
for the details go to #621

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Bugquery#4
