### ISSUE TITLE
setting up the working environment of Yarden Lev and Sharon Kuninin

### ISSUE THREAD

**Issue by SharonKL** [SpartanRefactoring/Spartanizer#617]
The working environment for this project includes
- [x] Linux
- [x] Eclipe Neon
- [x] Java 8 Programming
- [x] Formatting conventions
- [x] Spartan programming
- [x] Fixed cleanup routine
- [x] Highest level of warning settting
- [x] Git command line
- [x] Telegram (might be changed by another messaging application)

**Comment by SharonKL** [comment]
@yossigil Should I create the Exercise label?

**Comment by yossigil** [comment]
no

**Comment by zvili** [comment]
If you finished the tasks, close the issue ASAP; #614
