### ISSUE TITLE
Karma and Todos for Amir Sagiv

### ISSUE THREAD

**Issue by amirsagiv83** [SpartanRefactoring/Spartanizer#619]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by amirsagiv83** [comment]
@YossiGil: Done.

**Comment by inbalzukerman** [comment]
Nice Karma page :+1: 
Check out mine #684  :)

**Comment by Shahar-Y** [comment]
All other karma pages are stale and pale compering yours, oh great Sagiv!
Ihumbly request that you visit mine at #665

**Comment by EliaTraore** [comment]
yo ho check that out #694
nice page btw 👌

**Comment by RonGatenio** [comment]
What a beautiful page! Have some karma 🌟 🌠 ❇️ 🎇 ✨  🌠 ❇️🌟 🌠 ✨  
Now you have to give me some karma back #584... Those are the rules

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/IntelliJ-Spartanizer#9
