### ISSUE TITLE
Karma and Todos for Roy Shchory

### ISSUE THREAD

**Issue by roy-shchory** [SpartanRefactoring/Spartanizer#621]
- [x]  Use a picture, photo or distinct avatar.
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page 
- [x]  State that you are not in search for a job

**Comment by roy-shchory** [comment]
@yossigil Done.

**Comment by RonGatenio** [comment]
What an amazing page 
It's so beautiful! 
Here is mine: #584

**Comment by ZivIzhar** [comment]
Woo even shushi in this page
Here's mine #644

**Comment by yosefraisman** [comment]
Roy, you are making my dreams come true!

Here's my new and updated bucket list:
* High five a musician I like (Paul Simon, for example).
* ~~Visit the most beautiful karma page ever made.~~
* Attend a Technion lecture that's being recorded.
* See the Northern Lights.

Please visit my page too (it's over here #616)

**Comment by inbalzukerman** [comment]
Nice Karma pageee 😄 
Check out mine: #684

**Comment by EliaTraore** [comment]
brother from another motherrrr 💯 👌 
check this page its lit af #694

**Comment by RonGatenio** [comment]
I'm here for Emma's number...  But I think you lied 😢

**Comment by Shahar-Y** [comment]
I am here to bask at the greatness and awesomeness of your karma page. Not disappointed. 
#665 and stuff.

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Elderly-Support#10
