### ISSUE TITLE
Raz, Roei: TODOs

### ISSUE THREAD

**Issue by RoeiRaz** [SpartanRefactoring/Spartanizer#623]
- [x]  Use a picture, photo or distinct avatar.
- [x]  Make sure you present yourself by a readable nick
- [x]  Describe yourself in the bio page.
- [x]  State that you are (not) in search for a job.

**Comment by Roei-m** [comment]
@YossiGil: Done.

**Comment by AviadCo** [comment]
Great Job :) You can view mine if you want: #528

**Comment by yosefraisman** [comment]
Roei, your karma page is the single greatest achievement of mankind since the Apollo 11 spacecraft landed on the moon. It's the best. Please take a look at mine (#616), it's pretty great too!

**Comment by ArthurSap** [comment]
Roei, L2P nub volt
Check out mine (#647)!

**Comment by orimarco** [comment]
@Roei-m did you foget to _Describe yourself in the bio page_?

**Comment by Shahar-Y** [comment]
OHHHH MYYYY GOSHHHH
BEST KRMA PAGE EVERRRRRRR
Never have I ever seen such greatness and inspiration- concentrated into a single page of awesomeness.
Roei, you are my role model and my reason to live!!

**Comment by yossigil** [comment]
Your user name is Roei-m while your Karma page is Roei R. Is this true? if so, please fix ASAP. it is hard to find you. @zvili @idabran :FYI.

**Comment by yossigil** [comment]
Bad Karma: Todos are still there.

**Comment by yossigil** [comment]
I fixed your title to reflect your user name. K--
