### ISSUE TITLE
Afek, Oren: TODOs.

### ISSUE THREAD

**Issue by orenafek** [SpartanRefactoring/Spartanizer#624]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon.
- [x]  Make sure you present yourself by a readable **nick**.
- [x]  Describe yourself in the bio page.
- [x]  State that you are (**not**) in search for a job.

**Comment by orenafek** [comment]
@orimarco

**Comment by RonGatenio** [comment]
Nice page Oren! Good job 👍 😃

**Comment by inbalzukerman** [comment]
Pretty Karma page 😄 😘 
(Or not?)

Check mine - #684

**Comment by yossigil** [comment]
:+1:

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/IntelliJ-Spartanizer#8
