### ISSUE TITLE
setting up the working environment of Anna Belozovsky and Michal Cohen

### ISSUE THREAD

**Issue by michalcohen** [SpartanRefactoring/Spartanizer#625]
The working environment for this project includes
- [x] Linux
- [x] Eclipe Neon
- [x] Java 8 Programming
- [x] Formatting conventions
- [x] Spartan programming
- [x] Fixed cleanup routine
- [x] Highest level of warning settting
- [x]  Git command line
- [x] Telegram (might be changed by another messaging application)

**Comment by zvili** [comment]
If you finished the tasks, close the issue ASAP; #564 #565
