### ISSUE TITLE
Karma and Todos for Yaniv Levinsky

### ISSUE THREAD

**Issue by leyaniv** [SpartanRefactoring/Spartanizer#627]
- [x]  Use a picture, photo or distinct avatar.
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page
- [x]  State that you are (not) in search for a job

**Comment by SapirBismot** [comment]
_very beautiful karma page 👍_

**Comment by leyaniv** [comment]
@YossiGil: Done

**Comment by OmriBS** [comment]
Karma be upon you

**Comment by yossigil** [comment]
No milestone, no lables -> bad Karma

**Comment by yossigil** [comment]
@zvili : please move to student's current repo
