### ISSUE TITLE
setting up the working environment of Kfir Marx and Raviv Rachmiel

### ISSUE THREAD

**Issue by kfir-marx** [SpartanRefactoring/Spartanizer#628]
The working environment for this project includes
- [x] Linux
- [x] Eclipe Neon
- [x] Java 8 Programming
- [ ] Formatting conventions
- [ ] Spartan programming
- [ ] Fixed cleanup routine
- [ ] Highest level of warning settting
- [x]  Git command line
- [x] Telegram (might be changed by another messaging application)

**Comment by yossigil** [comment]
How come this is open? @zvili, FYI

**Comment by yossigil** [comment]
#516 #519 ????
