### ISSUE TITLE
Karma and Todos for Moshe Eliasof

### ISSUE THREAD

**Issue by MosheEliasof** [SpartanRefactoring/Spartanizer#632]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page;
- [x]  State that you are (not) in search for a job,

**Comment by NetanelFelcher** [comment]
awesome 💯 
check out mine #633

**Comment by AviadCo** [comment]
Great Job :) You can view mine if you want: #528

**Comment by yossigil** [comment]
:+1:

**Comment by AdiOmari** [comment]
👍 , Two things:
- [ ] Add teaching and quality assurance labels.
- [ ] Assign yourself

**Comment by MosheEliasof** [comment]
@AdiOmari  Hi , thank you for checking my TODOS. 
I'm having a problem though - I can't assign myself or add any labels for some reason. Could you help me please ?

**Comment by yossigil** [comment]
It was all posted on the facebook and in the course material. You are expected to be independent find the answer there.

**Comment by AdiOmari** [comment]
@MosheEliasof  Try now

**Comment by yossigil** [comment]
Bad karma again: 
![image](https://cloud.githubusercontent.com/assets/12775400/20176669/8111cf8a-a751-11e6-973b-8b95afc4851c.png)

Your user name is not recognized for some reason. 
See e.g. here: https://github.com/SpartanRefactoring/Spartanizer/commit/a2f202d3b34430bae1fb0adb3392d2db820029a7

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Info-Evaluation#7
