### ISSUE TITLE
Karma and Todos for Netanel Felcher

### ISSUE THREAD

**Issue by NetanelFelcher** [SpartanRefactoring/Spartanizer#633]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by NetanelFelcher** [comment]
@yossigil  Done

**Comment by MosheEliasof** [comment]
awesome 💯 
check out mine #632

**Comment by yossigil** [comment]
:+1:

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Info-Evaluation#6
