### ISSUE TITLE
foo

### ISSUE THREAD

**Issue by DavidCohen55** [SpartanRefactoring/Spartanizer#638]
Hiiiiii
David Cohen

**Comment by DavidCohen55** [comment]
#328

**Comment by AdiOmari** [comment]
👍, assign yourself (must be invited to the project, after doing assignment 0)

**Comment by yossigil** [comment]
#639 how come this is still open? I am closing this for you. Do not leave issues hanging out there.

@zvili @idabran @yh-github FYI.
