### ISSUE TITLE
Karma and Todos for David Cohen

### ISSUE THREAD

**Issue by DavidCohen55** [SpartanRefactoring/Spartanizer#639]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by DavidCohen55** [comment]
@yossigil: Done. I can't assign myself

**Comment by assaflu** [comment]
I liked your issue, i would appriciate if you would chek mine #640

**Comment by rodedzats** [comment]
💯 mem 
come to #656

**Comment by sefialbo** [comment]
Cool issue, check mine: #666

**Comment by shaysegal** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7897753-204257602_3-s4-v1.png?transparent=1&width=246)

**Comment by AdiOmari** [comment]
Add teaching and quality assurance labels. To assign yourself you must be invited to the project, which is done once you do assignment 0.

**Comment by Shahar-Y** [comment]
The only way I can describe the feeling I had while first entering David's karma page is by asking you to imagine diving into an endless ocean. And in this ocean, the water is made of pure happiness; the fish are the most colourful and life-like comments of the people supporting the page. The corals are made of David's amazing personality, wich holds together this entire world he created. 
I know in my heart, that this is a sanctuary of peace and quite for when the worries and fears of the world seem to be crushing your soul.
I will never get tired of wisiting this page. For me,  #639 has become a number representing all that is good in this world.


Also, check out mine at #665 :)

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-ParkingManagement#9
