### ISSUE TITLE
Karma and Todos for Assaf Lustig

### ISSUE THREAD

**Issue by assaflu** [SpartanRefactoring/Spartanizer#640]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by assaflu** [comment]
@yossigil : Done. I can't assign myself

**Comment by DavidCohen55** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/8139922-202779545_1-s4-v1.png?transparent=1&width=246)
nice page

I would appreciate feedback on my page #639

**Comment by rodedzats** [comment]
wow assaf pashut wow. come to my page #656

**Comment by tomerdragucki** [comment]
Hi Assaf! What a nice Karma page you got.
Come visit mine at #655 
🍾

**Comment by yossigil** [comment]
Bad:

You did not assign yourself,
No labels
No milestone
You did not edit the issue

Poor job.

Correct completely. Don't mention me until you have corrected all this.

**Comment by assaflu** [comment]
@yossigil Done.

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Accessibility#9
