### ISSUE TITLE
Karma and Todos for Ziv Izhar

### ISSUE THREAD

**Issue by ZivIzhar** [SpartanRefactoring/Spartanizer#644]
- [X]  Use a picture, photo or distinct avatar. Don't use an automatic icon
- [X]  Make sure you present yourself by a readable nick
- [X]  Describe yourself in the bio page;
- [X]  State that you are (not) in search for a job

**Comment by ZivIzhar** [comment]
@yossigil Done. (accidently changed the name before mentioning)

**Comment by yonzarecki** [comment]
Good job :D

**Comment by yosefraisman** [comment]
Your page is the Chuck Norris of karma pages, Ziv. Well done!
If you'd like, please check out mine - it's not too shabby either! (#616)

**Comment by RonGatenio** [comment]
Nice page Ziv! Have some karma:  🎇 ❇️ 🌟 ✨  🌠  🎇 ❇️ 🌟 ✨  🌠 🎇 ❇️ 🌟 ✨  🌠

**Comment by roy-shchory** [comment]
came here to check if you were doing anything.
#ziv_do_something_with_your_self
if you want a guide for doing stuff go to #621

**Comment by Shahar-Y** [comment]
Your karma page is truely a masterpiece.
Visit mine at #665

**Comment by yossigil** [comment]
@zvili : please move to student's current repo

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Bugquery#11
