### ISSUE TITLE
Karma and Todos for Arthur Sapozhnikov

### ISSUE THREAD

**Issue by ArthurSap** [SpartanRefactoring/Spartanizer#647]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by ArthurSap** [comment]
@YossiGil: Done.

**Comment by yaelAmitay** [comment]
Arthur, I like your page! :]
here's my karma page: #652

**Comment by Roei-m** [comment]
Arthur, this karma page is the best achievement in your life so far. Good job!

**Comment by yossigil** [comment]
I hope not 😃

**Comment by Shahar-Y** [comment]
Arthur, great karma page! visit mine at #665

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Accessibility#8
