### ISSUE TITLE
Karma and Todos for Yael Amitay

### ISSUE THREAD

**Issue by yaelAmitay** [SpartanRefactoring/Spartanizer#652]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by yaelAmitay** [comment]
@YossiGil: Done.

**Comment by tomerdragucki** [comment]
Nice Karma page! I hope Economics exam was good 💯

**Comment by yossigil** [comment]
Good job. Keep the page open

**Comment by Shahar-Y** [comment]
Great karma page! 
BTW, I have failed to find schizophrens who contributed to the mankind.
You win :(
#665 and stuff..

**Comment by yaelAmitay** [comment]
@Shahar-Y  thanks but i didn't said that...

**Comment by inbalzukerman** [comment]
Nice Karma page 😄 😘 
Check mine: #684

**Comment by yossigil** [comment]
Add quality assurance label

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Accessibility#7
