### ISSUE TITLE
Karma and Todos for Roded Zats

### ISSUE THREAD

**Issue by rodedzats** [SpartanRefactoring/Spartanizer#656]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by rodedzats** [comment]
@YossiGil: Done.

**Comment by tomerdragucki** [comment]
Hello friend, I liked your bio!

**Comment by Shahar-Y** [comment]
Awesome karma page! LOVED the Hello Kitty theme!
#665

**Comment by AdiOmari** [comment]
@rodedzats  Add teaching and quality assurance labels. Other than that, looks good 👍

**Comment by yossigil** [comment]
@zvili : please move to student's current repo

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Bugquery#10
