### ISSUE TITLE
Karma and Todos for Idan Atias

### ISSUE THREAD

**Issue by IdanAtias** [SpartanRefactoring/Spartanizer#659]
- [x]  Make sure you present yourself by a readable nick
- [x]  Describe yourself in the bio page
- [x]  State that you are (not) in search for a job
- [x]  Connect to the host repo

**Comment by IdanAtias** [comment]
@YossiGil: Done.

**Comment by AviadCo** [comment]
Great Job my friend! you have good karma :+1: 
my karma is #528

**Comment by LiorBenAmi** [comment]
Good Karma dude! 💯 
these is mine : #772

**Comment by yossigil** [comment]
Labels? Deadeline?  Who is the assignee? 
Karma -= 10

**Comment by yossigil** [comment]
@zvili @idabran @yh-github @AdiOmari @orimarco

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Market#3
