### ISSUE TITLE
Karma and Todos for Shahar Yair

### ISSUE THREAD

**Issue by Shahar-Y** [SpartanRefactoring/Spartanizer#665]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by Shahar-Y** [comment]
@YossiGil: Done.

**Comment by yosefraisman** [comment]
I feel sorry for whoever's going to invent time travel, because no accomplishment could ever compete with this original and, quite frankly, thought-provoking karma page. It's great.

**Comment by RoeyMaor** [comment]
I sincerely think your karma is amazing.
take a quick look at mine: #670

**Comment by EliaTraore** [comment]
"greatness" yeah right.

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-ParkingManagement#8
