### ISSUE TITLE
Karma and Todos for Sefi Albo

### ISSUE THREAD

**Issue by sefialbo** [SpartanRefactoring/Spartanizer#666]
- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon.
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page;
- [x]  State that you are (not) in search for a job

**Comment by sefialbo** [comment]
@yossigil Done.

**Comment by RoeyMaor** [comment]
You should definitely keep up the good work.
you might want to visit: #670

**Comment by dshames** [comment]
:dancer: 
my karma page #790

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-ParkingManagement#7
