### ISSUE TITLE
Roey Maor: TODOs

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Spartanizer#670]
- [x]  Use a picture, photo or distinct avatar
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page
- [x]  State that you are (not) in search for a job

**Comment by RoeyMaor** [comment]
@YossiGil: Done.

**Comment by RoeyMaor** [comment]
I sincerely think your karma is amazing.
take a quick look at mine: #670

**Comment by Shahar-Y** [comment]
As I ckicked on the link to youe page, I experienced a swirling of the most warm and embracive feeling while I entered the realm of calmness and acceptence. 
Here, I feel at home. This is a place I want to spend my time at. 
Roei, your karma page is one of the most relaxed and yet, inspiring places.
May all karma pages be as amazing as yours.
I am now at peace.

**VISIT MINE AT** #665 !!!!! (please)
@RoeyMaor <3 4ever

**Comment by DavidCohen55** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7681590-202779545_1-s4-v1.png?transparent=1&width=246)
This is one of the best Karma pages I have ever seen
keep up the good work
Also visit mine #639

**Comment by ArthurSap** [comment]
This karma page seems lacking as there is a typo in your name.

**Comment by Roei-m** [comment]
Here's what I think about your karma page:
![shutaf_karma](https://cloud.githubusercontent.com/assets/7161024/19878688/9372e394-9ff4-11e6-89ec-2ef380269479.PNG)
check out #623

**Comment by RoeyMaor** [comment]
thanks everyone!

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/IntelliJ-Spartanizer#12
