### ISSUE TITLE
Karma and Todos for Vivian Shehadeh

### ISSUE THREAD

**Issue by viviansh** [SpartanRefactoring/Spartanizer#674]
- [x]  Use a picture, photo or distinct, familiar, personal 
- [x] Present yourself by a not too rude **nick**  
- [x]  Describe yourself in the bio page; 
- [x]  State that you are (not) in search for a job
- [x]  State that you are (not) in search for a job

**Comment by viviansh** [comment]
@YossiGil: Done.

**Comment by AdiOmari** [comment]
👍 , Add teaching and quality assurance labels. Edit the content of the main issue, to remove the junk (examples and tables). Just leave the checked todos in it.

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Info-Evaluation#9
