### ISSUE TITLE
TDD: Count statements in an ASTNode

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#675]
A function named 

``` Java
public int statements(ASTNode n);
```
Which:
- takes a single parameter, which is an `ASTNode`.
- returns an `int` which is the number of expressions in `n`.

This function is to be implemented as a static member of `tdd.enumerate`.

**Comment by orimarco** [comment]
@AviadCo @noamyft why is issue still open?!

**Comment by AviadCo** [comment]
we finished the issue 5 days ago, didn't want to close it before your approval...

issue closed
