### ISSUE TITLE
TDD: Count methods in a CompilationUnit

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#679]
A function named 

``` Java
public int methods(CompilationUnit cu);
```
Which:
- takes a single parameter, which is a `CompilationUnit`.
- returns an `int` which is the number of methods in `cu`.

This function is to be implemented as a static member of `tdd.enumerate`.

**Comment by orimarco** [comment]
@ylevv @SharonKL why is issue still open?!

**Comment by yossigil** [comment]
Check that the tests are still meaningul, since the code changed.

**Comment by SharonKL** [comment]
We went through the changes and believe the tests are still relevant
