### ISSUE TITLE
Karma and Todos for Amit Ohayon

### ISSUE THREAD

**Issue by AmitOhayon** [SpartanRefactoring/Spartanizer#680]
- [x]  Use a picture, photo or distinct, familiar, personal 
avatar. Don't use an automatic icon (we need this to be able to identify you in the tens of students we have):

| Example | Score | Why? |
| --- | --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142710/39a00e24-8ba8-11e6-9971-da4e2f3b67c7.png) | Bad | Vague |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142719/472644c8-8ba8-11e6-8061-f152156545dd.png) | OK | Reasonably identifying |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142724/5a508a04-8ba8-11e6-80e4-25cff412acc9.png) | Huh? | Monkey? |
| | Example | Score | Why? |
| --- | --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142710/39a00e24-8ba8-11e6-9971-da4e2f3b67c7.png) | Bad | Vague |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142719/472644c8-8ba8-11e6-8061-f152156545dd.png) | OK | Reasonably identifying |
| ![image](https://cloud.githubusercontent.com/assets/12775400/19142724/5a508a04-8ba8-11e6-80e4-25cff412acc9.png) | Huh? | Monkey? |
|![image](https://cloud.githubusercontent.com/assets/12775400/19851642/9db66d36-9f67-11e6-8615-2a087b9d3b66.png) | Terrible | GitHub auto generated | | Terrible | GitHub auto generated |

If you have an issue with privacy, talk to the staff. We are usually reasonable.

- [x] Present yourself by a not too rude **nick**  

| Example | Score | Why? |
| --- | --- | --- |
| `Moshe Levy II` | Super | Clear identification |
| `YossiGil` | Very Good | You identify yourself by full name |
| `IDabran` | Very Good | == **I**tai **Dabran** |
| `YossiG` | Very Good | == **Yossi** **G**il |
| `rms`    | Good | == **R**ichard **M**. **S**tallman | 
| `yogi` | OK | Well known nick |
| `j1046` | Bad | Who the hell are  you? |
| `zm&4jk` | Worse | Not even pronounceable |
| `r2d2` | Terrible | We are not playing games here |
| `ghost` | Disaster | Are you a troll or what? |

    Summary:
      - Fine: `yogi`  (**Yo**ssi **G**il), `idarban` (**I**tai **D**arban)
      - Not so fine: `j1046` / `r2d2` / `bb8` / `biscuit` / `the destroyer`/`nukethem69h7`

    (Again, we need this to be able to identify you in personal meetings. If someone feels the bear with basket is the best representation of his identity, so be it. If someone presents herself the *Mac Apple Icon*? Not so sure.)
- [x]  Describe yourself in the bio page; FYI, here is my description:
  ![image](https://cloud.githubusercontent.com/assets/12775400/19105201/753bb934-8ae9-11e6-8f63-659f5c14162e.png)
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
  ![image](https://cloud.githubusercontent.com/assets/12775400/19105155/3554e8cc-8ae9-11e6-8915-a180075388b1.png)

**Comment by AmitOhayon** [comment]
@YossiGil: Done.

**Comment by tonylekhtman** [comment]
Awesome Page!

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/Bugquery#2
