### ISSUE TITLE
TDD: Find ancestor method of an ASTNode

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#681]
A function named 

``` Java
public MethodDeclaration ancestorMethod(ASTNode n);
```
Which:
- takes a single parameter, which is an `ASTNode`.
- returns a `MethodDeclaration ` which is the containing method of `n`.

This function is to be implemented as a static member of `tdd.find`.

**Comment by shaysegal** [comment]
@orimarco can you give us an example of how do we get ASTNode that the method deceleration is not itself or null ?

**Comment by shaysegal** [comment]
@orimarco is astNode which the root is a method should be the ancestor MethodDecleration of itself or should we look in the parents 
for example  if the tree is :
void func1(){
    class A{
          void func2(){
          }
    }
}
and the astNode we get is  void func2(){}

**Comment by shaysegal** [comment]
@orimarco does lambda expression considered is MethodDeclaraion?

**Comment by orimarco** [comment]
No
