### ISSUE TITLE
TDD: Find ancestor type of an ASTNode

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#683]
A function named 

``` Java
public TypeDeclaration ancestorType(ASTNode n);
```
Which:
- takes a single parameter, which is an `ASTNode`.
- returns a `TypeDeclaration` which is the containing type of `n`.

This function is to be implemented as a static member of `tdd.find`.

**Comment by michalcohen** [comment]
@orimarco - I accidently pushed "clear assignees" - added you right back!
@dormaayan - Do you still use this issue?

**Comment by dormaayan** [comment]
@michalcohen : No, that issue is all yours now... (:

**Comment by yossigil** [comment]
Michal #564 and Anna #565: you could contains warnings, this is bad Karma

**Comment by AnnaBel7** [comment]
@orimarco : If I have class B inside class A, what should the function return if it is called with B? B itself or A?

**Comment by orimarco** [comment]
A

**Comment by AnnaBel7** [comment]
@orimarco : so if the function is called with A it will return null?

**Comment by orimarco** [comment]
Yep
