### ISSUE TITLE
Karma and Todos for Inbal Zukerman

### ISSUE THREAD

**Issue by inbalzukerman** [SpartanRefactoring/Spartanizer#684]
- [x]  Use a picture, photo or distinct, familiar, personal 
avatar. 
- [x] Present yourself by a not too rude **nick**  
- [x]  Describe yourself in the bio page
- [x]  State that you are (not) in search for a job

**Comment by inbalzukerman** [comment]
@YossiGil: Done.

**Comment by amirsagiv83** [comment]
OMG. I think this Karma page is one of the most amazing things I have ever seen!

you should check out mine. please. I'm begging. #619

**Comment by Shahar-Y** [comment]
Wow! Inbal's karma page!! 
What more can life offer me, now that iv'e seen it?

Visit mine at #665

**Comment by roy-shchory** [comment]
this page is almost as holy as jerusalem.
for entertaiment please enter #621

**Comment by yaelAmitay** [comment]
this karma page is amazing! :)

**Comment by RonGatenio** [comment]
This is the most beautiful karma page here. Great job! 👍

**Comment by AdiOmari** [comment]
👍 looks good. Add teaching and quality assurance labels.

**Comment by yossigil** [comment]
![image](https://cloud.githubusercontent.com/assets/12775400/20240260/c37e9d68-a91c-11e6-85b1-99f00bd13221.png)

**Comment by yossigil** [comment]
I could not find your personal TODOs becuas you are not listed as the assiggnee for this issue.

**Comment by inbalzukerman** [comment]
@yossigil - I'm sorry, i didn't really got in hand with those github functionalities when i opened the issue. I added myself as an assignee right now.

**Comment by yossigil** [comment]
As long as we follow a positive gradient ...

**Comment by inbalzukerman** [comment]
Unfortunately every time i try to change a parameter name (not to be d) the Spartanizer fixes it to be d again which causes the warning. Should i not accept the Spartanizer's tip?

**Comment by inbalzukerman** [comment]
![image](https://cloud.githubusercontent.com/assets/23147895/20240359/08d386b0-a91f-11e6-9b40-5d723b714ed5.png)

**Comment by yossigil** [comment]
Ok, I fixed this for you. Take a look. Also, if you check the file you modified, you will find a similar bug to the one you had. You could gain ooldles of good Karma by fixing the bug.
You can get even more Karma, if you identify commonalities and refactor.
@rodedzats @yonzarecki @ZivIzhar @EliaTraore

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Elderly-Support#5
