### ISSUE TITLE
TDD: get List of String variables in a MethodDeclaration

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#686]
A function named 

``` Java
public List<VariableDeclaration> stringVariables(MethodDeclaration m);
```
Which:
- takes a single parameter, which is an `MethodDeclaration `.
- returns a `List<VariableDeclaration>` which is all String variable declarations in  `m`.

This function is to be implemented as a static member of `tdd.getAll`.

**Comment by Kolikant** [comment]
good catch with the false Typing. again, can't find any major issues, adding a few necessary tests that should probably pass

**Comment by Kolikant** [comment]
deleated my workspace and built a new one --easy--

**Comment by orimarco** [comment]
Good work.
I get a warning from your code... better fix quickly!

**Comment by KaplanAlexander** [comment]
Warnings fixed and we are done
