### ISSUE TITLE
TDD: get List of names in a Block

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#687]
A function named 

``` Java
public List<Name> names(Block b);
```
Which:
- takes a single parameter, which is a `Block`.
- returns a `List<Name>` which is all names in  `b`.

This function is to be implemented as a static member of `tdd.getAll`.

You might want to take a look at [this](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FSimpleName.html).

**Comment by kfir-marx** [comment]
@orimarco  what exactly does it mean "Names in a block"?
for example, let's look at the following block:
{a=1;b=2+2;System.out.println(a);c=b;}
should the returned list be - [a,b,c]
or - [a,b,System,out,println,a,c,b]
?

**Comment by OriRoth** [comment]
In my opinion, the second option. Anyway the first one is invalid, because it does not contain `System`, `out` and `println` which are valid names.

**Comment by yossigil** [comment]
#516 and #519 : Bad Karma. You did not write your name on it.

**Comment by ravivos** [comment]
@yossigil Thanks for the notification.
Fixed, closing the issue again.
