### ISSUE TITLE
Karma and Todos for Koral Chapnik

### ISSUE THREAD

**Issue by koralchapnik** [SpartanRefactoring/Spartanizer#689]
- [x]  Use a picture, photo or distinct, familiar, personal 
avatar. Don't use an automatic icon (we need this to be able to identify you in the tens of students we have):
- [x] Present yourself by a not too rude **nick**  
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by koralchapnik** [comment]
@orimarco : Done

**Comment by RoeyMaor** [comment]
wonderful.
#670

**Comment by mdoron** [comment]
One of a kind. 
Check [mine](#709) out, but it would never be as good as yours.

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Accessibility#6
