### ISSUE TITLE
TDD: Finding all casts in a MethodDeclaration

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#690]
A function named 

``` Java
public List<CastExpression> casts(MethodDeclaration m);
```
Which:
- takes a single parameter, which is a `MethodDeclaration `.
- returns a `List<CastExpression>` which is all casts in  `m`.

This function is to be implemented as a static member of `tdd.getAll`.

You might want to take a look at [this](http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FCastExpression.html).

**Comment by Tomnof** [comment]
@yossigil  can you please elaborate what can we improve ?

**Comment by matityahuinba** [comment]
@orimarco : Do we need to count explicit casts only? Implicit casts also counts?

**Comment by orimarco** [comment]
@matityahuinba what do you mean by implicit casts?

**Comment by matityahuinba** [comment]
@orimarco for example-
int a = 100;
long b = a;
counts as cast?

**Comment by orimarco** [comment]
@matityahuinba no need for this right now.
If you finished working, close the issue.
