### ISSUE TITLE
TDD: Finding all different methods which are invoked from a MethodDeclaration

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#691]
A function named 

``` Java
public Set<String> invocations(MethodDeclaration m);
```
Which:
- takes a single parameter, which is a `MethodDeclaration `.
- returns a `Set<String>` which are all methods invoked in  `m`.

This function is to be implemented as a static member of `tdd.getAll`.

You might want to take a look at [this](http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FMethodInvocation.html).

**Comment by dormaayan** [comment]
@orimarco : Name isn't comparable, so using a Set here is a problem.
Should we use a List instead ?

**Comment by orimarco** [comment]
good point!
@dormaayan use strings of the names instead

**Comment by orimarco** [comment]
@OmriBS @dormaayan 

- [ ] rename Issue file name
- [ ] move file to be with all other issues

**Comment by dormaayan** [comment]
@orimarco : We think we are done here...
I close the Issue...

**Comment by orimarco** [comment]
- [ ] very good! move test to tdd package (under tests)
