### ISSUE TITLE
Karma and Todos for Elia Traore

### ISSUE THREAD

**Issue by EliaTraore** [SpartanRefactoring/Spartanizer#694]
- [X]  Use a picture, photo or distinct, familiar, personal 
avatar. Don't use an automatic icon (we need this to be able to identify you in the tens of students we have)
- [X] Present yourself by a not too rude **nick**  
- [X]  Describe yourself in the bio page; FYI, here is my description
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box

**Comment by EliaTraore** [comment]
@YossiGil: Done.

**Comment by roy-shchory** [comment]
cool page fam, very lit very tight
for bottle flip videos and worldstar highlights go to #621

**Comment by Shahar-Y** [comment]
Hello, Elia. 
I am here as summoned. 
May your karma page be as amazing as Inbal and Amir's. I have dubts, tho.
You are allowed to visit mine at #665 and admire its greatness. 
Live long and prosper

**Comment by RonGatenio** [comment]
You couldn't have done it better, this page is great! 😃

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Elderly-Support#4
