### ISSUE TITLE
setting up the working environment of Dan Abramovich and Assaf Lustig and Arthur Sapozhnikov

### ISSUE THREAD

**Issue by danabramovich** [SpartanRefactoring/Spartanizer#696]
The working environment for this project includes
- [x] Linux
- [x] Eclipe Neon
- [x] Java 8 Programming
- [x] Formatting conventions
- [x] Spartan programming
- [x] Fixed cleanup routine
- [x] Highest level of warning settting
- [x]  Git command line
- [x] Telegram (might be changed by another messaging application)

**Comment by zvili** [comment]
If you finished the tasks, close the issue ASAP; #553 #640
