### ISSUE TITLE
setting up the working environment of Yevgenia shandalov and Osher Hajaj

### ISSUE THREAD

**Issue by geniashand** [SpartanRefactoring/Spartanizer#698]
The working environment for this project includes
- [x] Linux
- [x] Eclipe Neon
- [x] Java 8 Programming
- [x] Formatting conventions
- [x] Spartan programming
- [x] Fixed cleanup routine
- [x] Highest level of warning settting
- [x]  Git command line
- [x] Telegram (might be changed by another messaging application)

**Comment by yossigil** [comment]
#682 #604: If you are done with this issue, and it seems as if you are, close it immediately.
@zvili @orimarco @AdiOmari @idabran @yh-github

**Comment by yossigil** [comment]
#604 : K--. When an issue is done, close it.

**Comment by yossigil** [comment]
#604, bad Karma for ignoring request. Same for #682 

@zvili @idabran #

**Comment by yossigil** [comment]
Comes a matter of grading @AdiOmari
