### ISSUE TITLE
setting up the working environment of Tom Nof, Inbal Matityahu and Or Troyaner

### ISSUE THREAD

**Issue by Tomnof** [SpartanRefactoring/Spartanizer#700]
The working environment for this project includes
- [x] Linux
- [x] Eclipe Neon
- [x] Java 8 Programming
- [x] Formatting conventions
- [x] Spartan programming
- [x] Fixed cleanup routine
- [x] Highest level of warning settting
- [x]  Git command line
- [x] Telegram (might be changed by another messaging application)

**Comment by ortroyaner** [comment]
מוכנים!
