### ISSUE TITLE
TDD: Finding all instanceof expressions in a MethodDeclaration

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#705]
A function named 

``` Java
public List<InstanceofExpression> instanceofs(MethodDeclaration m);
```
Which:
- takes a single parameter, which is a `MethodDeclaration `.
- returns a `List<InstanceofExpression>` which are all instanceofs in  `m`.

This function is to be implemented as a static member of `tdd.getAll`.

**Comment by orimarco** [comment]
@kobybs have you really committed a failing test?

**Comment by kobybs** [comment]
@orimarco do you mean the first commit who failed compilation? Or I did more than that?

**Comment by orimarco** [comment]
There are no compilation errors but your test fails...

**Comment by kobybs** [comment]
@orimarco tests should be comitted only after the source code is fixed to pass them?

**Comment by orimarco** [comment]
When we run the tests there should be no failures.
you can add add an `@Ignore` annotation before the test to ignore it.
