### ISSUE TITLE
TDD: get List of String variables in a MethodDeclaration 2

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#706]
A function named 

``` Java
public List<VariableDeclaration> stringVariables(MethodDeclaration m);
```
Which:
- takes a single parameter, which is an `MethodDeclaration `.
- returns a `List<VariableDeclaration>` which is all String variable declarations in  `m`.

This function is to be implemented as a static member of `tdd.getAll2`.

**Comment by orimarco** [comment]
@SapirBismot assign your team too!
Good luck!

**Comment by yossigil** [comment]
@leyaniv @SapirBismot : I erased your file since you ignore todos.

#612 #627

**Comment by yossigil** [comment]
@AdiOmari : no response form @leyaniv  and @SapirBismot

**Comment by yossigil** [comment]
Closing this, it is going nowhere.
