### ISSUE TITLE
TDD: get List of names in a Block 2

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#707]
A function named 

``` Java
public List<Name> names(Block b);
```
Which:
- takes a single parameter, which is a `Block`.
- returns a `List<Name>` which is all names in  `b`.

This function is to be implemented as a static member of `tdd.getAll2`.

You might want to take a look at [this](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FSimpleName.html).

**Comment by orimarco** [comment]
@mdoron @tomerdragucki come on, show me some tests!

**Comment by mdoron** [comment]
There was a problem with the project 2 hours ago, that's why you see a lot of commits about starting the issue...

**Comment by mdoron** [comment]
@orimarco Is it the right way to test Name-s?
We saw that you guys didn't implement "equals" for Name-s...

**Comment by OriRoth** [comment]
Comparing `Name`s by String value is good. Be sure to compare the Strings using `equals` as usual.
On the other hand you can test list content in more [organized way](http://stackoverflow.com/questions/3236880/assert-list-in-junit), maybe something like:
```Java
assertEquals(result, Arrays.asList("name1", "name2", "name3"));
```

**Comment by mdoron** [comment]
Tests will be fixed this evening with @tomerdragucki, grazie.

**Comment by yossigil** [comment]
#709 #655 #169. Your file was erased since it had to many warnings. Please redo it.
@orimarco @zvili @yh-github @AdiOmari @idabran

**Comment by OriRoth** [comment]
The original file had 2 unused imports, no proper @since / @year tag and unnecessary repress-warnings-javadoc.

**Comment by yossigil** [comment]
#707 #655 #169. Your file was erased for the third time!

You injected CR/LF into the system. You were instructed to use Linux unless you know what you do.

**Comment by yossigil** [comment]
Karma -= DELTA ;-) issue still open even though the deadline is past #169, #709 #655 

@orimarco @idabran : FYI
