### ISSUE TITLE
TDD: Ideas

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#708]
A function named 

``` Java
public boolean potentiallyNullable(MethodDeclaration m);
```
Which:
- takes a single parameter, which is a `MethodDeclaration `.
- returns true iff the method **explicitly** returns `null`.
- You are *not* required to check for **unreachable code** or **implicit null returns**.

This task *may* have some issue. Consider the following example:
```Java
Object f() {
  return new Object() {
    @Override public String toString() {
      return null;
    }
  };
}
```

==> `potentiallyNullable(f)` ~> ???...

How can we deal with those cases?...

*Relevant Documentation*:
- http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FClassInstanceCreation.html

**Comment by OriRoth** [comment]
@orimarco ???

**Comment by OriRoth** [comment]
A function named 

``` Java
public boolean unawareToNewAPI(MethodDeclaration m);
```
Which:
- takes a single parameter, which is a `MethodDeclaration `.
- returns true iff there are occasions in the method in which lambda expression can be used, but is not.
- detect uses of `Function`, `Supplier`, `Consumer` in [ClassInstanceCreation](http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FClassInstanceCreation.html)s.
- help a clueless programmer get used to this [new Java feature](https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html)!

Example:
```
int oneLarger(int x) {
  Function<Integer, Integer> f = new Function<Integer, Integer>() {
    @Override public Integer eval(Integer f) {
      return f + 1;
    }
  };
  return f.eval(x);
}
```

@orimarco ???

**Comment by OriRoth** [comment]
A function named 

``` Java
public boolean publicFields(TypeDeclaration m);
```
Which:
- takes a single parameter, which is a `TypeDeclaration`.
- returns a list of public fields for this class.

**Comment by OriRoth** [comment]
A function named 

``` Java
public boolean isImmutable(TypeDeclaration m);
```
Which:
- takes a single parameter, which is a `TypeDeclaration` (a class ast node).
- returns true iff the class contains only final fields.

@orimarco may be a bit messy... but the idea is simple, which is gut.

**Comment by OriRoth** [comment]
A function named 

``` Java
public boolean isEffectivelyFinal(MethodDeclaration m, String variableName);
```
Which:
- takes two parameters:
  - first is a `MethodDeclaration`.
  - second is a variable name.
- returns true iff there are no assignments *into* a variable with that name in this method.
- read about [effectively final](http://stackoverflow.com/questions/20938095/difference-between-final-and-effectively-final)!

Consider this:
```
void f() {
  int x = 1;
  x = 2;
}
```
==> `isEffectivelyFinal(f)` ~> true, because first statement does ***not*** contains an assignment.

**Comment by OriRoth** [comment]
A function named 

``` Java
public boolean isRedundant(Block b);
```
Which:
- takes a single parameter, which is a Block.
- returns whether or not this block is *redundant*, i.e. contains only empty statements/other redundant blocks.
- can be implemented either by using an `ASTVisitor` or recursively.

Example:
```
{
  ;
  {
    ;
    ;
  }
}
```
==> redundant.

**Comment by OriRoth** [comment]
A function named 

``` Java
public int blockTypes(MethodDeclaration m);
```
Which:
- takes a single parameter, which is a method.
- returns count of block "types" used. Different blocks are differ by their parents' types.

Example:
```
Object f() {
  {} // a block as a statement in a method
  {} // another one, does not count!
  Supplier<Integer> s = ()->{return 0}; // a block used in lambda expression
  if (false) {} // if statement block
  return new Object{}; // NOT a block but part of ClassInstanceCreation
}
```
==> `blockTypes(f)` ~> 3

**Comment by OriRoth** [comment]
A function named 

``` Java
public boolean isComplicated(MethodDeclaration m);
```
Which:
- takes a single parameter, which is a method.
- returns true iff the method is *complicated*.
- a method is *complicated* only if at least *2* of the following requirements applies to it:
  - contains at least 10 statements.
  - has an **inner** block containing at least 5 statements.
  - has more than 5 parameters.
  - defines more than 5 variables.

@orimarco may be tough though...

**Comment by orimarco** [comment]
@OriRoth do you argue that `x=2` keep `x` effectively final?
> Consider this:
> 
> void f() {
>   int x = 1;
>   x = 2;
> }
> ==> isEffectivelyFinal(f, "x") ~> true, because first statement does not contain an assignment.

**Comment by OriRoth** [comment]
Yea thats a mistake... well you can get the idea.
בתאריך 1 בנוב 2016 14:42, "Ori Marcovitch" <notifications@github.com> כתב:

**Comment by OriRoth** [comment]
A function named 

``` Java
public boolean isUsing(ASTNode node, String name);
```
Which:
- takes two parameters:
  - an ASTNode node
  - a String name
- return true iff the name is used in the node as a `Name`

@AmitOhayon

**Comment by geniashand** [comment]
@orimarco 

@osherh and I would like to do the blockTypes method.

**Comment by OriRoth** [comment]
@geniashand you can have a simpler exercise:
* An existing exercise, then @orimarco can duplicate it to another issue
* A new exercise you come up with

**Comment by OriRoth** [comment]
A function named 

``` Java
public boolean isConventional(ASTNode node);
```
Which:
- takes a single parameter, which is a ASTNode.
- returns true iff this sub ASTree is written by Java's conventions, i.e.:
  - all variables' and parameters' names start with small letter
  - *thats enough*

@geniashand

**Comment by OriRoth** [comment]
A function named 

``` Java
public boolean containsUnused(MethodDeclaration node);
```
Which:
- takes a single parameter, which is a MethodDeclaration.
- returns true iff the method does not use one of its parameters.
- parameters are identified by their names

Thus true is returned even for the following cases:
```Java
void f(int x) {
  x();
}
```
```Java
void f(int x) {
  new Object() {
    int x;
    void f() {
      g(x);
    }
  };
}
```

**Comment by yonzarecki** [comment]
@orimarco We would like work on the containsUnused method
