### ISSUE TITLE
TDD: Determine whether a method returns null

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#710]
A function named 

``` Java
public boolean returnsNull(MethodDeclaration m);
```
Which:
- takes a single parameter, which is a `MethodDeclaration `.
- returns true iff the method contains a `return null ` statement .

This function is to be implemented as a static member of tdd.determineIf.

**Comment by orimarco** [comment]
Beware!
A naive solution might determine the following function as `true` although it does not return null:
```Java
Object f() {
  return new Object() {
    @Override public String toString() {
      return null;
    }
  };
}
```

**Comment by OriRoth** [comment]
Also consider:
```Java
Supplier<Integer> f() {
  return () -> {
    return null;
  };
}
```

*Clue*:
As the examples above shows, there can be rogue `return null` statements in `AnonymousClassDeclaration`s and `LambdaExpression`s. Thus you get two options:
1. When detecting a `return null` statement, check if one of its ancestors (up to original method node) is a `AnonymousClassDeclaration` or `LambdaExpression`.
2. When conducting recursive search in sub tree, do not go into `AnonymousClassDeclaration` or `LambdaExpression` nodes.

**Comment by zahimizrahi** [comment]
We are finished in time. @Shahar-Y  @DavidCohen55  @OriRoth  @orimarco  Thank you for all the help!
