### ISSUE TITLE
Inlining of lambda expression fails

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#711]
```
int oneLarger(int x) {
  Function<Integer, Integer> f = i -> i + 1;
  return f.eval(x);
}
```
==>
```
int oneLarger(int x) {
  return i->i + 1.eval(x);
}
```

@yossigil FYI. My first issue as a regular user! 🎉 
I could not find a way to inline lambda expressions that way though :| it refuses to compile.

**Comment by yossigil** [comment]
Please pass on

**Comment by dormaayan** [comment]
@danabramovich :
I pass it for you, if you need any help, feel free to talk to me

**Comment by yossigil** [comment]
@danabramovich : no progress so far?

**Comment by danabramovich** [comment]
I will add tests tomorrow
