### ISSUE TITLE
setting up the working environment of Nikita Dizhur and Lidia Piatigorski

### ISSUE THREAD

**Issue by nikitadizhur** [SpartanRefactoring/Spartanizer#712]
The working environment for this project includes
- [x] Linux
- [x] Eclipe Neon
- [x] Java 8 Programming
- [x] Formatting conventions
- [x] Spartan programming
- [x] Fixed cleanup routine
- [x] Highest level of warning settting
- [x]  Git command line
- [x] Telegram (might be changed by another messaging application)

**Comment by yossigil** [comment]
#599 #572 : How come this is still open?
