### ISSUE TITLE
TDD: get all public fields

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#713]
A function named 

``` Java
public List<String> publicFields(TypeDeclaration t);
```
Which:
- takes a single parameter, which is a `TypeDeclaration`.
- returns a list of public fields for this class (by fields' names).

This function is to be implemented as a static member of `tdd.getAll`.

**Comment by orimarco** [comment]
@inbalzukerman @EliaTraore alive?

**Comment by inbalzukerman** [comment]
We didnt finish yet but we're working on it! Exceptof the git commits, are we supposed to update on our progress here too?
Didn't know :/

**Comment by orimarco** [comment]
I don't see any commits!
Have you forgotten to tag the issue in your commits?

**Comment by inbalzukerman** [comment]
I'm afraid so 😞  
We'll tag it from now on 😅

**Comment by inbalzukerman** [comment]
@orimarco  Done! 😄  👍

**Comment by yossigil** [comment]
Take note that you are not to define variables which are not used.

**Comment by inbalzukerman** [comment]
@yossigil  Done- now recognizes also final fields. 
We didn't really understand - Are methods counted as fields?

**Comment by yossigil** [comment]
I did not check the revised code, but what you did in the original is compare the flags to PUBLIC, where you should be using bitwise operations.

**Comment by inbalzukerman** [comment]
yes thank you - i saw it is problematic and instead used the method - isPublic()
After adding a test with a "final public int x" field, it is safe to say it solved the problem - you will find it now after our last commit

Thank you for your help!

**Comment by yossigil** [comment]
@inbalzukerman, where is your todo page?

**Comment by inbalzukerman** [comment]
My todo page: #684

**Comment by yossigil** [comment]
Check that the tests are still meaningul after the removal.

**Comment by yossigil** [comment]
@AdiOmari : The students do not seem to respond. No point in chasing them. It is their choice.
Closing this.

Let me know if the class could stay or be removed

**Comment by AdiOmari** [comment]
@yossigil  I think after removing their code it is useless. They should use assertTrue(reurnvalue instanceof List);

**Comment by yossigil** [comment]
Well, If they are listening, they shoudl do that right away, and if not, I will get to it sometime in a batch cleanup.

**Comment by inbalzukerman** [comment]
@yossigil  @AdiOmari 
We didn't understand there are changes to be done in the code
We saw you removed some of the code- what changes should we do?

**Comment by inbalzukerman** [comment]
Checked right now- All tests pass and the method still works as it should. 
Sorry for the misunderstanding 😕
