### ISSUE TITLE
TDD: Determine whether a type is immutable

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#714]
A function named 

``` Java
public boolean isImmutable(TypeDeclaration m);
```
Which:
- takes a single parameter, which is a `TypeDeclaration` .
- returns true iff the class contains only final fields.

This function is to be implemented as a static member of `tdd.determineIf`.

**Comment by yossigil** [comment]
#647: You injected a DOS file. You must use Linux file format. Karma -= 20.
#640: You injected a DOS file. You must use Linux file format. Karma -= 20.
#553: You injected a DOS file. You must use Linux file format. Karma -= 20.

**Comment by yossigil** [comment]
Karma -= epsilon ;-) for unused variables: #647 #640 #553

**Comment by yossigil** [comment]
Karma -= DELTA ;-) issue still open even though the deadline is past #647 #640 #553

@orimarco @idabran : FYI

**Comment by danabramovich** [comment]
@yossigil But you reopened it yesterday!

**Comment by yossigil** [comment]
Yes, because you were supposed to fix the comments and close it. :8ball:

**Comment by danabramovich** [comment]
@yossigil but you said that you already have fixed it for us, so we assumed you kept it open for a reason.

**Comment by yossigil** [comment]
OK.

**Comment by yossigil** [comment]
Check that the tests still make sense after removing unused variables.

**Comment by danabramovich** [comment]
@yossigil we actually meant to put that unused variable there. the idea was that at first the return type of isImmutable was void. And then, as part of the **TDD process** we built a test that assigns the return value into a boolean variable (unused b), and then we got a compilation error so it forced us to fix the return type into boolean (instead of void). in summary, the unused variable b had a purpose.

**Comment by yossigil** [comment]
Assinging to a variable is not the TDD way to check that the value is not `void`, but rather ensuring that it is of a specific type.

To ensure that a value is non-void, you could add an empty string literal to it, and then compute, e.g., the hashValue.

The unused variable was confusing. Now I remember, I saw it at first iteration, and expected you to fix that. I even commented on it...

Cheers!

**Comment by danabramovich** [comment]
done (please ignore the change i did in the other file, it was a mistake).
