### ISSUE TITLE
TDD: determine if method has a big block

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#717]
A function named 

``` Java
public boolean hasBigBlock(MethodDeclaration m);
```
Which:
- takes a single parameter, which is a method.
- returns true iff the method  has an **inner** block containing at least 5 statements.

This function is to be implemented as a static member of `tdd.determineIf`.

**Comment by orimarco** [comment]
@nikitadizhur @Lidkin5 @alexvitho finished?

**Comment by nikitadizhur** [comment]
@orimarco almost. we still need to write some more tests.

**Comment by alexvitho** [comment]
@orimarco Almost. It will be done in 1 hour

**Comment by alexvitho** [comment]
@orimarco we are done i am closing the issue

**Comment by yossigil** [comment]
Please fix

**Comment by nikitadizhur** [comment]
@yossigil sorry for this. it is fixed now.

**Comment by yossigil** [comment]
Good job. Demonstrated how you respond, and fix! :100:
