### ISSUE TITLE
TDD: determine if method is loaded

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#718]
A function named 

``` Java
public boolean loaded(MethodDeclaration m);
```
Which:
- takes a single parameter, which is a method.
- returns true iff the method:
  - has at least 3 parameters.
  - defines more than 5 variables.

This function is to be implemented as a static member of `tdd.determineIf`.

**Comment by amirsagiv83** [comment]
@orimarco Done! :100:

**Comment by yossigil** [comment]
Karma -= epsilon ;-) #624  #619 unused variables.

**Comment by yossigil** [comment]
I removed these. Make sure the the tests and the code is still meaningful.

**Comment by yossigil** [comment]
@AdiOmari : @orenafek and @amirsagiv83  do not respond. Closing this.

**Comment by amirsagiv83** [comment]
Tests still pass, and the code still works as it should. Sorry for the delay.
