### ISSUE TITLE
TDD: determine if method defines many variables

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#719]
A function named 

``` Java
public boolean definesManyVariables(MethodDeclaration m, int x);
```
Which:
- takes two parameters, which are a method and an integer.
- returns true iff the method defines at least `x` variables.

This function is to be implemented as a static member of `tdd.determineIf`.

**Comment by OriRoth** [comment]
How many variable this method defines?
```Java
Object f() {
  Object o = new Object {
      int x;
    }
  return o;
}
```

**Comment by orimarco** [comment]
@OriRoth count them too, just to make things easier.

**Comment by yaelAmitay** [comment]
I made more commits, but i didn't referenced them correctly to this issue. However you can see them in the history of "determineIf.java" file and "Issue719.java" file.

**Comment by OriRoth** [comment]
You may tag this issue in retrospect by commenting those commits in github. See a1f599c

**Comment by Tomnof** [comment]
@yaelAmitay @koralchapnik 
not sure if you know, but you have 2 tests failing...

**Comment by yaelAmitay** [comment]
It looks like someone delete our function! 
what are we suppose to do in this situation?
 @orimarco

**Comment by orimarco** [comment]
Git remembers everything...

**Comment by orimarco** [comment]
@yaelAmitay @koralchapnik finished?

**Comment by yaelAmitay** [comment]
yes
