### ISSUE TITLE
Move issues such as 'foo' and other 'teaching' stuff to new repo?

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#720]
Do not move the TDDs. They will remain with the host Spartanizer project.

I suppose this should be done after the students were split into projects.

**Comment by zvili** [comment]
Ok

On Nov 1, 2016 3:43 PM, Yossi Gil <notifications@github.com> wrote:

Do not move the TDDs. They will remain with the spartan.

**Comment by zvili** [comment]
@yossigil - If I understand correctly, we want to define a new repo in the SpartanRefactoring organization and move to it "foo" and selected "teaching" issues ?

**Comment by yossigil** [comment]
Yes, I believe you created one already. We will only do the move when the first sprint is done
