### ISSUE TITLE
The magic numbers

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#721]
Let `x0` be the number of methods with no statements (initially), let `x1` be the number of methods with 1 statement initially, etc. Let `y0, y1, y2, ...` be the same after processing. 

- Find all `x`'s and `y`'s 
- In alll methods that the total did not change, compute ratio of savings in tokens, and in **stack complexity**
- Define the **stack complexity** metric, which is the total depth of stacks in interations reading the input.

**Comment by orimarco** [comment]
Analyzing commons-lang gives:

> **[num] before ->after**
> [0] 60 -> 60
> [1] 3 -> 3
> [2] 1065 -> 1323
> [3] 131 -> 185
> [4] 129 -> 149
> [5] 241 -> 97
> [6] 92 -> 84
> [7] 52 -> 86
> [8] 64 -> 110
> [9] 85 -> 64
> [10] 46 -> 74
> [11] 67 -> 40
> [12] 84 -> 38
> [13] 41 -> 23
> [14] 39 -> 25
> [15] 52 -> 20
> [16] 36 -> 22
> [17] 28 -> 9
> [18] 22 -> 19
> [19] 19 -> 11
> [20] 21 -> 9
> [21] 14 -> 18
> [22] 10 -> 5
> [23] 19 -> 3
> [24] 8 -> 3
> [25] 6 -> 3
> [26] 17 -> 4
> [27] 10 -> 11
> [28] 3 -> 2
> [29] 8 -> 4
> [30] 9 -> 1
> [31] 1 -> 1
> [32] 4 -> 0
> [33] 4 -> 3
> [34] 1 -> 1
> [36] 1 -> 2
> [37] 9 -> 2
> [38] 3 -> 3
> [39] 2 -> 1
> [41] 2 -> 1
> [42] 4 -> 4
> [43] 2 -> 1
> [44] 0 -> 1
> [45] 3 -> 1
> [46] 2 -> 1
> [48] 1 -> 1
> [49] 1 -> 0
> [50] 1 -> 1
> [51] 0 -> 2
> [52] 1 -> 0
> [54] 2 -> 1
> [55] 1 -> 0
> [57] 1 -> 2
> [60] 1 -> 0
> [61] 1 -> 1
> [63] 0 -> 1
> [64] 1 -> 0
> [65] 3 -> 0
> [68] 0 -> 1
> [76] 0 -> 1
> [77] 1 -> 0
> [78] 0 -> 1
> [79] 1 -> 0
> [88] 0 -> 1
> [90] 1 -> 0
> [93] 1 -> 0
> [94] 1 -> 0
> [95] 1 -> 0
> [96] 0 -> 1
> [102] 1 -> 0
> [108] 0 -> 1
> [127] 1 -> 0

**Accumulated:**

> [0] 60 -> 60
> [1] 63 -> 63
> [2] 1128 -> 1386
> [3] 1259 -> 1571
> [4] 1388 -> 1720
> [5] 1629 -> 1817
> [6] 1721 -> 1901
> [7] 1773 -> 1987
> [8] 1837 -> 2097
> [9] 1922 -> 2161
> [10] 1968 -> 2235
> [11] 2035 -> 2275
> [12] 2119 -> 2313
> [13] 2160 -> 2336
> [14] 2199 -> 2361
> [15] 2251 -> 2381
> [16] 2287 -> 2403
> [17] 2315 -> 2412
> [18] 2337 -> 2431
> [19] 2356 -> 2442
> [20] 2377 -> 2451
> [21] 2391 -> 2469
> [22] 2401 -> 2474
> [23] 2420 -> 2477
> [24] 2428 -> 2480
> [25] 2434 -> 2483
> [26] 2451 -> 2487
> [27] 2461 -> 2498
> [28] 2464 -> 2500
> [29] 2472 -> 2504
> [30] 2481 -> 2505
> [31] 2482 -> 2506
> [32] 2486 -> 2506
> [33] 2490 -> 2509
> [34] 2491 -> 2510
> [36] 2492 -> 2512
> [37] 2501 -> 2514
> [38] 2504 -> 2517
> [39] 2506 -> 2518
> [41] 2508 -> 2519
> [42] 2512 -> 2523
> [43] 2514 -> 2524
> [44] 2514 -> 2525
> [45] 2517 -> 2526
> [46] 2519 -> 2527
> [48] 2520 -> 2528
> [49] 2521 -> 2528
> [50] 2522 -> 2529
> [51] 2522 -> 2531
> [52] 2523 -> 2531
> [54] 2525 -> 2532
> [55] 2526 -> 2532
> [57] 2527 -> 2534
> [60] 2528 -> 2534
> [61] 2529 -> 2535
> [63] 2529 -> 2536
> [64] 2530 -> 2536
> [65] 2533 -> 2536
> [68] 2533 -> 2537
> [76] 2533 -> 2538
> [77] 2534 -> 2538
> [78] 2534 -> 2539
> [79] 2535 -> 2539
> [88] 2535 -> 2540
> [90] 2536 -> 2540
> [93] 2537 -> 2540
> [94] 2538 -> 2540
> [95] 2539 -> 2540
> [96] 2539 -> 2541
> [102] 2540 -> 2541
> [108] 2540 -> 2542
> [127] 2541 -> 2542

**Comment by yossigil** [comment]
OK. ENough with this one. We proceed on #837
