### ISSUE TITLE
Setting up the environment of Doron Meshulam and Tomer Dragucki

### ISSUE THREAD

**Issue by tomerdragucki** [SpartanRefactoring/Spartanizer#724]
The working environment for this project includes
- [x] Linux
- [x] Java 8 Programming
- [x] Eclipe Neon
- [x] Formatting conventions
- [x] Spartan programming
- [x] Fixed cleanup routine
- [x] Highest level of warning setting
- [x]  Git command line
- [x] Telegram (might be changed by another messaging application)

**Comment by mdoron** [comment]
You are the best partner, thank you for posting this issue for the both of us

**Comment by yossigil** [comment]
Bad Karma for keeping this open so long #709 #655

**Comment by yossigil** [comment]
Asking again. How come this is still open?  #709 #655
What's missing?

**Comment by mdoron** [comment]
Can you link at least 3 examples of students who GAINED Karma? @yossigil

**Comment by yossigil** [comment]
Good question. Incidentally, this happens every time I say :100:  or :+1: in the persona/issue page e.g., `#835 #804 #822 #810 #684 #659 ...`you may have not noticed a thumbup I often put on  a comment. Reason is simple: when I see something that is correct, I can just put a thumbs up. If something is not so good, I cannot just put a thumbsdown, I have to write something to explain. 

And you can right, this practice makes the medals less visible than the 'bad karam' note. I will make positive comments more visible.  Good work.
