### ISSUE TITLE
Setting up the working environment of Roei Rosenzweig and Roey Maor

### ISSUE THREAD

**Issue by Roei-m** [SpartanRefactoring/Spartanizer#727]
The working environment for this project includes
- [x] Linux
- [x] Eclipse Neon
- [x] Java 8 Programming
- [x] Formatting conventions
- [x] Spartan programming
- [x] Fixed cleanup routine
- [x] Highest level of warning settings
- [x]  Git command line
- [x] Telegram

**Comment by yossigil** [comment]
#737 #623: You finish with an issue? close it ASAP. I closed it for you. bad Karama

**Comment by yossigil** [comment]
![image](https://cloud.githubusercontent.com/assets/12775400/20185512/02a13202-a775-11e6-961e-7001a75b9ee1.png)
@orimarco : did you figure out if this is one or two students?

**Comment by orimarco** [comment]
Not sure what roei-m's _m_ stands for, but they **are** two students.
