### ISSUE TITLE
Inlining bug - primitives

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#731]
Yet another inlining bug:
```
Integer i = 0;
i.toString();
```
==>
```
0.toString();
```

@yossigil FYI

@yaelAmitay has the credit for finding this bug. Nice job! +10 karma 👍. #652

**Comment by yossigil** [comment]
If you reference his Issue with Karma/Todo, anyone scanning his Karma will know...

**Comment by OriRoth** [comment]
@SapirBismot : is this a duplicate issue? of something you work on...

**Comment by SapirBismot** [comment]
@OriRoth I am working on it.

**Comment by SapirBismot** [comment]
@yossigil this issue seams to be more complicated than we initially thought. Consider the following problems:
* inlining primitive array access/field access/variable:
```Java
int x = 0;
xxx(x);
Integer i = x;
i.toString();
```
Is inlining of `Integer`/`Boolean` etc. safe at all?
* invoking method is not allowed but calling to function is
```
Integer x = 0;
f(x);
```
=>
```
f(0);
```
but
```
Integer x = 0;
x.toString();
```

* hiding variables:
```Java
class A {
  Integer i;
  void f(Integer i) {
    i.toString();
  }
};
```
This is probably another issue.

**Comment by OriRoth** [comment]
Moreover, we are looking for suitable tools that check the primitive-hood of expressions such as:
```Java
(0+x)
```
We would be happy to see a use example (from `type`?) if those tools exist.

@yossigil in second thought, this issue is quite complicated. I think @SapirBismot should stay away from it at the moment.
