### ISSUE TITLE
setting up the working environment of Moshe Eliasof and Netanel Felcher

### ISSUE THREAD

**Issue by MosheEliasof** [SpartanRefactoring/Spartanizer#732]
The working environment for this project includes
- [x] Linux
- [x] Eclipe Neon
- [x] Java 8 Programming
- [x] Formatting conventions
- [x] Spartan programming
- [x] Fixed cleanup routine
- [x] Highest level of warning settting
- [x]  Git command line
- [ ] Telegram (might be changed by another messaging application)

**Comment by MosheEliasof** [comment]
@NetanelFelcher

**Comment by yossigil** [comment]
Why isn't this closed yet. #633 and #632 
@Zvili FYI
