### ISSUE TITLE
setting up the working environment of Oren Afek and Amir Sagiv

### ISSUE THREAD

**Issue by amirsagiv83** [SpartanRefactoring/Spartanizer#733]
The working environment for this project includes
- [x] Linux
- [x] Eclipe Neon
- [x] Java 8 Programming
- [ ] Formatting conventions
- [x] Spartan programming
- [x] Fixed cleanup routine
- [x] Highest level of warning settting
- [x]  Git command line

**Comment by OriRoth** [comment]
Eclipse is love, Eclipse is life.

**Comment by yossigil** [comment]
How come this is not closed yet? Bad Karma to #624 #619

**Comment by orenafek** [comment]
@yossigil 
still waiting for the Formatting conventions file, as promissed :)
WE WANT OUR GOOD KARMA BACK !
@amirsagiv83

**Comment by OriRoth** [comment]
@orenafek the Spartanizer project has a builtin conventions, maybe you can extract and use it.

**Comment by yossigil** [comment]
The formatting conventions are found in an .xml file, search for it and use it.

**Comment by yossigil** [comment]
?

**Comment by yossigil** [comment]
#624 #619

**Comment by yossigil** [comment]
ISSUE OPEN TWO DAYS AFTER MILESTONE

**Comment by yossigil** [comment]
Ok, @orenafek  and @amirsagiv83 , I am closing this due to lack of response. Make sure you adopt the formatting conventions.

@AdiOmari / @zvili : this should be counted towards grading.
