### ISSUE TITLE
Setting Up the Working Environment of Yosef Raisman and Ori Roth

### ISSUE THREAD

**Issue by yosefraisman** [SpartanRefactoring/Spartanizer#734]
## Working Environment
- [x] Linux
- [x] Eclipe Neon
- [x] Java 8 Programming
- [x] Formatting conventions
- [x] Spartan programming
- [x] Fixed cleanup routine
- [x] Highest level of warning settting
- [x]  Git command line
- [x] Telegram

## Class Work 1.11
Create a new issue, assing yourself, copy the checklist below, set labels and milestone.
- [x]  [Login](https://accounts.eclipse.org/user/login?destination=oauth2/authorize) to eclipse. If you do not have a user name, create one.
- [x] Search in the eclipse market place for the [spartanizer, version 2.6](https://marketplace.eclipse.org/content/spartan-refactoring-0)
- [x]  Star the project
- [x]  Install the plugin by dragging it into eclipse Neon
- [x]  run the plugin on one of your Java projects.to see what it does.
- [x] exit from eclipse
- [x] Star the project on github
- [x]  Install git and maven on your machine
- [x]  Clone the project, using ssh
- [x]  Mvn build the project
- [x]  Search for installation instructions in the spartanizer project
- [x]  Install all plugins in eclipse as described there
- [x]  Import the project into eclipse
- [x]  Run junit tests.
- [x] Start working on [TDD](https://github.com/SpartanRefactoring/Spartanizer/issues/478).

**Comment by OriRoth** [comment]
@yosefraisman [Eclipse is love, Eclipse is life](http://wanna-joke.com/wp-content/uploads/2015/05/funny-gif-dog-tooth-tongue-weird.gif).

**Comment by yossigil** [comment]
#616: K--. When an issue is done, you must close it.
