### ISSUE TITLE
Yael's copy of issue #592

### ISSUE THREAD

**Issue by yaelAmitay** [SpartanRefactoring/Spartanizer#735]
- [x] Login to eclipse. If you do not have a user name, create one.
- [x] Search in the eclipse market place for the spartanizer, version 2.6
- [x] Star the project
- [x] Install the plugin by dragging it into eclipse Neon
- [x] run the plugin on one of your Java projects.to see what it does.
- [x] exit from eclipse
- [x] Star the project on github:
- [x] Install git and maven on your machine:
 sudo apt-get update
 sudo apt-get install maven git
 sudo apt-get upgrade
- [x] Clone the project, using ssh: image
 mkir -p ~/git
 cd !$
 git clone git@github.com:SpartanRefactoring/Spartanizer.git
- [x] Mvn build the project
cd ~/git/Spartanizer
git status
git pull
mvn package

- [x] Search for installation instructions in the spartanizer project
- [x] Install all plugins in eclipse as described there
- [x] Import the project into eclipse
- [x] Run junit tests.
- [x] Start working on TDD.

**Comment by zvili** [comment]
Leaving this issue open does not contribute for a good Karma. #652
