### ISSUE TITLE
Creating & importing Spartanizer project to eclipse (using git and maven)

### ISSUE THREAD

**Issue by IdanAtias** [SpartanRefactoring/Spartanizer#739]
- [ ] Login to eclipse. If you do not have a user name, create one.
- [ ]  Search in the eclipse market place for the spartanizer, version 2.6
- [ ]  Star the project
- [ ]  Install the plugin by dragging it into eclipse Neon
- [ ]  run the plugin on one of your Java projects.to see what it does.
- [ ]  exit from eclipse
- [ ]  Star the project on github:

**Comment by yossigil** [comment]
@IdanAtias : I see that no progress was made. @shimonAzulay : DITTO.

@ZVILi: they have no Karma /TODO page. I presume they are not in the course. I close the issue.

**Comment by yossigil** [comment]
@ZVILI: remove them then from the allowed contributors.

**Comment by zvili** [comment]
@yossigil: He is not included in the collaborators list.
