### ISSUE TITLE
TDD: get all public fields 2

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#741]
A function named 

``` Java
public List<String> publicFields(TypeDeclaration t);
```
Which:
- takes a single parameter, which is a `TypeDeclaration`.
- returns a list of public fields for this class (by fields' names).

This function is to be implemented as a static member of `tdd.getAll2`.

**Comment by IdanAtias** [comment]
@orimarco @shimonAzulay @LiorBenAmi 
Hi, i am trying to understand how to use TypeDeclaration can i find any javadoc about it ? 
Is it a type of ASTNode ? 
For example i tried to execute it but i got NULL 
` (TypeDeclaration) wizard.ast("final int x") call.`

**Comment by orimarco** [comment]
@IdanAtias http://lmgtfy.com/?q=TypeDeclaration+ASTNode

**Comment by orimarco** [comment]
btw use az.typeDeclaration to cast an ASTNode into typeDeclaration
