### ISSUE TITLE
Yarden Lev's copy of issue #592

### ISSUE THREAD

**Issue by ylevv** [SpartanRefactoring/Spartanizer#743]
- [x] Login to eclipse. If you do not have a user name, create one.
- [x] Search in the eclipse market place for the spartanizer, version 2.6
- [x] Star the project
- [x] Install the plugin by dragging it into eclipse Neon
- [x] run the plugin on one of your Java projects.
- [x] exit from eclipse
- [x] Star the project on github
- [x] Install git and maven on your machine
- [x] Clone the project, using ssh
- [x] Mvn build the project
- [x] Search for installation instructions in the spartanizer project
- [x] Install all plugins in eclipse as described there
- [x] Import the project into eclipse
- [x] Run junit tests.
- [x] Start working on TDD.

**Comment by zvili** [comment]
Leaving this issue open does not contribute for a good Karma. #598
