### ISSUE TITLE
Zahi's copy of issue #592

### ISSUE THREAD

**Issue by zahimizrahi** [SpartanRefactoring/Spartanizer#744]
- [x] Login to eclipse. If you do not have a user name, create one.
- [x]  Search in the eclipse market place for the spartanizer, version 2.6
- [x] Install the plugin by dragging it into eclipse Neon
- [x] run the plugin on one of your Java projects.to see what it does.
- [x] exit from eclipse
- [x]  Star the project on github
- [x] Install git and maven on my  machine
- [x] Clone the project, using ssh
- [x] Mvn build the project
- [x] Search for installation instructions in the spartanizer project
- [x]  Install all plugins in eclipse as described there: #592  
- [x]  Import the project into eclipse
- [x] Run junit tests.
- [x] Start working on TDD.

**Comment by yossigil** [comment]
#551 : K--. When an issue is done, close it ASAP.
@ZVILI @idabran
