### ISSUE TITLE
Bug in Wiki tutorial

### ISSUE THREAD

**Issue by ortroyaner** [SpartanRefactoring/Spartanizer#749]
while using https://github.com/SpartanRefactoring/Spartanizer/wiki/Sterile--Import-into-Eclipse tutorial, it seems that clone command refers to not updated file name.
It should be refer to the clone button on the main page of the project I guess...

![image](https://cloud.githubusercontent.com/assets/9674645/19926026/1ae0d708-a0fb-11e6-983c-45ae86b535fb.png)

Thanks for @OriRoth who helped me figure this out

**Comment by orimarco** [comment]
guess you're right. fixed it.

**Comment by OriRoth** [comment]
@ortroyaner Nice. You get +10 karma 👍 #533
