### ISSUE TITLE
Problems with changing the name of variable on loops

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Spartanizer#750]
In a function with a parameter of ¢ and a for loop over a list, the spartanizer changed also the name of the variable of the loop to ¢.

**Comment by OriRoth** [comment]
I think this is a duplication of existing issue... check it out.

Also add loopy loops label (???)

**Comment by dormaayan** [comment]
@OriRoth : I'll check it out, I remember an Issue about that but I think it was solved....

**Comment by mdoron** [comment]
Quick check revealed that the bug still exists. I'm on it.

**Comment by mdoron** [comment]
@dormaayan What is wanted behavior in this case?

**Comment by yossigil** [comment]
Yes. I suspect so

**Comment by mdoron** [comment]
@yossigil I wrote a correction in EnhancedForParamemeterRenameToCent.java, but it didn't worked. So I looked a little bit deeper and found SingleVariableDeclerationEnhancedForRenameToCent.java.

I think it's a duplication, can you confirm? If you deny, can you explain each case because it's not clear to me.

PS: You are the author of both classes.

**Comment by yossigil** [comment]
Beyond my bandwidth. Work it yourself if you can

**Comment by mdoron** [comment]
@yossigil So... If I think it's unnecessary do I have the permission to eliminate the redundant Tipper?

**Comment by yossigil** [comment]
Yes. Just make sure that the semantics does not change, including all existing tests and perhaps a new ones

**Comment by yossigil** [comment]
OK, this does not work. The  correct change in this case is to prevent the function from changing its parameter name if there is a variable defined with the name ¢. I guess the search for the definition in
missed variale defined in the for loop

**Comment by mdoron** [comment]
@yossigil but if the user deliberately defined the parameter name to be ¢, isn't it just logical that we won't change the enhanced for loop parameter to ¢ ourselves? 
You are totally right if we were the only one that allow to change the name of the parameter, but what if the user decided to do this manually? Or even worse, he downloaded another (computational) plugin!

**Comment by yossigil** [comment]
Well,the corrent thing for the spartanizer is something else. To rename the parameter of the function.
But, anyway do something that this one works, without breaking tests.

**Comment by mdoron** [comment]
@yossigil Now everything works. I ran all the JUnit tests a few times...

**Comment by yossigil** [comment]
:100:
