### ISSUE TITLE
TDD: get all methods in CompilationUnit

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#753]
A function named 

``` Java
public static List<MethodDeclaration> methods(CompilationUnit cu);
```
Which:
- takes a single parameter, which is a `CompilationUnit`.
- returns a list of methods in `cu`.

This function is to be implemented as a static member of `tdd.getAll`.

**Comment by yossigil** [comment]
Well, you injected DOS files. Bad Karma to both
#737 
#670

**Comment by RoeiRaz** [comment]
Done

**Comment by yossigil** [comment]
#623 and #670 : Karma -= epsilon. You have unused variables.
