### ISSUE TITLE
Assaf Lustig cpoy of issue 592

### ISSUE THREAD

**Issue by assaflu** [SpartanRefactoring/Spartanizer#757]
- [x]  [Login](https://accounts.eclipse.org/user/login?destination=oauth2/authorize) to eclipse. If you do not have a user name, create one.
- [x] Search in the eclipse market place for the [spartanizer, version 2.6]
- [x]  Star the project
- [x]  Install the plugin by dragging it into eclipse Neon
- [x]  run the plugin on one of your Java projects.to see what it does.
- [x] exit from eclipse
- [x] Star the project on [github](https://github.com/SpartanRefactoring/Spartanizer/issues/new): ![image](https://cloud.githubusercontent.com/assets/12775400/19832195/bb8dc860-9e25-11e6-9d92-aee51fcedd8c.png)
- [x]  Install git and maven on your machine:
- [x]  Clone the project, using ssh: ![image](https://cloud.githubusercontent.com/assets/12775400/19832218/49de666a-9e26-11e6-8b73-3dc8672f61d2.png)
- [x]  Mvn build the project
- [x]  Search for installation instructions in the spartanizer project
- [x]  Install all plugins in eclipse as described there
- [x]  Import the project into eclipse
- [x]  Run junit tests.
- [x] Start working on [TDD](https://github.com/SpartanRefactoring/Spartanizer/issues/478).

**Comment by yossigil** [comment]
keep up the good work

**Comment by zvili** [comment]
Leaving this issue open does not contribute for a good Karma #640

**Comment by yossigil** [comment]
#640: Zvili was too gentle. If you finished the tasks, close the issue ASAP. This is bad Karma
