### ISSUE TITLE
Karma and Todos for Shimon Azulay

### ISSUE THREAD

**Issue by shimonAzulay** [SpartanRefactoring/Spartanizer#759]
- [x]  Make sure you present yourself by a readable nick
- [x]  Describe yourself in the bio page
- [x]  State that you are (not) in search for a job
- [x]  Connect to the host repo

**Comment by shimonAzulay** [comment]
@YossiGil: Done.

**Comment by IdanAtias** [comment]
the best karma page ive ever seen in my life

**Comment by shimonAzulay** [comment]
@IdanAtias  ya halalau

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Market#6
