### ISSUE TITLE
Moshe's Copy of #592

### ISSUE THREAD

**Issue by MosheEliasof** [SpartanRefactoring/Spartanizer#762]
- [x]  Login to eclipse. If you do not have a user name, create one.
- [x] Search in the eclipse market place for the spartanizer, version 2.6
- [x]  Star the project
- [x]  Install the plugin by dragging it into eclipse Neon
- [x]  run the plugin on one of your Java projects.to see what it does.
- [x] exit from eclipse
- [x] Star the project on github
- [x]  Install git and maven on your machine:
- [x]  Clone the project, using ssh
- [x]  Mvn build the project
- [x]  Search for installation instructions in the spartanizer project
- [x]  Install all plugins in eclipse as described there
- [x]  Import the project into eclipse
- [x]  Run junit tests.
- [x] Start working on TDD]

**Comment by yossigil** [comment]
#632, bad Karma, If it is done, close it. @zvili

**Comment by MosheEliasof** [comment]
@yossigil I got an invitation to the project just today. I was waiting so I can assign myself and add labels :)

**Comment by yossigil** [comment]
#632 bad karma: no milestone.
