### ISSUE TITLE
Run early build in non-UI thread

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#767]
To avoid hangs at buildup. See #764.

**Comment by OriRoth** [comment]
It may not be enough though - some of the problems are because of plugin classes not loading.

**Comment by yossigil** [comment]
Isn't this defunct?

**Comment by OriRoth** [comment]
I'll check it this week.

**Comment by OriRoth** [comment]
Maybe not a perfect solution, but the plugin shows better startup behavior (no modal pop up window... most of the time).

May be relevant, though it is old and I couldn't get anything useful from it: https://bugs.eclipse.org/bugs/show_bug.cgi?id=198591
