### ISSUE TITLE
Amit's copy of issue #592

### ISSUE THREAD

**Issue by AmitOhayon** [SpartanRefactoring/Spartanizer#771]
- [ ]  [Login](https://accounts.eclipse.org/user/login?destination=oauth2/authorize) to eclipse. If you do not have a user name, create one.
- [ ] Search in the eclipse market place for the [spartanizer, version 2.6](https://marketplace.eclipse.org/content/spartan-refactoring-0)
- [ ]  Star the project
- [x]  Install the plugin by dragging it into eclipse Neon
- [x]  run the plugin on one of your Java projects.to see what it does.
- [x] exit from eclipse
- [x] Star the project on [github](https://github.com/SpartanRefactoring/Spartanizer/issues/new)
- [x]  Install git and maven on your machine:
- [x]  Clone the project, using ssh
- [x]  Mvn build the project
- [x]  Search for installation instructions in the spartanizer project
- [x]  Install all plugins in eclipse as described there
- [x]  Import the project into eclipse
- [x]  Run junit tests.
- [x] Start working on [TDD](https://github.com/SpartanRefactoring/Spartanizer/issues/478).

**Comment by AmitOhayon** [comment]
Still waiting for user approval on eclipse website

**Comment by yossigil** [comment]
I am closing this with Bad Karma to #680

**Comment by AmitOhayon** [comment]
@yossigil 
The only things I haven't done on this list are the things that require eclipse account, and that is because they do not approve me. I registered twice, got a confirmation mail twice (and clicked on the link), but I couldn't and still can't login to my user. Please reconsider the Bad Karma.

**Comment by AmitOhayon** [comment]
@yossigil 
I just tried to register again, with the same email address, and this time I could login immediately (on the previous two times there was a message about waiting for approval). I could show you the previous two confirmations mail to support my claim...
Anyway, for whats it's worth, I've done the rest of the bullets.

**Comment by yossigil** [comment]
OK
