### ISSUE TITLE
TDD: determine if node uses some name

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#774]
A function named

public static boolean uses(ASTNode node, String name);
Which:

takes two parameters:

- an ASTNode node
- a String name

returns true iff the name is used in the node as a Name.

This function is to be implemented as a static member of `tdd.determineIf`.

**Comment by AmitOhayon** [comment]
@orimarco 

> returns true iff the name is used in the node as a Name.

If the node itself isn't a Name but has a child of type Name which uses name, should we return true?

**Comment by orimarco** [comment]
@AmitOhayon yes.  the name can be any descendant of `node`
