### ISSUE TITLE
TDD: get all methods in CompilationUnit 2

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#778]
A function named 

``` Java
public static List<MethodDeclaration> methods(CompilationUnit cu);
```
Which:
- takes a single parameter, which is a `CompilationUnit`.
- returns a list of methods in `cu`.

This function is to be implemented as a static member of `tdd.getAll2`.

**Comment by MosheEliasof** [comment]
Notice a mistake on the comment for the latest commit. The correct comment is:
test #2 for issue #778.

**Comment by yossigil** [comment]
@orimarco , I erased this class, Could not find a karma page for both students. And the code they committed is full of warnings. Beyond repair.

@NetanelFelcher  and @MosheEliasof: you would have to rewrite this class, feel free to dig it from history. But do not check it in, until you made sure your code is up to standards.

**Comment by MosheEliasof** [comment]
@yossigil I fixed it. Can I close it ?

**Comment by yossigil** [comment]
Cannot check now. Do what you think is right. I will check later.

**Comment by yossigil** [comment]
I erased the file again. You did not bother to run cleanup on it.
#633 , #632 , bad Karma. You are supposed to run cleanup each time befor you commit.

@zvili @idabran @yh-github @AdiOmari @orimarco : FYI.

**Comment by MosheEliasof** [comment]
There is a mistake in my username again. I fix it now.

**Comment by yossigil** [comment]
Karma -= epsilon ;-) for unused variables #632 #633

**Comment by yossigil** [comment]
Check that the tests still work!

**Comment by MosheEliasof** [comment]
@yossigil  I checked the tests again. They all pass.

**Comment by yossigil** [comment]
No.  make sure that the functionality of the tests did not change.

**Comment by yossigil** [comment]
:100: #632

**Comment by MosheEliasof** [comment]
:)
