### ISSUE TITLE
Consolidate test cases

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#78]
We want no duplications in tests. and we want all disabled tests to be in one class

**Comment by yossigil** [comment]
Class TrimmerTest and TrimmerTest240 have zillion of test methoods duplicationsetc.

**Comment by OriRoth** [comment]
There are *some* tests (like actualExampleForSortAdditionInContext) that are different between the files... what is the preferred version? (i.e. what is the base file to which I add *new* tests from the other)

**Comment by yossigil** [comment]
In case of doubt, keep the duplicates. Just do a quick trimming of duplicates, and then move everything to one file. We need a coherent list of what's old and what's new, and more importantly, what's not resolved.

**Comment by OriRoth** [comment]
OK, several results:
* Merged tests in ValidTrimmerTest
* Ignored merged tests in IgnoreTrimmerTest
* Duplicated tests in DuplicatedTrimmerTest
* I cannot guarantee each test in DuplicatedTrimmerTest is the duplicated test and not the *original*, in case they are different (a small logical problem)... probably means this class is irrelevant
* I already removed each @Ignore annotation from the ignored tests (now in IgnoreTrimmerTest), so it can be run immediately.
* I am not sure how to check if it has been done correctly... by raw counting it seems legit

**Comment by yossigil** [comment]
Great job. Eliminate the old test classes. We do not want duplications with these, or anyone adding to them now.

**Comment by OriRoth** [comment]
OK I have renamed TrimmerTest->TrimmerTest_old and ValidTrimmerTest->TrimmerTest and posted a clarification in the telegram group... well in second thought I'll backup TrimmerTest_old localy then delete it, it may cause a confusion
