### ISSUE TITLE
Karma and Todos for Daniel Shames

### ISSUE THREAD

**Issue by dshames** [SpartanRefactoring/Spartanizer#790]
- [x]  Use a picture, photo or distinct, familiar, personal 
avatar. Don't use an automatic icon (we need this to be able to identify you in the tens of students we have):
- [x] Present yourself by a not too rude **nick**  
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

**Comment by dshames** [comment]
@yossigil

**Comment by yossigil** [comment]
Make sure you use lables and milestone. Bad karma for starting TDD without a TODO page.

**Comment by yossigil** [comment]
@AdiOmari : 
He did not place a milestone.
fixed it.

**Comment by AdiOmari** [comment]
👍

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-ParkingManagement#15
