### ISSUE TITLE
Plugin does not automatically start for new projects

### ISSUE THREAD

**Issue by danielmittelman** [SpartanRefactoring/Spartanizer#8]
Although the default value for the plug-in is "true", the plug-in does not automatically start working for new projects, requiring to turn it off and on again

**Comment by OriRoth** [comment]
Relevant documentation:
http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_core_resources_natures.html&cp=2_1_1_22&anchor=e.one-of-nature

**Comment by yossigil** [comment]
Ori: I hope you understand this. I don't...

**Comment by OriRoth** [comment]
Closed, see issue #160

**Comment by OriRoth** [comment]
Revived from the dead!
http://stackoverflow.com/questions/7664758/how-to-subscribe-to-an-openproject-event-in-eclipse
http://stackoverflow.com/questions/30330667/iworkspace-search-for-file-type
http://stackoverflow.com/questions/12243926/how-to-delay-modificactions-to-the-resource-tree-when-it-is-locked

**Comment by OriRoth** [comment]
@yossigil well... there are some issues with this matter we should discuss about the next time we meet. Nonetheless, we can already see results:
- [X] Markers in new project
- [X] Markers in imported project
- [ ] Markers in opened-after-close project
- [ ] Solved issue about `org.eclipse.core.internal.resources.ResourceException: The resource tree is locked for modifications`

**Comment by yossigil** [comment]
That would be very useful and interesting. But, it is too great a challenge, or is it? I am very hesitant to go on this adventure now.

**Comment by yossigil** [comment]
I am not so sure that I am happy to endorse this. It sounds too big.
