### ISSUE TITLE
Code coverage - Assignment 2: spartanizer.utils.Bool

### ISSUE THREAD

**Issue by ArthurSap** [SpartanRefactoring/Spartanizer#800]
We chose to cover the code in the file spartanizer/utils/Bool.java for issue #799 .
*** No milestone for assignment 2 while opening the issue.

**Comment by shaysegal** [comment]
i think that you can put sprint0 as milestone of this assignment because it due to nov 14th which is the last day of sprint0

**Comment by yossigil** [comment]
Functionality of this class is minimal. Try to find another class.

**Comment by danabramovich** [comment]
@yossigil I made a new issue #824  for this assignment with a different class.

**Comment by yossigil** [comment]
Thanks. Good job. #757 #553
