### ISSUE TITLE
 il.org.spartan.spartanizer.utils -> Int.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by zahimizrahi** [SpartanRefactoring/Spartanizer#801]
we chose the code coverage of the file il.org.spartan.spartanizer.utils/Int.java.
I think it's very easy so maybe we will add another file later. 

Test Coverage for now: 18.8% 

Please do not choose this file. :)

**Comment by yossigil** [comment]
@zvili @orimarco @yh-github @AdiOmari @idabran : FYI. I erased this class, since it was checked in with failing tests.

**Comment by orimarco** [comment]
@zahimizrahi why you no spartanize your code?
