### ISSUE TITLE
NP analysis

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#802]
# Ignore the following results
**They are under construction**

| repo        | #methods |  avg. Statements ratio| avg. Expression ratio  | % of methods with 1s | 
|:----------------:|:-----:|:-------------:|:-----:|:--:|
| commons-lang |   3025   | 0.247| 0.240 |--|
| commons-bcel  | 3984 | 0.248    |  0.264 |--|
| Guava| 9915| 0.207 | 0.219 |--|

Ratios are measured per method.
_**Statements ratio** : \#statements matched by NPs/\#statements_  
_**Expressions ratio** : \#expressionsmatched by NPs/ \#expressions_

If we don't use method patterns (NPs that matched whole method, like Setter, Getter, JD, ...) we get:

| repo        | #methods |  avg. Statements ratio| avg. Expression ratio  |  % of methods with 1s | 
|:----------------:|:-----:|:-------------:|:-----:|:-----:|
| commons-lang |   3025   | -- | -- | --|
| commons-bcel  | 3984 | 0.774    |  0.787 | --|
| Guava| 10909|  0.687  |   0.702 | -- |

**Comment by orimarco** [comment]
@yossigil

**Comment by orimarco** [comment]
So... I decided to organize things up.
We can divide NanoPatterns to 3 groups:

1. patterns which match a Statement, Expression.
2. patterns which match a whole Method and explain the essence of it (Setter, Getter, Examiner, ...)
3. patterns which match a method but only specifies some characteristics about the method (JD, Delegator, Carrier, ...)

If we want to show that we **cover our repo with patterns** we need to measure the coverage by groups 1-2.
If we want to show that we **know to characterize methods** we should measure group 3 coverage.

So from now on I will do the analyzes and put the results so that groups 1-2 are separated from 3.

**Comment by orimarco** [comment]
Oh, and when counting statements and expressions there's a big list of node types which I don't count, like breakStatement, literals, names, etc.
Whole list can be found in `measure.java`

**Comment by M4tt30rru** [comment]
@orimarco, Speaking of which, it could be interesting have a look how nano patterns have been categorized in literature. You may be interested to have a look at the report I made (you can find it on the bitbucket repo).

**Comment by orimarco** [comment]
We have a bitbucket repo?

**Comment by M4tt30rru** [comment]
sent via pm ;)

**Comment by orimarco** [comment]
![image](https://cloud.githubusercontent.com/assets/12089145/20879606/63658dba-badd-11e6-814f-e17825e64c78.png)

**Comment by orimarco** [comment]
with `SuperDelegator`
![image](https://cloud.githubusercontent.com/assets/12089145/20882912/ff1655ba-baeb-11e6-97b4-d5a40885b996.png)

**Comment by yossigil** [comment]
Use
X.Y% or XX% for the last three columns, i.e., two significant digits. What's data of before and after. I still cannot undestand.

**Comment by orimarco** [comment]
Updated...
The results show the avg. coverage for methods with `n` statements. Moreover it shows for number of statements `n` the portion of statements/methods out of the total number of statements/methods.

**Comment by yossigil** [comment]
Try to remove constructors. This may help. Or deal with them separately. I am not sure I understand how many methods are there in precent and how many are covered in precentage.

**Comment by orimarco** [comment]
This is actually without constructors already.

Columns 4 and 5 show statistics about methods with n statements -  what percentage of the methods are with n statements? what percentage of the statements do methods with n statements cover? (Those columns have no connection to Nano Patterns but to general statistics on methods).

**Comment by yossigil** [comment]
where is the numer 62% in the table?

**Comment by yossigil** [comment]
I guess we need another column: what's the fraction of methods with 1 statement

**Comment by orimarco** [comment]
(I assume you mean adding the column to the first table)

**Comment by orimarco** [comment]
# Commons-lang - anlysis
![image](https://cloud.githubusercontent.com/assets/12089145/20917739/f2924604-bb9b-11e6-81c9-72cb50da00bc.png)

**Comment by orimarco** [comment]
# Commons-bcel - anlysis

![image](https://cloud.githubusercontent.com/assets/12089145/20917939/1e858806-bb9d-11e6-8ab1-08f9be7b9b5d.png)

**Comment by yossigil** [comment]
I am still having problems in understanding the tables. Closing this issue. Let's produce a LaTeX table with caption. or many tables.

**Comment by orimarco** [comment]
Does this explain? 😬 
![image](https://cloud.githubusercontent.com/assets/12089145/20923661/3eb02d16-bbb6-11e6-875c-0376ae968a48.png)

**Comment by yossigil** [comment]
Maybe, but we need LaTeX files,  and I have other comments....
e.g., missing % symbol.

**Comment by orimarco** [comment]
**Some LaTeX**
![image](https://cloud.githubusercontent.com/assets/12089145/21079490/916c862e-bf9b-11e6-851e-752be16373e6.png)

**Comment by orimarco** [comment]
```latex
\documentclass{article}
\usepackage{csvsimple}

\begin{document}

\section*{Nanos Analysis - Guava}
    \begin{tabular}{c|c|c|c}%
    \bfseries Statements & \bfseries \% of methods & \bfseries \% of statements & \bfseries \% coverage [Avg.]% specify table head
    \csvreader[head to column names]{methodStatistics.csv}{}% use head of csv as column names
    {\\\hline\csvcoli&\csvcoliv&\csvcolv&\csvcoliii}% specify your coloumns here
    \end{tabular}
\end{document}
```
