### ISSUE TITLE
il.org.spartan.spartanizer.cmdline->Essence.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by shaysegal** [SpartanRefactoring/Spartanizer#804]
we chose the code coverage of the file il.org.spartan.spartanizer.utils/Writer.java .
Please do not choose this file. :)

**Comment by sefialbo** [comment]
@yossigil someone deleted Writer and LogWriter including our tests, what should we do ?

**Comment by yossigil** [comment]
It was me. The class was defunct, and there was little to test in it anyway. Choose another class.

**Comment by shaysegal** [comment]
change to il.org.spartan.spartanizer.cmdline/Essence.java

**Comment by yossigil** [comment]
:+1:

**Comment by dshames** [comment]
I'm looking for the file to add a test but I can't find the file. 
Am I missing something? @yossigil

**Comment by yossigil** [comment]
which flle is missing?

**Comment by dshames** [comment]
both @sefialbo and @shaysegal committed changes for the file EssenceTest.java however the file is missing now

**Comment by dshames** [comment]
@yossigil can I just add my test and push the file back?

**Comment by yossigil** [comment]
💪go ahead

**Comment by dshames** [comment]
I checked the few things I didn't see were covered.
