### ISSUE TITLE
il.org.spartan.spartanizer.ast.navigate->have.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by kfir-marx** [SpartanRefactoring/Spartanizer#807]
we will make code coverage for il.org.spartan.spartanizer.ast.navigate.have.java  #799
current coverage ~ 33%

**Comment by yossigil** [comment]
make sure you follow the conventions for tests of this class

**Comment by ravivos** [comment]
Current coverage improved to - 86.2%.
Basically - we covered all lines in all of the functions.
Closing the issue.
