### ISSUE TITLE
il.org.spartan.spartanizer.java -> Term.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by zahimizrahi** [SpartanRefactoring/Spartanizer#808]
we chose the code coverage of the file il.org.spartan.spartanizer.utils/Term.java.
we also did #801 

Test Coverage for Term.java: 60.1%

I did the first one, now it's your turn to shine! @DavidCohen55  @Shahar-Y

**Comment by yossigil** [comment]
I vaguely remember writing many tests for this one. Make sure you search for current tests

**Comment by Shahar-Y** [comment]
@OriRoth 
We seem to have trouble with writing one of the tests. When we call the 'asExpression' method with 'true' parameter, the test fails. It seems to be we way we instantiate our expression. Please help :(

**Comment by OriRoth** [comment]
Do you have a test file? I could not find it. Where is it located?

**Comment by OriRoth** [comment]
Use `duplicate.of` when sending parameters to `Term`.
*Explanation*: (complicated, you don't have to read it)
* When creating a new ASTNode for some AST, it cannot have any sons from the original AST (only nodes which are new as well)
* For creating a negative version of the Expression, `Term` creates a new PrefixExpression and specify the Expression as its son
* Thus we get an error if the Expression is part of the original AST - this is exactly what you did
* The solution is to offer a *duplication* of the original Expression, which is regarded as a new node of the AST, so it can be a legitimate son of our new PrefixExpression

@yossigil maybe we can add to the code something like
```Java
assert expression.getClass() == null;
```
when creating a new `Term` (this is the way the AST checks the node is new).

**Comment by yossigil** [comment]
getClass never returns null!

**Comment by Shahar-Y** [comment]
note: test02 was added by me, through David's computer.

**Comment by OriRoth** [comment]
Corrected `getClass` -> `getParent`

**Comment by zahimizrahi** [comment]
@OriRoth  thank you for all your help. :)

**Comment by yossigil** [comment]
++K @OriRoth
