### ISSUE TITLE
 setting up the working environment of Lior Ben Ami

### ISSUE THREAD

**Issue by LiorBenAmi** [SpartanRefactoring/Spartanizer#809]
The working environment for this project includes
- [x] Linux
- [x] Eclipe Neon
- [x] Java 8 Programming
- [x] Formatting conventions
- [x] Spartan programming
- [x] Fixed cleanup routine
- [x] Highest level of warning settting
- [x]  Git command line
- [x] Telegram (might be changed by another messaging application)

**Comment by yossigil** [comment]
Make sure you use lables and milestone.

**Comment by yossigil** [comment]
How is it going?

**Comment by LiorBenAmi** [comment]
@yossigil : Done
