### ISSUE TITLE
 il.org.spartan.spartanizer.ast.navigate->haz.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by NetanelFelcher** [SpartanRefactoring/Spartanizer#810]
we will make code coverage for  il.org.spartan.spartanizer.ast.navigate.haz #799
code coverage percentage now: 53.8%

**Comment by yossigil** [comment]
I am not sure that this is a good class to test. Check where and why it is used in the project.

**Comment by NetanelFelcher** [comment]
Is this a better one? @yossigil

**Comment by yossigil** [comment]
:+1: Check if there are existing tests. I did not.

**Comment by yossigil** [comment]
keep up the good work :+1:

**Comment by yossigil** [comment]
:100:
