### ISSUE TITLE
il.org.spartan.spartanizer.engine -> MethodScanner.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by inbalzukerman** [SpartanRefactoring/Spartanizer#811]
We chose to increase the code coverage of the file il.org.spartan.spartanizer.engine/MethodScanner.Java

Current Test Coverage: 0.0%

Please do not choose this file 😄

**Comment by yossigil** [comment]
@inbalzukerman , @EliaTraore : did you notice the todo's / Karma I left you?

**Comment by inbalzukerman** [comment]
@yossigil - we did, and we're actually working on it right now 😄

**Comment by yossigil** [comment]
Great.
