### ISSUE TITLE
il.org.spartan.spartanizer.java -> precedence.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by RonGatenio** [SpartanRefactoring/Spartanizer#813]
We chose to increase the code coverage of the file il.org.spartan.spartanizer.java/precedence.java.
The current coverage is 85.3%

Please do not choose this file...

This is part of assignment 2 #799

**Comment by yossigil** [comment]
K-- Not cleaning up code before commit #584 #621

**Comment by yossigil** [comment]
Please start from `precedenceTest` and enrich it.
