### ISSUE TITLE
il.org.spartan.spartanizer.tippers->AssignmentAndReturn.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by koralchapnik** [SpartanRefactoring/Spartanizer#814]
we chose il.org.spartan.spartanizer.tippers->AssignmentAndReturn.java and currently it has no tests, so we'll create one

**Comment by koralchapnik** [comment]
@OriRoth

**Comment by yossigil** [comment]
#652  K-- Not cleaning up code before commit
#689 K-- Not cleaning up code before commit

**Comment by yaelAmitay** [comment]
Now we have about 96% coverage. 
We tried to check what happen if the assignment is in for loop, but the parent of the assignment is of type ExpressionStatement and the parent of the ExpressionStatement is ForStatement. In the code it looks like the expected parent of the assignment is ForStatement but as we said it doesn't.
We are probably missing something...
By the way if the assignment is in block(that belong to for loop) then the parenting goes like this:
ForStatement->Block->ExpressionStatement ->Assignment.

**Comment by OriRoth** [comment]
[Assignment](http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FAssignment.html) is an Expression, and [ForStatement](http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FForStatement.html) has an Expression son! Thus you can create a legacy as you described, like so:

![astview](https://cloud.githubusercontent.com/assets/15183108/20242520/636db022-a939-11e6-9a61-0a982c953c02.jpg)

BTW the tool I used in this screenshot is *ASTView*, an eclipse view you can install to better understand the Java AST (it translates your code into an AST).
As you can see in *ASTView*, the legacy is ForStatement->Assignment.

**Comment by yaelAmitay** [comment]
i meant something like that: 
int a;
for(;;)
    a=3;
return a;

**Comment by OriRoth** [comment]
It is not possible, because the Expression sons of ForStatement are located inside its parenthesis. What comes after the parenthesis is a Statement, thus cannot be an assignment (which is an Expression).

**Comment by OriRoth** [comment]
It is possible some code is unreachable - in that case it should be eliminated (though you have to be sure 100% it IS unreachable!).

**Comment by yaelAmitay** [comment]
what will the nextStatement be in the example I wrote? will it be "return a;"?

**Comment by OriRoth** [comment]
The next statement of the ForStatement is indeed the ReturnStatement.

**Comment by yaelAmitay** [comment]
So there is a case in which the nextStatement is "return a;" and the assignment is "a=3;" and the assignment is inside the block of the loop. In this case the function will delete the assignment and merge it with the return but it souldn't do it, no?

**Comment by OriRoth** [comment]
The Assignment is not ought to be in a Block, as in your example above.
I do not think your Tip can be applied here - there is no "assignment then return", although it looks similar.

**Comment by yossigil** [comment]
good job#169

**Comment by yossigil** [comment]
good job for great coverage👏 to all
