### ISSUE TITLE
il.org.spartan.spartanizer.engine -> NameGuess.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by amirsagiv83** [SpartanRefactoring/Spartanizer#815]
We chose to increase the code coverage of the file il.org.spartan.spartanizer.engine/NameGuess.Java

Current Test Coverage: 0.0%

Please do not choose this file 🐷

**Comment by yossigil** [comment]
#624 K-- Not cleaning up code before commit
#619 K-- Not cleaning up code before commit

**Comment by amirsagiv83** [comment]
Upgraded the coverage to 90.4% ! :open_mouth:  :tired_face:  :israel:  :pig2: 
@orenafek

**Comment by yossigil** [comment]
You missed class `NameGuessTest`...

Please consolidate your work into `NameGuessTest` and follow the style there as much as possible.

@orimarco , @AdiOmari @yh-github @zvili @idabran, FYI

**Comment by amirsagiv83** [comment]
You are right, Sorry, We did not notice it because it was not in the src/test/engine directory.
It appears the NameGuessTest covers 70% of NameGuess's code. Is it ok if We Just merge our tests (without tests that alreasy exist) into the NameGuessTest so it will be 90.4% coverage? or are we supposed to choose another .java file?
@yossigil  @orenafek

**Comment by yossigil** [comment]
Sure.
Move the test file to where it belongs.
Move your tests into the existing test file.
Try to make your tests in the style of NameGuessTest

**Comment by amirsagiv83** [comment]
Do you mean you want us to move NameGuessTest.java to src/test/engine directory?
@yossigil
