### ISSUE TITLE
/Spartanizer/src/main/java/il/org/spartan/spartanizer/cmdline/TrimmerLog.java (Assignment 2) Code Coverage #799

### ISSUE THREAD

**Issue by michalcohen** [SpartanRefactoring/Spartanizer#816]
We chose to increase the code coverage of the file /Spartanizer/src/main/java/il/org/spartan/spartanizer/cmdline/TrimmerLog.java
The current coverage is 67.7%

**Comment by michalcohen** [comment]
Increased coverage to 73%

**Comment by yossigil** [comment]
#564 Bad Karma for using DOS and for Committing failed tests.
#565 Bad Karma for using DOS and for Committing failed tests.

@orimarco, @zvili @idabran @AdiOmari : FYI.

**Comment by michalcohen** [comment]
נשמח להיפגש כדי לברר מדוע דבר כזה קרה מפני ש**אף אחת מאיתנו** לא עובדת עם DOS (אני עובדת בVM עם הלינוקס שאתם נתתם לנו את הלינק שלו ואנה עובדת עם MAC) ובנוסף הטסטים עברו אצל שתינו.
נשמח להתייחסות ולהבנה.
@yossigil

**Comment by yossigil** [comment]
Bad Karma is not bad Grade! Bad Karma means you did something wrong. Doing something wrong is OK for students, unless it persists.... the idea is to chastise, not punish neither penalize (at least in initial stages)

I do not know what happened, but I found CR/LF on this file.
Check in the file again, and I will get to it in my next batch.

**Comment by yossigil** [comment]
I think there was a class named `TrimmerLogTest` or something, expand it.
