### ISSUE TITLE
il.org.spartan.spartanizer.tippers -> InfixExpressionConcatentateCompileTime.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Spartanizer#818]
We chose to increase the code coverage of ~~MultipleReplaceCurrentNode.java~~ InfixExpressionConcatentateCompileTime.java

the current coverage is 0.0%

please do not choose this file {(>_<)}

**Comment by Roei-r** [comment]
We've decided to change the chosen file from **il.org.spartan.spartanizer.tipping.MultipleReplaceCurrentNode.java** to **il.org.spartan.spartanizer.tippers.InfixExpressionConcatentateCompileTime.java** which currently is at 0% code coverage

**Comment by RoeyMaor** [comment]
code coverage is now 92.1%
