### ISSUE TITLE
il.org.spartan.spartanizer.utils-> Str.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by IdanAtias** [SpartanRefactoring/Spartanizer#819]
We chose to increase coverage of /Spartanizer/src/main/java/il/org/spartan/spartanizer/utils/Str.java.
Current coverage is 50%

**Comment by IdanAtias** [comment]
Done.
Increased coverage to 100%

**Comment by yossigil** [comment]
#759 : You have no Karma page. You did not cleanup the code.
@IdanAtias : You have no Karma page. Bad.

**Comment by yossigil** [comment]
Karma -= epsilon ;-) #759 
@zvili : can you please check why @IdanAtias  has no TODOs page?

**Comment by IdanAtias** [comment]
@yossigil I actually do have a Karma page. plz have a look at it : #659
And it is also a TODOs page, isn't it ?

**Comment by yossigil** [comment]
OOPS, don't know why I could not find it. Thanks.

**Comment by IdanAtias** [comment]
@yossigil so ++Karma ? :)

**Comment by yossigil** [comment]
Karma, as you should realize, is a joke... We want to make sure you work on a positive gradient.  No one sits and manages a bank account of Karma. Not one feeds the "total" karma, into a calculator to get a grade. There is no such thing as total Karma.

All that there is a total impression of your work. If you work fine, if you are not an `askhole` nor a `bugger`, and  you cooperate, that's great. If you don't, and try to do the absolute minimum, in such a fashion that makes other work hard to cover up for your laziness/incapability, or whatever, then you are bad.

In the current case,  you used Windows without being professional enough not to impact the project: not a big deal if this happened once. 

I scan the project regularly using various teachniques. This means that I scan some 100 issues about four or five times a day. When I see something that appears to be a problem, I try to make the quickest correction. But, just as anyone else, I can err. If I err a lot then I gain bad Karma. If I err rarely, and fix quckly, I keep good Karma.

Hope this clarifies things:

@inbalzukerman , @zvili , @orimarco @OriRoth @MosheEliasof @shimonAzulay @AdiOmari @idabran : FYI.

**Comment by IdanAtias** [comment]
@yossigil Understood.
but just fyi, we are using ONLY ubuntu. No Windows os involved here.
so i am a bit surprised by what u said....dont really know how this could happen.

**Comment by yossigil** [comment]
Can't explain it either, but the fact remains...

**Comment by yossigil** [comment]
Good job so far :+1:

**Comment by shimonAzulay** [comment]
@yossigil increased code coverage to 100% :)

**Comment by yossigil** [comment]
:100: not only for that but also for your total cooperation so 2 x :100:
