### ISSUE TITLE
il.org.spartan.spartanizer.engine -> Linguistic.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by rodedzats** [SpartanRefactoring/Spartanizer#820]
We chose to increase the code coverage of Linguistic.java. the current coverage is 0.0%. please don't choose this file.

**Comment by yossigil** [comment]
:+1:

**Comment by yossigil** [comment]
#644 #613 take a bit of bad Karma on @rodedzats  not having a TODO page.
:-1:

**Comment by ZivIzhar** [comment]
He actually do have a TODO page #656 @yossigil

**Comment by yossigil** [comment]
Thanks, I missed that.

**Comment by yossigil** [comment]
Make sure you find current tests for this class

**Comment by yossigil** [comment]
:100: to all, pending checks.
