### ISSUE TITLE
Suppressing static-methods in unit test

### ISSUE THREAD

**Issue by orenafek** [SpartanRefactoring/Spartanizer#821]
When a test created using the "@Test" annotation, the method must be `public void f()`. 
Eclipse makes a warning about making a method in which no instance members are used, and recommends making it `static`. can we commit with a `@SuppressWarinings("static-method")` in this case ?

@orimarco

**Comment by yossigil** [comment]
You can.

Though, you issues is not the optimal way to deal with such queries. #624 K--
Your issue has no deadline nor labels.

**Comment by yossigil** [comment]
You could have figured this out yourself, by checking many many test class in the repository. Please try to be independent. Lesson for #624: explore and investigate before asking.

If you examine other test files you will see that we use `SuppressWarnings` one for class.
