### ISSUE TITLE
il.org.spartan.spartanizer.ast.navigate-> metrics.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by matityahuinba** [SpartanRefactoring/Spartanizer#823]
We chose to increase the code coverage of the file /Spartanizer/src/main/java/il/org/spartan/spartanizer/util/Counter.java
The current coverage is 0.0%
Notice - this file not in use!

Update -
We chose to increase the code coverage of the file /Spartanizer/src/main/java/il/org/spartan/spartanizer/ast/navigate/metrics.java
The current coverage is 67.0%

**Comment by yossigil** [comment]
:+1:

**Comment by matityahuinba** [comment]
after a long time of assuming, wondering, and mainly confusion (which file is the main test?!),
we decide to change our file!

**Comment by matityahuinba** [comment]
We just want to clarify - we have only one commit to do, but all the three of us worked together :)
Mission accomplished!

**Comment by yossigil** [comment]
If you got to class Counter and press Ctrl-Shift-G, you will find that it used no where. Class `Counter` should therefore have been removed and so is your test. Your test class does not even check what `Counter` is supposed to do.

To gain Karma, you should erase both, and apply tests to some class that:
- really does something
- tested against the thing it is supposed to do.

**Comment by tomnof** [comment]
@yossigil  - Done. We did not notice that the Counter class is not being used. Thank you for pointing this out.
Can you please recommend a different class to test? We found it hard to pick one that fits.

**Comment by yossigil** [comment]
See facebook. Karma++.

**Comment by yossigil** [comment]
You are committing warnings. Please setup your workdspace:
![image](https://cloud.githubusercontent.com/assets/12775400/20238545/d97a1bd6-a8f6-11e6-967c-17186c9af873.png)

#533 #521

**Comment by matityahuinba** [comment]
Sorry! my mistake! Thank you!

**Comment by tomnof** [comment]
@yossigil 
I've added some code to the class itself (null pointer check). Please let me know if I shouldn't have done so.

**Comment by yossigil** [comment]
Excellent job :100: #556 #521 #533
