### ISSUE TITLE
il.org.spartan.spartanizer.engine -> ExpressionComparator.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by danabramovich** [SpartanRefactoring/Spartanizer#824]
We chose to cover the code of the file il.org.spartan.plugin/src/main/java/il/org/spartan/spartanizer/engine/ExpressionComparator.java for issue #799 .

**Comment by yossigil** [comment]
Not easy, but not too difficult. Good luck

**Comment by assaflu** [comment]
started from 45% code coverage

**Comment by danabramovich** [comment]
we went from 45% code coverage to 93.6% code coverage!

**Comment by yossigil** [comment]
:100: to all, pending later discoveries...
