### ISSUE TITLE
il.org.spartan.spartanizer.ast.navigate -> count.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by Kolikant** [SpartanRefactoring/Spartanizer#825]
We chose to cover the code of the file 
il.org.spartan.spartanizer.ast.navigate -> count.java for issue #799

**Comment by Kolikant** [comment]
I changed the class name to Issue825 before, Git though didn't upload that change

**Comment by yossigil** [comment]
#538 , #539 , Karma -= epsilon ;-)
