### ISSUE TITLE
No Safety Check for Identical if-else Branches

### ISSUE THREAD

**Issue by yosefraisman** [SpartanRefactoring/Spartanizer#826]
Before Spartanization:
```
	return changeGlobal() ? adder1 + adder2 : adder1 + adder2;
```
After "Tip: Eliminate conditional expression with identical branches":
```
	return adder1 + adder2;
```
Which can be problematic if `changeGlobal()` has an effect other than returning a boolean (e.g. if it does `++globalVariable`) @yossigil @OriRoth

**Comment by yosefraisman** [comment]
Same issue with "Tip: Consolidate common prefix of then and else branches to just before if statement"
Before Spartanization:
```
public class Test {
	static boolean check(int n) {
		return true;
	}

	public static void main(String[] args) {
		int i = 0;
		if (check(++i))
			System.out.println(i);
		else
			System.out.println(i);
	}
}
```
After:
```
public class Test {
    static boolean check(int __) {
        return true;
    }

    public static void main(String[] args) {
        System.out.println(0);
    }
}
```
Which ends up printing 0 instead of 1

**Comment by OriRoth** [comment]
Now go and fight some Persians.

**Comment by yossigil** [comment]
I will not touch, not at this stage. We should decide what it is to be done, if the user creates weird code such as this.

**Comment by yossigil** [comment]
#616 Karma++

**Comment by yossigil** [comment]
Let's go for it.

**Comment by yossigil** [comment]
@OriRoth 
@dormaayan

**Comment by tomerdragucki** [comment]
@yossigil Bugs solved using `SideEffects.free` util.
