### ISSUE TITLE
il.org.spartan.spartanizer.ast.navigate->analyze.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by viviansh** [SpartanRefactoring/Spartanizer#827]
we will make code coverage for il.org.spartan.spartanizer.ast.navigate->analyze.java #799

**Comment by yossigil** [comment]
How is it going? Did  you fix the TODOs you were given?

**Comment by ward-mattar** [comment]
The warnings in the test file "Issue692.java" were fixed, but in "getAll.java" we can't see link {@link step} did you mean [this](http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FMethodInvocation.html) ?

**Comment by matityahuinba** [comment]
hi other team! please note that our team is already working on this class :(

**Comment by ward-mattar** [comment]
Hi, sorry for the mix up, we'll change it!

**Comment by yossigil** [comment]
Change the milestone to sprint 0

**Comment by ward-mattar** [comment]
We added tests, and fixed a bug in 'type' method, in the case where the name was not found in a method declaration.

**Comment by yossigil** [comment]
ISSUE OPEN TWO DAYS AFTER MILESTONE>

**Comment by yossigil** [comment]
:+1:
