### ISSUE TITLE
il.org.spartan.spartanizer.utils-> Int.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by AviadCo** [SpartanRefactoring/Spartanizer#829]
We chose to increase coverage of /Spartanizer/src/main/java/il/org/spartan/spartanizer/utils/Int.java.
Current coverage is 18.8%

**Comment by yossigil** [comment]
Are you sure that this is the best class to demonstrate your skills?

**Comment by AviadCo** [comment]
we looked at the percentage (18.8%), and we can reach there to 100%.
we will choose another one :)

**Comment by yossigil** [comment]
It took me 3 min todo... check out the code. Sorry, you have to find something better.
