### ISSUE TITLE
il.org.spartan.spartanizer.ast.safety-> iz.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by AviadCo** [SpartanRefactoring/Spartanizer#830]
We chose to increase coverage of /Spartanizer/src/main/java/il/org/spartan/spartanizer/ast/safety/iz.java.
Current coverage is 73.9%

**Comment by AviadCo** [comment]
@yossigil Yossi, is this challenging enough?

**Comment by yossigil** [comment]
Good enough!

**Comment by ravivos** [comment]
Current coverage improved to - 86.2%.
Closing the issue

**Comment by noamyft** [comment]
Finished code coverage of /Spartanizer/src/main/java/il/org/spartan/spartanizer/ast/safety/iz.java.
Current coverage is 83.4%
