### ISSUE TITLE
il.org.spartan.spartanizer.utils -> Int.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#832]
We weill increase code coverage of il.org.spartan.spartanizer.ast.factory -> make.java for #799

**Comment by yossigil** [comment]
I trust this was taken already.

**Comment by kobybs** [comment]
Update: We will increase code coverage of il.org.spartan.utils -> Int.java for #799

**Comment by yossigil** [comment]
Good job so far :+1: (pending later checks)
