### ISSUE TITLE
il.org.spartan.spartanizer.cmdline -> code.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by SharonKL** [SpartanRefactoring/Spartanizer#833]
We will take this class if its ok @yossigil #799 
In addition, could you help us understand what is the purpose of the last three calls to the `String#replaceAll` in the `code#essence` method:

`
.replaceAll("\\([^a-zA-Z¢$_]\\) \\([^a-zA-Z¢$_]\\)", "\\([^a-zA-Z¢$_]\\)\\([^a-zA-Z¢$_]\\)")
        .replaceAll("\\([^a-zA-Z¢$_]\\) \\([a-zA-Z¢$_]\\)", "\\([^a-zA-Z¢$_]\\)\\([a-zA-Z¢$_]\\)")
        .replaceAll("\\([a-zA-Z¢$_]\\) \\([^a-zA-Z¢$_]\\)", "\\([a-zA-Z¢$_]\\)\\([^a-zA-Z¢$_]\\)");
`

We (hopefully) understand it discards the space between expressions like `(4) (5)`, but do not understand the purpose of this action.

**Comment by yossigil** [comment]
Workout the semantics of re-exp in Java, try to figure out what the function is supposed to do, and you will know whether this is a bug or not.

**Comment by yossigil** [comment]
Take note that in order to make thorough testing, you must deal with all awkward cases of quotes, escapes, strings, comments etc in Java.

**Comment by yossigil** [comment]
Great job so far. If it is too tough, don't worry. Just document that you don't deal with quotes.

**Comment by SharonKL** [comment]
I tried to remove the conditional, replacing
`$.trim().isEmpty() ? 0 : $.trim().split("\\s+").length;`
with
`$.trim().split("\\s+").length`
but then 1 was returned for the empty string (because the result of `split()` was an array with one empty string).

**Comment by ylevv** [comment]
We think maybe there is a bug at:
`.replaceAll("(\\([^a-zA-Z¢$_]\\)) (\\([^a-zA-Z¢$_]\\))", "$1$2")
.replaceAll("(\\([^a-zA-Z¢$_]\\)) (\\([a-zA-Z¢$_]\\))", "$1$2")
.replaceAll("(\\([a-zA-Z¢$_]\\)) (\\([^a-zA-Z¢$_]\\))", "$1$2")`
Is it possible that the parenthesis were not supposed to be escaped but instead to group the reg-exes?

**Comment by yossigil** [comment]
#598 : very good job in raising this point.

The code is quite ancient: no one really understands it. So, do your best to leave it in a better shape. Still, I think it might be correct.

Note that you want the regexp interpreter to receive a backslash followed by something. So, it may be necessary to escape the backslash. 

If you have good enough tests, they will detect that. Conversely, write a test that makes the distinction clear.

Cheers!

**Comment by SharonKL** [comment]
@yossigil After looking at other parts of the project, we believe the `essence` function is a "conceptual duplicate" of the `of` function found in the `Essence.java` file:

https://github.com/SpartanRefactoring/Spartanizer/blob/master/src/main/java/il/org/spartan/spartanizer/cmdline/Essence.java

In addition, `code.essence()` is being called only twice in the whole project. Do you want us to replace these calls with a call to the `Essence.of()` function which seems to be written and documented better?

**Comment by yossigil** [comment]
:100:

**Comment by yossigil** [comment]
consolidate them in a way that would maximize the number of running tests

**Comment by yossigil** [comment]
But this is optional not required
