### ISSUE TITLE
Creating Block nodes using wizard.ast

### ISSUE THREAD

**Issue by tomerdragucki** [SpartanRefactoring/Spartanizer#836]
`wizard.ast` fails to create proper blocks from strings.
It wraps the block with another block.
for example this:
```Java
az.block(wizard.ast("{return 1;}"))
```
returns
```Java
{
  {
   return 1;
  }
}
```

@OriRoth  said:

@dormaayan its not only an empty-block issue. Talk to Yossi if you think it is too complicated to solve on the fly.

@yossigil this bug prevents us from completing our exercise #835, we prefer not to use some sort of bypass but rather wait for proper solution.

**Comment by dormaayan** [comment]
@tomerdragucki 
@OriRoth 
@yossigil :
Solved the bug, you can keep working

**Comment by mdoron** [comment]
Great, we can proceed now. 
Grazie

**Comment by yossigil** [comment]
K |= (1 << 31) #133

**Comment by dormaayan** [comment]
@yossigil 
What did you mean ?

**Comment by yossigil** [comment]
read this as c
