### ISSUE TITLE
Study the Spartanizer plugin

### ISSUE THREAD

**Issue by michalcohen** [SpartanRefactoring/Spartanizer#840]
- What are the main classes?
- How does the plugin mark the code of the user?

**Comment by michalcohen** [comment]
I coulsn't think of more specific questions, you may refer to more aspects as you dive into code

**Comment by yossigil** [comment]
@OriRoth shoudl be able to help here.
@orenafek talk to him.

**Comment by OriRoth** [comment]
@yossigil I think we should organize a Spartanizer intro, as the one I got when I started working :P was very helpful. I don't mind taking care of it, I just need a full list of future Spartans.

So you're moving the project to IntelliJ?

**Comment by yossigil** [comment]
Yes, we are checking the option of moving to IntelliJ. Students seem enthuiastic, serious and strong, so we give this a try. 

@dormaayan, perhaps we can organize the session with your group?

**Comment by dormaayan** [comment]
@yossigil :
Do you mean you want our group to convert the Spartanaizer to  work on IntelliJ ?

**Comment by OriRoth** [comment]
*Useful Stuff*:
* https://plugins.jetbrains.com/category/index?pr=idea&category_id=51

**Comment by yossigil** [comment]
@dormaayan : no there is another group that does that. As part of their training they are to study this

**Comment by orenafek** [comment]
As @OriRoth  stated, he is planning on making a guided tour to the architecture of the project.
I believe that no one is better for this issue.
@yossigil : is it ok for you, that for now i'll be assisting in the other issues ?
@michalcohen : is possible, reassign me in another issue, where i can be more helpful.

**Comment by yossigil** [comment]
Good point. @michalcohen @orenafek try to find something with "folks" label.

**Comment by yossigil** [comment]
I pretty much know it all, so if you do not study it, I can make up for you

**Comment by yossigil** [comment]
@orenafek: what's the stat of this one?

**Comment by orenafek** [comment]
Still waiting for @OriRoth to give his lecture to all of the Spartan related teams of the YP, as he suggested.

**Comment by yossigil** [comment]
Closing this for now
