### ISSUE TITLE
How does the Tippers work?

### ISSUE THREAD

**Issue by michalcohen** [SpartanRefactoring/Spartanizer#842]

**Comment by yossigil** [comment]
I think the best completion would be a in a good doc for clas 'Tipper' and its main descendants.
You would also have to check out class `Trimmer` and talk to @orimarco since dispatching works is also applied in other ways.

**Comment by michalcohen** [comment]
You mean that I'll write the javadoc to the methods of those classes?

**Comment by yossigil** [comment]
Or, the class. I think we have a decent start already.

**Comment by OriRoth** [comment]
See #331, hopefully a clarification will be provided in future Spartanizer walkthrough.

**Comment by yossigil** [comment]
What's the current state of this? In progress? On hold? Done?

**Comment by michalcohen** [comment]
There are many classes, so I documented the highest level classes. If it helps the Spartan project I might continue document during the semester. This is why I hadn't closed the issue.

**Comment by yossigil** [comment]
It is better that we close it now. The main purpose, i.e., that you understand it, was achieved.
