### ISSUE TITLE
How does Leonidas work?

### ISSUE THREAD

**Issue by michalcohen** [SpartanRefactoring/Spartanizer#845]
- How can we use it to minimize the work on the "new" plugin for IntelliJ?
- Is its engine portable with IntelliJ?

**Comment by yossigil** [comment]
I think the best result is 1 page (max), Wiki page, in the current project.

**Comment by orimarco** [comment]
They are actually tippers 😄

**Comment by yossigil** [comment]
I mean interpeted `Leonidas

**Comment by yossigil** [comment]
What about Leonidas Says?

**Comment by RoeiRaz** [comment]
I've studied the classes **leonidasSays**, **TipperFactory**, **Matcher**. These 3 classes implement features that are related to the 'pattern matching' tipping technique which we talked about during the meeting.

In a nutshell:

- **Matcher** is used to match between patterns and nodes, and also to link between variables within the pattern and the relevant element within a code snippet.
- **TipperFactory** is used to create tippers that can "transform" a node from one pattern to another.
- **leonidasSays** seems like an abstraction layer to TipperFactory and Matcher that allows operations to look like sentences in English (its actually quite neat :+1:)

I added javadoc to these classes, and to methods that I thought were important.

@yossigil Waiting for your input (should I write more documentation or move on to a more critical assignment?)

@michalcohen Regarding your questions, these 3 classes are heavily dependent on **ASTNode** so it probably isn't portable with intellij. I don't see how we can use it to minimize our work.

**Comment by yossigil** [comment]
@orimarco is the expert. What do you say?

**Comment by orimarco** [comment]
**Leonidas** lets you match and replace a pattern using strings instead of a big pile of code.
ask @orenafek 

If you implement **Leonidas** using your new platform, all tippers that are defined with **Leonidas** will work on both platforms!

Of course you're going to need to convert existing tippers to Leonidas, which is not that hard.

**Comment by yossigil** [comment]
I think this is good enough.
