### ISSUE TITLE
Organize Labels

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#846]
We should decide whether to create a label per group, can be useful. Some group already done so - there should be a uniformity, and each group should have one label at most (? probably).

@yossigil please note your decision here.

**Comment by OriRoth** [comment]
I have created `group1`, michal has created `initial-training` and `intellij`.

**Comment by yossigil** [comment]
How about using projects?

**Comment by OriRoth** [comment]
@michalcohen do you want to create a project for your group? We want to reduce labels count so consider using a project rather than labels.

**Comment by michalcohen** [comment]
If it is ok by @yossigil I think the group had preferred some measure of separation.
Can I add new project?

**Comment by OriRoth** [comment]
@michalcohen you can open a project for your group. Its up to you to decide level of separation- you can do this by:
* Simply assign different issues to different group members
* Open different **column** for each group member

The project idea just make it easier to track issues related to your group. Also it can help us reduce number of labels which is, at the moment, absurd.

**Comment by yossigil** [comment]
@dormaayan, Talk to @OriRoth. In fact, why won't the three of you discuss policies? @michalcohen

**Comment by dormaayan** [comment]
@OriRoth , @michalcohen :
We consider using a new project to manage everything when the tasks will become serious, but I think for now, (until we will think on the best way to manage the columns of the project) to use a 
label of "Team-2", is that ok ?

**Comment by OriRoth** [comment]
I suggest establishing a project right away, but of course you can just yolo it with a label.
Project seams a bigger deal, but actually easier and less costly to create and delete.

**Comment by dormaayan** [comment]
Ok I will create aproject today

**Comment by yossigil** [comment]
Ok. Done for now.
