### ISSUE TITLE
Wiki article: The Working of Leonidas

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#851]
Start from #845 and convert it into a wiki article.

**Comment by yossigil** [comment]
Yuval any progress?

**Comment by yossigil** [comment]
@dormaayan, seems as if @yuvalsimon  needs a hand here. This should have been an hour at most.

**Comment by dormaayan** [comment]
@yossigil : Sure, @yuvalsimon : If you want any help please talk to me, we can meet at the beginning of next week or you can ask me on telegram/here

**Comment by yossigil** [comment]
@yuvalsimon : what's going on?

**Comment by yuvalsimon** [comment]
The wiki page: https://github.com/SpartanRefactoring/Spartanizer/wiki/Leonidas:-tipper-factory-and-pattern-matching
