### ISSUE TITLE
ranges

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#853]
```Java
for(int $N = $L1; $N < $L2; ++N)
   $B
```
into
```Java
for(Integer $N : range.from($L1).to($L2))
   $B
```

**More options:**

- `from($L1).to($L2).inclusive()`
- `from($L1).to($L2).[inclusive()].when($X)`
- `from($L1).step($L3).to($L2)`
- `from($L1)`
- `to($L2)`
- ` from($L1).to($L2).and.from($L3).to($L4)`

To be implemented using classes and fluent API, the idiomatic way.

**Comment by orimarco** [comment]
#877

**Comment by danabramovich** [comment]
@orimarco when I try to extract $B from the pattern, like this:
`¢.getMatching(x, "$B")` (where `¢` is the tipper and `x` is ForStatement)
I get `null`. Do you have any idea why is this happening?

**Comment by danabramovich** [comment]
`¢.getMatching(x, "$L1")` returns `null` also

**Comment by danabramovich** [comment]
@orimarco One more thing: it seems like the pattern `--$N` can fit for both `--¢` and `¢-=2`, which makes writing tests difficult (even impossible for some cases)

**Comment by orimarco** [comment]
That's wierd...
You are welcome to fix this if you can...
Otherwise, I will get to it somewhen...

**Comment by orimarco** [comment]
Next time please write a test that causes the failure!

**Comment by yossigil** [comment]
Closing this. Not so essential at this stage.
