### ISSUE TITLE
KNN pattern classifier

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#854]
Given a Node, figure out what is its closest pattern.

## Option 1:

Given a set of patterns **p_1, ..., p_k** and a node **n**, 
for each **p_i** try matching **p_i** and **n**:

- if similiar - finished.
- else - matching has failed in some depth, denote this depth as **d_i**

return **p_i** which for, **d_i** is maximal.

**Comment by orimarco** [comment]
Great idea @orimarco, maybe another time.

**Comment by yossigil** [comment]
Indeed, amazing idea: you can advise student how to do it
