### ISSUE TITLE
Inline expression into later statement even if not consecutive

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#856]
For now, this happens only if statements are consecutive.

Of course we need to verify that statements between doesn't affect the inlined expression.

**Comment by yossigil** [comment]
actually, inlining from s_i to s_j could be more difficult, if s_k , i < k < j, relies on s_i running before.
So, I would suggest inlinding to s_{i+1} even if s_{i+1} is not the last statement, but it is the last time it is used.

**Comment by orimarco** [comment]
example:
```jAvA
  public static String yay() {
    String res = "one expression";
    System.out.println(res);
    return "and another";
  }
```
into:
```javA
  public static String yay() {
    System.out.println("one expression");
    return "and another";
  }

```

**Comment by dormaayan** [comment]
@orimarco :
I suspect you just pushed a test that fails...
