### ISSUE TITLE
[ if (false) s; ] => []: a "no impact" wring

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#86]
Should not be in "real" code.

Dor: I see that you are catching with stuff. Can you do this one using class Subject that you documented,.
Feel free to share with @Phantom1472  and @NivShalmon

**Comment by yossigil** [comment]
This seems be buggy. Can you add here a reference to the tests?

**Comment by dormaayan** [comment]
@yossigil  :
Im was originally assigned to that but from a reason I don't understand @sakopzon took that issue...
I don't have any idea where the tests are ask @sakopzon

**Comment by sakopzon** [comment]
under TrimmerTests250

**Comment by yossigil** [comment]
No worry, just fix the tests

**Comment by sakopzon** [comment]
Everything works

**Comment by yossigil** [comment]
Try this one:
```java
	public int removeDeadCodeAfterIfFalseWithThrow(int i) {
		if (false)
			i++;
		else {
			System.out.println(i);
			throw new RuntimeException();
		}
		return 2;
	}
```

It does not work for me.

**Comment by yossigil** [comment]
The bug is still there...

**Comment by yossigil** [comment]
@sakopzon
