### ISSUE TITLE
Sorting of labels in the same branch

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#860]
From
```java
switch (E) {
  case b: 
  case a:
    something();
    break;
default:
    somethingElse();
    break;
}
```
to 
```java
switch (E) {
  case a:
  case b: 
    something();
    break;
default:
    somethingElse();
    break;
}
```
Sorting order should be first by label length, and only then alphabetically

**Comment by yuvalsimon** [comment]
@yossigil The current implementation sorts in such a way that it swaps each time two adjacent cases of the branch, so for example the conversion for the following will be:
```
switch(x) {
case 3:
case 2:
case 1:
}
```
=>
```
switch(x) {
case 2:
case 3:
case 1:
}
```
=>
```
switch(x) {
case 2:
case 1:
case 3:
}
```
=>
```
switch(x) {
case 1:
case 2:
case 3:
}
```
Do you prefer it this way or to put each case in it's final place from beggining (for example taking the minimum case from the nonsorted yet cases and put it in it's place)?

**Comment by yossigil** [comment]
No, small movements are even better.
However, make sure you only highlight the code you change, not the entire switch

**Comment by yuvalsimon** [comment]
@yossigil Alright now?

**Comment by yuvalsimon** [comment]
I will also change the hightlighting issue for RemoveRedundantSwitchCases later.

**Comment by yossigil** [comment]
Don't know. I cannot run the spartanizer any more...

**Comment by yuvalsimon** [comment]
Ok I changed RemoveRedundantSwitchCases to highlight exactly as this tipper does

**Comment by yuvalsimon** [comment]
Should I put methods I use for all switch tippers in extract class?

**Comment by yossigil** [comment]
Thanks.

**Comment by yossigil** [comment]
Yuval: I have to reopen this. Sorry. Tests fail

**Comment by yuvalsimon** [comment]
Fixed, one of the tests checked firstly the switch branch sorting so it failed because it is not in toolbox. 
@OriRoth Is there a way to to use trimmer.using only once such that it would work for all the next gives? (check https://github.com/SpartanRefactoring/Spartanizer/commit/c60dada3568c245947614fb35dc88e5e246e0610) It would be better, isn't it?

**Comment by yossigil** [comment]
use trimmingOf.using

**Comment by OriRoth** [comment]
Notice there are currently two `trimmingOf(...).using(...)` methods: `using(Tipper)` and `using(Class<ASTNode>, Tipper)`. The first one does indeed require you to have the tipper in the toolbox! So use the second.
