### ISSUE TITLE
Short tip descriptions ==> Into WIKI

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#862]
Please keep tips' descriptions as short as possible. Inserting code into description --> makes description long --> makes marker resolutions menu unusable! (unless you are **sure** the code is short).
#188 #308 @dormaayan please fix.
Also show this to your gang for extra karma.

**Comment by dormaayan** [comment]
@OriRoth :
Ok I will fix that !

**Comment by dormaayan** [comment]
Please mark here that you saw the important remark of @OriRoth , and remember that when writing tips :

- [ ] @SapirBismot 
- [ ] @yuvalsimon 
- [ ] @danabramovich 
- [ ] @kobybs 

(How is my karma now, The karma man (@OriRoth)  ?)

**Comment by yossigil** [comment]
- [ ] @orimarco 

- [ ] @amirsagiv83 

- [ ] @orenafek

**Comment by yossigil** [comment]
Let's convert this into an action item, asking someone to go over the description. @OriRoth, I think this is small enough to serve as an introductory exercise for @tomerdragucki or @mdoron or @ravivos or @kfir-marx

**Comment by OriRoth** [comment]
@tomerdragucki Find relevant wiki under "Developer guide" and add it there.

**Comment by tomerdragucki** [comment]
Added as part of the reorganizing of the project's wiki
