### ISSUE TITLE
Eclipse tricks

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#864]
I now some of those [tricks](http://gnuarmeclipse.github.io/developer/eclipse/tips-tricks/) are life saving, worth having a look at it.

**Comment by yossigil** [comment]
@ravivos: please close this by moving/creating a wiki

**Comment by ravivos** [comment]
Done.
Added a wiki for the tricks, Copied to it some tricks  I thought might be necessary and added a link to the original document as an appendix.
[Link to wiki](https://github.com/SpartanRefactoring/Spartanizer/wiki/Some-Eclipse-Tips-&-Tricks)

**Comment by yossigil** [comment]
:+1:
