### ISSUE TITLE
Convert Nano: isn't this Map?

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#865]
from 
```java
  private static List<Expression> peel(final List<Expression> xs) {
    final List<Expression> $ = new ArrayList<>();
    for (final Expression ¢ : xs)
      $.add(peel(¢));
    return $;
  }
```
to 
```java
  private static List<Expression> peel(final List<Expression> xs) {
    final List<Expression> $ = xs.stream().map(minus::peel).collect(Collectors.toList());
    return $;
  }
```

**Comment by yossigil** [comment]
@dormaayan : You may want to think about this

**Comment by OriRoth** [comment]
Converting `peel(¢)` to `minus::peel` maybe tough. It require some utility class that checks imports (environment?). A simpler solution would be using Functions. Thus we get `peel(¢)` ==> `x -> peel(x)`.

**Comment by yossigil** [comment]
Good point. I am considering using binding information in some operations. For now, just implement a simple function that determines if a method can be written as `minus::peel`. The method should make a verysimple attempt. In the future, we may be able to extend it.

**Comment by yossigil** [comment]
I think this NP is in a sense a "select" of relational DB. I am changing the name accordingly.

**Comment by yossigil** [comment]
Oops, this is a Map,
but we still need 'Select Nano: return a sub collection with elements satisfying a certain condition'

**Comment by OriRoth** [comment]
I think you should change the label of this issue (?).

**Comment by orimarco** [comment]
Nano - `SelectBy` should cover this example.
