### ISSUE TITLE
Implement class 'range'

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#869]
Basic design: 'range' is abstract, and implements `Iterable<Integer>`, it has these fields:

1. `from` starting point, defaults to '0'
1. `to` ending point, no default
1. `inclusive` boolean, says whether `to` is included, default `false`
1. `step`, integer, default `1`, size of step

Lots of inner classes which should not be `static` to represent the legal steps
Lots of static methods representing protocol:

- `to(i+12)`
- `from(i).to(i+12).inclusive()`
- `range(3)`
- `to(i+12).from(3).notInclusive()`

**Comment by orimarco** [comment]
#853

**Comment by yossigil** [comment]
add two more methods:
- `kNaturals()` to return the Klingon naturals: 0, 1, ..., 
- `tNaturals()` to return the Trump naturals: 1, 2, ...,

**Comment by dormaayan** [comment]
@yossigil : Why should range be an abstract class ?

**Comment by dormaayan** [comment]
@yossigil : Why should range be an abstract class ? According to what I understand from above, we want to implement range only for integers... , isn't it much simple and more practical to implement it as a concrete class ?

**Comment by yossigil** [comment]
Here is the design I had in mind:
```java
class range {
  IntField from(0), /* other fields*/
  private range(range other) { /* copy ctor */}
  Q0 from(int from) { return new range.new Q0(..)}
  public class Q0  { 
   Q1 to(int n) { return new Q1() }
}
}
```
in this design, each state is an inner class, which has access to all fields of `range`. State transition is done by using the same common instance of `range`, to creae a new object of an inner class, which has reference to the same instance of the outer class (`range`) that does not change.

I hope this is clear

**Comment by dormaayan** [comment]
@yossigil :
Please have a look at my design, is it ok ?
(I saw your message after I already wrote it)

**Comment by dormaayan** [comment]
@yossigil : I think I'm done here, can we close or should I add more things ?

**Comment by yossigil** [comment]
Fields CANNOT be static. Write a test case with nested loop, e.g.,
``for (Integer i: to(10))
     for (Integer j: to(i))
       $ += i * j;
```

**Comment by dormaayan** [comment]
@yossigil : 

- When I turn all the fields to be non-static It turns that all the methods can't be static nighter, so now, in order to use range you need to create a concrete instance of it, and that's I guess not good for a fluent api...
I couldn't find any elegant way to combine non-static fields together with static methods, is there any elegant way to do that ?

- If I declare the inner classes as non-static, the methods inside them also can't be static inspire the fact we want them to be static

**Comment by yossigil** [comment]
You are right, the methods cannot be static. You have two kinds of methods: factory methods that generate a range (actually an inner class of range) and transition methods, defined in each of the state classes.'


Methods in inner classes should not be static. They should use `this` to find the instance of class `range` that contain the state class.

Here is an example:
```java
class range {
int from
 
class Q13 {
Q17 from(int n) {
range.this.from = n;
return range.this.new Q17();
}
}

**Comment by dormaayan** [comment]
@yossigil : Thanks, done

**Comment by dormaayan** [comment]
@yossigil :
Passed over the rewriting and fixed the tests.
Closed
