### ISSUE TITLE
Int with default

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#871]
Define and implement a class using TDD that supports the following

1. Constructor with default Value.
2. Ctor with no default value
3. hasValue(): boolean
2. intValue():  int throws exception if no set and no default
1. set(int v): void; can only be called once. illegal argument exception if called twice
6. hasDefault() 

You may want to create a hierarchy:

ParameterInt, ParameterIntWithDeault, ParameterIntWithNoDefault

**Comment by kobybs** [comment]
@yossigil  
about : intValue(): int throws exception if no set and no default
should I use one of the java.lang exceptions or create a new type?
same question about  "illegal argument exception".

**Comment by yossigil** [comment]
Existing exception

**Comment by kobybs** [comment]
@yossigil I'm currently using IllegalArgumentException for both. 
any idea for a better RunTime(it has to be) exception to describe the uninitialized intValue() or just keep it like that?

**Comment by yossigil** [comment]
keep it.

**Comment by kobybs** [comment]
@yossigil Done. check it out :)

**Comment by yossigil** [comment]
Looks ok. But, why no `@author`, `@since` and some documentation?

**Comment by kobybs** [comment]
@yossigil my bad. reopen if more changes are needed.
