### ISSUE TITLE
Generalize 'range' to 'ancestors'

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#874]
See existing code that does that. Your challenge is to also rewrite existing codes which  does a search on ancestors

**Comment by dormaayan** [comment]
@yossigil :
Just to make sure before I start : 
Did you mean that I will convert all the for loops that does searches on ancestors in the file `searchAncestors.java` to a fluent api of range (that is similar to what I already implemented, just not over Integers) ?

**Comment by yossigil** [comment]
Yes... All... But do convert these manually.
