### ISSUE TITLE
Testing your Tipper

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#875]
See also #425 
**What is the best way to test Tippers?**
The main problem with testing Tippers is creating the AST designated for spartanizing. There are currently many tools available, here I'll describe some of them, explain how to use them and suggest pros/cons.

**trimmingOf**
The main testing tool used in our project. It invokes the Trimmer, which is the main project application that is being run by the plugin at runtime.
Usage example (from ArithmeticTest.java):
```Java
@Test public void issue206_3() {
  trimmingOf("3-4-a").gives("-1-a").stays();
}
```
`trimmingOf` accept String, converts it into an AST, checks it spartanized to something else using `gives` and checks it does not spartanized using `stays`.
* pros:
  * not Tipper dependent: tests written using `trimmingOf` are global principles that offer demands to the *Spartanizer*, not to specific *Tipper*.
  * easy to use
  * allows you to specify required spartanization steps
* cons:
  * all Tippers activated at once: if you want to test a specific Tipper, you should test a piece of code that is spartanized by it only - if not, other Tipper would spartanized it instead and ruin your test
  * thus can fail when unrelated code is changed

Another example:
```Java
@Test public void A$a() {
  trimmingOf("abstract abstract interface a{}")//
      .gives("abstract interface a{}")//
      .gives("interface a{}")//
      .stays();
  }
```

**Comment by OriRoth** [comment]
@dormaayan show this to your gang
@tomerdragucki @ravivos @kfir-marx @mdoron FYI
If someone wants to turn this and #425 into a wiki tutorial, s/he is more than welcomed. Extra KARMA$$$ guarantied!

**Comment by yossigil** [comment]
@kobybs I will let you do it. It is easy and quick to finish.
