### ISSUE TITLE
Recycle Spartanizer code in IntelliJ - do, or do not?

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#876]
After a talk with @amirsagiv83 we have reached the following conclusions:
Using the Spartanizer's Tippers classes in the IntelliJ plugin *may* be possible under the following conditions:
* **Compiling** the Tippers is only possible if you will **use  the eclipse libraries** supporting ASTNode and ASTRewrite (and something else?).
* **Using** the Tippers is only possible if you will **implement some technical classes** under IntelliJ, in particular TextFileChange that accepts an ASTRwriter and textually updates the file (may be tough).

Some notes:
* The other options besides full recycling are:
  * Partial recycling, by implementing Leonidas in IntelliJ then using the existing patterns from the Spartanizer (may come out as a great resolution)
  * Writing the Tippers all over again (in my opinion the best solution, even the easiest!)
  * Something else?
* Trying to recycle the Tippers is a risky thing: you can find yourselves working on connections between eclipse and IntelliJ throughout the semester, without guaranty it is possible at all (performance??)
* Deciding whether to recycle the Spartanizer's Tippers is, in my opinion, a major decision that would influence your project's appearance and should involve all team members

@amirsagiv83 please tag all of your gang members, you may also tag Yossi.
Close/edit this issue as you wish.

**Comment by yossigil** [comment]
@michalcohen fyi.

**Comment by amirsagiv83** [comment]
@michalcohen 
@orenafek 
@AnnaBel7 
@RoeiRaz 
@RoeyMaor

**Comment by amirsagiv83** [comment]
We have decided to check and test two options.
1. implement ASTRewrite.
2. Make Leonidas work directly with Psi.

Nothing much to discuss about it here.
Closing.
