### ISSUE TITLE
Replace every Loop in the project to use Range

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Spartanizer#877]
Use the fluent API of range, see #869

**Comment by SapirBismot** [comment]
This should be ?
```Java
for(int i=0;true;i++)
```
==>
```Java
for (final Integer i: range.from(0))
```

**Comment by dormaayan** [comment]
@SapirBismot  currently we don't support infinite loops but that's a good point!

**Comment by yossigil** [comment]
I think you can fix this extending class `range`, so that the sequence
```java
range.infininite.from(12).step(3)
range.infinite.from(12)
```
would also work.
This is very easy. All you have to do is create an inner class of `range`. @dormaayan / @OriRoth , see if you can meet with @SapirBismot to guide her through in this.

**Comment by yossigil** [comment]
or
```java
range.from(12).step(3).infinitely();
range.from(12).infinitely();
range.from(12).infinitely().step(4);
```

**Comment by kobybs** [comment]
@dormaayan maybe step should get some lambda expression instead of just an increment number, so we can support things like i *= a, or i = -i.

**Comment by dormaayan** [comment]
@kobybs :
@yossigil : 
I also thought about that but Im not sure whether sending Lambda Expressions as an arguments is a good Fluent Api...
What do you think is the right approach over here ?

**Comment by yossigil** [comment]
no lambda expression...

**Comment by dormaayan** [comment]
@kobybs : So I think we should add here more functions like step for different cases of steps,
I suggest we will open a different issue with list of all the changes we should do in range.
If you agree please like my comment and I will open an issue.

**Comment by dormaayan** [comment]
@SapirBismot @danabramovich  @yuvalsimon :
Let's remember that the goal of that issue is also to write the changes is Leonis's Style for use in the upcoming tipper...

**Comment by danabramovich** [comment]
yes I have already started implementing the tipper, you can all see how to write the changes in the correct format.

**Comment by kobybs** [comment]
`tippers.add(TipperFactory.patternTipper("for(int $N = $L1; $N < $L2; $N+=$L3)$B", "for(Integer $N : range.from($L1).step($L3).to($L2))$B",
 "replace non-inclusive for loop with the matching range"));`

`tippers.add(TipperFactory.patternTipper("for(int $N = $L1; $N <= $L2; $N+=$L3)$B", "for(Integer $N : range.from($L1).step($L3).to($L2).inclusive())$B",
 "replace non-inclusive for loop with the matching range"));`

`tippers.add(TipperFactory.patternTipper("for(int $N = $L1; $N < $L2; N--)$B", "for(Integer $N : range.from($L1).step(-1).to($L2))$B",
 "replace non-inclusive for loop with the matching range"));`

`tippers.add(TipperFactory.patternTipper("for(int $N = $L1; $N <= $L2; N--)$B", "for(Integer $N : range.from($L1).step(-1).to($L2).inclusive())$B",
 "replace non-inclusive for loop with the matching range"));`

**Comment by yuvalsimon** [comment]
Need to be careful on for statements like this:
```
for (int i = 0; j < list.size(); ++i)
```
In the original code I changed the list size inside the for block, so the range is changed.

**Comment by yuvalsimon** [comment]
@danabramovich I think you cannot write range.from($L1).step(-1).to($L2), instead write this range.from($L1).to($L2).step(-1)

**Comment by yossigil** [comment]
Enough for now.
