### ISSUE TITLE
Remove redundent ReturnStatement in void type method

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#879]
```Java
void f() {
  return;
}
```
==>
```Java
void f() {
}
```

(this time I checked there is no such a tipper already!)

**Comment by danabramovich** [comment]
@OriRoth You meant to make a new tipper for this specific case only, right?
because in general cases it can cause compilation errors.

**Comment by OriRoth** [comment]
Yes. It is up to you to decide whether to check return statement is empty, return type is void or both.

**Comment by OriRoth** [comment]
It is not just this case... generalize as you can.

**Comment by OriRoth** [comment]
Also not all return statements are inside functions!

**Comment by yossigil** [comment]
Why are `@Test` marked with `@Ignore`?

**Comment by danabramovich** [comment]
yes i already fixed it

**Comment by danabramovich** [comment]
https://github.com/SpartanRefactoring/Spartanizer/commit/5ff4678e14f4fc0128dffe09f9a79a2352bc93d2

**Comment by OriRoth** [comment]
You can put issue-tags in commit message:
```
working on #879
```
You can also close/open issues that way:
```
close #879
```
Or even:
```
finally fixed #879
```
No need to tag commits in issues, tag issues in commits instead. Looks cleaner.

**Comment by danabramovich** [comment]
yes I know, I just forgot to tag the Issue on that specific commit.

**Comment by ravivos** [comment]
*spartanizer - not related to athenizer*
Hey @danabra, there's a unit test failing in your tipper which I came upon when fixing Athenizer tests.
Probably you would like to fix it or delegate?

**Comment by danabra** [comment]
I'll see what I can do

**Comment by OriRoth** [comment]
I... guess you did not meant to close this.

**Comment by danabra** [comment]
https://github.com/SpartanRefactoring/Spartanizer/commit/11d5ba2ab418f493feb8517fbc06b7eefc083266

**Comment by OriRoth** [comment]
Yeah my bad.. good job :)
