### ISSUE TITLE
Improving test API

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#884]
Adding some useful and easy to implement options. At the moment I have the following suggestions:
* `givesEither` - like `gives` but accepts multiple options. Good for cases such as:
```Java
trimmingOf("for (int ¢ = 0 ; ¢ < 5 ; ++¢) {++¢; continue;}")
.gives("for (int ¢ = 0; ¢ < 5 ; ++¢) {++¢;}");
```
can be written better:
```Java
trimmingOf("for (int ¢ = 0 ; ¢ < 5 ; ++¢) {++¢; continue;}")
.givesEither("for (int ¢ = 0 ; ¢ < 5 ; ++¢) {++¢;}",
             "for (int ¢ = 0 ; ¢ < 5 ; ++¢) ++¢;");
```

**Comment by yossigil** [comment]
```java
trimmingOf(X).
  gives(maybe(X), maybe(Y), maybe(Z))

**Comment by yossigil** [comment]
Not crucial, but you may enjoy this quick one

**Comment by dormaayan** [comment]
@yossigil : It's seems really useful, I'll work on that after sprint-1 is over

**Comment by dormaayan** [comment]
@yossigil  @OriRoth  : Added givesEither : get few options and check if one of them is correct.
Any more nice ideas ?

**Comment by yossigil** [comment]
Good job.
