### ISSUE TITLE
Possible Changes to Range

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Spartanizer#886]
- [ ] add support for more kinds of increments :

1. - [ ] multiplication
2. - [ ] subtraction
3. - [ ] Division

**Comment by orimarco** [comment]
Do we have reverse?

**Comment by kobybs** [comment]
@orimarco reverse can be achieved by negative step, isn't it good enough?

**Comment by orimarco** [comment]
That's great!

**Comment by yossigil** [comment]
The natural extensions to range are different: take a look at this and tell me what you think. This is a quiz
```java
  private int[] fill(final int[] $) {
    for (int ¢ = 0; more(); ++¢, advance())
      $[¢] = current();
    return $;
  }
```
@orimarco @OriRoth

**Comment by yossigil** [comment]
can you do this one
```java
static long load64Safely(byte[] input,int offset,int length){
  long $=0;
  for (int limit=Math.min(length,8), ¢=0; ¢ < limit; ++¢)   $|=(input[¢ + offset] & 0xFFL) << (8 * ¢);
  return $;
}
```

**Comment by dormaayan** [comment]
@yossigil :
I close it for now...
