### ISSUE TITLE
The spartan engine goes into an infinite loop

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#889]
Yuval, I suspect this is your switch algorithm. 
To produce the bug, run the spartanizer on itself.

**Comment by yuvalsimon** [comment]
@yossigil I fail to produce the bug, so I can't check it. If it is because of issue #858 then I hope it is fixed, I changed the tipper to work only as in the example in the issue. I kept #880 not active but maybe it didn't produce the bug from the beginning.

**Comment by yossigil** [comment]
OK, restore it and the tests. Let's see what can be done in a different direction.

**Comment by yuvalsimon** [comment]
I restored it

**Comment by OriRoth** [comment]
@yuvalsimon what is the status of this issue? Is the relevant Tipper removed from the Toolbox? What is it?

**Comment by yossigil** [comment]
I run the spartanizer on itself, and some of the switch tips produce bugs.
@yuvalsimon please do so, and **DISABLE*** the buggy tippers. Do not correct them.

**Comment by OriRoth** [comment]
`RemoveRedundantSwitchBranch` disabled. Problem may not be in this Tipper.

**Comment by OriRoth** [comment]
There is no current issue with the spartanizer going into infinite loop.
@yuvalsimon `RemoveRedundantSwitchBranch` is your tipper. It was written using "build nodes from Strings" method, which is not good! (you may open yourself an issue about it, or not). Nevertheless, the seams not to be a problem with this tipper- it's test class is well written, all tests pass and there is no risk for infinite running in either of it's loops (I checked), thus I close this issue.
