### ISSUE TITLE
bugs in leonidas

### ISSUE THREAD

**Issue by danabramovich** [SpartanRefactoring/Spartanizer#894]
- return $L1 instead of a number literal

- x-=2 matches the pattern ++$N

Im commiting some tests that show the problems (they use the tipper from #853 )

**Comment by orimarco** [comment]
Solved all these...
Now we've got these problems:

-  `-$L1` s is replaced as if it was `L1`.
- `;` is getting ripped of statements because of inner implementation of `$X` matching

Hope to get working on these some when...

**Comment by yossigil** [comment]
Close the issue and open another one for what's left
