### ISSUE TITLE
Trivial deflators (reducers?) - using appropriate tippers

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Spartanizer#896]
A trivial solution for the deflators (or maybe we should call them reducers?) should be the tippers for now - meaning the opposite direction of scrolling will spartanize back the code.
For every expander we write, we should add the opposite Tipper for the deflation.

@OriRoth, @yossigil - what do you think of this idea? should we open an issue for each reducer, or should it be part of the "writing an expander" task?

**Comment by yossigil** [comment]
Yes. Please open a label "new-inflator"

**Comment by ravivos** [comment]
Already opened one for the expanders last week... called it "new-expanders".
Did you mean that I should open also "new-reducers" (or "new-deflators")?

**Comment by yossigil** [comment]
No. It is the same.
