### ISSUE TITLE
Rogue Tipper - seek and destroy

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#897]
@yossigil FYI, you may join the search

**Comment by OriRoth** [comment]
Javadoc stuff? Seams so.
```Java
/***/
class A {
  Integer i = new Integer(0); // no tip
}
```
```Java
class A {
  Integer i = new Integer(0); // tip
}
```

**Comment by OriRoth** [comment]
*Update*: this is a bug in `disabling`! All nodes containing Javadoc are considered as disabled. @yossigil is it ok if I would revert your changes or do you want to deal with it?

**Comment by OriRoth** [comment]
Done, currently 380 (approx) tips for Spartanizer project. It was not a Tipper after all... I'll check if there is any failing Tipper though.

**Comment by OriRoth** [comment]
*Some conclusions*:
* Creating tips for the Spartanizer project takes about a minute
* This time is reduced to twelve seconds (!) if we disable InfixExpression tippers

@yossigil is this a normal behavior, or do you think I need to take a closer look at InfixExpression's tippers? I will keep investigating those tippers for now.

**Comment by yossigil** [comment]
Should not take that long. It must be the Leonidas tippers.

**Comment by OriRoth** [comment]
@orimarco do you remember what tippers of InfixExpression use Leonidas?

**Comment by OriRoth** [comment]
@yossigil OK Lionidas' `InfixIndexOfToStringContains` is disabled, run time decreased by 80% approx! Please try it now. Make sure you pull my latest change to the `Toolbox`.

**Comment by OriRoth** [comment]
Conclusions: tippers removed from the Toolbox:
* CachingPattern
* BlockInlineStatementIntoNext
* InfixIndexOfToStringContains

**Comment by yossigil** [comment]
@yuvalsimon Your task is to make an issue out of each of these failures.

**Comment by OriRoth** [comment]
I am currently moving all issues from 2.7 to 2.8 milestone so you'll need to find them there OR in 2.7 if they are closed.
