### ISSUE TITLE
Create a quality assurance and project standard wiki page

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#899]
QA tasks:

- Format
- CLEANUP
- Spartanize
- NO @IGNORE ON SINGLE TESTS
- Apply spartanization on itself
- Clean spartanization on projects
- SUPPRESS ONLY on bugs with issues
- Link to classes that create tests
- Using library iz/az/lisp/step

**Comment by OriRoth** [comment]
A QA *mega* task would be to organize WIKI pages... it is a big mess. Not programming related... but still QA in my opinion.

**Comment by yossigil** [comment]
At this stage code only...
- @danabramovich : do not commit commented out code.
- Author/Since for each new class.
- One sentence doc to each new class.

**Comment by yossigil** [comment]
Whenever the spartanizer fails on project 
- An issue is created, with correct labels/milestones/etc.
- An issue test class is created, with at least one test
- This class is marked `@Ignore`
- You use @orimarco code for creating tests.

**Comment by danabramovich** [comment]
@yossigil I've already fixed that https://github.com/SpartanRefactoring/Spartanizer/commit/c2626f532fe2579020cb8fc49617953eba0f8c6f...

**Comment by yossigil** [comment]
@danabramovich I know, but then... it would be nice if @yuvalsimon nagged you rather than me...

**Comment by dormaayan** [comment]
- For each tipper, mention as part of the documentation the Issue it solves.

- Also, mention the name of the test class of the tipper

**Comment by OriRoth** [comment]
* No commented out Tippers in the Toolbox (an issue instead)

**Comment by yossigil** [comment]
This is part of no commented out code, but should be emphasized.

**Comment by yuvalsimon** [comment]
The wiki page for this issue is
https://github.com/SpartanRefactoring/Spartanizer/wiki/Quality-Assurance-and-Project-Standard

**Comment by yossigil** [comment]
We have a bunch of projects used for testing. Junit and Guava I think should be sufficient.
Please try to add the wiki page so it looks a bit more than cut and paste.

**Comment by yuvalsimon** [comment]
@yossigil Is it better now?

**Comment by yossigil** [comment]
Yes. Thanks!

**Comment by yuvalsimon** [comment]
@OriRoth @ravivos @dormaayan @tomerdragucki @danabramovich @mdoron 
Check this out please:
https://github.com/SpartanRefactoring/Spartanizer/wiki/Quality-Assurance-and-Project-Standard

**Comment by yossigil** [comment]
Splendid job
