### ISSUE TITLE
Warnings in MANIFEST.MF

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#900]
I get those:
![image](https://cloud.githubusercontent.com/assets/12089145/21001650/5a892888-bd2a-11e6-8f70-53e8641f63d1.png)

I don't know how this manifest works and I don't want to ruin anything so I'll just assign 👑 @OriRoth

**Comment by OriRoth** [comment]
If I knew how the manifest works we would had much less trouble :P
