### ISSUE TITLE
Manage all tests broken in release 2.7

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#901]
For each class that has failing tests:

1. add `@Ignore` to the entire class.
2. Create a new Issue to fix the class.
3. Create a new issue test class which has a copy of the failing tests.
4. Mention in the issue both test class should be fixed by removing the `@Ignore`
5. Assigning the issue to right person.
6. Adding labels and milestone.

Create a milestone for entitled "Version 2.7 aftermath", with a near deadline. All this should be ready for our next meeting, in which we will try to understand what we did right and not so right for the next iteration.

Each failure of running spartan with reenabled tippers on itself should be handled similarly.

This is a large issue but NO unexpected mishaps are expected with it.

**Comment by orimarco** [comment]
You can use `trimmingOf.withTipper` to test a tipper without adding it to the toolbox

**Comment by OriRoth** [comment]
I was the one removing Tippers from the Toolbox. I did not put an @Ignore on those tests because I was *not sure* they failed because the missing Tippers. Each test file should contain a Tipper declaration, such as `/** This is a unit test for {@link SomeRandomTipper} */`, that would make our job much easier.
@yuvalsimon FYI

**Comment by yuvalsimon** [comment]
Issues #909, #910 have to be assigned to someone, the authors are not in the project for now.
#911 should work @OriRoth , I can add them back.

**Comment by yossigil** [comment]
Is this done?

**Comment by yuvalsimon** [comment]
Should all bugs I find be resolved for milestone Version 2.7 aftermath? (Also bugs of running spartan on itself)

**Comment by yossigil** [comment]
All bugs of running spartan on itself should be for version 2.8. Current version is released.

**Comment by yuvalsimon** [comment]
Done

**Comment by yossigil** [comment]
:+1:
