### ISSUE TITLE
RedundentReturnStatementInVoidTypeMethod failing test

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#902]
#879 
Checkout Issue902 test class with the failing tests from Issue879 test class.
Don't forget to unignore both test classes.

**Comment by yossigil** [comment]
good job :100:

**Comment by yossigil** [comment]
I went over this problem. Seems as if the fault lies with `BlockRemoveDeadVariables` , @kobybs .
I think this class should be rewritten, to deal with fragments, not entire block.

**Comment by yuvalsimon** [comment]
Ok so for the problem with BlockRemoveDeadVariables there is issue #904 .

**Comment by yossigil** [comment]
Let's put this one hold for now.

**Comment by yuvalsimon** [comment]
@yossigil I moved it to Sprint-2 so we won't forget unignore tests...
