### ISSUE TITLE
ReturnToBreakFiniteFor test failing

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#903]
#131  
Checkout Issue903 test class that contains failing test from Issue131 test class. 
Also remove comments on Issue131 class and don't forget unignore both test classes.

**Comment by yuvalsimon** [comment]
** fixed, it was issue131

**Comment by yossigil** [comment]
- [ ] More descriptive title
- [ ] Add labels as approriate to describe the problem.

**Comment by yossigil** [comment]
You missed this label.

**Comment by yuvalsimon** [comment]
@dormaayan some of your tests from few days ago failing now

**Comment by yossigil** [comment]
:+1:
