### ISSUE TITLE
Reimplement BlockRemoveDeadVariables

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#904]
#359 
Checkout Issue904 test class with the failing tests from Issue359 test class. 
Don't forget to unignore both test classes.

**Comment by yossigil** [comment]
- [ ] More descriptive title
- [ ] Add labels as approriate to describe the problem.

**Comment by yossigil** [comment]
Done with new AbstractPattern and hierarchy
