### ISSUE TITLE
RemoveRedundantIf/For/While failing test

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#905]
#251 
Checkout Issue905 test class with the failing tests from Issue251 test class.
Don't forget to unignore both test classes.

**Comment by yossigil** [comment]
- [ ] More descriptive title
- [ ] Add labels as approriate to describe the problem.

**Comment by dormaayan** [comment]
@yossigil 
@OriRoth  :
All the test who fail here are related to changes @kobybs did  for issue #359 on dead variables.
Aren't we include that tipper right now ? should I return those tests to the original version without the effect of this tipper ?

**Comment by yossigil** [comment]
I wonder how this went through in previous rounds of tests? I will have to take a deeper look.  cannot help at this stage. Probably tomorrow.

**Comment by dormaayan** [comment]
now #359 is disabled...
I think that's the reason

**Comment by dormaayan** [comment]
@danabramovich : I pass the responsibility over that for you, I assume after you will rewrite the Dead Variable tipper you will need to correct that anyway...
