### ISSUE TITLE
PrefixPlusRemove test failing

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#906]
#75 
Checkout Issue906 test class with the failed test from Issue075 test class
Don't forget to unignore both test classes.

**Comment by yossigil** [comment]
- [ ] More descriptive title
- [ ] Add labels as approriate to describe the problem.

**Comment by yuvalsimon** [comment]
I think the test fails because the last 'gives' checks for the dead variables issue:
`trimmingOf("int i; i = +0;").gives("int i = +0;").gives("");`
I remove it.
