### ISSUE TITLE
IfTrueOrFalse test failing

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#907]
related to issue #86 . failing test is found in Version250 test class. 
Checkout Issue907 test class with failing test.
Do not forget to unignore both classes.

**Comment by yuvalsimon** [comment]
I put the failed in NotWorking inner class of Version250, dont forget to unignore

**Comment by yuvalsimon** [comment]
I see now this occured too after commit [36ac801 ](https://github.com/SpartanRefactoring/Spartanizer/commit/36ac801561bd366d61489c7b11452e05daaddc76) for dead variables. I rollback

**Comment by yossigil** [comment]
@ravivos please start working on this

**Comment by ravivos** [comment]
@yossigil 
I believe there is some kind of a mistake here.
It is not related to me in anyway.
@yuvalsimon, care to explain?

**Comment by yossigil** [comment]
@ravivos I wanted you to help in previous issues as well. I will load with you small ones like this.

**Comment by yuvalsimon** [comment]
@ravivos What mistake? I reverted it, it occured because of [36ac801 ](https://github.com/SpartanRefactoring/Spartanizer/commit/36ac801561bd366d61489c7b11452e05daaddc76)
