### ISSUE TITLE
InitializationListRemoveComma test failing

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#908]
Related to issue #74 . failing test is found in Version230 tests class. 
Checkout Issue908 test class with failing tests. 
Don't forget to unignore the failing test in Version230 test class, which I put in an inner ignored class there.

**Comment by yossigil** [comment]
This is a tipper that was never implemented. Find the original issue and consolidate all tests there. Make sure the original is still open and close this one.

**Comment by yuvalsimon** [comment]
There is an implementation in InitializationListRemoveComma tipper. I created Issue074 test class for #74 and copied some tests I found in IgnoredTrimmerTest for this issue and a test from Version230 which failed yesterday before I ignored it. Should I remove the tests from these files or should they be unignored after finishing #74 ?
