### ISSUE TITLE
Test cases for environment scanner

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#91]
Note that you only need to manage variables. I believe these can be defined in the following places:
1.  as fields of classes
2.  as paramers to function
3. as local variables
4. inside  element marked X in " for (X;;)  {...}"
5. Inside a foreach loop "for (int x: myArray) {...}
6. In a try statement, "try(X; X1;) {...}"
7. In a catch statement "catch (RuntimeExcption | NullPointerException X) {...}"
8.  In initializers and static initializer blocks (similar to local variables)
9. In parameters to lambda expressions "    BiFunction<Integer,Short, Double> f= (Integer n, Short d)->1.*n/d;"
10. In implicit lambda expressions, e.g.  "    Consumer<Boolean> = (b) -> ();" don't be confused by things
    such as ()->which are also legal.

Check out the full list here, in case I forgot something:
https://docs.oracle.com/javase/specs/jls/se8/html/jls-6.html#jls-6.3

This reference should also give you plenty of ideas for examples

**Comment by sakopzon** [comment]
We added annotations, could you please look at them and mark where do we have mistakes in our understanding of @Environment?

**Comment by sakopzon** [comment]
Just now the lambda test is done.

**Comment by yossigil** [comment]
I checked out the tests. They could not work. No @Test method should be `static`. I fixed that for you.

**Comment by sakopzon** [comment]
Wanted to clarify, there is a difference between declaration and definition even for variables (and of course for classes and functions in the future).
`int a;` is a declaration, while `int a = 0;` is a declaration with definition.
Did you actually mean declaration when said definition?
I think that the two methods use() and defines() from issue 106 should be use() and declares(), while both should include expressions like `int a = 0;`
Am I wrong?

**Comment by yossigil** [comment]
I did not really think of the difference between the terms. It seems as if you are right

**Comment by yossigil** [comment]
No work for now

**Comment by yossigil** [comment]
I think this one should be defunct. @dormaayan  take a quick look and close

**Comment by dormaayan** [comment]
@yossigil : Indeed defunct, I close

**Comment by yossigil** [comment]
try to erase as much as you can
