### ISSUE TITLE
Fix RemoveRedundantSwitchBranch, RemoveRedundantSwitchCases

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#911]
#858 
#880 
Test classes are Issue858 for RemoveRedundantSwitchBranch and Issue880 for RemoveRedundantSwitchCases
The tests pass (after adding tippers to ToolBox), they should work

**Comment by yossigil** [comment]
Where is the test class? How would we know that the issue is resolved.
Tests in Issue880 pass.

**Comment by yossigil** [comment]
- [ ] More descriptive title
- [ ] Add labels as approriate to describe the problem.
- [ ] Breakdown into distinct issues by tipper class.
- [ ] Close this issue

**Comment by yuvalsimon** [comment]
RemoveRedundantSwitchBranch worked but wa disabled so I enabled it.
New case is opened for RemoveRedundantSwitchCases - #913
