### ISSUE TITLE
Low priority:  returning switch nano

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#920]
The returning switch nano.
```java
        switch (level--) {
          default:
            return;
```

**Comment by orimarco** [comment]
Do you mean switch which all it's branches return?

**Comment by yossigil** [comment]
Indeed. This header is a clue: this switch is the last statement in this block. Saw it about 5 times in our code, so I thought it might be considered a nano if it occurs so often.
