### ISSUE TITLE
Laconize project: Add running total of tips applied so far.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#921]
The running total should appear in the dialog box, and should have two lines:

Pass Number: 1
Tips (total): 721
Tips (this pass): 15

**Comment by OriRoth** [comment]
I'll see what I can do...

**Comment by OriRoth** [comment]
Current dialogs status:

![screens](https://cloud.githubusercontent.com/assets/15183108/21081698/9f4add20-bfd4-11e6-8820-76d1b8f2ba50.jpg)
