### ISSUE TITLE
Create from Nano

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#924]
```Java
  StatsAccumulator $=new StatsAccumulator();
  $.addAll(values);
```

**Comment by yossigil** [comment]
Replace by `  StatsAccumulator $=new StatsAccumulator(values);`

**Comment by orimarco** [comment]
This will only works if values is a collection, in our case it's an Iterable...

**Comment by yossigil** [comment]
so value of pattern is smaller.
