### ISSUE TITLE
Problems with UsesCollector traverse

### ISSUE THREAD

**Issue by mdoron** [SpartanRefactoring/Spartanizer#937]
@yossigil Hi! I hope you'll be able to help me here...

I am currently implementing #20 `MatchCtorParamNamesToFieldsIfAssigned`. In order to commit the renaming job I am using `Tippers.rename` that calls `UsesCollector`. I am trying to rename something like this:
```Java
A(int y) {
  this.x = y;
}
```
into
```Java
A(int x) {
  this.x = x;
}
```
My problem here is `UsesCollector` collects uses for name **x** in method **f** only if **x** is *not* a parameter of **f**. Moreover, it does not traverse the parameters, only the method's body.
Current implementation:
```Java
  @Override public boolean visit(final MethodDeclaration ¢) {
    return !declaredIn(¢) && recurse(¢.getBody());
  }
```
what I need:
```Java
  @Override public boolean visit(final MethodDeclaration ¢) {
    for (SingleVariableDeclaration p : (List<SingleVariableDeclaration>) ¢.parameters())
      recurse(p);
    return recurse(¢.getBody());
  }
```

So what I can do here? Is there a more suitable replacement for `UsesCollector` in renaming context?

**Comment by OriRoth** [comment]
Traverse the constructor's body instead of the whole constructor, then rename the parameter separately.

**Comment by mdoron** [comment]
Done

**Comment by yossigil** [comment]
thanks @OriRoth
