### ISSUE TITLE
When is a Nano worthy?

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#939]
So @yossigil had two ideas:

1. use an `h-index` like ranking, which will rank both **methods and Nanos** and count how many uses they have, and every Nano which will be over  the h-index will be employed, all others will be fired shamefacedly.
We will call this `r-index`, and we can use re-usability metric instead which will rank a method\Nano by the number of tokens which it saves (which is `(\#calls-1)*tokens-\#calls*price(invoking+parameters)` .

2. We can use re-usability metric and just take the Nanos which are ranked above the Avg. or Median.

These metrics are **project specific** and that's OK.
If a Nano is good in few projects it's a really good Nano.

What do you think @M4tt30rru  ?

**Comment by yossigil** [comment]
Take note that you can apply h-index idea to weighted ranking. You simply sort the tokens by the numer of time they are used. So, if a method is used fifty times, then all tokens in it are considered as being used fifty times, thrown into the pile of tokens, and sorted among them.

If you do that, and you compute the t-index, you can say that if the R_t reuse factor (subscript tokens) is 1,243, then this repository has at least 1,243 tokens which are being reused 1,243 times or more.

**Comment by yossigil** [comment]
Well, the other point is regarding the average, a pattern is admissible if it increases the average reuse level of a project. The average reuse level could be measured token wise, or method wise. I would suggest token wise.

**Comment by yossigil** [comment]
@M4tt30rru : add to Threats to Validity, reuse level errors.

**Comment by yossigil** [comment]
Let's create an issue to compute the T-index of two repositories?
Or maybe much more urgent is an issue to check whether we improve the average.
And a preliminary issue to approximate the reuse level, or simply use binding information to know how many times a certain method was reused.

@OriRoth / @dormaayan : you might be interested in this challenge.

**Comment by M4tt30rru** [comment]
Great idea. These metrics should be idiosyncratic, right? Is there any way to normalize them so we can measure the worthiness of a nano pattern on a dataset (I mean a bunch of projects)?
