### ISSUE TITLE
toString methods

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#941]
Not that we really need one, but an example:
```Java
@Override public String toString(){
  return ordering + ".onResultOf(" + function+ ")";
}
```

In Guava they form 2% of the methods with one parameter, should we consider them as a `toString `pattern?

**Comment by orimarco** [comment]
I think we should, maybe even other functions that return String.
@yossigil what do you think?

**Comment by yossigil** [comment]
let  you decide I have no particular opinion now
