### ISSUE TITLE
Leonidas bug - operator comparison

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#943]
When comparing `InfixExpression`s, operators don't get compared.

Failure example: (from file MatcherTest.java)
```java
 assertFalse(Matcher.patternMatcher("x < 7", "").matches(findFirst.infixExpression(wizard.ast("x <= 7"))));
```

That's an easy one to fix if you'd like @dormaayan

**Comment by dormaayan** [comment]
@orimarco: Done
