### ISSUE TITLE
lisp Nanos

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#946]
```Java
li.get(0) ---> first(li)
li.get(li.size()-1)  ---> last(li)
li.size()-1 ---> lastIndex(li)
```

**Comment by orimarco** [comment]
### Guava:
![image](https://cloud.githubusercontent.com/assets/12089145/21182474/ff163e46-c20b-11e6-9147-8cff13f369be.png)
![image](https://cloud.githubusercontent.com/assets/12089145/21182469/f768b8fe-c20b-11e6-8029-4126f8b7e4f6.png)
![image](https://cloud.githubusercontent.com/assets/12089145/21182507/2e5eb98a-c20c-11e6-9909-5aab1dff5353.png)

**Comment by yossigil** [comment]
Good results. Now, we have the following dilemma. If we group them all together, we obtain something which hits the threshold, but separately, they are not... 

Can you try also on spartanizer?

**Comment by orimarco** [comment]
was actually thinking about adding them together (although lastIndex is defined on an InfixExpression an the others on MethodDeclaration so it will be hard to put them in the same tipper...).

Will do Spartanizer now.

**Comment by orimarco** [comment]
### Spartanizer:
![image](https://cloud.githubusercontent.com/assets/12089145/21188990/d45bb518-c225-11e6-8d60-bf7c64ec676c.png)

**Comment by yossigil** [comment]
Any chance you can throw a commit that will do this?
