### ISSUE TITLE
NP usage in Guava

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#948]
When I'll have time I'll put it into a proper LaTeX table...

![image](https://cloud.githubusercontent.com/assets/12089145/21183078/e54b6b96-c20e-11e6-83ed-10f381d8c6de.png)

**Comment by orimarco** [comment]
@yossigil

**Comment by orimarco** [comment]
I'll do Spartanizer later...

**Comment by yossigil** [comment]
Can this table be sorted?
