### ISSUE TITLE
Rename project to spartanizer

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#95]
@M4tt30rru : what was the name we agreed on?

**Comment by M4tt30rru** [comment]
We talked about several names (and related concepts) during the time. One was the "Cookbook", for example. But some of this names and concept were also questioned and, as far as I remember, we did not agree definitely on a specific name. Also, I am not sure we are talking about rename the entire project or a subset of it. As far as I understand, the cookbook should work inside (or behind) the Spartanization engine, being a part of it, although it could also be considered a system on its own.

**Comment by yossigil** [comment]
@OriRoth: change the name to il.org.spartan.spartanizer

**Comment by yossigil** [comment]
@OriRoth :+1: I trust you can do it. You wrote the wring, or was around at that time.

**Comment by OriRoth** [comment]
OK name is change (+ appropriate maven definitions)
