### ISSUE TITLE
NP analysis - commons-lang, high coverage!

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#953]
### np usage
![image](https://cloud.githubusercontent.com/assets/12089145/21189814/8c1dbe9c-c228-11e6-80e7-3dbabeab41b1.png)

### method statistics
![image](https://cloud.githubusercontent.com/assets/12089145/21189718/47b95018-c228-11e6-85cd-995b893633e6.png)

**Comment by yossigil** [comment]
NAME | NODE-TYPE | INFIX | ASSIGNMENT | METHOD | PREFIX | ASSIGN | POSTFIX | EXTERNAL
---- | --------- | ----- | ---------- | ------ | ------ | ------ | ------- | --------
clix | 24 | 5 | 1 | 6 | 2 | 0 | 0 | 6
services | 50 | 8 | 2 | 15 | 3 | 0 | 1 | 9
guava | 63 | 19 | 7 | 37 | 5 | 0 | 2 | 15
refactoring | 56 | 17 | 2 | 37 | 4 | 0 | 2 | 22
spartan | 56 | 15 | 4 | 31 | 4 | 0 | 1 | 10
commons-lang | 53 | 16 | 4 | 22 | 5 | 0 | 2 | 13
commons-bcel | 54 | 15 | 3 | 25 | 4 | 0 | 2 | 13
fajita | 33 | 7 | 3 | 14 | 2 | 0 | 1 | 10
junit4 | 42 | 9 | 2 | 16 | 2 | 0 | 2 | 10
mockito | 46 | 10 | 2 | 17 | 2 | 0 | 1 | 10
netty | 67 | 22 | 8 | 50 | 5 | 0 | 2 | 18
AutoRefactor | 50 | 14 | 2 | 27 | 3 | 0 | 1 | 18
