### ISSUE TITLE
Bug in inlining

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#954]
```java
 Object[] objectArray = {value};
String arrayString = Arrays.deepToString(objectArray);
anotherStatement();
```
Should **not** inline `value`, but `new Object[]{value}`.

Fixed `DeclarationFragmentInlineIntoNext` to not inline array initializers at all...
need to fix it to inline as in `DeclarationInitializerStatementTerminatingScope`...

**Comment by yossigil** [comment]
Is this solved? @OriRoth

**Comment by OriRoth** [comment]
Yes this is a duplicated issue. Anyway I added a test case `Issue0954`, you may check it out (contains only above example, there are more tests in the other issue file). The tipper has been renamed since to `DeclarationInlineIntoNext`, BTW.

**Comment by yossigil** [comment]
renamed to FragmentInlineIntoNext
