### ISSUE TITLE
Much Better Performance in Leonidas

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Spartanizer#956]

**Comment by orimarco** [comment]
### Optimization 1
Compare trees **BFS**ically instead of DFS as now...
This way, we can disqualify nodes quicker and we won't need to iterate them deeply for no purpose.

This might help especially with `statementsPattern`.

**Comment by dormaayan** [comment]
@orimarco : In which situation and on which tipper did you find the performance are really slow ? 
I guess that the performance can't be measures with the unit tests but only when you run it for the entire project...

**Comment by orimarco** [comment]
I didn't find them slow, it was @OriRoth who noticed that...

**Comment by orimarco** [comment]
But we can implement some simple tipper with Leonidas and compare results...
Perhaps `IfTrueOrFalse` might be easy to implement with Leonidas...

**Comment by dormaayan** [comment]
I put it in hold for now since we don't use leonids right now
