### ISSUE TITLE
AssignmentToPostfixIncrement tests failing

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#958]
Related to #107 
I put the failing tests in inner class in Issue107 test class.
It does not seem to fail because of some change in the tippers. (I tried to remove all tippers in Toolbox except for this one and yet not working, even though the tipper/test code wasn't edited from last time it worked)

**Comment by yuvalsimon** [comment]
same for #103

**Comment by yuvalsimon** [comment]
#960 fixed this

**Comment by yossigil** [comment]
Splendid
