### ISSUE TITLE
Cleanup of plugin.xml

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#96]
All menu options that are unused, must, sadly die.

**Comment by yossigil** [comment]
@OirRoth: I did some work here, but I broke the build. Can you check?

**Comment by OriRoth** [comment]
Did you try to make the spartan button run "spartanize entire project"? It now works

**Comment by OriRoth** [comment]
@yossigil OK as it appears there is no spartanizations marking- did you renamed/moved spartanizationSuggestion class? I cannot find it

**Comment by OriRoth** [comment]
@yossigil OK the plugin seems to work:
* Spartanize entire project when clicking on spartan button
* End message and picture appear with no exceptions
* Spartanization suggestions marking
* Hover marking opens window with preview suggestion
* Preferences page appearing

You can check it out (is there something I forgot?). What do you want to do with Refactor->Spartanization window? (remove or clean)

**Comment by yossigil** [comment]
Ori: There is a strange menu of Refactoring/Spartnizaton with raw class names

**Comment by OriRoth** [comment]
The two only undeprecated features from that window are:
1) spartanize entire project
2) spartanize active window
Feature 1 can be activated using the button. In my opinion we should use the shortcut (ctrl+alt+shft+s) for feature 2 (it should work but in my computer it refuses to). What do you think? maybe another button?
In the meanwhile... I'll get to it after tests merging

**Comment by yossigil** [comment]
No one will remember the shortcut...
Better a menu option until we sort things out.

**Comment by OriRoth** [comment]
OK I tamed the beast! the menu now shows two options:
* spartanize active window
* spartanize entire project
that do as they should. I can add more features to this menu if needed.

As Daniel said in other issue, I cannot see any warnings as well. I will try solving it later on.

**Comment by yossigil** [comment]
Brilliant. At last!
