### ISSUE TITLE
Possible bug in wizard.assign2infix

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#960]
There is an error in TippersTest test class that is caused by wizard.assign2infix(Operator) returns null. The test wasn't edited lately so I think the bug is from change in wizard.assign2infix hash map. It probably causes #958 and #959 ...

**Comment by yuvalsimon** [comment]
@yossigil In this commit: https://github.com/SpartanRefactoring/Spartanizer/commit/59a9f266958d0e6a136dff76e9ebab5df256b90b 
you changed in wizard class the assign2infix and infix2assign hash tables and it causes failures in some tippers tests and the error in TippersTest.
You changed to this:
```
Map<Assignment.Operator, InfixExpression.Operator> assign2infix = new HashMap<Assignment.Operator, InfixExpression.Operator>() {
    static final long serialVersionUID = 1L;
    {
      put(PLUS_ASSIGN, PLUS2);
      put(MINUS_ASSIGN, MINUS2);
...
InfixExpression.Operator MINUS2 = InfixExpression.Operator.MINUS;
InfixExpression.Operator PLUS2 = InfixExpression.Operator.PLUS;
```

If I change to 
```
Map<Assignment.Operator, InfixExpression.Operator> assign2infix = new HashMap<Assignment.Operator, InfixExpression.Operator>() {
    static final long serialVersionUID = 1L;
    {
      put(PLUS_ASSIGN, InfixExpression.Operator.PLUS);
      put(MINUS_ASSIGN, InfixExpression.Operator.MINUS);
...
```
it fixes the failures. Should I change it back?

**Comment by yossigil** [comment]
Yes. Please. Bravo!

**Comment by yuvalsimon** [comment]
Done
