### ISSUE TITLE
Expand to toString();

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Spartanizer#965]
convert `""+a` to `a.toString();`

**Comment by dormaayan** [comment]
@OriRoth , @ravivos : Is currently there any place we need to add the new expanders to(like the toolbox) ?

**Comment by dormaayan** [comment]
I think Im done here...

**Comment by OriRoth** [comment]
Please change class name according to conventions.

**Comment by yuvalsimon** [comment]
```
final String $ = us.size() + "";
```
to
```
final String $;
$ = us.size().toString();
```
makes error for invoking toString on primitive type.
There are many similar cases, try Ctrl+Alt+Q on the project to expand all

**Comment by OriRoth** [comment]
Isn't the error caused by the `final` attribute? This is a bug of other expander.

**Comment by dormaayan** [comment]
@OriRoth : there isn't any way to check if that type is primitive or not right now, I also checked binding and it dopes't give any useful information for that, do you think we should cancel it or simply keep it like that ?

**Comment by dormaayan** [comment]
Done

**Comment by OriRoth** [comment]
@dormaayan did you used binding?

**Comment by dormaayan** [comment]
Yes, but now we can't test it...

**Comment by OriRoth** [comment]
It can be tested while running the plugin... for now.

**Comment by dormaayan** [comment]
Yes I know...
But that's not the right way to do that

**Comment by yossigil** [comment]
Perhaps it is time you use the idea I presented for testing?

**Comment by dormaayan** [comment]
@yossigil : Sure, Im currently on that, hope for nice results soon
