### ISSUE TITLE
If - else Expander

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Spartanizer#971]
Convert : `if(condition)statement`
to : `if(condition){statement}`

as well as with elses

**Comment by ravivos** [comment]
I am not sure of the necessity of this expander

**Comment by dormaayan** [comment]
@ravivos : I think that's good because all the purpose of the expander is to expand as much as possible and many people prefer to write their code with blocks and consider it as more readable

**Comment by yossigil** [comment]
More generally, wrap all inner statements including, do, for, while in curlies.

**Comment by mdoron** [comment]
@dormaayan, did you finish this expander? It would really help #999 in cases such as:
```
if (boolean_expression)
    a = b = c = 3;
```

Which cannot be identified by #999 now, but will be okay after adding `{}`

**Comment by dormaayan** [comment]
Done
