### ISSUE TITLE
+= Expander : write tests using binding

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Spartanizer#973]
convert : `a+=b` to : `a=a+b`

**Comment by OriRoth** [comment]
Also `-=` etc., of course.

**Comment by yuvalsimon** [comment]
```
totalMethodsTouched = 0;
    for (final Integer ¢ : statementsCoverageStatistics.keySet())
      totalMethodsTouched += totalMethodsTouched(statementsCoverageStatistics.get(¢));
```
to
```
totalMethodsTouched = 0;
    for (final Integer ¢ : statementsCoverageStatistics.keySet())
      totalMethodsTouched = totalMethodsTouched + totalMethodsTouched(statementsCoverageStatistics.get(¢));
```
makes error "cannot convert from double to int".
(totalMethodsTouched is int and totalMethodsTouched() returns double)

**Comment by OriRoth** [comment]
Can you give me the whole context? Or at least the variable declarations.

**Comment by OriRoth** [comment]
OK now the expander is safer using *binding information*. The test is disabled because there is currently no binding in tests.
