### ISSUE TITLE
++ Expander

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Spartanizer#974]
convert `i++;` to `i=i+1`

**Comment by OriRoth** [comment]
Also `++i`, `--i` etc.

**Comment by OriRoth** [comment]
Sometime parenthesis are require!
```Java
f(i++ + ++i);
```

**Comment by OriRoth** [comment]
Also you cannot do this in all cases:
`f(i++); =/= f(i+=1);`

**Comment by dormaayan** [comment]
Done
