### ISSUE TITLE
conjunction of long ifs to different ifs expander

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Spartanizer#976]
```
if(a==b && c==d)
    a = 5;
```
to
```
if(a==b)
    if(c==d)
        a = 5;
```

**Comment by OriRoth** [comment]
This is very hard one. Consider this case:
```Java
if (a && b)
  f();
else
  g();
```
There are many more... there is some utility available though.

**Comment by yossigil** [comment]
There are mechanism in the library that allow you to check whether parenthesis are required when you open a case.

**Comment by OriRoth** [comment]
@tomerdragucki please clarify how you chose to implement this expander.

**Comment by tomerdragucki** [comment]
If there is logical AND in the expression than the first expression of the AND will be moved to a separate if. In addition if there is an else statement, all the new if's will have this else.
For example:
```java
if (a && b && c) { 
  t = 5; 
} else {
  t = 2;
}
```
==>
```java
if (a) { 
  if (b && c) {
    t = 5;
  } else {
    t = 2;
  }
} else {
  t = 2;
}
```
==>
```java
if (a) { 
  if (b) {
    if (c) {
      t = 5;
    } else {
      t = 2;
    }
  } else {
    t = 2;
  }
} else {
  t = 2;
}
```

**Comment by yossigil** [comment]
Make sure this is reversible, i.e., that the spartanizer can deal with this.

**Comment by tomerdragucki** [comment]
The spartanizer can deal with it but it's not exactly the reverse because of the use of ternary in the spartanizer. Spartanizing the expanded code above yields ```java t = a && b && c ? 5 : 2; ``` and expanding this line yields the expanded code shown above.
