### ISSUE TITLE
Class instance creation into a variable

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#978]
```Java
new Stuff();
```
==>
```Java
Stuff stuff = new Stuff();
```
Usage of *namespace* is required.
We can consider cases such as:
```Java
w.x().y(new Z());
```
but there should be a check for side effects (in this case there are side effects!).

**Comment by yossigil** [comment]
:+1:

**Comment by mdoron** [comment]
@yossigil I understand that the environment is finished, where can I find the API?

**Comment by mdoron** [comment]
@OriRoth already implemented this one

**Comment by OriRoth** [comment]
Are you sure? There are no tests yet... open it please

**Comment by OriRoth** [comment]
@mdoron this is **not** implemented, and there are now tests! Please close issues only if you are *sure* they are obsolete (probably after you solved them).

**Comment by yossigil** [comment]
#709

**Comment by mdoron** [comment]
@OriRoth you told me your zoomer contains all the naming zoomers and also that you finished it. Moreover, I took the second example and ran it and got good results (`new Z()` was extracted).

The problem is you confused two different zoomers into one...

But if it is not implemented yet, I will do it.

**Comment by yossigil** [comment]
Is it, or is **not** implemented?

**Comment by mdoron** [comment]
This is implemented;
`w.x().y(new Z());` >> `Z z1 = new Z(); w.x().y(z1);`
This is not implemented:
`new Z();` >> `Z z1 = new Z();`

**Comment by yossigil** [comment]
💯

**Comment by OriRoth** [comment]
@mdoron good job, looks great! 👍
