### ISSUE TITLE
Declaration with ternary to if

### ISSUE THREAD

**Issue by tomerdragucki** [SpartanRefactoring/Spartanizer#983]
```java
int a = b ? 3 : 2;
```
===>

```java
int a = 2;
if (b)
  a = 3;
```

**Comment by ravivos** [comment]
If you do not plan on implementing this expander this week, please add me as an assignee, so I can as I have experience working on ternary expanders.
In addition, the expansion of what you wrote in my opinion should be:
```
int a;
if (b)
  a = 3;
else 
 a = 2
```
what do you think @tomerdragucki ?

**Comment by tomerdragucki** [comment]
@ravivos I actually planned implementing it this week.
And I like your suggestion of how to expand and I think we should go your way. I wrote mine just cause there is a tipper doing the opposite.

**Comment by tomerdragucki** [comment]
Solved with 996.
