### ISSUE TITLE
Assign with ternary to assign with if

### ISSUE THREAD

**Issue by tomerdragucki** [SpartanRefactoring/Spartanizer#985]
```java
a += x ? 3 : 9;
```
==>
```java
if (x)
  a += 3;
else
  a += 9;
```

**Comment by yossigil** [comment]
trenary = ternary

**Comment by ravivos** [comment]
regular assign with ternary already exists as part of #883.
+=,-=, etc do not.
We should decide wether they should each get an individual issue and expander, or be united as one.
This is a political question which I think @OriRoth should be also part of

**Comment by OriRoth** [comment]
Consider this:
```Java
int a += x ? 3 : 9;
```
==>
```Java
int a;
if (x)
  a += 3;
else
  a += 9;
```

**Comment by ravivos** [comment]
this is relevant for a different issue Ori.
@tomerdragucki please see what I reference to this issue

**Comment by ravivos** [comment]
@OriRoth 
You probably meant `int a = x ? 3 : 9;`
I didn't notice it when I copied your example to a new issue.
good thing we have a good client @yossigil

**Comment by tomerdragucki** [comment]
@ravivos  I didn't understand why did you close this one?

**Comment by OriRoth** [comment]
@ravivos please explain yourself - posting an answer on a different thread usually achieves confusion.
