### ISSUE TITLE
Bug in TernaryExpander

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#986]
*Originally posted by @tomerdragucki*
I ran into a bug:
```Java
a += x ? 5 : 3;
```
becomes:
```Java
if (x)
  return 5;
else
  return 3;
```
@ravivos I opened a new issue for implementing the += with trenary as a new expander but I guess inserting it into your expander is also an option.

**Comment by ravivos** [comment]
Still working on it.
But when I finish it, we will get #985 for free, because I wrote and combined some expanders issues to one expander - ternary expander, which is #883

**Comment by OriRoth** [comment]
Try this:
```Java
switch (1) {
  case f(x -> x |= b ? true : false):
    break;
}
```

**Comment by ravivos** [comment]
@OriRoth 
Both of your examples are not trenary expressions but a function which gets as an argument a lambda function.
There for are not related to this expander but might actually be a great idea for a new one, dealing with anonymous functions in general

**Comment by OriRoth** [comment]
It should be testable, as in TrimmerTest.
