### ISSUE TITLE
reduce number of warnings to less than 40.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#99]
Disable all warnings other than:

- Null
- Java doc.
- Access through this.
- No externilized string 

reduce the number of warnings, by fixing the code.

**Comment by yossigil** [comment]
You are expected to learnon your own how to deal with warnings.

**Comment by yossigil** [comment]
You are expected to deal with warnings, not disable them

**Comment by Stav1472** [comment]
you said "Disable all warnings other than..."

what did you mean by that?

**Comment by yossigil** [comment]
Done. Pending on #146 .
Currently we have 25 warnings. Let's try to shoot for zero.
