### ISSUE TITLE
Safe Invocation

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#990]
```Java
$ != null && $.getKey().isConnected(subRange)
```

**Comment by yossigil** [comment]
this is exactly '?.'
or do I miss something?

**Comment by orimarco** [comment]
Kind of, but in a different form of
x == null ? null : x.y()

**Comment by yossigil** [comment]
I think you observed something important.

?. applies to all types that have default values, but since all types have default value it applies also to ?.

**Comment by yossigil** [comment]
Well,  some day we should generalize ?. to deal with any type that has a default value, 
e.g., x ?. y 

only computes y if x is not the "default=null/0/false"
