### ISSUE TITLE
Dollarization/Centification in Spartanizer

### ISSUE THREAD

**Issue by zahimizrahi** [SpartanRefactoring/Spartanizer#994]
Hi, 

I'm not sure if this is the right place to tell you this, and I'm not sure who do I need to assign this. 

I'm using your spartanizer in my SmartParking project, and often it's very helpful, but I don't like the dollarization tippers. 

the spartanizer keeps telling me that I should rename my variables to $. but I don't see how it helps spartanize my code. 
I prefer naming my variables with meaningful names than dollars. 
also the same about centification. 

So to be honest, most of the times I avoid using these tips.

On one hand, I don't want to supresss tippers on Sparanizer on my function&classes. 
On the other hand, This tip is not  helping my code to be more clearer - the opposite.

I would like to hear your comments about it, and see if it's something you can fix/change in the future. 

it's my 2 cents (¢), Thank you. 
@yossigil

**Comment by tomnof** [comment]
+1

**Comment by yossigil** [comment]
Several issues here:

1. Standard name for the return variable
2. Identify correctly the return variable
3. Should the return variable be named '$' or,say ' result'
4. Configuring the return variale name.
5. Configuring tippers.

I think 2 is buggy due to some changes made recently by the team @ravivos.  I think 5 is necessary @OriRoth 

I think 1 should stay. Return name should be '$' by default, but could be configured.

**Comment by tomnof** [comment]
1. Let's assume that I get the reason behind this (but I don't, if you would like the explain that would be nice), why don't you use the name "returnedValue" or something more suitable?

**Comment by zahimizrahi** [comment]
also, I'm not quite sure why do we need a default name for return value at all. 
I think each method should have its own return-object variable name, according to its functionality.

**Comment by ravivos** [comment]
An important principle of spartanization is to use as least code as possible.
It is like looking at characters in the code as money that you spend, therefore you should minimize the use of "everything".
for more information I suggest to read this awesome slide from the [technion webcourse](http://webcourse.cs.technion.ac.il/236700/Spring2016/ho/WCFiles/06-Spartan%20Programming.pdf)
On a more personal level, I agree that sometimes it is hard to understand when we want to debug for example and that is why I am fond of our project Idea (The Athenizer) :)

**Comment by zahimizrahi** [comment]
@ravivos 
I get the idea of spartanization. but I think still one of the main goals is keeping the code clearer and easier to read. 

Sparanization try to maximizes the number of: lines of code, variables, branches but it says nothing about the length of the name of the variables, so why does it need to be $ (or cent as arguments to function)?

**Comment by ravivos** [comment]
"Everything should be as short as possible, but not shorter"
It also tries to minimize the columns which stands for minimizing the length of each line.
As I said before, in general, it tries to minimize the characters in your code.
Fun fact/ assumption - I guess @yossigil  chose dollars and cents to represent the money spent on writing it, because chars in code equals money spent.
Orm aybe to say that a function returns valuable money (dollars) but the cents are only temporary and less valuable

**Comment by yossigil** [comment]
@tomnof : I agree, it should be configurable.

**Comment by yossigil** [comment]
The cent argument to function, can be read as "the argument name is immaterial, it is not important, the function would be the same with any other name, and would loose its clarity.

In this context "cent" can be read as "sent"...

**Comment by OriRoth** [comment]
@zahimizrahi you can disable dollarization/centification tips in the Spartanizer preferences menu.
@tomnof a good idea actually, but rather hard to implement... Maybe it will be available in later releases - stay tuned!

**Comment by zahimizrahi** [comment]
@OriRoth  I know I can.
 from what I see, a lot of students using this tool is disabling those tips this anyway.
 which means those tips bother us. 
and by  students doing that,  doesn't it miss the whole point of your plugin? 

also, disabling is not very helpful. there's still problem - when you  load my project on your machine, you can still see those tippers if you hadn't disable those yourself. 

I think @tomnof 's idea is great. It should be configurable to something else.

**Comment by yossigil** [comment]
@zahimizrahi: why should anyone be troubled to give "meaningful" name to a function return variable? How much creative can you be about it. Why would you call it at one point "result" and at another point "ret" and at a third point "ret_val"? 

Configuration is important, indeed!

**Comment by zahimizrahi** [comment]
@yossigil  you shouldn't. I just think it needs to be configurable, so we can switch it to something more clearer than dollars.

**Comment by dormaayan** [comment]
Ok, due to duplications of Issues, I close that.
We will introduce ways to configure most of the renaming soon.
Thanks for your comments.
